### ISSUE TITLE
cell_measures with a value of @OPT

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#108]
In the 01.beta.38 version of the MIP tables, the `cell_measures` for `ua` and `va` for `6hrLev` has the value `@OPT`. According to cmip6dr/CMIP6_DataRequest_VariableDefinitions#40, this value is a valid value, but CMOR errors with the message `Error: Dataset error, required attribute external_variables was not passed or blanked`. Would it be possible for CMOR to handle `cell_measures` with a value of `@OPT`?

**Comment by dnadeau4** [comment]
@taylor13 explained to me why we have cell_measures to "@OPT",  I changed the code so that if "@OPT" is found, it reset `VARIABLE_ATT_CELLMEASURES` to `""`, so no `external_variable` attribute will be produced.   That will be in 3.2.0.

**Comment by dnadeau4** [comment]
I also add the "--OPT" option in the code, since some of the tables are set to that string.

**Comment by dnadeau4** [comment]
This is now working.
