### ISSUE TITLE
Add min/max time limits per experiment

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#11]

**Comment by dnadeau4** [comment]
This will be ensured with the Control Vocabulary.   Values for sub_experiment_id will be controlled to be from s1960 to s2020.  That range will be valid for all model.   Is this what you want? @doutriaux1 @taylor13

**Comment by taylor13** [comment]
No, this will only ensure that groups don't perform any DCPP experiments (a subset of the CMIP6 set of experiments) that are initialized outside the range 1960 - 2020.  It will be difficult to *enforce* start and end times for most experiments.

**Comment by dnadeau4** [comment]
@durack1   I don't think this is necessary.  Can you close this issue?

**Comment by dnadeau4** [comment]
@durack1   I don't think this is necessary.  Can you close this issue?

**Comment by durack1** [comment]
@dnadeau4 yes following the comments above I think this issue is no longer relevant. @taylor13 can chirp in if it needs to be reopened
