### ISSUE TITLE
clt in aermonthly

### ISSUE THREAD

**Issue by goord** [PCMDI/cmor#110]
Hi,

in the aermonthly table, the variable clt has a vertical axis alevel. However, in other tables this is not the case, and the description (cloud area fraction as seen from toa or sfc) also suggests this is a 2D variable. Should this model level dimension be omitted?

**Comment by ehogan** [comment]
Hi @goord, in the latest version of the [data request](http://clipc-services.ceda.ac.uk/dreq/u/7c2249d424dde72f8616d42870a9d425.html) / [MIP tables](https://github.com/PCMDI/cmip6-cmor-tables/search?utf8=%E2%9C%93&q=clt), `clt` only exists in `Amon`, `day` and `3hr`. So I think this issue has already been resolved in the data request :)

**Comment by dnadeau4** [comment]
I will close this issue, since it seems to be solved.
