### ISSUE TITLE
Is CMOR3 thread-safe?

### ISSUE THREAD

**Issue by goord** [PCMDI/cmor#114]
Is it safe to write multiple variables (in the same table, I assume only one table can be loaded at once) at the same time with CMOR3?

**Comment by dnadeau4** [comment]
I don't think it is, but NASA gave me some code using MPI with many instance of CMOR in parallel.  I will revisit it and implement it.  

If you CMOR uses the PID to create the `temporary file`, and multiple instance will overwrite `temporary` the file over and over.

**Comment by dnadeau4** [comment]
@goord I added `mkstemp()` to the output name which is safe for `race condition`.  That should do the trick for parallelism.

**Comment by goord** [comment]
OK, I may run a test if I get the time... Thank you.

**Comment by dnadeau4** [comment]
I have implemented the thread safe option in 3.2.2.  Please reopen if it is not working properly for you.
