### ISSUE TITLE
Provide more grnaular distribution of CMOR via anaconda

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#115]
using the `feature` of anaconda we could distribute it as
*  pure `C`
* `C` and `Fortran`
* `C` plus `Fortran` plus `Python`
  * `numpy 1.9`
  * `numpy 1.10`
  * `numpy 1.11`

**Comment by dnadeau4** [comment]
What are the feature of anaconda?  

I've distribute with numpy 1.9, 1.10 and 1.11 last Wednesday.

**Comment by doutriaux1** [comment]
`feature` is an anaconda thing that let it automatically download various version of a package based on which packages you have in your conda environment for example if gfortran installed then get the `C+Fortran` version. If Python  installed (I believe it's always true) install C+Python, etc...

**Comment by dnadeau4** [comment]
I thought `feature` and `track_features` were for `meta-packages`?   I right now CMOR includes this:

* `C` plus `Fortran` plus `Python`
  * `numpy 1.9`
  * `numpy 1.10`
  * `numpy 1.11`
