### ISSUE TITLE
Unable to subscribe to the CMOR mailing list

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#119]
I seem to be unable to subscribe to the CMOR mailing list. I have followed the instructions [here](https://pcmdi.github.io/cmor-site/mailing-list.html) and have received confirmation e-mails, but if I send a command to `LISTSERV@LISTSERV.LLNL.GOV`, I get the response `You are not subscribed to the CMOR list.`. Are there newer instructions I should be following? Are the mailing lists working?

**Comment by dnadeau4** [comment]
@taylor13 @doutriaux1 I don't have access to the cmor list. Can someone log in listserv.llnl.gov and see if Emma is a subscriber?

**Comment by dnadeau4** [comment]
emma.hogan@metoffice.gov.uk

**Comment by taylor13** [comment]
I suggest giving Denis access to the cmor list.  Anyone know how to do that?

**Comment by durack1** [comment]
@dnadeau4 this URL will work onsite (or maybe VPN) https://listserv.llnl.gov/Scripts/wa.exe?A0=CMOR& my guess is that @doutriaux1 is the list owner

@ehogan send an email to cmor-request@listserv.llnl.gov.. That should trigger a subscription

**Comment by ehogan** [comment]
> @ehogan send an email to cmor-request@listserv.llnl.gov.. That should trigger a subscription

I just sent an e-mail ...

**Comment by ehogan** [comment]
I just got the reply:

```
To cut  down on  spam, the CMOR  list has been  configured to  request positive
confirmation  of messages  posted to  the  CMOR-request address.  You must  now
confirm that  the enclosed  message did  originate from you.  To do  so, simply
reply to the present message and type  "OK" (without the quotes) in the text of
your message,  or click on  the link below.  If this does  not work, or  if the
message did not originate from you, then contact the list owner for assistance.

To APPROVE the message:
http://listserv.llnl.gov/SCRIPTS/wa.exe?OK=A02A0F26&L=CMOR
```
The link doesn't work for me (I get a `504 Gateway Timeout`), so I replied to the e-mail with `OK`.

**Comment by ehogan** [comment]
I just received three more e-mails, one of which contained a large amount of text; buried in this text was a sentence saying I should resend the request to LISTSERV@LISTSERV.LLNL.GOV. I'm now subscribed. Would it be worth updating the instructions to specify this e-mail instead?

**Comment by dnadeau4** [comment]
@doutriaux1 Can you give me access to the cmor the mailing list?  I called listserv a month ago and they told me that it had to be you,  since you are the admin.  They did not want to give me direct access.  

It would have been easier to just had Emma directly to the list, instead of having her going through these hoops.

**Comment by durack1** [comment]
@ehogan the listserv system and the web-based interface is locked behind a firewall, so anyone outside the network can only interact using the standard listserv email commands.. Take a peek at https://www.lsoft.com/resources/manuals.asp if you want to know more

@doutriaux1 this owner of the list should be @dnadeau4 so he can administer things quickly.. @dnadeau4 put a request through with 4Help to solve that..

@ehogan can we close this?

**Comment by durack1** [comment]
@ehogan apologies I didn't respond to your [comment above](https://github.com/PCMDI/cmor/issues/119#issuecomment-276665475).

Sending an email to cmor-request@listserv.llnl.gov triggers an email reply to the senders email address, which validates your email (you need to reply "ok") to continue to subscription. Upon receiving the "ok" reply the system triggers the list owner to add you as a list subscriber.. When you refer to "instructions" to you mean the information presented (the mailing list address) at http://cmor.llnl.gov/mydoc_contacts/?

**Comment by dnadeau4** [comment]
@durack1 4Help refused to add my name last time.  @doutriaux1 was able to add my email, so I am now an owner of CMOR and I can finally add people to the list.

**Comment by dnadeau4** [comment]
@durack1 I would love to add the instructions to `mydoc_contacts` cmor documentation.

**Comment by doutriaux1** [comment]
@dnadeau4 i made you owner weeks ago.

**Comment by dnadeau4** [comment]
I did not know until yesterday.  Thanks!

**Comment by ehogan** [comment]
@durack1 I was following the instructions at https://pcmdi.github.io/cmor-site/mailing-list.html (the first page Google displays when searching for `cmor mailing list`). The instructions at http://cmor.llnl.gov/mydoc_contacts/ are better; apologies for not spotting these earlier :)

Thanks everyone for your help!

**Comment by durack1** [comment]
@dnadeau4 we should probably redirect the site [pcmdi.github.io/cmor-site/](https://pcmdi.github.io/cmor-site/) to your revised pages [cmor.llnl.gov/](http://cmor.llnl.gov/)

**Comment by dnadeau4** [comment]
@durack1 This site is for CMOR2.  Some people at NASA are still using CMOR2, there might be a better way to link to it somehow.... Maybe @mattben could help with this.
