### ISSUE TITLE
Deal with salinity unit variants better

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#12]
The issue described at https://github.com/PCMDI/pcmdi_metrics/issues/162 and it's solution should probably be implemented in CMOR. It would appear that CMOR already knows about `psu` (https://github.com/PCMDI/cmip5-cmor-tables/blob/master/Tables/CMIP5_Omon#L2925-2989) however the other realistic variants of `pss*` should also be considered.

As part of an update to CF in 2011, all the new salinity variants were included in the standard name table (http://mailman.cgd.ucar.edu/pipermail/cf-metadata/2011/022581.html) these (and their units) should be incorporated into CMOR..

@doutriaux1 I'd be happy to work with you on this.. As part of a V3.0 push..

**Comment by doutriaux1** [comment]
@durack1 it is in metrics will copycat what we did there in here at the C level.

**Comment by durack1** [comment]
@doutriaux1 I will need to test the metrics functionality.. We can talk more about metrics later in the week..

**Comment by dnadeau4** [comment]
@durack1 ping!!

**Comment by durack1** [comment]
@dnadeau4 ping indeed.. @doutriaux1 what is/was the status of the salinity fudges for `CMOR2` is this something that can be pulled forward into `CMOR3`? I ask this as the inclusion of salinity `units` in `UDUNITS` was blocked

**Comment by dnadeau4** [comment]
@durack1 should we close this issue?

**Comment by doutriaux1** [comment]
@dnadeau4 no we should add all the units asked for by @durack1 in a similar fashion as what we did for `psu`

**Comment by durack1** [comment]
@dnadeau4, @doutriaux1 created the ability to add salinity "units" in CMOR, I had tried to get these into `udunits` upstream, but was blocked so instead wanted to catch this in the CMOR software. Has the salinity units work of @doutriaux1 been included in `CMOR 3.2.x`?

**Comment by dnadeau4** [comment]
What is the salinity works of @doutriaux1?  I don't think it is in CMOR.

**Comment by durack1** [comment]
@doutriaux1 was that units stuff in a branch?

**Comment by dnadeau4** [comment]
@doutriaux1 where is you salinity code?

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/pcmdi_metrics/pull/477

**Comment by durack1** [comment]
This is more directly relevant [this code block](https://github.com/jservonnat/pcmdi_metrics/blob/9b0814c9dc9ab5d8b0c6091208e82456e333bec9/src/python/pcmdi/scripts/pcmdi_metrics_driver_OceanLevels.py#L20-L35)
```python
import unidata
# Created scaled units for dimless
unidata.addScaledUnit("psu", .001, "dimless")
unidata.addScaledUnit("PSS-78", .001, "dimless")
unidata.addScaledUnit("Practical Salinity Scale 78", .001, "dimless")
```

**Comment by dnadeau4** [comment]
@durack1 I was able to create `psu`, `PSS-78`, `Practical Salinity Scale 78`.  Here is the output:
```
	float sos(time, lat, lon) ;
		sos:standard_name = "sea_surface_salinity" ;
		sos:long_name = "Sea Surface Salinity" ;
		sos:units = "0.001" ;
		sos:original_units = "psu" ;
		sos:history = "2017-07-13T22:16:05Z altered by CMOR: Converted units from \'psu\' to \'0.001\'. 2017-07-13T22:16:05Z altered by CMOR: replaced missing value flag (0) with standard missing value (1e+20)." ;
		sos:cell_methods = "area: mean where sea time: mean" ;
		sos:cell_measures = "area: areacello" ;
		sos:missing_value = 1.e+20f ;
		sos:_FillValue = 1.e+20f ;
```

**Comment by durack1** [comment]
@dnadeau4 excellent, `PSS-78` should be the units we aim for (as it is the correct notation).. not sure what CMIP6 specifies

**Comment by taylor13** [comment]
for CMIP6 model output the correct units are 0.001

**Comment by dnadeau4** [comment]
Actually udunits does not allow characters `-` and `0-9`.  The best I can do is "pss",  which will also validate "pss-78".    

Now,  CMOR can convert `PSS-78` to `0.001` which is what we want for CMIP6.  This is good since you have the conversion in the `history` and the `original_unis` attribute. 

If you want `PSS-78`  you need to talk to `WCRP`.   I cannot change the tables.

**Comment by durack1** [comment]
@dnadeau4 what PR was this closed by?
