### ISSUE TITLE
tracking_id validation gives errors

### ISSUE THREAD

**Issue by goord** [PCMDI/cmor#122]
Hi,

I am using the latest cmor anaconda package and I am experiencing the following error:

```shell
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The attribute "tracking_id" could not be validated. 
! The current input value is "0ae8c76d-4eab-49c1-8a7b-1c13889a27ac" which is not valid 
! Valid values must match the regular expression:
! 	["hdl:21.14100/.*"  ...] 
! 
! Check your Control Vocabulary file "/home/gvdoord/Data/Primavera/cmor/scripts/ece2cmor/resources/tables/CMIP6_CV.json".
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

However, my configuration json file clearly contains the line

```shell
    "tracking_id":                  "hdl:21.14100/02d9e6d5-9467-382e-8f9b-9300a64ac3cd"
```
It seems that this filed is somehow not read and an incorrect default value is used...
Greetings, Gijs van den Oord

**Comment by dnadeau4** [comment]
It seems to me that you are not reading the right user input files.  Your tracking ID and the one cmor displayed is different.  What version of cmor are you using.  The WIP changed all the table names which I update on github during the MLK long holiday.  They just sent me another update today? (sigh).  I am in Seattle for AMS.  Are you there?

**Comment by goord** [comment]
Highly unlikely, there is no other user input json in my project, and other warnings contain the correct values. I also noticed that every time a different uid appears in the error message, perhaps the uuid library generates one and overwrites the field before validation? BTW I am using the head of the master branch of the CMIP6 tables.

I am not in Seattle, as I am working for the Dutch Royal Met. Institute, preparing the EC-Earth cmorization tools for upcoming runs (AMIP, CMIP6, HighResMIP).  P.S. The user input json I am using is

[cmor3_metadata.zip](https://github.com/PCMDI/cmor/files/724956/cmor3_metadata.zip)

**Comment by taylor13** [comment]
It seems odd to me that a full tracking I.D. should appear in an input file (or as you say a "configuration json file") to CMOR.  CMOR is supposed to *generate* the random portion of the tracking id.  The input file should only contain "hdl:21.14100/.*"

I'm not that familiar with all this, so perhaps I'm wrong.

**Comment by goord** [comment]
I have tried that as well, no success. Also, if the tracking-id is validated to match hdl:21.1411/.* (listed in the CV table), then I would guess that CMOR generates such an id and there is no need to adopt this field in the user input, right?

**Comment by dnadeau4** [comment]
Can you look at the tracking I'd test that I have for cmi6 cv on github.  I am in the middle of a talk so I can't provide you with more info not until Friday.



Lawrence Livermore National Laboratory
Atmospheric, Earth and Energy Division
925-423-3123

________________________________

**Comment by dnadeau4** [comment]
@goord  just got back from travel and was able to look at your file.   

You set `tracking_id` instead of `tracking_prefix` in your `cmor3_metadata.json` file.  The `tracking_id` is creating by adding prepending `tracking_prefix` when present.    For CMIP6, `PrePARE` make sure that `hdl:21.14100` is present, but for obs4MIPs and input4MIPS project they don't need to be there.


Have a look the [test_python_CMIP6_CV_trackingprefix.json](https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_CV_trackingprefix.json)

**Comment by dnadeau4** [comment]
http://cmor.llnl.gov/mydoc_cmor3_python/

**Comment by goord** [comment]
Thank you @dnadeau4, that solves my problem. Closing issue.
