### ISSUE TITLE
Segfault with problematic input table

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#124]
@dnadeau4 the `Segmentation fault: 11` that I reported earlier today can be replicated in `CMOR 3.2.1` using the files contained in the attached archive.
[cmor321SegFault.zip](https://github.com/PCMDI/cmor/files/743428/cmor321SegFault.zip)

You can replicate the segfault by executing:
```python
> python runCMOR3-test.py
```

**Comment by dnadeau4** [comment]
Fix in 3.2.2

**Comment by durack1** [comment]
@dnadeau4 nice!
