### ISSUE TITLE
running PrePARE.py script fails

### ISSUE THREAD

**Issue by cehbrecht** [PCMDI/cmor#126]
i've installed cmor via conda. There is a `PrePARE.py` script in the `bin/` folder but when you call it it exists with an error:

```
$ PrePARE.py 
~/.conda/envs/qa-dkrz-cmip6/bin/PrePARE.py: line 17: $'\nCreated on Fri Feb 19 11:33:52 2016\n\n@author: Denis Nadeau LLNL\n': command not found
```

Currently one has to run it like this:

```
python ~/.conda/envs/qa-dkrz-cmip6/bin/PrePARE.py
```

Probably the `setup.py` needs to be fixed to install `PrePARE.py` as a script.

**Comment by dnadeau4** [comment]
@cehbrecht  I did not add the `#!/usr/bin/env python` on the first line.  It seems to work on the MAC so I will add that line.  You need to run it using `python` for now.

**Comment by dnadeau4** [comment]
@cehbrecht Does this solution work for you?

**Comment by cehbrecht** [comment]
@dnadeau4 
it might work that way ... but personally i would prefer to use the `setup.py` configuration with entry_points and moving the command line code to the package. See the following examples:

* cfchecker:
https://github.com/cedadev/cf-checker/blob/master/setup.py#L33

* compliance-checker:
https://github.com/ioos/compliance-checker/blob/master/setup.py#L46

**Comment by dnadeau4** [comment]
@cehbrecht That will make prepare a package, not a script.  That might work better for ESGF to import it thought.  @sashakames  would it be better for your to set PrePARE.py as an entry point?

**Comment by sashakames** [comment]
@dnadeau4 If you convert to a package, thats fine and probably preferable for ESGF as I access it now through a bit of a hack.  Bottom line, best to get done before we release ESGF 2.5 in case a standalone upgrade were to break what I have now

**Comment by dnadeau4** [comment]
@sashakames I was able to create an entry_point instead of a script.  It will be in the next release.

**Comment by dnadeau4** [comment]
@cehbrecht I have an entry_point in cmor 3.2.2 release.  Thanks.
