### ISSUE TITLE
setting env variables with conda recipe

### ISSUE THREAD

**Issue by cehbrecht** [PCMDI/cmor#127]
The docu mentions one has to set the following environment variable:

```
export UDUNITS2_XML_PATH=${HOME}/anaconda/share/udunits/udunits2.xml
```
Could this be done with the conda recipe?

https://conda.io/docs/using/envs.html#saved-environment-variables

See gdal example:

https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/build.sh

**Comment by dnadeau4** [comment]
`UDUNITS2_XML_PATH` is documented in the [installation](http://cmor.llnl.gov/mydoc_cmor3_conda/)

I looked at the `gdal build` recipe, and did not find out how they setup an environment variable `UDUNITS_XML_PATH` as part of the `conda` package. 

 I could actually add it to `PrePARE.py`, but not to the `cmor` library itself.   I'll investigate more

**Comment by dnadeau4** [comment]
I was able to add this to `CMOR-3.2.2` tag.   This worked well with source activate and deactivate.
Thanks!
