### ISSUE TITLE
conda package for cmip6-cmor tables?

### ISSUE THREAD

**Issue by cehbrecht** [PCMDI/cmor#128]
Could the cmip6-cmor tables be provided as conda package (going into `share/` folder) as well and then added as dependency to the cmor conda package?

**Comment by dnadeau4** [comment]
you mean something like `linux-64/CMIP6-CMOR-TABLES-3.2.2.tar.bz2`?  I never tried to create a recipe without code before.  @durack1 @taylor13 what do you think?

**Comment by taylor13** [comment]
I think we want the build of the software to remain independent of the tables used as input to it.  At some point we expect the software to be only updated infrequently while the tables are still evolving.  Note that different activities require different tables, but will all use the same CMOR package, so this is another reason to keep the two separate.  This comes at a very minor inconvenience to users who not only will have to run conda and also git update (for the tables).

**Comment by durack1** [comment]
@dnadeau4 you could add the tables as a dependency of the `CMOR` conda package, so that it's independent, but installed when the conda `CMOR` installation occurs.. Sounds like a good idea to me.. It also allows conda to be used to update the existing tables in an existing `CMOR` installation

**Comment by doutriaux1** [comment]
I personally think it's an horrible idea. conda is for software. What you could do is add convenience functions in cmor python to fetch the tables for you (git clone) that would make more sense. Look under the cmip5 repo there is convenience functions already to retrieve a set of tables at any date and to check your tables.

**Comment by doutriaux1** [comment]
see: https://github.com/PCMDI/cmip5-cmor-tables/tree/master/Lib

**Comment by dnadeau4** [comment]
@durack1 I don't think there is a hook in `conda` to run a script when you do `install`, `create` or `update`.  `conda` only retrieves tarball packages including dependencies and deploys them.


I could write a convenience script like @doutriaux1 suggest in the script directory perform a `git clone` and set the table (as long as the user has `git`.  Or the user could just follow my documentation.  

[cmor installation](http://cmor.llnl.gov/mydoc_cmor3_conda/#installing)

**Comment by dnadeau4** [comment]
@durack1 If I create a `CMIP6 Table` `conda` package, then we will need to maintain an `Inputs4MIPs`, `obs4MIPs`, `CREATE`, etc `conda` package as well.  It will be difficult to keep them up to date and maintain.   

I could use `TRAVIS CI` to create push automatically to anaconda when there is a change into the `master` branch.  If you think this is a `critical` priority for `CMOR` let me know.

**Comment by taylor13** [comment]
Let's not spend too much time on this.  I don't think it is so difficult to obtain the tables needed to run CMOR.

**Comment by durack1** [comment]
@dnadeau4 I think the "operational" projects would only include `CMIP` and `obs4MIPs` at this stage, both tables are hosted in github, so we have versioning etc, I wonder whether leveraging the work on nightly auto updates could be done here.. I agree with @taylor13 that it's a low priority, so if/when some spare time appears....

**Comment by dnadeau4** [comment]
@durack1 Do you want to create a conda package for CMIP6 tables?

**Comment by durack1** [comment]
@dnadeau4 let's push this off to the next release, as there are still issues upstream I don't think automating this now is a good use of time

**Comment by dnadeau4** [comment]
@taylor13 can you revisit this issue.

**Comment by durack1** [comment]
@dnadeau4 already bumped this to 3.2.7

**Comment by taylor13** [comment]
I think this is very low priority.  I don't think it is necessary for CMIP6, but might possibly be useful to some obs4MIPs users.  See if we get any further outside requests.

**Comment by dnadeau4** [comment]
This is not a priority and we will close this issue at the moment. We might re-open it at a later date.
