### ISSUE TITLE
Problem producing ps with CMOR 3.2.1

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#129]
When producing `ps` using CMOR 3.2.1, the values of the data variable attributes in the output netCDF file match the information for `ps` in the [CMIP6_formula_terms.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_formula_terms.json) file rather than the information for `ps` in the MIP table, e.g. [CMIP6_Amon.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_Amon.json#L765).

**Comment by dnadeau4** [comment]
The `CMIP6_Amon.json` is read first and then `CMIP6_formula_terms.json` is read.  Both tables goes into the same array.    I thought it would find the one from `Amon` first.   I guess the `zfactor` variable names are saved somewhere else.  I'll try to figure this out.  That code is not mine, so it might take a bit of time.

**Comment by dnadeau4** [comment]
I fixed this issue and pushed it in the CMOR-3.2.2 branch.  @taylor13 wants to get rid of `ps` in [CMIP6_formula_terms.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_formula_terms.json) for the next cmor update.

**Comment by dnadeau4** [comment]
@ehogan is this working for your now in version 3.2.2?

**Comment by ehogan** [comment]
According to https://github.com/PCMDI/cmor/releases, version 3.2.2 hasn't been released (or tagged) yet?

**Comment by dnadeau4** [comment]
@taylor13 does not want me to release,  he has a WIP meeting today and he wants me to release by the end of the week.  I'll see how much work comes out of this meeting and what I can do...

**Comment by ehogan** [comment]
@dnadeau4 @taylor13 if you're not able to release by the end of the week, would you consider making a release candidate (3.2.2-rc1) available that I could use for testing prior to the release? :)

**Comment by dnadeau4** [comment]
I am release CMOR 3.2.2 today, but I like the `release candidate` idea for next time.  I need to verify if `conda` will accept a version number with characters in it.

**Comment by dnadeau4** [comment]
This is now working in 3.2.2.

**Comment by ehogan** [comment]
Confirmed; thank you very much! :)

**Comment by ehogan** [comment]
Would it be possible to reopen this ticket? @jonseddon just discovered an issue when trying to produce `ps` using the `3hr` MIP table, which I believe is related to this ticket. The error message is `Error: You defined variable 'ps' (table 3hr) with axis id 'time1' which is not part of this variable according to your table, it says: ( time latitude longitude )`

**Comment by ehogan** [comment]
My apologies, please ignore me (it's Friday!); I forgot to tell Jon to use CMOR 3.2.2!
