### ISSUE TITLE
Strange and inconsistent characters for commit info in CMOR-configure-out.log

### ISSUE THREAD

**Issue by jypeter** [PCMDI/cmor#13]
I'm installing UV-CDAT 2.1.0 on different platforms and, when comparing the output files created for cmor by cmake, I have noticed some **strange characters** (non ascii? control chars?) in the *CMOR-configure-out.log* files. And the characters are not the same on both platforms...

On our RH server (*Red Hat Enterprise Linux Server release 6.6 (Santiago)*): **â_(ÿ^?**
```
config.status: creating compile_line.txt
config.status: creating include/cmor_locale.h
configure: 
configure: ************************************************************************
configure:                               SUMMARY
configure:                             VERSION: 2.9.0 (commit: (â (ÿ)
configure: ************************************************************************
```
On a FC20 (*Fedora release 20 (Heisenbug)*): **^A**
```
configure:                               SUMMARY
configure:                             VERSION: 2.9.0 (commit: )
```

**Comment by durack1** [comment]
@jypeter do you see the same issues with `CMOR 3.1.x`? If not, can you please close? (@dnadeau4 ping!)

**Comment by ehogan** [comment]
If it's helpful, I checked the log from the CMOR 3.1.0 build I did yesterday on Red Hat Enterprise Linux Client release 6.8 (Santiago) and there are no strange characters:
```
config.status:790: creating compile_line.txt
config.status:790: creating include/cmor_locale.h
configure:5593: 
configure:5595: ************************************************************************
configure:5597:                               SUMMARY
configure:5599:                             VERSION: 3.0.0 (commit: d9ea09cfee43c03110761da2ae08d2636118f04c)
configure:5601: ****************************************************************
```

**Comment by durack1** [comment]
@ehogan thanks, that was also my experience so I'll go ahead and close this issue. @jypeter if you find this behaviour again, please reopen

**Comment by jypeter** [comment]
OK, I'll do that. Thanks @durack1 !
