### ISSUE TITLE
Memory issue introduced in CMOR 3.1.3

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#130]
After some investigation, I discovered that the [chunking](https://github.com/PCMDI/cmor/commit/fc738dfa35e978721ae8ebb70a3627b82861961f#diff-038204a94c57f8deea5747661ee23c31) code that was introduced to [cmor.c](https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L2042) between CMOR 3.1.2 and 3.1.3 causes CMOR to use an excessive amount of memory. For example, when I run one of my tests using CMOR 3.1.2, it uses just under 1G of memory (to create an output netCDF file that is just under 1G on disk). However, when I run the same test using CMOR 3.1.3, it uses over 35G of memory!

**Comment by ehogan** [comment]
I just noticed the comment on #99; if it's helpful, the variable in my test has 2D axes.

**Comment by dnadeau4** [comment]
Can you give me more info about your file? `ncdump -hs <filename>`.   I was thinking of letting the user define a chunking attribute for each dimension (CMIP6_coordinates.json).  I set it to  `1` as asked in #99 for the default is just some crazy arbitrary size.   

Right now I chunk the entire length of lat/lon dimensions and the other chunk is set to 1 (level/time).   That makes sense when you want to extract 1 arbitrary level for a timestamp.  I am not sure why you get such a big file.... 

[cmor.c#L3132-L3138](https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L3132-L3138)

**Comment by dnadeau4** [comment]
You can also set compression, which might be of help.

[speed_test_table_A#L1691-L1693](https://github.com/PCMDI/cmor/blob/master/Test/speed_test_table_A#L1691-L1693)

**Comment by ehogan** [comment]
My apologies, I made a mistake in my initial comment. When I run CMOR 3.1.2, the output netCDF file is 22M on disk and uses ~0.94G of memory, but when I run CMOR 3.1.3, the output netCDF file is 929M on disk (~42 times larger) and uses ~35.5G of memory (~38 times larger).

Here is the difference between the output of `ncdump -hs <filename>` for the output netCDF file created using CMOR 3.1.2 and the output netCDF file created using CMOR 3.1.3 (not including `history`, `creation_date` and `tracking_id`):

```
% diff ncdump_3.1.2.txt ncdump_3.1.3.txt 
27c27
< 		j:_ChunkSizes = 1020 ;
---
> 		j:_ChunkSizes = 1 ;
34c34
< 		i:_ChunkSizes = 1440 ;
---
> 		i:_ChunkSizes = 1 ;
43c43
< 		lat:_ChunkSizes = 510, 720 ;
---
> 		lat:_ChunkSizes = 1, 1 ;
51c51
< 		lon:_ChunkSizes = 510, 720 ;
---
> 		lon:_ChunkSizes = 1, 1 ;
56c56
< 		lat_vertices:_ChunkSizes = 510, 720, 1 ;
---
> 		lat_vertices:_ChunkSizes = 1, 1, 1 ;
61c61
< 		lon_vertices:_ChunkSizes = 510, 720, 1 ;
---
> 		lon_vertices:_ChunkSizes = 1, 1, 1 ;
90c90
< 		:external_variables = "mean" ;
---
> 		:external_variables = "areacella" ;
123c123
< 		:cmor_version = "3.1.2" ;
---
> 		:cmor_version = "3.1.3" ;
```
Please let me know if you need anything else :)

**Comment by doutriaux1** [comment]
@dnadeau4 `i` and `j` chunk sizes have changed. Is that you or is it an artifact of a new netcdf?

**Comment by dnadeau4** [comment]
That's me as requested by #99.

**Comment by dnadeau4** [comment]
@doutriaux1  The file seems to have a grid (lon_vertices),  it might also be a artifact of netcdf 4.4.x
The 1,1,1, size is definitely the problem here.

**Comment by dnadeau4** [comment]
@ehogan @doutriaux1 should I remove all chunking by default then and let using set values in the JSON file if needed like for compression?

**Comment by doutriaux1** [comment]
I would say yes, do nothing by default and let the user decide. It's safer.

**Comment by dnadeau4** [comment]
@ehogan I fixed the chunking issues. There is no chunking unless you specify them.  Look at Test/test_chunking.py

**Comment by dnadeau4** [comment]
Actually the chunking is set here.  HDF5 also can deflate/shuffle each chunk.

https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_chunking.json#L16-L20

**Comment by ehogan** [comment]
When I run CMOR 3.2.2, the output netCDF file is 22M on disk and uses ~0.94G of memory (just like CMOR 3.1.2) :) Thank you very much!
