### ISSUE TITLE
PrePARE.py asking for (wrong) missing_values

### ISSUE THREAD

**Issue by SophieCerfacs** [PCMDI/cmor#132]
Running the PrePARE.py on my files, I get error messages like:
"CMIP6 variable gpp requires "missing_values":"1e+20"."
Indeed, my gpp variable has an attribute 
"gpp:missing_value = 1.e+20f ;" and not
"gpp:missing_values = 1.e+20f ;"

I suppose this is a bug in PrePARE.py, as missing_values with a final "s" does not conforms to the CF convention. Can you confirm and hopefully correct in a future version?

  Thank you very much!

**Comment by dnadeau4** [comment]
@SophieCerfacs It is a bug,  I fixed it to missing_value a while back.  What version are you using?

**Comment by SophieCerfacs** [comment]
Hi Denis,

My version is 3.2.1, I think. It is dated Feb 8.

I just did a git pull and I get:
[cglo765@beaufixlogin0 cmor]$ git pull
remote: Counting objects: 92, done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 92 (delta 62), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (92/92), done.
From https://github.com/PCMDI/cmor
   9e462cc..d227bf8  cmor-3.2.2 -> origin/cmor-3.2.2
Already up-to-date.

But I see no difference between my “old” PrePARE.py and the update one. Furthermore I still get the missing_values error when I use the updated one.

There is obviously something I don’t understand, sorry about that!

  Thanks,
  Sophie

On 21 Feb 2017, at 18:31, Denis Nadeau <notifications@github.com> wrote:

> @SophieCerfacs It is a bug, I fixed it to missing_value a while back. What version are you using?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---------------------------------------------------------------
Sophie Valcke

  Research Engineer
  Climate Modelling and Global Change team
  CECI UMR 5318 CNRS/CERFACS
  42 Av. G. Coriolis
  31057 Toulouse Cedex 01, FRANCE
  Tel: 05.61.19.30.76  Fax: 05.61.19.30.00

**Comment by dnadeau4** [comment]
Can you recreate your file with `cmor-3.2.2`.   I looked in every file I have and `missing_values` seems to be gone.  I found `missing_values` in version `cmor-3.2.0`

**Comment by SophieCerfacs** [comment]
Hi Denis,

I am NOT creating my files with cmor. We have a complete alternative chain based on the XIOS I/O server implemented in all components of our coupled model. Our goal is to produce directly cmor-compliant files with XIOS without any post-processing and without using cmor. 
In the files I create with XIOS, I have missing_value (and not missing_values with an s), which seems to be right to me. My problem is that when I check my files with PrePARE.py, the checker asks for missing_values (with an s). 

Here is what I get:
-----------------------
+ python /home/ext/cf/cglo/valckes/SAVE/cmor/scripts/PrePARE.py /home/ext/cf/cglo/valckes/SAVE/cmip6-cmor-tables/Tables/CMIP6_E3hr.json ./gpp_E3hr_CNRM-CM6-1_historical_r1i1p1f1_gn_1950_1950.nc

C Traceback:
In function: _CV_checkExperiment
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: Your input attribute "description" with value 
! "Created by xios" will be replaced with value "CMIP6 historical"
! as defined for experiment_id "historical".
! 
!  See Control Vocabulary JSON file.(/home/ext/cf/cglo/valckes/SAVE/cmip6-cmor-tables/Tables/CMIP6_CV.json)
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!


=====================================================================================
CMIP6 variable gpp requires "missing_values":"1e+20".
=====================================================================================


!!!!!!!!!!!!!!!!!!!!!!!!!
! Error:  The input file is not CMIP6 compliant
! Check your file or use CMOR 3.x to achieve compliance for ESGF publication.
———————————

So my current problem is with the checker PrePARE.py not with cmor per se; therefore the issue I opened.

  Thank you for your help,
  Regards,
  Sophie

On 21 Feb 2017, at 20:15, Denis Nadeau <notifications@github.com> wrote:

> Can you recreate your file with cmor-3.2.2. I looked in every file I have and missing_values seems to be gone. I found missing_values in version cmor-3.2.0
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---------------------------------------------------------------
Sophie Valcke

  Research Engineer
  Climate Modelling and Global Change team
  CECI UMR 5318 CNRS/CERFACS
  42 Av. G. Coriolis
  31057 Toulouse Cedex 01, FRANCE
  Tel: 05.61.19.30.76  Fax: 05.61.19.30.00

**Comment by dnadeau4** [comment]
I think you are using PrePARE.py with an old version of cmor.  Can you run the following commands in python?

```python
import cmip6_cv
print cmip6_cv.CMOR_VERSION_MAJOR
print cmip6_cv.CMOR_VERSION_MINOR
print cmip6_cv.CMOR_VERSION_PATCH
```

If you don't get 3.2.x,  you should recompile cmor or get it the latest from anaconda using `conda install`.

I grep in all my files, and I don't have *missing_values* anymore, only *missing_value*.

* http://cmor.llnl.gov/mydoc_cmor3_conda/

**Comment by dnadeau4** [comment]
The tag `description` is attached to the `experiment_id`.  

@taylor13 @durack1  What is the different between `description` and `experiment` in your CMIP6 Table?

I forced `description` to be attached to `experiment_id`.  Did I get this right?

**Comment by SophieCerfacs** [comment]
I did that and I get:
3
2
1
I suppose this is OK then?

To make sure I cloned and installed cmor again:
git clone https://github.com/PCMDI/cmor.git
./configure --prefix=/home/ext/cf/cglo/valckes/SAVE/cmor/cmor/here --with-uuid=/home/ext/cf/cglo/valckes/SAVE/uuid-1.6.2/usr/local --with-udunits2=/opt/softs/libraries/ICC16.1.150/udunits-2.2.20 --with-netcdf=/opt/softs/libraries/ICC16.1.150/netcdf-4.4.0
make
make install

And I still get:
3
2
1

Is this right? Should I get 3.2.2?

  Thanks

On 22 Feb 2017, at 18:51, Denis Nadeau <notifications@github.com> wrote:

> I think you are using PrePARE.py with an old version of cmor. Can you run the following commands in python?
> 
> import cmip6_cv
> print cmip6_cv.CMOR_VERSION_MAJOR
> print cmip6_cv.CMOR_VERSION_MINOR
> print cmip6_cv.CMOR_VERSION_PATCH
> If you don't get 3.2.x, you should recompile cmor or get it the latest from anaconda using conda install.
> 
> I grep in all my files, and I don't have missing_values anymore, only missing_value.
> 
> http://cmor.llnl.gov/mydoc_cmor3_conda/
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---------------------------------------------------------------
Sophie Valcke

  Research Engineer
  Climate Modelling and Global Change team
  CECI UMR 5318 CNRS/CERFACS
  42 Av. G. Coriolis
  31057 Toulouse Cedex 01, FRANCE
  Tel: 05.61.19.30.76  Fax: 05.61.19.30.00

**Comment by dnadeau4** [comment]
Ok I was able to reproduce the problem with 3.2.1.  Time for me to release 3.2.2.   ;-)

Please get version 3.2.2  

git clone -b cmor-3.2.2  https://github.com/PCMDI/cmor.git

Thanks for your help finding this...

**Comment by dnadeau4** [comment]
@SophieCerfacs Did you try 3.2.2?  Is it working for you?

**Comment by SophieCerfacs** [comment]
It takes longer than expected because I had to ask the admin system people to reinstall cmip6_cv. I will let you know!

On 23 Feb 2017, at 20:11, Denis Nadeau <notifications@github.com> wrote:

> @SophieCerfacs Did you try 3.2.2? Is it working for you?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---------------------------------------------------------------
Sophie Valcke

  Research Engineer
  Climate Modelling and Global Change team
  CECI UMR 5318 CNRS/CERFACS
  42 Av. G. Coriolis
  31057 Toulouse Cedex 01, FRANCE
  Tel: 05.61.19.30.76  Fax: 05.61.19.30.00

**Comment by senesis** [comment]
I think that the 'description' NetCDF attribute should simply be equal to the 'description' attribute in CMIP6_experiment_id.json
Example : 
        "historical":{
            "activity_id":[ "CMIP"  ],
               ......
            "description":"CMIP6 historical",
...
        "1pctCO2":{
	         ....
		"description":"DECK: 1pctCO2",

**Comment by taylor13** [comment]
"description" is included in the CV .json file only to help humans understand what the experiment is.  "description" is *not* a required global attribute (see https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit ) and like some of the other items in the experiment_id file, it really isn't considered part of controlled vocabulary.  For this reason, CMOR does not automatically write this into files and PrePARE should not check it.  A user is, of course, free to provide additional global attributes and might decide to include one named "description", but the value of "description" is not controlled in any way.

**Comment by SophieCerfacs** [comment]
Everything is fine now, I installed 3.2.2 and PrePARE.py is not asking for missing_values (with an s) anymore!
  Thanks,
   Sophie

On 23 Feb 2017, at 20:11, Denis Nadeau <notifications@github.com> wrote:

> @SophieCerfacs Did you try 3.2.2? Is it working for you?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---------------------------------------------------------------
Sophie Valcke

  Research Engineer
  Climate Modelling and Global Change team
  CECI UMR 5318 CNRS/CERFACS
  42 Av. G. Coriolis
  31057 Toulouse Cedex 01, FRANCE
  Tel: 05.61.19.30.76  Fax: 05.61.19.30.00

**Comment by SophieCerfacs** [comment]
There is still the "description" issue though (see Karl's comment). Will you release a new version of PrepARE.py not controlling the value of "description"?
  Thanks

**Comment by dnadeau4** [comment]
I will release CMOR 3.2.2 today,  I will make sure that `description` is no longer used, but `experiment`.   I got some work about  `sub_experiment`, `parent_experiment_id` and `parent_activity_id`.  As well, the `license` has changed which is always difficult to parse as a regular expression.

**Comment by dnadeau4** [comment]
@SophieCerfacs I fixed the `description` issue in PrePARE.py for version 3.2.2.
