### ISSUE TITLE
cmor tables not up-to-date wrt the CMIP6 Data Request

### ISSUE THREAD

**Issue by SophieCerfacs** [PCMDI/cmor#133]
Running PrePARE.py on my newly generated files, I get error messages like for example for my file ccldncl_Eday_CNRM-CM6-1_historical_r1i1p1f1_gn_1950_1959.nc

"You file contains "standard_name":"ccldncl" and CMIP6 tables requires "standard_name":"number_concentration_of_convective_cloud_liquid_water_particles_in_air_at_liquid_water_cloud_top"."

and 

You file contains "cell_measures":"time: mean" and
CMIP6 tables requires "cell_measures":"area: areacella".

I think this means that the cmor tables are not up-to-date as the content of my files is based on the latest version of the CMIP6 Data Request.
Please find here attached a list of such error messages I got while checking my atmospheric files for the historical run.
[list_variables_with_wrong_cell_measures_or_standard_name.txt](https://github.com/PCMDI/cmor/files/790906/list_variables_with_wrong_cell_measures_or_standard_name.txt)

**Comment by dnadeau4** [comment]
@SophieCerfacs I mixed cell_measure and cell_methods in a old version of cmor.  This should be fixed in `CMOR 3.2.2.`  I think you need to update your CMIP6 tables and CMOR. What is your cmor_version attribute in the netcdf file?

```		
:cmor_version = "3.2.2" ;
```

**Comment by SophieCerfacs** [comment]
Yes, thanks for these explanations. Indeed we also mixed cell_measure and cell_methods in our chain based on XIOS and this explains why I get the error.
Sorry about this, I close the issue!
  Thanks a lot
