### ISSUE TITLE
Using CMOR_REPLACE and CMOR_REPLACE_3 as the value of netcdf_file_action in the call to cmor.setup does different things

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#134]
According to the [documentation](http://cmor.llnl.gov/mydoc_cmor3_api/#cmorsetup) for the `netcdf_file_action` argument for `cmor.setup`, `The default values (no underscore) are aliased to the _3 values`. However, when I use `netcdf_file_action=CMOR_REPLACE` in the call to `cmor.setup`, CMOR produces an output netCDF file with the format `netCDF-4 classic model` (and introduces chunking), but when I use `CMOR_REPLACE_3`, the format is `classic`.

Would it be possible for you to confirm whether the documentation is correct, or whether the code is correct, please?

**Comment by ehogan** [comment]
The fifth bullet point on http://cmor.llnl.gov/#design-considerations-and-overview may also need updating.

**Comment by dnadeau4** [comment]
I will change the documentation,  the default is now NetCDF-4 classic model
https://github.com/PCMDI/cmor/blob/master/include/cmor.h#L46-L48
```C
#define CMOR_PRESERVE CMOR_PRESERVE_4
#define CMOR_APPEND CMOR_APPEND_4
#define CMOR_REPLACE CMOR_REPLACE_4
```

**Comment by dnadeau4** [comment]
I changed the documentation.  Scripts to update runs every hour. `:00`
https://github.com/PCMDI/cmor3_documentation/pull/29
