### ISSUE TITLE
CMOR 3.2.2 doesn't include chunking fixes or 01.00.03 MIP tables

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#137]
https://github.com/PCMDI/cmor/releases states that there have been 3 changes to master since CMOR 3.2.2 was released; these changes include the chunking fixes and the 01.00.03 MIP tables, see, e.g. https://github.com/PCMDI/cmor/blob/CMOR-3.2.2/Src/cmor.c#L2045 and https://github.com/PCMDI/cmor/blob/CMOR-3.2.2/TestTables/CMIP6_AERday.json. According to the release notes, these changes should have been included.

**Comment by dnadeau4** [comment]
It is there. 
https://github.com/PCMDI/cmor/blob/cmor-3.2.2/Src/cmor.c#L2045

**Comment by dnadeau4** [comment]
You type CMOR-3.2.2 instead of cmor-3.2.2,  I just moved the tag CMOR-3.2.2 to master.

**Comment by ehogan** [comment]
Ah, I was using just `3.2.2`, which is now different to `CMOR-3.2.2` (see https://github.com/PCMDI/cmor/tags); could the `3.2.2` tag be updated too, please? :)

**Comment by dnadeau4** [comment]
Just did, I must have create the tag before pushing my last update.

**Comment by ehogan** [comment]
Wonderful, thank you very much! :)
