### ISSUE TITLE
cmor.load_table('CMIP6_grids.json') in CMOR 3.2.1 generates warning about cf_version

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/cmor#141]
When calling cmor.load_table('CMIP6_grids.json') in CMOR 3.2.1, a warning is generated about the cf_version element of the JSON file. The message is:

```
Warning: table: , This keyword: cf_version value (table: , This keyword: cf_version) is not a valid table header entry.!
 Use the user input JSON file to add custom attributes.
```
If I delete the cf_version entry from the Header section of the CMIP6_grids.json file, no warning is displayed. It seems that either the code or the file should be changed.

**Comment by dnadeau4** [comment]
I saw that too, It must be something in the Table header that was left over.  I did not find it yesterday and  had to release.

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_grids.json#L4

I fixed this in 
https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables

**Comment by JimBiardCics** [comment]
Did a new pull and found that everything is peachy now. Thanks!
