### ISSUE TITLE
can't import PrePARE

### ISSUE THREAD

**Issue by sashakames** [PCMDI/cmor#142]
PrePARE.py is still in in /bin but not installed as a site-package
@dnadeau4 started investigating and knows why

**Comment by dnadeau4** [comment]
I changed `setup.py` and forgot to change `setup.py.in` and my entry_point was lost.  Thanks for notifying me.  I will recreate it in `setup.py.in` this time.

**Comment by dnadeau4** [comment]
in CMOR3.2.3 you will be able to `import` PrePARE this way.
```python
import cmip6_cv.PrePARE
```

Here is how to run it.
```python
>>> cmip6_cv.PrePARE.main()
usage: PrePARE [-h] [--variable VARIABLE] cmip6_table infile [outfile]
PrePARE: error: too few arguments
1
```

**Comment by dnadeau4** [comment]
This has been fixed in CMOR 3.2.3

**Comment by sashakames** [comment]
Thanks.  Looking forward to the pushed update (still on the pcmdi channel?)

**Comment by dnadeau4** [comment]
Yep,  I just updated the channel.  I will send the notification before the end of the day.
