### ISSUE TITLE
json/yaml output?

### ISSUE THREAD

**Issue by cehbrecht** [PCMDI/cmor#143]
It would be nice if the cmor checker has (optional) json or yaml output with the check results. This json document could then easily be evaluated by other tools for further steps.

For example, the ioos compliance checker supports text, html and json output, see the docs:

https://github.com/ioos/compliance-checker/blob/master/README.md

**Comment by dnadeau4** [comment]
@cehbrecht You are right, it would look much better, I'll try to get to it, but I am really busy with other major issues.

**Comment by doutriaux1** [comment]
@cehbrecht I cocnur with @dnadeau4 that this would be awesome to have! Unfortunately @dnadeau4 and I are quite oversubscribed at the moment, any chance you could submit a PR for this?

**Comment by cehbrecht** [comment]
@doutriaux1 
i'm also busy ;) But it would be nice to have a "structured" output which can be used by other tools for evaluation ... html output is optional.

Maybe i will have a look at it and come back with a suggestion (PR).

**Comment by doutriaux1** [comment]
Thanks @cehbrecht! Hopefully one of us can get to this soon!

**Comment by dnadeau4** [comment]
@cehbrecht I looked at the code and might be able to create a plugin like Glider DAC did.  No promise  thougj. :smirk:

**Comment by dnadeau4** [comment]
I have looked into this and @taylor13 will tell me if he wants an plugin for CMIP6 into https://github.com/ioos/compliance-checker/blob/master/README.md

**Comment by cehbrecht** [comment]
@dnadeau4 
would be nice to have compliance-checker plugin :) By this we would have a common way to use and also to implement all these checking tools.

**Comment by dnadeau4** [comment]
This is not a priority and we will close this issue at the moment.  We might re-open it at a later date.
