### ISSUE TITLE
QA checks for CMOR and PrePARE

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#145]
See this document:
[CMOR_PrePARE_QA_checks.pdf](https://github.com/PCMDI/cmor/files/849323/CMOR_PrePARE_QA_checks.pdf)
Revised: 3/22/17
[CMOR_PrePARE_QA_checks.pdf](https://github.com/PCMDI/cmor/files/862555/CMOR_PrePARE_QA_checks.pdf)

**Comment by durack1** [comment]
@taylor13 is this document available through google docs or an equivalent web-browse-able link?

**Comment by taylor13** [comment]
@durack1  nope.  I just completed it and am waiting for feedback from Denis.  Do you want to make some suggestions before then?  If so, I could email the word doc to you.

**Comment by durack1** [comment]
@taylor13 might I suggest a copy and paste into google docs.. It might save our inboxes

**Comment by dnadeau4** [comment]
@taylor13 @durack1 I will implement the QA_checks document into CMOR tomorrow.  

1. Am I allowed to run the CF-1 compliance program and distribute it?
2. I will check if I have test for all those cases
3. This part is new and need to be implemented.
4. Need to be implemented. I need to check what is timerange for fx files.

**Comment by dnadeau4** [comment]
Ok,  I have dones 2,3,4, but not 1 since I don't think I am allow to distribute other people software.
