### ISSUE TITLE
Precision of coordinates

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#147]
The file:
```
$ ncdump /cmip5_css02/data/cmip5/output1/IPSL/IPSL-CM5A-LR/historical/mon/ocean/Omon/r1i1p1/so/1/so_Omon_IPSL-CM5A-LR_historical_r1i1p1_195001-199912.nc | more
```
includes the following weird values:
```
$ ncdump /cmip5_css02/data/cmip5/output1/IPSL/IPSL-CM5A-LR/historical/mon/ocean/Omon/r1i1p1/so/1/so_Omon_IPSL-CM5A-LR_historical_r1i1p1_195001-199912.nc | more                                                                                    
netcdf so_Omon_IPSL-CM5A-LR_historical_r1i1p1_195001-199912 {
dimensions:
        time = UNLIMITED ; // (600 currently)
        lev = 31 ;
        j = 149 ;
        i = 182 ;
        bnds = 2 ;
        vertices = 4 ;
variables:
...
 lev = 4.99993801116943, 15.0002880096436, 25.0017585754395,
    35.0054130554199, 45.0133171081543, 55.0294990539551, 65.0618057250977,
    75.1255111694336, 85.2503662109375, 95.4942855834961, 105.969917297363,
    116.896240234375, 128.697906494141, 142.195251464844, 158.96061706543,
    181.962783813477, 216.647918701172, 272.476715087891, 364.303039550781,
    511.534759521484, 732.200866699219, 1033.21728515625, 1405.69750976562,
    1830.88500976562, 2289.76782226562, 2768.24243164062, 3257.47875976562,
    3752.44213867188, 4250.4013671875, 4749.9130859375, 5250.2265625 ;

 lev_bnds =
  0, 10.0000152587891,
  10.0000152587891, 20.0008335113525,
  20.0008335113525, 30.0032157897949,
  30.0032157897949, 40.0086441040039,
  40.0086441040039, 50.0200042724609,
  50.0200042724609, 60.0429153442383,
  60.0429153442383, 70.0883331298828,
  70.0883331298828, 80.1775665283203,
  80.1775665283203, 90.3521270751953,
  90.3521270751953, 100.692794799805,
  100.692794799805, 111.356666564941,
  111.356666564941, 122.648773193359,
  122.648773193359, 135.159744262695,
  135.159744262695, 150.026809692383,
  150.026809692383, 169.415969848633,
  169.415969848633, 197.367782592773,
  197.367782592773, 241.125930786133,
  241.125930786133, 312.744659423828,
  312.744659423828, 429.723358154297,
  429.723358154297, 611.889099121094,
  611.889099121094, 872.873779296875,
  872.873779296875, 1211.58801269531,
  1211.58801269531, 1612.97570800781,
  1612.97570800781, 2057.13134765625,
  2057.13134765625, 2527.216796875,
  2527.216796875, 3011.8994140625,
  3011.8994140625, 3504.455078125,
  3504.455078125, 4001.15893554688,
  4001.15893554688, 4500.021484375,
  4500.021484375, 5000,
  5000, 5500.453125 ;
```
And similar precision-like occurrences with the lat and lon values

I wonder whether a warning should be thrown to a user? @dnadeau4 for additional test cases, many CMIP5 datasets can be found at crunch:/work/cmip5/

@taylor13 @dnadeau4 what behavior should be undertaken here?

**Comment by taylor13** [comment]
@durack1  @dnadeau4   
Are the values wrong or just odd?  
Is lev a dimensionless (parametric) vertical coordinate or actual depth?
I presume vertices applies to the horizontal grid.
In any case I don't think CMOR could answer these questions, so would not know how to respond.

**Comment by dnadeau4** [comment]
This is a data provider problem.  Not sure how to proceed.

**Comment by durack1** [comment]
@dnadeau4 let's reopen this and consider the idea of issuing a warning to a user indicating these values are unusual.. I'll move to `3.2.4`

**Comment by dnadeau4** [comment]
@durack1 give me some kind of algorithm on how to do this...  Here is a valid projection as an example.  https://www.dropbox.com/s/ugzw3ctjth14vab/orog_GIS_LGGE_ELMER2_asmb.nc?dl=0

How can we make the warning valid in every cases.

**Comment by dnadeau4** [comment]
@durack1 you should try `ncdump -p 4 -v tas` to display only 4 digits.  It does round up.

**Comment by dnadeau4** [comment]
There is nothing i can do here,  the data provider has to pass the data to cmor.  I am not playing with model output just pass it to netCDF.

**Comment by durack1** [comment]
@dnadeau4 my hope was that these values could be written to a warning, so that a user knows they are writing ***very weird*** values to their output file..

**Comment by dnadeau4** [comment]
what is the algorithm to trigger the warning?  How many digits, some variable are very small and other are very big....

**Comment by durack1** [comment]
@dnadeau4 good question, @taylor13 @doutriaux1 any ideas?

**Comment by doutriaux1** [comment]
@durack1 only half-baked ones

**Comment by taylor13** [comment]
My idea is to close this issue and move on.  We have more important things to do than trying to guess what is user error and what is user intent.
