### ISSUE TITLE
Catching invalid specified grids

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#148]
@dnadeau4 the following file was generated using `CMOR 2.7.1`:
```
ncdump -c /cmip5_css02/data/cmip5/output1/BNU/BNU-ESM/historical/fx/atmos/fx/r0i0p0/sftlf/1/sftlf_fx_BNU-ESM_historical_r0i0p0.nc | more                                                      
netcdf sftlf_fx_BNU-ESM_historical_r0i0p0 {                                                                                             
dimensions:                                                                                                                             
        lat = 64 ;                                                                                                                      
        lon = 128 ;                                                                                                                     
        bnds = 2 ;                                                                                                                      
variables:                                                                                                                              
        double lat(lat) ;                                                                                                               
                lat:bounds = "lat_bnds" ;                                                                                               
                lat:units = "degrees_north" ;                                                                                           
                lat:axis = "Y" ;                                                                                                        
                lat:long_name = "latitude" ;                                                                                            
                lat:standard_name = "latitude" ;                                                                                        
        double lat_bnds(lat, bnds) ;                                                                                                    
        double lon(lon) ;                                                                                                               
                lon:bounds = "lon_bnds" ;                                                                                               
                lon:units = "degrees_east" ;                                                                                            
                lon:axis = "X" ;                                                                                                        
                lon:long_name = "longitude" ;                                                                                           
                lon:standard_name = "longitude" ;                                                                                       
        double lon_bnds(lon, bnds) ;                                                                                                    
        float sftlf(lat, lon) ;                                                                                                         
                sftlf:standard_name = "land_area_fraction" ;                                                                            
                sftlf:long_name = "Land Area Fraction" ;                                                                                
                sftlf:units = "%" ;                                                                                                     
                sftlf:cell_measures = "area: areacella" ;                                                                               
                sftlf:history = "2012-11-15T09:15:43Z altered by CMOR: replaced missing value flag (1e+30) with standard missing value (
1e+20)." ;                                                                                                                              
                sftlf:missing_value = 1.e+20f ;                                                                                         
                sftlf:_FillValue = 1.e+20f ;                                                                                            
                sftlf:associated_files = "baseURL: http://cmip-pcmdi.llnl.gov/CMIP5/dataLocation gridspecFile: gridspec_atmos_fx_BNU-ESM
_historical_r0i0p0.nc areacella: areacella_fx_BNU-ESM_historical_r0i0p0.nc" ;                                                           

// global attributes:
                :institution = "GCESS,BNU,Beijing,China" ;
                :institute_id = "BNU" ;                   
                :experiment_id = "historical" ;           
                :source = "BNU-ESM" ;                     
                :model_id = "BNU-ESM" ;                   
                :forcing = "Nat,Ant" ;                    
                :parent_experiment_id = "piControl" ;     
                :parent_experiment_rip = "r1i1p1" ;       
                :branch_time = 0. ;                       
                :contact = "Ji Duoying (duoyingji@bnu.edu.cn)" ;
                :initialization_method = 0 ;
                :physics_version = 0 ;
                :tracking_id = "07552e34-e98b-4e07-80e9-c6ca97fbb1e8" ;
                :product = "output" ;
                :experiment = "historical" ;
                :frequency = "fx" ;
                :creation_date = "2012-11-15T09:15:43Z" ;
                :history = "2012-11-15T09:15:43Z CMOR rewrote data to comply with CF standards and CMIP5 requirements." ;
                :Conventions = "CF-1.4" ;
                :project_id = "CMIP5" ;
                :table_id = "Table fx (26 July 2011) 491518982c8d8b607a58ba740689ea09" ;
                :title = "BNU-ESM model output prepared for CMIP5 historical" ;
                :parent_experiment = "pre-industrial control" ;
                :modeling_realm = "atmos" ;
                :realization = 0 ;
                :cmor_version = "2.7.1" ;
data:

 lat = -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281,
    -87.8638000488281, -87.8638000488281, -87.8638000488281, -87.8638000488281 ;

 lon = 0, 2.8125, 5.625, 8.4375, 11.25, 14.0625, 16.875, 19.6875, 22.5,
    25.3125, 28.125, 30.9375, 33.75, 36.5625, 39.375, 42.1875, 45, 47.8125,
    50.625, 53.4375, 56.25, 59.0625, 61.875, 64.6875, 67.5, 70.3125, 73.125,
    75.9375, 78.75, 81.5625, 84.375, 87.1875, 90, 92.8125, 95.625, 98.4375,
    101.25, 104.0625, 106.875, 109.6875, 112.5, 115.3125, 118.125, 120.9375,
    123.75, 126.5625, 129.375, 132.1875, 135, 137.8125, 140.625, 143.4375,
    146.25, 149.0625, 151.875, 154.6875, 157.5, 160.3125, 163.125, 165.9375,
    168.75, 171.5625, 174.375, 177.1875, 180, 182.8125, 185.625, 188.4375,
    191.25, 194.0625, 196.875, 199.6875, 202.5, 205.3125, 208.125, 210.9375,
    213.75, 216.5625, 219.375, 222.1875, 225, 227.8125, 230.625, 233.4375,
    236.25, 239.0625, 241.875, 244.6875, 247.5, 250.3125, 253.125, 255.9375,
    258.75, 261.5625, 264.375, 267.1875, 270, 272.8125, 275.625, 278.4375,
    281.25, 284.0625, 286.875, 289.6875, 292.5, 295.3125, 298.125, 300.9375,
    303.75, 306.5625, 309.375, 312.1875, 315, 317.8125, 320.625, 323.4375,
    326.25, 329.0625, 331.875, 334.6875, 337.5, 340.3125, 343.125, 345.9375,
    348.75, 351.5625, 354.375, 357.1875 ;
}
```
It seems the longitude values are repeated, and do not span the -90 to 90 range that you would expect. It would be useful for CMOR to throw a warning in this case.

When plotted `VCS` tries pretty hard
![cmip5 bnu-esm historical r0i0p0 fx atm fx sftlf ver-1 latestx](https://cloud.githubusercontent.com/assets/3229632/24381612/070829a2-1306-11e7-91ac-ea918e280d3e.png)

**Comment by durack1** [comment]
@dnadeau4 and here is another issue, upside down grid:
![cmip5 ec-earth historical r0i0p0 fx atm fx sftlf ver-v20130211](https://cloud.githubusercontent.com/assets/3229632/24381618/1350c8ea-1306-11e7-9148-755eb123f21d.png)

**Comment by taylor13** [comment]
I thought we trapped both types of errors: 1) coordinates that do not increase or decrease monotonically, and 2) coordinates increasing in the right direction.  How do you explain the above results?

**Comment by durack1** [comment]
@taylor13 remember this is `CMOR 2.7.1` so @dnadeau4 has no need to explain these results.. We just need to make sure that `CMOR3` doesn't write such data..

**Comment by taylor13** [comment]
Understood, but I'm pretty sure both CMOR1 & CMOR2 included these checks, so it would be nice to double check those parts of the code are intact and working properly.

**Comment by dnadeau4** [comment]
@durack1  I cannot change the input values from the data providers.  What you see is they did not care enough to round their `lat/lon` values to an appropriate values.  For projections in "meters" it make senses to have such precise `lat/lon` or for land people working on a small area.

**Comment by durack1** [comment]
@dnadeau4 I never wanted you to change values, just throw a warning for such cases.. It's best to not let these kind of errors propagate without notifying the user

**Comment by dnadeau4** [comment]
@durack1 how many decimal should I used to trigger a warning?

**Comment by durack1** [comment]
@dnadeau4 I think the same number as your previous fix (for cdms), was that 4 (https://github.com/PCMDI/cmor/issues/146)?

**Comment by dnadeau4** [comment]
@durack1 your upside-down picture looks like a vcs issue,  the lat/lon are find but they have 80S on the top.  not sure why.

**Comment by durack1** [comment]
@dnadeau4 I think specifying another warning would be a good idea, so warning that the left, lower (index 0,0) value is starts at the southern-most bound.. That is uniform across all CMIP5 contributed data APART from this model

**Comment by dnadeau4** [comment]
@doutriaux1 why vcs did not flip the picture above?

**Comment by taylor13** [comment]
@dnadeau4 @durack1 Note that the first file above was *not* written my CMOR.  CMOR would have trapped this error (both then and now.)  PrePARE, on the other hand isn't yet checking the order of coordinates, so wouldn't notice this problem.

I don't know why VCS isn't smart enough to put the S. Pole at the bottom of the plot.

I don't think there is anything we need to do now as far as modifying CMOR or PrePARE, but sometime in the next 6 months it would be nice for PrePARE to trap this sort of thing.

**Comment by dnadeau4** [comment]
This is a VCS problem

**Comment by durack1** [comment]
@dnadeau4 the issue is that `CMOR 2.7.1` allowed the invalid grid to be written to a file [see above](https://github.com/PCMDI/cmor/issues/148#issue-217397601), I'll set it for the next milestone - I wanted to make sure that such issues were caught in `CMOR 3.2.3+` and such invalid grids are not generated by CMOR

**Comment by durack1** [comment]
@dnadeau4 for the [top problem, all `lats` are identical]:
```
In [35]: a = [-87.8638000488281, -87.8638000488281, -87.8638000488281,
    ...:     -87.8638000488281, -87.8638000488281, -87.8638000488281,
    ...:     -87.8638000488281, -87.8638000488281, -87.8638000488281,
    ...:     -87.8638000488281, -87.8638000488281, -87.8638000488281,
...
    ...:     -87.8638000488281, -87.8638000488281, -87.8638000488281, -87.863800048828]
In [36]: 
In [37]: for count in range(0,len(a)):
    ...:     print a[count]-a[count+1]   
0.0
0.0
0.0
...
```
So that's a simple problem

**Comment by dnadeau4** [comment]
@taylor13 PrePARE was meant to be for metadata not data.  This is beyond PrePARE scope in my opinion.

**Comment by durack1** [comment]
@dnadeau4 for the second one, the `lat` ***should be stored*** smallest (southern negative value) to largest (northern positive value), if the order is not this way an error could be thrown..

**Comment by taylor13** [comment]
@durack1   All versions of CMOR would trap (and I think correct) this error.  PrePARE is currently checking file-level metadata (not variable or dimension stuff).  There are lots of additional things for PrePARE to check, but for now we need to make sure it is working flawlessly on the things it checks.

**Comment by durack1** [comment]
@taylor13 if you look at the [`global_atts` for the first file](https://github.com/PCMDI/cmor/issues/148#issue-217397601), it indicates that `:cmor_version = "2.7.1"` was used to write the file.. Admittedly this is not `CMOR3`, but I am curious if a test in `2.7.1` which appears to not have worked is now functioning correctly..

**Comment by taylor13** [comment]
Presence of "cmor_version="2.7.1" doesn't guarantee use of CMOR.  That being said, perhaps we should check that the code checks monotonicity by requiring a coord. value to be ">" and not just ">=" the previous coord. value.

**Comment by dnadeau4** [comment]
CMOR check if every axis it creates is monotonic. 
https://github.com/PCMDI/cmor/blob/master/Src/cmor_axes.c#L1363-L1364

**Comment by taylor13** [comment]
Reviewing Charle's code, I see in line 737:  
if( ( ( values[i] - values[i + 1] ) / ( values[i + 1] - values[i + 2] ) ) <  0. )

This leads to a divide by zero if consecutive values are equal.  Could this explain why the error in the output file wasn't caught?  One fix would be to replace "/" with "*"  (multiply instead of divide) and replace "<" with "<=".  

Also, will there be a problem if the length of the coordinate variable is less than 3?  Won't values[I+2] be undefined in this case?  Or is the "for loop" skipped in this case?

Denis, could you please review this and perhaps also prepare a test that would check what happens if you pass coordinate values that are identical?

**Comment by dnadeau4** [comment]
@doutriaux1

**Comment by dnadeau4** [comment]
Fixed monotonic issue in 3.2.6.  @durack1 @doutriaux1 any idea on the reverse image?

**Comment by durack1** [comment]
@dnadeau4 the upside down image https://github.com/PCMDI/cmor/issues/148#issuecomment-289610732 above would just be a check to make sure that latitude values ***increase*** monotonically, rather than ***decreasing***

**Comment by doutriaux1** [comment]
@durack1 @dnadeau4 data are stored from North to South, so vcs plots them reversed. That's what the user asked to plot.

**Comment by dnadeau4** [comment]
I think the user is right and wanted that picture reverse.  I cannot change his decision, his latitudes are valid in a CF-1 compliance way.

**Comment by durack1** [comment]
@dnadeau4 @doutriaux1 this is against the standard convention of CMIP data (the 30+ models in the CMIP5 suite vs this one), it's not wrong, just not standard. As I noted above, I think a warning would be useful, so that the user is made aware they are going again the standard protocol, however the data are not an error

**Comment by doutriaux1** [comment]
@durack1 I was just talking in the context of vcs. CMIP does require South to North so I'm assuming CMOR will flip the latitudes. Correct @dnadeau4 ?

**Comment by dnadeau4** [comment]
Karl and I verified that CMOR check for South to North and CMOR will change the axis direction.  There is metadata called "stored_direction" which is set to "increasing".  @doutriaux1 must remember it.

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/cmor/blob/master/Src/cmor_axes.c#L804-L831

**Comment by taylor13** [comment]
All CMOR issues raised here have been addressed. Let's close it.
