### ISSUE TITLE
Problems getting latest from conda channel

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#149]
@dnadeau4 it seems that the PCMDI conda channel is not serving up the latest `cmor-3.2.2`:
```
(cmor3) [170118_PaperPlots_input4MIPs]:[3999]> conda update cmor
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /export/duro/anaconda2/envs/cmor3:
#
cmor                      3.1.2                     PCMDI    pcmdi
```

**Comment by dnadeau4** [comment]
try `conda install cmor -c pcdmi` instead

**Comment by durack1** [comment]
@dnadeau4 my environments were just messed up with a machine rebuild, so will close this.. I'm not sure the conda `update` is working correctly however

**Comment by dnadeau4** [comment]
I think the `update` command does not work, but you can do `install` with all the channel and it will update to the latest version.

**Comment by durack1** [comment]
@dnadeau4 it seems this issue has reappeared:
```
(cdatcmornclnco) durack1@oceanonly:[~]:[4284]> conda install -c conda-forge -c uvcdat -c pcmdi cmor
Fetching package metadata ...............
Solving package specifications: .
Package plan for installation in environment /export/durack1/anaconda2/envs/cdatcmornclnco:
The following NEW packages will be INSTALLED:
    cmor:      3.1.3-np111py27_2 uvcdat
The following packages will be DOWNGRADED due to dependency conflicts:
    libnetcdf: 4.4.1.1-4         conda-forge --> 4.4.1-0 conda-forge
```

**Comment by durack1** [comment]
@dnadeau4 the issue is the `-c uvcdat`:
```
(cdatcmornclnco) durack1@oceanonly:[~]:[4285]> conda install -c conda-forge -c pcmdi cmor
Fetching package metadata .............
Solving package specifications: .
Package plan for installation in environment /export/durack1/anaconda2/envs/cdatcmornclnco:
The following NEW packages will be INSTALLED:
    cmor:      3.2.2-np111py27_0 pcmdi
The following packages will be DOWNGRADED due to dependency conflicts:
    libnetcdf: 4.4.1.1-4         conda-forge --> 4.4.1-0 conda-forge
```

**Comment by durack1** [comment]
@dnadeau4 I also wonder about the netcdf library version, it would be good to bump that up for the `3.2.3` release, as `netcdf 4.4.1.1` is now out

**Comment by durack1** [comment]
@dnadeau4 ok the way to solve this is to purge the `cmor` files on https://anaconda.org/uvcdat/cmor/files - these were uploaded by @doutriaux1 and should just be purged

**Comment by dnadeau4** [comment]
So I deleted the files cmor 3.1.3 and moved the old ones to pcmdi.  I did changed the label to v2.9 for now on the uvcdat channels just in case some ask for it.

**Comment by durack1** [comment]
@dnadeau4 this should be ok then.. I think this should resolve my issue, although if folks reference `-c uvcdat` they will not get `CMOR3`..
