### ISSUE TITLE
Error after closing 3D variable

### ISSUE THREAD

**Issue by goord** [PCMDI/cmor#150]
After closing the 2nd 3d (hybrid model levels) variable in the Amon table (the first always passes without problems), cmor complains about the surface pressure not being written. However, I have written the surface pressure after each write of cli, with the appropriate storevar argument...
```
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: while closing variable 14 (clw, table Amon) we
! noticed it has a time varying associated
! variable, you wrote 1 time steps for the
! variable, but its associated variable 12 (ps)
! has 0 times written
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by dnadeau4** [comment]
@goord Can you send me your scripts? I would like to reproduce this issue. 
Thanks!

**Comment by dnadeau4** [comment]
@goord It seems that you don't write the "ps" data for each time step.  Please take a look at this example:

https://github.com/PCMDI/cmor/blob/master/Test/test_sophie.f90#L315-L347

where zfactor_id is defined as "ps"
https://github.com/PCMDI/cmor/blob/master/Test/test_sophie.f90#L262-L266

**Comment by goord** [comment]
Apparently I had a copy of the surface pressure id associated to my variable, which was not written along with it, so the problem was in my part of the code. PS, the code I am working on is [https://github.com/goord/ece2cmor3](url)

**Comment by dnadeau4** [comment]
Excellent!!
