### ISSUE TITLE
Shape mismatch error with 2D histograms

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/cmor#151]
I would like to re-write 2D histograms ( cloud-top-pressure vs cloud-optical-thickness) using cmor:

    import cmor
    import numpy as np
    
    cmor.setup(netcdf_file_action=cmor.CMOR_REPLACE)
    cmor.dataset_json('Tables/user_input.json')
    cmor.load_table('Tables/CMIP6_Amon.json')
    
    # Generate dummy data
    time = np.array([0, 30, 60])
    time_bounds = np.array([[0, 30],
                            [30, 60],
                            [60, 90]])
    
    grid_resol = 1
    max_latlon = 3
    lon = np.arange(0, max_latlon, grid_resol)
    lon_bounds = np.vstack((lon, lon+grid_resol)).transpose()
    lat = np.arange(0, max_latlon, grid_resol)
    lat_bounds = np.vstack((lat, lat+grid_resol)).transpose()
    
    tau_bin_centres = np.array([0, 1, 2])
    tau_bin_bounds = np.array([[0, 1],
                               [1, 2],
                               [2, 3]])
    
    p_bin_centres = np.array([700, 800, 900])
    p_bin_bounds = np.array([[700, 800],
                             [800, 900],
                             [900, 1000]])
    
    
    jch = np.ones((1, p_bin_centres.size, tau_bin_centres.size,
                   lat.size, lon.size))
    
    # Define axes
    cmor_time = cmor.axis(table_entry='time',
                          units='days since 1970-01-01 00:00')
    cmor_p = cmor.axis(table_entry='p1000',
                       units='hPa',
                       length=p_bin_centres.size,
                       coord_vals=p_bin_centres,
                       cell_bounds=p_bin_bounds)
    cmor_tau = cmor.axis(table_entry='tau',
                         units='1',
                         length=tau_bin_centres.size,
                         coord_vals=tau_bin_centres,
                         cell_bounds=tau_bin_bounds)
    cmor_lon = cmor.axis(table_entry='longitude',
                         units='degrees_east',
                         length=lon.size,
                         coord_vals=lon,
                         cell_bounds=lon_bounds)
    cmor_lat = cmor.axis(table_entry='latitude',
                         units='degrees_north',
                         length=lat.size,
                         coord_vals=lat,
                         cell_bounds=lat_bounds)
    
    # Define variables
    cmor_jch = cmor.variable(table_entry='jch',
                             units='1',
                             axis_ids=[cmor_time, cmor_p, cmor_tau, cmor_lat,
                                       cmor_lon])
    
    # Write data
    for i in range(time.size):
        print time[i], time_bounds[i]
    
        cmor.write(var_id=cmor_jch,
                   data=jch[:].astype('f4'),
                   ntimes_passed=1,
                   time_vals=time[i],
                   time_bnds=time_bounds[i])
    filename = cmor.close(cmor_jch, file_name=True)

This works fine until I increase `max_latlon` beyond 3. Then I get the following error:

    File "...pywrapper.py", line 640, in write
        raise Exception,"Error: your data shape (%s) does not match the expected variable shape (%s)\nCheck your variable dimensions before caling cmor_write" % (str(osh),str(ogoodshape))
    Exception: Error: your data shape ((1, 3, 3, 4, 4)) does not match the expected variable shape ([0, 3, 4, 4])
    Check your variable dimensions before caling cmor_write

**Comment by Funkensieper** [comment]
P.S. I added the following variable definition to `CMIP6_Amon.json`:

        "jch": {
            "modeling_realm": "atmos",
            "standard_name": "atmosphere_optical_thickness_due_to_cloud_and_air_pressure_at_cloud_top_histogram",
            "units": "1",
            "cell_methods": "area: time: histogram",
            "cell_measures": "area: areacella",
            "long_name": "Joint histogram of cloud optical thickness and cloud top pressure",
            "dimensions": "longitude latitude tau p1000 time",
            "out_name": "jch",
            "type": "real",
            "positive": "",
            "valid_min": "",
            "valid_max": "",
            "ok_min_mean_abs": "",
            "ok_max_mean_abs": ""

**Comment by Funkensieper** [comment]
Sorry, my bad. Using variable ``clisccp`` from table ``CF_Amon`` (with the expected coordinate values and bounds) works just fine. I must have broken something when editing the CMIP tables.

**Comment by dnadeau4** [comment]
@Funkensieper happy to hear about this,  these error message are usually about dimensions.
