### ISSUE TITLE
cmor.close() does not work on NAS drive

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/cmor#153]
I'm having trouble deleting the cmor output directory if it is located on a NAS drive. Although I'm calling cmor.close(), a file handle remains open which prevents the directory from being deleted. Here is a minimal example:

    import cmor
    import numpy as np
    import shutil
    
    cmor.setup(netcdf_file_action=cmor.CMOR_REPLACE)
    cmor.dataset_json('Tables/user_input.json')
    cmor.load_table('Tables/CMIP6_Amon.json')
    
    
    time = np.array([0, 30, 60])
    time_bounds = np.array([[0, 30],
                            [30, 60],
                            [60, 90]])
    lon = np.array([1, 2, 3])
    lon_bounds = np.array([[0, 1],
                           [1, 2],
                           [2, 3]])
    lat = lon.copy()
    lat_bounds = lon_bounds.copy()
    clt = np.ones((time.size, lat.size, lon.size))
    
    cmor_time = cmor.axis(table_entry='time',
                          units='days since 1970-01-01 00:00',
                          length=time.size,
                          coord_vals=time,
                          cell_bounds=time_bounds)
    cmor_lon = cmor.axis(table_entry='longitude',
                         units='degrees_east',
                         length=lon.size,
                         coord_vals=lon,
                         cell_bounds=lon_bounds)
    cmor_lat = cmor.axis(table_entry='latitude',
                         units='degrees_north',
                         length=lat.size,
                         coord_vals=lat,
                         cell_bounds=lat_bounds)
    cmor_clt = cmor.variable(table_entry='clt',
                             units='1',
                             axis_ids=[cmor_time, cmor_lat, cmor_lon])
    
    cmor.write(var_id=cmor_clt, data=clt.astype('f4'))
    
    filename = cmor.close(cmor_clt, file_name=True)
    cmor.close()
    shutil.rmtree('output')

The traceback is:

    ! ------
    ! All files were closed successfully. 
    ! ------
    ! Traceback (most recent call last):
      File ".../test.py", line 46, in <module>
	shutil.rmtree('output')
      File "/cmsaf/nfshome/routcm/Modules_sw/python/2.7.13/lib/python2.7/shutil.py", line 247, in rmtree
	rmtree(fullname, ignore_errors, onerror)
      File "/cmsaf/nfshome/routcm/Modules_sw/python/2.7.13/lib/python2.7/shutil.py", line 247, in rmtree
	rmtree(fullname, ignore_errors, onerror)
      File "/cmsaf/nfshome/routcm/Modules_sw/python/2.7.13/lib/python2.7/shutil.py", line 252, in rmtree
	onerror(os.remove, fullname, sys.exc_info())
      File "/cmsaf/nfshome/routcm/Modules_sw/python/2.7.13/lib/python2.7/shutil.py", line 250, in rmtree
	os.remove(fullname)
    OSError: [Errno 16] Device or resource busy: 'output/Amon/clt/.nfs000000000016865700000598'

I can verify that the python script is blocking the file:
    
    $ fuser output/Amon/clt/.nfs000000000016865700000598
    output/Amon/clt/.nfs000000000016865700000598: 26514
    $ ps aux | grep 26514
    sfinkens 26514  0.2  2.7 853360 452120 pts/13  S+   13:48   0:00 /cmsaf/nfshome/routcm/Modules_sw/python/2.7.13/bin/python .../test.py

**Comment by dnadeau4** [comment]
We do call nc_close on every files that are opened, except when CMOR crash, I think the `temporary` file is not closed properly.

Do you know what is the `./.nfs*` file doing?  

Can you try this command to find which `netcdf` files are opened?
```bash
lsof | grep \.nc$ 
```

Here code from CMOR closing all files.
```C
  for( i = 0; i < cmor_nvars + 1; i++ ) {
	if( cmor_vars[i].initialized != -1 ) {
	    if( cmor_vars[i].closed == 0 ) {
	        cmor_close_variable( i, NULL, NULL );
        }
    }
}
```

**Comment by Funkensieper** [comment]
Here is a nice explanation what ``.nfs`` files are for: https://uisapp2.iu.edu/confluence-prd/x/_YJjBw
The ``lsof`` command does not print anything. If I kill the python script, the ``.nfs`` file is gone as well.

**Comment by dnadeau4** [comment]
if `lsof` does not return anything this means that all `netcdf` files are closed.  
You might want to try different command to find what files you have opened. 
```bash
lsof | grep python |grep "$USER" 
```
I put a `pdb.set_trace()` command  in my test just before `cmor.close()` and got this CMOR temporary file.   After `cmor.close()`  it disappeared.
```
lsof | grep \.nc$
lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
      Output information may be incomplete.
python    19073                nadeau1   11u      REG                8,1     34921   72091920 /software/cmor3/cmor/CMIP6/ISMIP6/PCMDI/PCMDI-test-1-0/piControl-withism/r11i1p1f1/Omon/masso/gr/v20170406/masso_Omon_piControl-withism_PCMDI-test-1-0_r11i1p1f1_grR1LqVu19073.nc

```

**Comment by Funkensieper** [comment]
Exactly. The temporary file disappears both from the filesystem and from the list of open files when cmor.close() is called. But simultaneously the .nfs file appears both in the filesystem and in the list of open files. Even after a couple of minutes it is still there, which is why I don't believe the problem is caused by some kind of network lag.

**Comment by Funkensieper** [comment]
Maybe renaming the file using ``rename( cmor_vars[var_id].current_path, outname );`` leaves the .nfs file, but I can't confirm that in a simple C program. Anyway, I will go for a workaround by deleting the output directory outside the python script. Thanks for your effort!

**Comment by dnadeau4** [comment]
@Funkensieper I found out that my tables/json file might not be closed.  The log file seems to be closed properly.  As well I added some fclose() statements in the cmor_validateFilename() function.  

Can you check if the you still have ".json" files open?  Are you using a log file?

**Comment by dnadeau4** [comment]
I found that my JSON files were not closed properly.  I fixed it for the next version. 
Thanks for your help!

```python
python     4803                nadeau1    6r      REG                8,1     81532   72091973 /software/cmor3/cmor/TestTables/CMIP6_coordinate.json
python     4803                nadeau1    7r      REG                8,1    223179   72091878 /software/cmor3/cmor/TestTables/CMIP6_Omon.json
python     4803                nadeau1    8r      REG                8,1      4383   72090800 /software/cmor3/cmor/TestTables/CMIP6_formula_terms.json
python     4803                nadeau1    9r      REG                8,1    338838   72091868 /software/cmor3/cmor/CMIP6_CV.json
```

**Comment by Funkensieper** [comment]
Yes, the .json files are left open as well, but in a different directory. So that's probably not the reason. In which branch did you commit the changes? I would give it a try.

**Comment by dnadeau4** [comment]
That is in cmor-3.2.3, but I will make a formal release this week.
