### ISSUE TITLE
Rogue values being written

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#154]
Here is another example where rogue values are being written by `CMOR 2.5.7`:
```
 time = 5.34313102907011e-315, 113085, 113115, 113145, 113175, 113205, 
    113235, 113265, 113295, 113325, 113355, 113385, 113415, 113445, 113475, 
    113505, 113535, 113565, 113595, 113625, 113655, 113685, 113715, 113745, 
    113775, 113805, 113835, 113865, 113895, 113925, 113955, 113985, 114015, 
    114045, 114075, 114105, 114135, 114165, 114195, 114225, 114255, 114285, 
    114315, 114345, 114375, 114405, 114435, 114465, 114495, 114525, 114555, 
    114585, 114615, 114645, 114675, 114705, 114735, 114765, 114795, 114825, 
    114855, 114885, 114915, 114945, 114975, 115005, 115035, 115065, 115095, 
    115125, 115155, 115185, 115215, 115245, 115275, 115305, 115335, 115365, 
    115395, 115425, 115455, 115485, 115515, 115545, 115575, 115605, 115635, 
    115665, 115695, 115725, 115755, 115785, 115815, 115845, 115875, 115905, 
    115935, 115965, 115995, 116025, 116055, 116085, 116115, 116145, 116175, 
    116205, 116235, 116265, 116295, 116325, 116355, 116385, 116415, 116445, 
    116475, 116505, 116535, 116565, 116595, 116625, 116655, 116685, 116715, 
    116745, 116775, 116805, 116835, 116865, 116895, 116925, 116955, 116985, 
    117015, 117045, 117075, 117105, 117135, 117165, 117195, 117225, 117255, 
    117285, 117315, 117345, 117375, 117405, 117435, 117465, 117495, 117525, 
    117555, 117585, 117615, 117645, 117675, 117705, 117735, 117765, 117795, 
    117825, 117855, 117885, 117915, 117945, 117975, 118005, 118035, 118065, 
    118095, 118125, 118155, 118185, 118215, 118245, 118275, 118305, 118335, 
    118365, 118395, 118425, 118455, 118485, 118515, 118545, 118575, 118605, 
    118635, 118665, 118695, 118725, 118755, 118785, 118815, 118845, 118875, 
    118905, 118935, 118965, 118995, 119025, 119055, 119085, 119115, 119145, 
    119175, 119205, 119235, 119265, 119295, 119325, 119355, 119385, 119415, 
    119445, 119475, 119505, 119535, 119565, 119595, 119625, 119655, 119685, 
    119715, 119745, 119775, 119805, 119835, 119865, 119895, 119925, 119955, 
    119985, 120015, 120045, 120075, 120105, 120135, 120165, 120195, 120225, 
    120255, 120285, 120315, 120345, 120375, 120405, 120435, 120465, 120495, 
    120525, 120555, 120585, 120615, 120645, 120675, 120705, 120735, 120765, 
    120795, 120825, 120855, 120885, 120915, 120945, 120975, 121005, 121035, 
    121065, 121095, 121125, 121155, 121185, 121215, 121245, 121275, 121305, 
    121335, 121365, 121395, 121425, 121455, 121485, 121515, 121545, 121575, 
    121605, 121635, 121665, 121695, 121725, 121755, 121785, 121815, 121845, 
    121875, 121905, 121935, 121965, 121995, 122025 ;
```
And the file can be found at /cmip5_css02/scratch/cmip5/output1/MOHC/HadGEM2-ES/piControl/mon/atmos/Amon/r1i1p1/v20120307/wap/wap_Amon_HadGEM2-ES_piControl_r1i1p1_217312-219811.nc
And an `ncdump -c` output for the whole header:
[css02-MOHC-HadGEM2-ES-piControl-mon-atmos-Amon-r1i1p1-v20120307-wap_Amon_HadGEM2-ES_piControl_r1i1p1_217312-219811.txt](https://github.com/PCMDI/cmor/files/894790/css02-MOHC-HadGEM2-ES-piControl-mon-atmos-Amon-r1i1p1-v20120307-wap_Amon_HadGEM2-ES_piControl_r1i1p1_217312-219811.txt)

**Comment by durack1** [comment]
@taylor13 this requires your input

**Comment by durack1** [comment]
@ehogan, @jkettleb, @dnadeau4 wanted me to point this out to you both. It would be good to trace where things went wrong in the writing of this file and that `CMOR3.2+` has the checks in place to prevent errors in CMIP6

**Comment by taylor13** [comment]
@ehogan, @jkettleb, @dnadeau4  When CMOR writes several time samples at once (rather than one by one) I think it checks for monotonicity and checks that the spacing between time-samples is correct (to within a few percent).  Thus, in the above sample, the first time-slice at least was written separately from the others, so the check couldn't be performed.  
We could include a check that would trap this error in PrePARE, but currently PrePARE focuses almost exclusively on the global attributes.

**Comment by taylor13** [comment]
I think this ticket can probably be closed, because enhancements of this sort to PrePARE won't be forgotten.

**Comment by durack1** [comment]
@taylor13 @dnadeau4 should this be reopened as an open issue for PrePARE? I really do think catching (or at least warning a user) about such problems is a good idea

**Comment by jkettleb** [comment]
Its very hard for us to say why we have these rogue values in the file.  If you look at the full ncdump output that @durack1 [links to](https://github.com/PCMDI/cmor/files/894790/css02-MOHC-HadGEM2-ES-piControl-mon-atmos-Amon-r1i1p1-v20120307-wap_Amon_HadGEM2-ES_piControl_r1i1p1_217312-219811.txt) you can see that is not just the time that has a funny value, but also the plev and lats and lons.  @alaniwi at BADC has also identified this as an issue in our data too.

Prompted by @alaniwi I've also reviewed the equivalent `hur_Amon` data and see a similar issue.  I wonder if we have a rogue file input into CMOR that resulted in the funny times and other coordinates.  As far as I can tell the files before and after in the time series are clean. I can try to go back to our source data to investigate, but don't think this needs to reopen this issue.

**Comment by durack1** [comment]
@jkettleb thanks for looking, we are hoping that at the very least a user will get a warning when such issues are encountered. It would be great to determine what caused this output, and determine a fix that will prevent this occurring in the future

From memory this is not a single isolated incident as you note, we have uncovered a number of unusual inconsistencies with the CMIP5 MOHC contributed data
