### ISSUE TITLE
standard_name not written to latitude and longitude variables in output netCDF files

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#155]
Using CMOR 3.2.2 and version `01.00.06` of the MIP tables, the `standard_name` attribute is no longer written to the latitude and longitude variables in the output netCDF file, even though the `standard_name` attribute exists in the MIP table, see https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json#L781.

**Comment by dnadeau4** [comment]
I tested with 3.2.3 and it worked fine.   If you want to install it there is a new release on conda for  each PR i create.  Try:  

```
conda install -n <YourEnv> -c conda-forge -c pcmdi/label/nightly cmor 
```

I will **try** to release cmor 3.2.3 this week.

**Comment by dnadeau4** [comment]
@ehogan is this working for you with 3.2.3?

**Comment by ehogan** [comment]
> @ehogan is this working for you with 3.2.3?

I'm afraid not :( After further investigation, I discovered the `standard_name` attribute for the `latitude` and `longitude` variables is set in the `01.beta.45` version of the `CMIP6_grids.json` file (see [here](https://github.com/PCMDI/cmip6-cmor-tables/blob/4675acbb016df9e052568f9647715f9cc4fb981e/Tables/CMIP6_grids.json#L123)), but is missing from the `01.00.00` version of the `CMIP6_grids.json` file (see [here](https://github.com/PCMDI/cmip6-cmor-tables/blob/2a52ee8d48785dbaf7e4154589c11fc612781e3b/Tables/CMIP6_grids.json#L123)). I believe this is the cause of the issue I reported :)

**Comment by durack1** [comment]
@dnadeau4 @ehogan this appears to have propagated along to the latest `master` too: [CMIP6_grids.json#L116-L151](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_grids.json#L116-L151)

**Comment by durack1** [comment]
@dnadeau4 should this be moved to the [3.2.4 milestone](https://github.com/PCMDI/cmor/milestone/12)?

**Comment by dnadeau4** [comment]
I fixed this in 3.2.4.  It was the way CMIP6_grids were created.  I used of mixed of CMIP5 and CMIP6DQ database.

**Comment by dnadeau4** [comment]
@ehogan @durack1 reopen if needed.

**Comment by ehogan** [comment]
I have finally tested CMOR 3.2.4 and can confirm that this issue is resolved. Thanks @dnadeau4! :)

**Comment by taylor13** [comment]
@ehogan 
To be sure, you should now be using CMOR 3.2.5 (not 3.2.4).  I think there were several important changes made (e.g., now the file names are generated correctly.)
thanks.

**Comment by ehogan** [comment]
Thanks @taylor13; I am currently testing CMOR 3.2.5 and have discovered one issue so far (see #214), but I think we can work around it :)
