### ISSUE TITLE
SImon table issue - doesn't contain cell_measures

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#157]
@dnadeau4 updating the `input4MIPs` data today I encountered the following problem:
```
!!!!!!!!!!!!!!!!!!!!!!!!!
! Error: Your table (SImon) does not contains CELL_MEASURES                                                                             
! that matches 'area: <text> volume: <text>                                                                                             
! CMOR cannot build the 'external_variable' attribute.
! Check the following variable: 'siconcbcs'.
!!!!!!!!!!!!!!!!!!!!!!!!!
```
The variable in the table is:
```
{
    "Header":{
        "Conventions":"CF-1.7 CMIP-6.0",
        "approx_interval":"30.00000",
        "cmor_version":"3.2",
        "data_specs_version":"01.00.06",
        "frequency":"mon",
        "generic_levels":"",
        "mip_era":"CMIP6",
        "missing_value":"1e20",
        "product":"input4MIPs",
        "realm":"seaIce",
        "table_date":"13 April 2017",
        "table_id":"Table SImon"
    },
    "variable_entry":{
...
        "siconcbcs":{
            "cell_measures":"time: point",
            "cell_methods":"area: time: mean ",
            "comment":"Area fraction of grid cell covered by sea ice",
            "dimensions":"longitude latitude time2",
            "long_name":"Constructed mid-month Sea-ice area fraction",
            "modeling_realm":"seaIce",
            "ok_max_mean_abs":"",
            "ok_min_mean_abs":"",
            "out_name":"siconcbcs",
            "positive":"",
            "standard_name":"sea_ice_area_fraction",
            "type":"real",
            "units":"%",
            "valid_max":"1000",
            "valid_min":"-1000"
        }
    }
}
```
Any tips for me here?

**Comment by durack1** [comment]
@dnadeau4 @taylor13 it seems this issue is related to a change upstream in [PCMDI/cmip6-cmor-tables#0ad7689](https://github.com/PCMDI/cmip6-cmor-tables/commit/0ad7689eec872228cd23ed33aa85c5e6349bc7ba), with the `01.00.06` update (PCMDI/cmip6-cmor-tables#50) `cell_methods` went from:
```
from
21 "cell_methods": "time: mean",
to
22 "cell_methods": "area: time: mean ",
23 "cell_measures": "area: areacella",
```
This seems to be a weird hybrid of the `cell_methods` and `cell_measures` and a clear error in the table update

**Comment by taylor13** [comment]
Denis and I talked about this.  I'm not sure how siconcbcs gets into table SImon since it is not a CMIP6 output variable and its not included in Martin's "data request".  The variable entry is wrong.  Does Denis create this variable and put it into SImon?

**Comment by durack1** [comment]
@taylor13 apologies.. I close the `siconc` variable and then update this for the boundary conditions and call the updated variable `siconcbcs` - which is a sea ice analogue to `tos` and `tosbcs` - so it's a problem with `siconc` as the links above show

**Comment by durack1** [comment]
@taylor13 @dnadeau4 to be clear, the identical error would appear with the dataRequest version of `siconc` when the code got to that variable, it's just `siconcbcs` was processed first

**Comment by taylor13** [comment]
Unless we include areacella in the file along with siconcbcs, then "cell_measures" should not appear as part of the variable entry.  The cell_methods should be:

cell_methods: area: mean time: point

And be sure that "time2" doesn't have bounds.

**Comment by dnadeau4** [comment]
@taylor13 , I don't check if the variables are linked to an experiment anymore for consistency with Martin's tables.  This mean that some variables might be in the tables, but never used for `CMIP6`.

**Comment by durack1** [comment]
@dnadeau4 @taylor13 this is something that I think the three of us are going to have to stare at a screen and try and decipher.. @dnadeau4 I recreated the CMOR input json files for input4MIPs, and had to change some of the variable entries (pulled from cmip6-cmor-tables) to make CMOR work for me.. That doesn't seem like something any other user should have to do

**Comment by durack1** [comment]
@dnadeau4 it appears that I managed to get all tangled up with this, and now have things working more cleanly with `CMOR 3.2.2`. If you wanted to see what the files that I am using look like, take a peek at https://github.com/PCMDI/input4MIPs-cmor-tables and https://github.com/PCMDI/amipbcs/tree/master/CMOR.

There is no longer an issue (if there ever was), so am closing this
