### ISSUE TITLE
"rank is deprecated" warning message (in pywrapper.py?)

### ISSUE THREAD

**Issue by jypeter** [PCMDI/cmor#16]
I got the following warning, when running the *Sample Program 1* example script from the CMOR2 documentation (page 56)
```
/usr/local/install/cdat/versions/cdat_install_uv-2.1.0_x86_64_gcc4_VB_13/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2499: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
``` 

pywrapper does use *numpy.rank()* many times, so maybe it's coming from there

I'm using python 2.7.8 from UV-CDAT 2.1.0

**Comment by doutriaux1** [comment]
thx @jypeter will fix soon (most likely this coming Thursday)

**Comment by jypeter** [comment]
No rush, as long as it's working. I will probably report other problems by the end of the week

**Comment by dnadeau4** [comment]
I have changed this in CMOR3 I now use numpy.ndims as suggested.

**Comment by jypeter** [comment]
Thanks Denis!

**Comment by durack1** [comment]
@jypeter @dnadeau4 closing - please open a new issue if there are other problems in `CMOR 3.1.x`
