### ISSUE TITLE
UGRID grid specification

### ISSUE THREAD

**Issue by martinjuckes** [PCMDI/cmor#162]
I'm planning to add a request for a variable "ugrid" which will contain UGRID information about any unstructured grids (we expect data from at least one model with an unstructured ocean grid).
My understanding is that CMOR can handle data variables on unstructured grids following the CF convention, but does not provide the full specification of the grid as defined in the UGRID convention. So a separate variable is requested with this information, but perhaps it will not be supported by CMOR? At this point, it is a very small use-case, and it may be better to let the one modeling group that needs this provide their own file.

**Comment by dnadeau4** [comment]
@martinjuckes CMOR tables have the Conventions attribute written in their header.  You can redefine them.
.i.e
https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_AERhr.json#L14

 I make sure it match this regular expression in PrePARE.  `CF-1.7 CMIP-6.0` or `CF-1.7 CMIP-6.0 UGRID-1.0`.  

**REGEX**
* ^CF-1.7 CMIP-6.0\\( UGRID-1.0\\)\\{0,\\}
https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L8886

**Comment by dnadeau4** [comment]
@martinjuckes If you can send me a file,  I will take a look.   It is true that CMOR does not 
>> provide the full specification of the grid as defined in the UGRID convention.

**Comment by taylor13** [comment]
@martinjuckes @dnadeau4 The structure of a "ugrid" file is probably quite different from the structure of CMIP6 files.  Modeling groups will have to figure out how they should write properly formatted/structured ugrid files.  

CMOR, of course, accepts inclusion of UGRID-1.0 as one of those appearing in the "Conventions" global attribute.  

A "ugrid" file probably includes many variables, so I'm not sure how this data will get published (and searched for) on ESGF.  I would note that for input4MIPs we have some files with multiple variables.  @durack1 can explain what special treatment is done for them.

I don't think any action is required on our end as far as CMOR is concerned.

**Comment by martinjuckes** [comment]
I agree with Karl that CMOR doesn't need to process UGRID files. I've put it in the request so that there is a variable name which can be used to construct a file name and any identifiers needed for ESGF.
