### ISSUE TITLE
chunking time coordinate

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#164]
It appears that CMOR compresses the time coordinate (but not other coordinates).  Since users might write one time sample at a time, we should check that the chunks are not wasting a lot of space (since the chunk size for each write of the coordinate value is in only 1 double precision variable).  If a full chunk (of say 512 bytes) is written, that's a lot of wasted space.

This is not particularly high priority.

**Comment by durack1** [comment]
@dnadeau4 this is linked to the same deflation issue #158 - a resolution will solve both of these issues, both with time and lat/lon/depth/height coordinate deflation (and chunking)

**Comment by dnadeau4** [comment]
@taylor13 I set the "coordinate_variable" the `CONTINUOUS`,  time is `UNLIMITED` and need to be `CHUNKED`, so I default to `1`.

**Comment by dnadeau4** [comment]
Solved in 3.2.5
