### ISSUE TITLE
Problem with effectRadLi|tau CMIP6_Eday.json

### ISSUE THREAD

**Issue by svalcke** [PCMDI/cmor#166]
Hi,
I have another problem with the CMIP6_Eday.json table when I try to validate one of my output file with PrePARE. When I type:
+ python /home/ext/cf/cglo/valckes/SAVE/cmor/LibCV/PrePARE/PrePARE.py /home/ext/cf/cglo/valckes/SAVE/cmor/Tables/CMIP6_Eday.json ua_Eday_CNRM-CM6-1_highresSST-present_r1i1p1f1_gr_19500101_19501231_ua.nc

I get the error:
! Error: Reading table Eday: axis name: 'effectRadLi|tau' for variable: 'jpdftaureliqmodis' is not defined in table. Table defines dimensions: 'longitude latitude plev7c effectRadLi|tau time' for this variable

This variable  'jpdftaureliqmodis' (or "jpdftaureicemodis") is not in the file I am checking so I suspect a problem with the table itself (maybe the "|" in  'effectRadLi|tau' ?)
  Thanks,
  Sophie

**Comment by dnadeau4** [comment]
@svalcke I remember seeing this issue a while ago, but was told that this table(at the time) was not part of CMIP6.  

Anyways, CMOR3 tables in master have been updated on April 28th and I changed the`|` for a `space` which eliminate the error message.  CMOR3  always checks that every variable dimension is found in `CMIP6_coordinates.json` and `effectRadLi|tau` could not be found.   

(It is the first time I see a variable with 6 dimensions...)

[CMIP6_Eday.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Eday.json#L833)

**Comment by dnadeau4** [comment]
@svalcke can we close this issue?

**Comment by svalcke** [comment]
Yes, of course!
  Thanks and best regards,
   Sophie

On 24 May 2017, at 22:50, Denis Nadeau <notifications@github.com> wrote:

> @svalcke can we close this issue?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---------------------------------------------------------------
Sophie Valcke

  Research Engineer
  Climate Modelling and Global Change team
  CECI UMR 5318 CNRS/CERFACS
  42 Av. G. Coriolis
  31057 Toulouse Cedex 01, FRANCE
  Tel: 05.61.19.30.76  Fax: 05.61.19.30.00
