### ISSUE TITLE
Error in Python Sample Program 1 from cmor_users_guide

### ISSUE THREAD

**Issue by jypeter** [PCMDI/cmor#17]
I have copy/pasted the *Sample Program 1* example script from the CMOR2 documentation (page 56) and I had to use the following *cmor.dataset* call instead of the one supplied in the example. I don't know if I got all the meta-data right, but at least I got rid of the **spurious quotes** and I have added the **missing parent_experiment_rip** parameter

```
cmor.dataset('historical', 'ukmo', 'HadCM3 (2010)', '360_day',
             model_id='HadCM3',forcing='Nat',
             parent_experiment_id='N/A', parent_experiment_rip='N/A',
             branch_time=0.,
             contact='Tim Lincecum, timmy@sfgiants.com', institute_id='pcmdi')
```

Are the examples used in the documentation available somewhere in the github repo of CMOR? I have seen that there are several scripts in cmor/Test, but the documentation does not supply names for the examples and I have not opened all the scripts available in Test to check

**Comment by ehogan** [comment]
If it's useful, there's already an example script containing a copy of 'Sample Program 1' in #26 :)

**Comment by dnadeau4** [comment]
cmor_dataset has been replaced with cmor_dataset_json.  With the control vocabulary, this is no onger valid. for 3.1

**Comment by durack1** [comment]
@jypeter the documentation has just been reformulated - see https://cmor.llnl.gov - so we'll close this issue, please reopen if you see remaining issues

**Comment by dnadeau4** [comment]
http://cmor.llnl.gov @durack1

**Comment by durack1** [comment]
@dnadeau4 link above updated..
