### ISSUE TITLE
Segmentation fault in cmor.load_dataset_json

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/cmor#170]
``cmor.dataset_json`` crashes with a segmentation fault If there is a ``null`` value in the JSON file, for example

    "comment":  null

I stumbled upon that when I accidentally dumped a ``NoneType`` object to the JSON file using python.

**Comment by dnadeau4** [comment]
I now check if the json values is not null before continuing.  `(value == 0)`, for some JSON API reason `(value == NULL)` did not work.

**Comment by dnadeau4** [comment]
Fixed in 3.2.4 Please test with latest release.
