### ISSUE TITLE
cmor 3.2.3 sha256 changed

### ISSUE THREAD

**Issue by iMichka** [PCMDI/cmor#173]
Hi. I am one of the maintainers of the homebrew package manager.

We noticed that the sha256 checksum of the cmor 3.2.3 release has changed.

> ==> Downloading https://github.com/PCMDI/cmor/archive/CMOR-3.2.3.tar.gz
==> Downloading from https://codeload.github.com/PCMDI/cmor/tar.gz/CMOR-3.2.3
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.0-66-g459fef3 (Macintosh; Intel Mac OS X 10.11.6) curl/7.43.0 --fail --silent https://codeload.github.com/PCMDI/cmor/tar.gz/CMOR-3.2.3 -C 0 -o /Users/brew/Library/Caches/Homebrew/cmor-3.2.3.tar.gz.incomplete
Downloaded to: /Users/brew/Library/Caches/Homebrew/cmor-3.2.3.tar.gz
SHA256: e4dcd7e16f6bce5817470e628ae9ba7cb51d7f5cd9e2e3ba86b26ee6a9a916bf
==> Verifying cmor-3.2.3.tar.gz checksum
Warning: Formula reports different SHA256: 4f1039ddb3fe2237404a3a18ae018e2df49c3cdee736ca44c7a91b4b4147944d
Downloaded to: /Users/brew/Library/Caches/Homebrew/cmor-3.2.3.tar.gz
SHA256: e4dcd7e16f6bce5817470e628ae9ba7cb51d7f5cd9e2e3ba86b26ee6a9a916bf

As this is a GitHub archive, I guess nobody malicious has hijacked your tar.gz archives, and I hope this was just non-announced tag move.

The best practice is to bump an new version, like cmor 3.2.4 or 3.2.3.1 (or whatever your prefer).

Could you please confirm that this change was made on purpose?

Issue on our bug tracker for reference: https://github.com/Homebrew/homebrew-science/pull/5664

**Comment by dnadeau4** [comment]
I had to move my tag,  Cmor-3.2.3 which was different than the tag on 
zenodo.  A user in New York was having difficulties.
Next version will be CMOR-3.2.4 and i will make sure to make 
CMOR-3.2.3.1 tag if this happens again.

Sorry for the inconvenience.
Denis

**Comment by iMichka** [comment]
Thanks; no problem. We just always double check this with upstream.

I'll update the sha256 on our side. Have a nice weekend :)
