### ISSUE TITLE
PrePARE not working?

### ISSUE THREAD

**Issue by klauswyser** [PCMDI/cmor#176]
I try checking a file with PrePARE (from CMOR 3.2.3), but unfortunately it doesn't work. I then try just running PrePARE with -h and get the same error:
```
(python-ve) [sm_wyser@triolith1 ece2cmor3]$ PrePARE -h
Traceback (most recent call last):
  File "/home/sm_wyser/ece2cmor3/python-ve/bin/PrePARE", line 11, in <module>
    load_entry_point('CMOR==3.2', 'console_scripts', 'PrePARE')()
  File "/home/sm_wyser/ece2cmor3/python-ve/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sm_wyser/ece2cmor3/python-ve/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/home/sm_wyser/ece2cmor3/python-ve/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/sm_wyser/ece2cmor3/python-ve/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named PrePARE
```
When  running `PrePARE.py` (not the script!), it tells me that cdms2 is missing:
```
(python-ve) [sm_wyser@triolith1 ece2cmor3]$ ../python-ve/bin/PrePARE.py
Traceback (most recent call last):
  File "../python-ve/bin/PrePARE.py", line 21, in <module>
    import cdms2
ImportError: No module named cdms2
```
Is this the reason that PrePARE doesn't work for me? If so, where do I get the cdms2 package?

**Comment by doutriaux1** [comment]
@klauswyser I'm not sure why cdms2 did not come in for you, did you install via `conda`

in any case you can obtain `cdms2` as follow:
```
conda install cdms2 -c conda-forge
```

**Comment by dnadeau4** [comment]
Try to run `python ../python-ve/bin/PrePARE.py` in `CMOR 3.2.3`
You are probably using the /bin/python instead of the anaconda one.

I try to setup an `entry_point` and somehow it did not work in `3.2.3`.  But PrePARE will run.

**Comment by doutriaux1** [comment]
@dnadeau4 if it's an executable/script why don't you use the script argument in setup.py?

**Comment by doutriaux1** [comment]
I see you actually commented it out? why? It would prevent these sort of issues.

**Comment by dnadeau4** [comment]
@doutriaux1 scripts are the old ways to do business.  If you use `setuptools` you can defined a `entry_points` and this is `setuptools` will create a wrapper for you.
```
 79        entry_points = {
 80           'console_scripts':['PrePARE=cmip6_cv.PrePARE:main']
 81         }

```

**Comment by dnadeau4** [comment]
Actually this is working on `3.2.3`

**Comment by klauswyser** [comment]
@doutriaux1:  I am using a virtual python environment, I have downloaded cmor3 (3.2.3) from github (not conda!) and installed in this virtual environement, including PrePARE. I can process the model output with the cmor3 library and get reasonable netCDF file, but the checker doesn't seem to work.

Is it a problem that I use github instead of Anaconda? What about the cdms2 module? Can it be included even on github?

**Comment by durack1** [comment]
@klauswyser as a fellow user of CMOR3, I would strongly recommend using the conda python virtual environments. This has enabled me to jump quickly from one version of CMOR to another and update my environment and get up and running in minutes.

This is considerably preferable to the previous path of having to build your environment from source.. An additional advantage is all the environment variable and path magic is dealt with by the software so the issue you've hit above will not likely ever occur

**Comment by doutriaux1** [comment]
@klauswyser it's not an issue, @dnadeau4 you need to add a requirement file somewhere so people are aware of this.
@klauswyser cdsm2 comes with lots of dependencies and is hard to install outside of a conda environment. I would recommend anaconda.

**Comment by klauswyser** [comment]
Good news, the cdms2 module is part of cdat-lite that I could install with
```pip install cdat-lite```

Now it's the question of the script not working and entry point, I leave this to you Python cracks. I can run ``PrePARE.py`` and that seems to work fine. But then I run into the next problem when checking a file that I have created with the very same version of the CMOR library (and Tables):
```
!
! Warning: Could not find label string in experiment_id section.
! 
! 
!See Control Vocabulary JSON file. (resources/cmip6-cmor-tables/Tables/CMIP6_CV.json)
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!


!!!!!!!!!!!!!!!!!!!!!!!!!
! Error:  The input file is not CMIP6 compliant
! Check your file or use CMOR 3.x to achieve compliance for ESGF publication.
!!!!!!!!!!!!!!!!!!!!!!!!!
```
Does the error come beacuse of the missing `label`? And when I check my CMIP6_CV.json file I cannot find an attribute called `label`. ???

**Comment by durack1** [comment]
@klauswyser the `cdat-lite` package is using a non-supported and very old version of `cdms` and the `netcdf` library that was generated by some UK colleagues many many years ago. If you want to be supported in your use of CMOR I recommend going down the conda installation path. You can install this using the directions found at https://cmor.llnl.gov/mydoc_cmor3_conda/

@taylor13 pinging you here

**Comment by doutriaux1** [comment]
@klauswyser I confirm the cdat-lite will get you a bad version which is likely to fail at best or give you wrong answers at worst!

**Comment by doutriaux1** [comment]
@klauswyser i strongly recommend you follow the instructions at:
https://github.com/UV-CDAT/uvcdat/wiki/Install-using-Anaconda

And install cmor using conda. Conda is essentially a virtual env on steroids.

**Comment by klauswyser** [comment]
Thanks for all the comments.  I will give the anaconda stuff a try, however, a long weekend is starting here today and I will be away for a couple of days before getting started.

**Comment by dnadeau4** [comment]
long weekend on a Wednesday??? ;-)

**Comment by doutriaux1** [comment]
@dnadeau4 what is the assignments? requirements.txt file? Or setup.py script? or both?

**Comment by dnadeau4** [comment]
following up with answering questions if needed.  Nice to see you back in CMOR project. 👍

**Comment by doutriaux1** [comment]
I never left, just got my self a great partner.

**Comment by klauswyser** [comment]
Hello, I am back after a long weekend (working in Europe has its advantages sometimes), and after some struggle with anaconda I finally got cmor3 running. Now I want run PrePARE on the output after cmorisation and still get
```
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: Could not find label string in experiment_id section.
! 
! 
!See Control Vocabulary JSON file. (resources/cmip6-cmor-tables/Tables/CMIP6_CV.json)
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!


!!!!!!!!!!!!!!!!!!!!!!!!!
! Error:  The input file is not CMIP6 compliant
! Check your file or use CMOR 3.x to achieve compliance for ESGF publication.
!!!!!!!!!!!!!!!!!!!!!!!!!
```
I cannot find ``label`` in the CMIP6_CV.json file, what's wrong here?

**Comment by klauswyser** [comment]
Got it! I happened to install CMOR3.2.2 instead of 3.2.3... With the proper version things work just fine. Closing the issue, thanks for all the help.
