### ISSUE TITLE
cmor.close(): slight error in the returned path and question about the duplicate close()

### ISSUE THREAD

**Issue by jypeter** [PCMDI/cmor#18]
When I call cmor.close() in the *Sample Program 1* example script 
```
cmor.write(varid, [273])
path=cmor.close(varid, file_name=True)
print path
cmor.close()
```
I get a path that has a **duplicate /** before the file name
```
./CMIP5/output/pcmdi/HadCM3/historical/mon/atmos/ts/r1i1p1//ts_Amon_HadCM3_historical_r1i1p1_200001-200001.nc
```

I have also a question about **the second cmor.close()** (no parameters) that prints the message pasted below. Is it necessary to call cmor.close a last time at the end of the script?
```
------
CMOR is now closed.
------

We encountered no warnings or errors during execution
------
Congratulations!
------
```

Oh, I have just tried to generate a warning by calling *cmor.write(varid, [400])* and the second cmor.close() printed some usage statistics. The documentation (p 38) says *To be safe, before exiting any program that invokes CMOR, it is best to call this function with the argument omitted*, but it would be more useful to say that the last cmor.close() will print some statistics and use something more clear than *to be safe*
```
------
CMOR is now closed.
------
During execution we encountered:
  2 Warning(s)
  0 Error(s)
------
Please review them.
------
```

**Comment by dnadeau4** [comment]
That is still happening in cmor 3.1.  Each time you call cmor close, it print this message.  I did not mind it and did not change it.   I think I got rid of the duplicate "/", but that is not an error and is allowed in Unix.

**Comment by durack1** [comment]
@jypeter a template is now used and should have resolved this issue - if you see the behaviour in `CMOR 3.1.x` please reopen (@dnadeau4 pinging you here)
