### ISSUE TITLE
CMIP6 license

### ISSUE THREAD

**Issue by dnadeau4** [PCMDI/cmor#181]
> Can you give me an example of the license attribute in a cmip6 file? 
>
> My dummy test fails at-
>
> ! Error: The attribute "license" could not be validated.
> ! The current input value is "This CMIP6 model data produced by NOAA-GFDL is licensed under a Creative Commons Attribution.*ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) .The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." which is not valid
> ! Valid values must match the regular expression:
> !       ["^CMIP6 model data produced by .* is licensed under a
> !
> !!!!!!!!!!!!!!!!!!!!!!!!!^[[0m
>
> -- 
> Aparna Radhakrishnan

**Comment by dnadeau4** [comment]
Here is the license use for testing

 "license":                 "CMIP6 model data produced by Lawrence Livermore PCMDI is licensed under a Creative Commons Attribution ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) and at https:///pcmdi.llnl.gov/. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law."

**Comment by dnadeau4** [comment]
@taylor13 There is so much text that it is cut.   The maximum message size in cmor is 1024 characters which is defined by CMOR_MAX_STRING.

**Comment by taylor13** [comment]
but it appears that only about 50 characters are written correctly.  Seems like the message got corrupted.   ???

**Comment by dnadeau4** [comment]
That is right,  only 132 characters from Validation is written, which is normally sufficient but not for license.  The validation is the string from the Control Vocabulary.  Not sure why 132 was chosen!
```snprintf( szOutput, 132, "%s ...", szValids);```

I can increase this to 1024, but I am not sure if this will be enough for the entire message.

**Comment by taylor13** [comment]
I would say you should count the number of characters actually in the string (after subtracting trailing blanks), and print all of them.  If you try to *always* print 1024, you'll probably either get a lot of warnings that are mostly blank or gibberish  (I'm not sure which).

**Comment by dnadeau4** [comment]
@taylor13 I think what you call `gibberish` is probably the `REGEX` to validate the license.

**Comment by taylor13** [comment]
Are you saying there is a REGEX function that you can't control that produces the error message?  If so, could you follow that error message with one where you write the entire string?

**Comment by dnadeau4** [comment]
No,  the error message is right,  but it display the Current Value set by the user and the REGEX it is trying to use to validate.


**USER INPUT**
> ! Error: The attribute "license" could not be validated.
> ! The current input value is "This CMIP6 model data produced by NOAA-GFDL is licensed under a Creative Commons Attribution.*ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) .The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." which is not valid
> ! Valid values must match the regular expression:

**REGEX**

> !       ["^CMIP6 model data produced by .* is licensed under a
> !
> !!!!

**Comment by taylor13** [comment]
Does REGEX stop looking after it finds the problem that the string passed begins with "This", but "This" doesn't appear in the CV expression?  I think it would be nice to follow this error message with the full license template copied from the CV?  Not a high priority though.
thanks,
Karl

**Comment by dnadeau4** [comment]
You are right, that is probably the issue the **REGEX** says `^CMIP6` which means `start with CMIP6`.  I can try to just update the number of characters and see what happens.  This the longest user input and I never counted the number of characters.
