### ISSUE TITLE
Time labels in file names: need to conciliate CMOR  and the WIP convention

### ISSUE THREAD

**Issue by mpmoine** [PCMDI/cmor#182]
Hi,

About time range in file names... (more or less linked to  #178)

It seems that there is a need to conciliate what CMOR/prePARE expects and what is specified in the  "WIP position paper":https://drive.google.com/file/d/0B-X2uY_FGt7XMTg2eUpMZ3lUb2M/view (Table2) or at least clarify the demand.

It looks like prePARE requires that the time range in file names exactly matches the time axis content in the file, for some frequencies, but not for others...

We noticed that:

- for `6hr`, WIP-Table2 requires `'yyyyMMddhhmm'` but PrePARE expects `'yyyyMMddhhmmss' `where `'ss'='00'`
- for `3hr `(time average),  WIP-Table2 requires `'yyyyMMddhhmm'` and Prepare expects the same format with `'mm'='30'` and that's fine
- for `mon` (time average), WIP-Table2 requires `'yyyyMM'` and Prepare expects the same, but in that case it does not match the time axis; to do so, we should have `'yyyyMMdd'` with `'dd'='15'` (equivalent thoughts for monthly means and yearly means)

What do you think?

Thanks,
Marie-Pierre.

**Comment by dnadeau4** [comment]
#178 is currently handling this issue,  I running all tests and I will merge then.

**Comment by dnadeau4** [comment]
PrePARE use the same code as cmor to create the file `timestamp`.   When this is merge I will release 3.2.4.   I will be on travel by the end of next week, so hopefully I can do this Monday.

**Comment by taylor13** [comment]
@mpmoine Note that it is a coincidence that the 1st and last coordinate values in the file are precisely the same as the time label in the filename for most frequencies.  There is no requirement for this.  In the case of monthly data, it is sufficient for purposes of identification to record only the 1st and last months (YYYYMM-YYYYMM) in the file name.

**Comment by mpmoine** [comment]
@taylor13 
Thanks for the clarification. I understand that `yyyyMM` is sufficient for a non-ambiguous identification of monthly data, but I'm still puzzeled with the coherency across frequencies. If we apply the same reasoning, then we should stop at `yyyyMMddhh` for 1hr, 3hr and 6hr, isn't it?

**Comment by taylor13** [comment]
Except for climatological data, for sampling frequencies greater than a day, our rule is that the time-labels should match the first and last coordinate values in the file.  CMOR/PrePARE is being modified as we speak to make sure this happens.  For 3-hourly and 1-hourly data, those values commonly occur on the half-hour, so minutes are needed.  The rules governing this are now written in Table 2 at goo.gl/v1drZl .  Comments welcome.

**Comment by svalcke** [comment]
So we understand that for the time labels in file name, we have one rule for "yr", "mon" and "day" frequencies (i.e. stop at the frequency e.g. yyyMM for "mon") and a different rule for frequencies greater than a day, e.g. 6hr, 3hr, 1hr, subhr (i.e include an additional level e.g. yyyyMMddhhmm for 3hr). This does not seem coherent to us and it will be quite a twist to code this in our I/O library. (But maybe we are misunderstanding something here?)

**Comment by taylor13** [comment]
The time labels are meant to make it easy on users and to avoid unnecessary precision.  Decades, months, and days have well defined beginnings and ends, but 1 hr, 3hr, and 6hr periods don't and although most of the time the center of a 6hr sample will fall on the hour (so minutes would be unnecessary), this is not the case for 1hr and 3hr sampling.  This is where the rules need to be seemingly inconsistent.

Perhaps the easiest thing to do (in your code) is treat each frequency as a special case, although the algorithm will be the same for (6hr, 3hr, and 1hr) and for (yr and dec). Here are the rules:

For non-climatological data:  Extract the first and last time coordinate values from the file and construct labels using the following templates:

    dec, yr:  YYYY
    mon:      YYYYMM
    day:       YYYYMMdd
    6hr, 3hr, 1hr:   YYYYMMddhhmm  (but be sure to round off to nearest minute)
    subhr:              yyyyMMddhhmmss  (but be sure to round off to nearest second)

For climatological data:  Extract the first and last time coordinate climatological *bounds* (pointed to by the "climatology" attribute attached to the time coordinate) and construct labels using the following templates:

    1hrClimMon: YYYYMMddhhmm (but be sure to round off to nearest minute)
    monClim: YYYYMM (but you must add an increment to the first climatology bound 
                  and substract an increment from the last bound because the bounds are 
                 *between* months and you want to point to the first and last months that 
                 actually have been sampled in the climatology.  The increment can be 
                 anywhere from a second to a day; it shouldn't matter.)

CMOR3 is currently being revised to do this correctly.   See https://github.com/WCRP-CMIP/CMIP6_CVs/issues/338#issuecomment-307102130

**Comment by dnadeau4** [comment]
This is now solved in 3.2.4  Please test and close issue.
