### ISSUE TITLE
source_id in CV versus file

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [PCMDI/cmor#185]
Here's what I have in my netCDF file for 
:source_id = "GFDL-AM4" ;

And, the corresponding value in CV for GFDL-AM4 is "GFDL-AM4". While running PrePARE, I get the following warning and was wondering what went wrong. Please let me know. Thanks,

C Traceback:
In function: _CV_checkSourceID
!

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: Could not find source string in source_id section.
!
!
! See Control Vocabulary JSON file. (/home/a1r/CMIP6_work/Tables/CMIP6_CV.json)
!
!
!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by dnadeau4** [comment]
@durack1  I think your `\n` characters introduced a problem in CMOR.  not sure what is going on yet....
https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json#L348-L359

**Comment by durack1** [comment]
@dnadeau4 the `\n` characters were in place so that the netcdf dump output would be more cleanly formatted - these could be removed if required

**Comment by taylor13** [comment]
I like clean formats.  Don't see why a clean format should  cause trouble.

**Comment by dnadeau4** [comment]
@aradhakrishnanGFDL can you check that `GFDL-AM4` is in your `CMIP6_CV.json` file.

**Comment by dnadeau4** [comment]
@aradhakrishnanGFDL I cannot reproduce this problem.

**Comment by aradhakrishnanGFDL** [comment]
Denis, Yes. I had GFDL-AM4 in the the CV as well. But, the issue seems to be resolved in CMOR 3.2.4 + CMIP6 Table upgrade.  Thank you.

**Comment by dnadeau4** [comment]
Good to hear!
