### ISSUE TITLE
cmor build - configure: WARNING: unrecognized options: --with-zlib

### ISSUE THREAD

**Issue by jmcgove** [PCMDI/cmor#188]
Hi,
Have any come across this. When I compile cmor with the --with-zlib option I get
configure: WARNING: unrecognized options: --with-zlib
and when I do make install I get
cp -pr include/*.h cmor_users_functions.* /data/jmcgovern/p-process-ECEarth/other/cmor-CMOR-3.2.3/include
cp: ‘include/cmor_func_def.h’ and ‘/data/jmcgovern/p-process-ECEarth/other/cmor-CMOR-3.2.3/include/cmor_func_def.h’ are the same file
Thanks

**Comment by dnadeau4** [comment]
@jmcgove There is not `--with-zlib` option in `configure` for cmor.

Maybe the `travis CI` build can be of help to you.  
Look at line 484 and click on the down arrow.   The file that it is running is `.travis.yml`
https://travis-ci.org/PCMDI/cmor/jobs/243771775

**Comment by jmcgove** [comment]
Hi, tried without --with-zlib option, still get the error when I do make install

cp -pr include/.h cmor_users_functions. /data/jmcgovern/p-process-ECEarth/other/cmor-CMOR-3.2.3/include
cp: ‘include/cmor_func_def.h’ and ‘/data/jmcgovern/p-process-ECEarth/other/cmor-CMOR-3.2.3/include/cmor_func_def.h’ are the same file

You mentioned travis:  there does not seem to be line 484 in the link you sent me, only 483. Which do you mean, the line in the code, which line in the code? Or the download of travis CI? 
Thanks

**Comment by dnadeau4** [comment]
If you click on the **arrow** ▶️ next to line 483, the command will expand.

It seems the `cp` command only tells your that the file you are copying are exactly the same.  This is not an error, and will not affect compilation of cmor.  If you don't like the warning, you can change the make file to use the `-n` option which is used to not overwrite an existing file.

**Comment by jmcgove** [comment]
Thanks! that output is useful. 

./configure and make ok (I see you only do make install), python setup.py install -user also builds ok. Make test is also ok, even if is not the same output as yours at least I think, as I get 
All C and Fortran Test passed successfully

make install build is shorter than yours. make install gives 
cp: ‘include/cmor_md5.h’ and ‘/data/jmcgovern/p-process-ECEarth/other/cmor-CMOR-3.2.3/include/cmor_md5.h’ are the same file
make: *** [install] Error 1 
With make install -n, no Error 1
cp -pr include/cdTime/cdunifpp/*.h /data/jmcgovern/p-process-ECEarth/other/cmor-CMOR-3.2.3/include/cdTime/cdunifpp 

Except when I run ece2cmor.py in ece2cmor3, uuid can't be seen
ImportError: libuuid.so.16: cannot open shared object file: No such file or directory,
But I compiled cmor with the correct uuid path. It prob is an ece2mor3 issue then

**Comment by dnadeau4** [comment]
I guess you got this working.  closing.
