### ISSUE TITLE
Trailing characters in attribute validation

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/cmor#192]
If one of the allowed attribute values defined in the CV is a substring of the attribute to be validated, CMOR (3.2.4) does not raise an error. For example,

     "activity_id": [ "obs4MIPs", "foobar" ]

in the CV and

    "activity_id": "123obs4MIPs123"

supplied via ``cmor.dataset_json`` would pass.

**Comment by dnadeau4** [comment]
@Funkensieper I did try your example and it worked with `3.2.4`

**Note** the value has been overwritten by the experiment_id entry `piControl-withism` in CMIP6_CV.json
```json
7150             "piControl-withism":{
7151                 "activity_id":[
7152                     "ISMIP6"
7153                 ],
```
```bash
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: Your input attribute "activity_id" with value 
! "123obs4MIPs123" will be replaced with value "ISMIP6"
! as defined for experiment_id "piControl-withism".
! 
!  See Control Vocabulary JSON file.(Tables/CMIP6_CV.json)
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!


```
```bash
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The attribute "activity_id" could not be validated. 
! The current input value is "ISMIP6" which is not valid 
! Valid values must match the regular expression:
! 	["obs4MIPs" "foobar"  ...] 
! 
! Check your Control Vocabulary file "Tables/CMIP6_CV.json".
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!

```
[test_python_CMIP6_wrong_activity.py.txt](https://github.com/PCMDI/cmor/files/1092599/test_python_CMIP6_wrong_activity.py.txt)

**Comment by Funkensieper** [comment]
I just checked out the script you provided. Could you please rename ``activity_id`` to ``dummy`` in CMIP6_CV.json, 

    "piControl-withism":{
        "dummy":[
            "ISMIP6"
        ],

to prevent CMOR from resetting the value and then re-run the test script with 

    cmor.set_cur_dataset_attribute("activity_id", "123ISMIP6123")

? This does not raise an error in my environment. Can you reproduce that?

**Comment by taylor13** [comment]
For CMIP6, you should not alter the .json files that contain "controlled vocabularies".  These files ensure compliance with the CMIP6 requirements.  Does CMOR have any problems when the CV's are not modified?

**Comment by Funkensieper** [comment]
With the original CV CMOR works just fine. The problem occurs with the custom obs4MIPs CV, where the activity_id is not being reset.

**Comment by Funkensieper** [comment]
Here is a [minimal example](https://github.com/Funkensieper/obs4MIPs_activity_id) . Just clone the repo and run test.py.

**Comment by dnadeau4** [comment]
I used a regular expression to match each item of your list,  This `123ISMIP6123` will match the regular expression "ISMIP6".  If you want to be so strict change `ISMIP6` to `^ISMIP6$` in your list of activity_id.

**Comment by Funkensieper** [comment]
Ah yes of course. Thanks for the reminder!

**Comment by durack1** [comment]
@taylor13 @dnadeau4 we need to revisit this - as we can't accept problem entries, so reopening

**Comment by dnadeau4** [comment]
@Funkensieper `PCMDI` decided to change the `C` code to add strict regular expression to the Control Vocabulary.  

This will be part of `3.2.5`  you can find the code [here](https://github.com/PCMDI/cmor/blob/cmor-3.2.5/Src/cmor_CV.c#L1781-L1793).
