### ISSUE TITLE
extra_link_args to build python extensions

### ISSUE THREAD

**Issue by jmrgonza** [PCMDI/cmor#193]
Hi,
I use the CMOR3 python extension, which I compiled using netcdf, udunits and uuid shared libraries in non standard paths. I found a small issue to import the module in a python session, due to a problem to find those libraries. It can be solved by setting the paths to the libraries in the LD_LIBRARY_PATH environment variable, but I'd like to propose to set the rpath information in the compilation of the python extension (in the _cmor.so and _cmip6_cv.so binaries).
This can be achieved easily with a few extra lines in the setup.py.in template, by parsing the options starting with "-Wl," in the for loop starting at line 14, and adding them to the extension options as an argument named "extra_link_args". I could post a patch, but I do not know if you like external users messing with your code.
I think this issue may be related to the one of the comments reporting an ImportError in #188

**Comment by jmcgove** [comment]
That solved Import Error, thanks! Setting LD_LIBRARY to uuid on command line, export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/uuid-1.6.2/lib did it. That works ok, but am not sure where the paths of these go in setup.py.in in cmor, in library_dirs.

**Comment by jmrgonza** [comment]
I just forked the project to implement those changes. You can take a look [here](https://github.com/jmrgonza/cmor/blob/master/setup.py.in).

**Comment by dnadeau4** [comment]
@jmrgonza if you make a `Pull Request` (PR), I will be able to merge it in `CMOR` repo directly.

**Comment by jmrgonza** [comment]
I just created the Pull Request. I tested the code with gcc compiler, but I think that it should also work at least with Intel and Cray compilers.

**Comment by jmcgove** [comment]
Thanks. When I run ece2mor3 I get errors which seem to do with paths. If you want to have a look see if you have an idea, the errors are in the link. (If not it is ok, these may be due to an actual ece2cmor3 issue)

https://github.com/goord/ece2cmor3/issues/40

**Comment by durack1** [comment]
@jmcgove it's very difficult to debug issues with another package that is repackagin cmor3, is there a way that you can test cmor standalone and work out the kinks, before wrapping it into ece2cmor3?

**Comment by jmcgove** [comment]
Cmor3 on its own builds ok, so there is no prob there. I have the path of the ifs2cmor files declared ok, unless I need to specify another option, which I don't think I need to. Looks like it something with ece2cmor3.

**Comment by dnadeau4** [comment]
@jmcgove I don't find `griddes` in any of my code.  I grep every possible files.

**Comment by jmcgove** [comment]
Denis, griddes in ifs2cmor.py in ece2mor3 (meant to say it's to do with
ece2mor3 not cmor, prob why you didnt see it).

**Comment by dnadeau4** [comment]
@jmcgove Do you still have problem with grids?
