### ISSUE TITLE
source Global Attribute sometimes corrupt

### ISSUE THREAD

**Issue by jonseddon** [PCMDI/cmor#200]
Hi,

Occasionally the source global attribute is corrupt in files generated by CMOR. Unfortunately I've not been able to work out the precise input conditions that cause this or to generate a simple reproducible example that would allow you to see what's going on. For a set of input conditions that causes this problem then the problem occurs every time that CMOR is run.

When the source global attribute is corrupt then it appears in ncdump as something like:
`                :source = "<FF><FF><FF><FF><F3><87><C3><C0>3333<F3><87><C3><C0>" ;`

I have uploaded an example affected file to http://192.171.139.48/static/ta_Amon_HadGEM3-GC31-LM_highresSST-present_r1i1p1f1_gn_195001-195012.nc

I'm using CMOR version 3.2.4. It also occurs in data generated by the EC-Earth institution using an earlier version of CMOR. Therefore I don't think that this is a problem with our front end to CMOR as EC-Earth have their own. Unfortunately I haven't been able to make the problem occur in a simple Python example.

I'm really sorry that I can't give you more information to work with. Do you have any suggestions from the information that I have given here? If not, then please don't worry and I will continue to try and generate a reproducible example for you.

Thanks,

Jon

**Comment by dnadeau4** [comment]
@jonseddon I looked at you file and found out that `HadGEM3-GC31-LM`  did **not** exist in the experiment section of the [CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json). (It does now...)   I also found that it **was** added to the [CMIP6_source.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json)


I reran my [script](https://github.com/PCMDI/cmor/blob/master/scripts/createCMIP6CV.py) to create the CMIP6_CV.json file.  And the source now appear in this new section.   


**_Note:_**  
------------
The source has `carriage return \n` in the string

source_entry
------------
Here is the source you needed for `cmor`

```json
            "HadGEM3-GC31-LM":{
                "activity_participation":[
                    "HighResMIP"
                ],
                "cohort":[
                    "Registered"
                ],
                "institution_id":[
                    "MOHC"
                ],
                "source_id":"HadGEM3-GC31-LM",
                "source":"HadGEM3-GC31-LM (2016): \naerosol: UKCA-GLOMAP-mode\natmos: MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)\natmosChem: none\nland: JULES-HadGEM3-GL7.1\nlandIce: none\nocean: NEMO-HadGEM3-GO6.0 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude; 75 levels; top grid cell 0-1 m)\nocnBgchem: none\nseaIce: CICE-HadGEM3-GSI8 (ORCA025 tripolar primarily 0.25 deg; 1440 x 720 longitude/latitude)"
            },

```

**Comment by durack1** [comment]
@jonseddon out of curiosity, did you edit the `CMIP6_CV.json` file to add in `HadGEM3-GC31-LM`? We're trying to figure out how this occurred

**Comment by jonseddon** [comment]
We have a modified copy of the MIP tables and `CMIP6_CV.json` file (at https://github.com/jonseddon/cmip6-cmor-tables) because we also use CMOR to generate PRIMAVERA data (https://www.primavera-h2020.eu/), which contains some additional variables that we will use in PRIMAVERA but which aren't part of HighResMIP. I manually included `HadGEM3-GC31-LM` in `CMIP6_CV.json` in my local clone while WCRP-CMIP/CMIP6_CVs#343 was in progress so that I could test data generation with our front-end to CMOR.

I've not finished testing yet, but late yesterday we believe that there was a difference between the latest  `CMIP6_CV.json` and our copy that was causing this issue. I'll process a year of data later to confirm that this is the case and update this issue.

Thanks for taking the time to look into this!

**Comment by durack1** [comment]
@jonseddon we would recommend that the latest version of CMOR/tables are always being used, as there are many issues that are being resolved in the dataRequest, and once these are released @dnadeau4 propagates the fixes into the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables). Even with the latest [01.00.12](https://www.earthsystemcog.org/projects/wip/CMIP6DataRequest) version of the dataRequest, there are still outstanding issues

Regarding the problem above, my first guess would be that the `HadGEM3-GC31-LM` entry in your edited `CMIP6_CV.json` is the problem, I was unable to find this model registered in your [`CMIP6_CV.json`](https://github.com/jonseddon/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) file

**Comment by dnadeau4** [comment]
@jonseddon in version 3.2.5,  I changed `cmor` to verify only the text up to `)`

source ='HadGEM3-GC31-LM (2016)' will be valid.  If you don't set it, `cmor` will use the one from the`CMIP6_CV.json` file.
This one:
[`CMIP6_CV.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L708)

**See NOTE 13**

Source has very strict rules that you can find in the CMIP6 google doc.
https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit

**Comment by jonseddon** [comment]
@durack1 @dnadeau4 Thanks for all that. Using the latest CMIP6_CV.json file fixes this issue.

We are trying to move to the latest version of the data request, but we need to remain consistent with the other institutions in the PRIMAVERA project. I think that we have agreement to change now.

**Comment by dnadeau4** [comment]
I am releasing a new version today.  I have 2 issues to solves first.  Hopefully I can the horrific checklist today.

**Comment by dnadeau4** [comment]
@jonseddon I just release [3.2.5](https://github.com/PCMDI/cmor/releases/tag/CMOR-3.2.5)
