### ISSUE TITLE
PrePARE treatment of missing "cell_measures"

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#205]
We need to make sure CMOR can handle checks of cell_measures when Martin has specified "-opt"  (i.e., optional).  Details to follow.

**Comment by dnadeau4** [comment]
`-opt` is changed automatically to "" in the output file.  There is nothing to check unless the user modify `cell_measures`  manually using CMOR API.

If this happens PrePARE will warn the user that cell_measure does not match what is in the table.  
There is no way for me to verify it.

**Comment by taylor13** [comment]
In this case does cmor write cell_measures = "" or does it omit cell_measures.  I think it should omit it.

**Comment by dnadeau4** [comment]
Every attributes are omitted if they have an empty value ("").

**Comment by taylor13** [comment]
o.k. that's good.
thanks.
