### ISSUE TITLE
Variable name: template

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#208]
Hi,
`extern int cmor_CreateFromTemplate(int vid, char *template, char *outpath, char *sep)` 
has an argument `*template`.
If I try to link CMOR to CDOs with the g++ compiler, the compiler says:
`error: expected ',' or '...' before 'template'`
It is the only error which arises and if I change the name to `templateSTH` the compiling works. Is there a way to make the compiler work without changing the code or can you otherwise just name the variable different? It would help a lot.
Regards and thanks for an answer,
Fabi

**Comment by dnadeau4** [comment]
@wachsylon CMOR is not object oriented, You will need to encapsulate its functions with 
```C
#ifdef __cplusplus
extern "C" {
#endif

// all of your legacy C code here

#ifdef __cplusplus
}
#endif
```

I will rename the variable, but it will happens only in 3.2.6 release.

**Comment by dnadeau4** [comment]
I pushed it in branch `cmor-3.2.6` Denis

https://github.com/PCMDI/cmor/blob/cmor-3.2.6/Src/cmor.c#L5280-L5281

**Comment by wachsylon** [comment]
Ok thank you! I did in the way you mentioned. It seems that `template` is a key in cplusplus which confuses the compiler.

**Comment by dnadeau4** [comment]
I have changed the name template for you in 3.2.6.
