### ISSUE TITLE
Changes in long names

### ISSUE THREAD

**Issue by martinjuckes** [PCMDI/cmor#211]
An issue has been raised about PrePare expecting different long names from those specified in the data request (https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/218 ). Can you stick to those specified in the request to avoid confusion? If you need a filter applied to remove quotes etc, let me know and I will apply it before distributing.

**Comment by dnadeau4** [comment]
Quotes are problemantic in Python. I strip a lot of special characters, from your database or my program crash.

**Comment by dnadeau4** [comment]
I add to change your `single quote` character to 2 `single quote` characters for SQL command.
```
'surface ''skin'' temperature on land use tile', '', 
```
The JSON file now shows this.  (and was read correctly by Python).

``` json
        "tslsiLut": {
            "frequency": "mon",
            "modeling_realm": "land",
            "standard_name": "surface_temperature",
            "units": "K",
            "cell_methods": "area: time: mean where landuse",
            "cell_measures": "area: areacella",
            "long_name": "surface 'skin' temperature on land use tile",
            "comment": "temperature at which long-wave radiation emitted",
            "dimensions": "longitude latitude landUse time",
            "out_name": "tslsiLut",
            "type": "",
            "positive": "",
            "valid_min": "",
            "valid_max": "",
            "ok_min_mean_abs": "",
            "ok_max_mean_abs": ""
        },
```
This SQL command 
```sql
insert into CMORvar values ('0', '0', '', 'mon', 'tslsiLut', 'Emon', 
'land', '', '', '', 'LUMIP [Lmon_Lut]', 
'', '12', '0', 'e9fa6830-c1ce-11e6-8067-ac72891c3257', 
'surface ''skin'' temperature on land use tile', '', 
'd22db4d8-4a9f-11e6-b84e-ac72891c3257', '', '', 
'590e417e-9e49-11e5-803c-0d0b866b59f3') 
```

**Comment by martinjuckes** [comment]
OK, I understand the problem .. I've already stripped a lot of special characters to stop my programs crashing when people provide me with spreadsheets. Can you provide a list of the characters which are causing problems, or the python snippet that does the stripping, so that I can clean the request at source?

**Comment by dnadeau4** [comment]
This has  been taking care of in 3.2.6.  I changed the parser to accept `'` if they still exist.
