### ISSUE TITLE
Redundant message added to history attribute for variables

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#215]
Using CMOR 3.2.5, I noticed some variables now have a `history` attribute containing a redundant message: `2017-07-24T11:50:20Z altered by CMOR: replaced missing value flag (1e+20) with standard missing value (1e+20).`; just thought I'd let you know :)

**Comment by dnadeau4** [comment]
Can you provide me with an example,  all my tests seem to be ok.

**Comment by dnadeau4** [comment]
Ok found one.  I have to release today, so it might not make it.
                hfls293:history = "2017-08-24T18:36:18Z altered by CMOR: Changed sign. 2017-08-24T18:36:18Z altered by CMOR: Reordered dimensions, original order: time lon lat. 2017-08-24T18:36:18Z altered by CMOR: replaced missing value flag (1e+20) with standard missing value (1e+20)." ;

**Comment by dnadeau4** [comment]
Fix in 3.2.6  I change the float equality comparison with a < EPSILON comparison.

**Comment by taylor13** [comment]
I don't think this is necessarily the right thing to do.  The representation of 1.0e20 as single precision floating point is well defined and so if there is any difference, then CMOR should correct the value specified.  

But I suspect that what is happening is that when the user tells CMOR what their missing value is, it gets passed as a double precision float (or is caste as double) and then converted back to float for comparison with CMOR's missing_value (as specified in the CMOR table.  CMOR then detects a difference.   The way to correct this is to make sure the user actually passes to CMOR a single precision float to CMOR.

**Comment by ehogan** [comment]
I just checked one of my tests and `missing_value` is a single precision float (`numpy.float32`); could the conversion you're suggesting be happening in CMOR somewhere?

**Comment by dnadeau4** [comment]
@taylor13 it is the right think to do.   You should never compare floats with equality in computer sciences. 
 
http://www.cygnus-software.com/papers/comparingfloats/Comparing%20floating%20point%20numbers.htm

**Comment by dnadeau4** [comment]
@ehogan if your variable is `float` and not `double` then your are fine.   There were some missing values in the formula terms which are double and casting from 1e20f to 1e20 (double) is problematic in that case.

**Comment by dnadeau4** [comment]
@ehogan in CMOR 3.2.6 I got rid of the missing_value and fill_value for `formula_terms` so this won't be an issue anymore.

**Comment by taylor13** [comment]
I would note that the floating point representation of 1.e20 should be identical no matter what code is used to assign that value to a variable.  On the other hand, I don't think you can guarantee that the following code will always lead to the same result, independent of the coding language:

```
define e and f as single precision, 32 bit variables
define d = double precision, 64 bit variable

          f = 1.e20    
          d = 1.d20 
          e = d
         if (e == f) 
             print "equivalent"
         else
             print "not equivalent"
         endif
```
Similarly, if in the above you set d = 1.e20 (single cast to double), you won't necessarily expect to get "equivalent".

*BUT*, you should be able to count on the result of the following to be "TRUE":

```
define e, f and g as single precision, 32 bit variables

      f = 1.e20
      g = 1.e20
      h = f

      if (f == g) and (g = h) 
            print,  "TRUE"
      else
            print, "FALSE"
      endif
```

In the case of "missing_value", we want to be sure that the value that appears in the attribute "missing_value" is identical (bit for bit) with the value appearing in the data array where values are missing.

**Comment by dnadeau4** [comment]
@taylor13 that issue #215 was for the history log message.  The change I made will ensure that the history attribute does indicate some erroneous information like this one. 

`replaced missing value flag (1e+20) with standard missing value (1e+20)."`

finally, missing_value will always be set right.  the `output missing value` is set to double and `cmor` will change the `input missing value` by casting from a double to a float which is valid.   

As well, the user can pass it's own missing value tolerance, the default is 1e-4.

See code,  I am sure you wrote this...
https://github.com/PCMDI/cmor/blob/master/Src/cmor_variables.c#L2593-L2597

**Comment by ehogan** [comment]
I have just tested CMOR 3.2.7 and can confirm that this issue is resolved. Thanks @dnadeau4! :)
