### ISSUE TITLE
further_info_url

### ISSUE THREAD

**Issue by markcollier** [PCMDI/cmor#217]
I've installed latest cmor3 using conda on new machine, and trying to port my working pything code to it. Struggling to get through what are probably minor issues:

for example,
! Error: The attribute "further_info_url" could not be validated. 
! The current input value is "http://research.csiro.au/dfp" which is not valid 
! Valid values must match the regular expression:
!       ["^http://furtherinfo.es-doc.org/[[:alpha:]]\{1,\}$"  ...] 
! 
! Check your Control Vocabulary file "cmor/Tables/CMIP6_CV.json".
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!ESC[0m

I have tried multiple versions to get this through but what is wrong with:

    "further_info_url":             "http://research.csiro.au/dfp",
?

Admittedly my regular expression syntax knowledge is poor.

Thanks,
Mark.

**Comment by markcollier** [comment]
I also have a similar problem for the license attribute:

! Error: The attribute "license" could not be validated. 
! The current input value is "CMIP6 model data produced by CSIRO is licensed under a Creative Commons Attribution "ShareAlike" 4.0 International License (https://creativecommons.org/licenses/by/4.0/). Use of the data must be acknowledged following guidelines found at.* Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in data files). The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." which is not valid 
! Valid values must match the regular expression:
!       ["^CMIP6 model data produced by .* is licensed under a Creative Commons Attribution.*ShareAlike 4.0 International License (https

to me it looks like my string would be matched by the regular expression macro?

Thanks,
Mark.

**Comment by dnadeau4** [comment]
@markcollier `further_info_url` does not need to be set,  `CMOR` will set it for you to a link that is created by`es-doc.org.`

`license` was imposed to us by `WCRP` and is a bit of a nightmare to validate. 
Make sure that you don't have any special character such as `"`.  

The license REGEX can be found here:
https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L1323

Here is the one I used in my tests:

CMIP6 model data produced by Lawrence Livermore PCMDI is licensed under a Creative Commons Attribution ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) and at https:///pcmdi.llnl.gov/. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law.

**Comment by dnadeau4** [comment]
https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html

**Comment by markcollier** [comment]
Thanks I was able to squeeze through your modified license string, replacing institution.

Still can't get further_info_url to work, it automatically creates:
http://furtherinfo.es-doc.org/CMIP6.CSIRO.CAFE-1-0.ism-pdControl-std.none.r0i1p1f1
which it says is not valid?
I'll keep trying some random approaches - keen to get past this so that I can create some data...thanks for help and happy birthday Paul for tomorrow!

**Comment by markcollier** [comment]
I think I can bypass this for now by simply assigning it to "" - I am getting a core dump in my code but don't think it has anything to do with cmor ;)

**Comment by dnadeau4** [comment]
`CMIP6_CV.json` `cronjob` changed `my further_url_info` REGEX to an old version where there were no `-` characters.

Try this instead. `"http://furtherinfo.es-doc.org/.*"`
https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L8545-L8546


It should pass....

**Comment by taylor13** [comment]
Is this for CMIP6?  If so, looks to me like institution_id should be specified as CSIR-CSIRO or CSIRO-BOM, which have both been registered, but "CSIRO" hasn't.  Also CAFE-1-0 hasn't yet been registered.  Did both of these problems pass CMOR's check of source_id and institution_id?

**Comment by markcollier** [comment]
Hi, I tried the suggested further_info_url that you suggested but with same error. My "" entry seems to get past that issue for now. Hi Karl, it is a long story but I am now part of a decadal modelling team, we are using the GFDL modelling system configured to have a grid like the CMIP5 ACCESS model. I am not part of the ACCESS group, I was made redundant from there last year and was redeployed into the new project (but I am still sitting in the ACCESS team structure!)... Anyway, I have been rewriting the decadal model (using CMOR) which has been called CAFE, the CSIRO Climate Analysis Forecasting Ensemble system. It is being run in "climate mode" but also in an ensemble and DA mode, in a python based system called CAFEPP (CAFE post-processor). Although there is no formal commitment, one possibility is to submit data to CMIP6, clearly the decadal MIP would be an obvious one. Like a lot of groups doing decadal simulation, there is a lot of interest to benchmark current performance and put it on the web. My thinking is that we should take advantage of the ESG infrastructure where possible, even if it is not being published publicly as part of CMIP6. Although, as we are developing the model, it could be submitted to CMIP6 if there is enough resources and interest. The institution is clearly CSIRO (there are no formal partners), and the model name I believe has been signed off, although there might be changes as the project is only 6 months old now. Do you think I should try to formally submit a model/institution name, incase we go down the path of submitting to CMIP6? I believe CMOR gives me a warning about the values I have given but not an error. I'll try to check it out further but currently stuck with a segmentation fault on my macbook, I'm porting my code to a machine dedicated to the decadal project now and see how far I can get. More info. about the modelling project can be found at https://research.csiro.au/dfp/
Hope all is well and good your end...

**Comment by dnadeau4** [comment]
@markcollier Can you send me your USER INPUT JSON file, I would like to fix the sgementation fault.  You should not be getting these, there must be a NULL pointer that I have not found yet.

**Comment by dnadeau4** [comment]
REGEX `.*`  means followed by 0 or more characters.  So it should have passed the test.   

Make sure that you don't define it anywhere and let CMOR handle it.

**Comment by markcollier** [comment]
{
    "_control_vocabulary_file":     "CMIP6_CV.json",
    "_cmip6_option":                "CMIP6",
    "activity_id":                  "CMIP",
    "outpath":                      "CMIP6",
    "experiment_id":                "ism-pdControl-std",
    "calendar":                     "noleap",
    "realization_index":            "1",
    "initialization_index":         "1",
    "physics_index":                "1",
    "forcing_index":                "1",
    "source_type":                  "ISM",
    "sub_experiment":               "none",
    "sub_experiment_id":            "none",
    "contact ":                     "mark.collier@csiro.au",
    "branch_time":                  "90945",
    "branch_method":                "standard",
    "further_info_url":             "",
    "grid":                         "native atmosphere N96 gaussian grid (90x144 latxlon)",
    "grid_label":                  "gn",
    "grid_resolution":              "100 km",
    "nominal_resolution":           "100 km",
    "tracking_prefix":              "hdl:21.14100",
    "institution_id":               "CSIRO",
    "institution":                  "Commonwealth Scientific and Industrial Research Organisation, Australia",
    "references":                   "Model system described by O'Kane et al. (2017)",
    "run_variant":                  "forcing: GHG, Oz, SA, Sl, Vl, BC, OC, (GHG = CO2, N2O, CH4, CFC11, CFC12, CFC113, HCFC22, HFC125, HFC134a)",
    "source_id":                    "CAFE-1-0",
    "source":                       "CAFE-1-0",
    "output_path_template":         "<activity_id><institution_id><source_id><experiment_id><variant_label><table><variable_id><grid_label><version>",
    "output_file_template":         "<variable_id><table><experiment_id><source_id><variant_label><grid_label>",
    "license":                      "CMIP6 model data produced by CSIRO is licensed under a Creative Commons Attribution ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file) and at https:///pcmdi.llnl.gov/. The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law."
}

**Comment by markcollier** [comment]
On another issue, after trialing various things yesterday, now I cannot import cmor into python:

(CMOR) Snapper-as:cafepp col414$ python
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 13:29:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
>>> import numpy
>>> import cmor
Fatal error in MPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(474)..............: 
MPID_Init(190).....................: channel initialization failed
MPIDI_CH3_Init(89).................: 
MPID_nem_init(320).................: 
MPID_nem_tcp_init(173).............: 
MPID_nem_tcp_get_business_card(420): 
MPID_nem_tcp_init(379).............: gethostbyname failed, Snapper-as (errno 1)
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=3191311
:
system msg for write_line failure : Bad file descriptor

no idea where this has come from as it was at least stable. Perhaps I should be trying an older version of cmor for now...

Regards,

**Comment by dnadeau4** [comment]
Were you able to fix the issue?

**Comment by dnadeau4** [comment]
Reopen if needed. @markcollier
