### ISSUE TITLE
CMOR conda package is still 3.2.5.

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/cmor#221]
@dnadeau4 The CMOR conda package is still at 3.2.5. When can we expect 3.2.6?

**Comment by durack1** [comment]
@JimBiardCics @taylor13 - @dnadeau4 is currently on a well earned vacation and will be back in the office 21st August, so expect a new CMOR release later that, or the following week

**Comment by dnadeau4** [comment]
I will try to work on the `obs4MIPs` `source_id` this week.  No promises.

**Comment by durack1** [comment]
@dnadeau4 great, I've got a PR with the updated demo ready to test

@gleckler1

**Comment by durack1** [comment]
@JimBiardCics the `nightly` channel (see https://anaconda.org/PCMDI/cmor/files) will get you there, this has been confirmed to work with the latest [PCMDI/obs4MIPs-cmor-tables](https://github.com/PCMDI/obs4MIPs-cmor-tables) so is good to go

We'll next need to start registering your `institution_id` and `source_id` values so they are automagically in the `obs4MIPS_CV.json` file.

I'll close this issue, as it's not really `cmor`-related
