### ISSUE TITLE
tweak treatment of "frequency"

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#223]
We are very likely going to shorten the frequency label for "monClim" to  "monC".  CMOR could be generalized to treat both these cases by replacing 

```
} else if (strstr(frequency, "monClim") != NULL) {
frequency_code = 6;
```
with 
```
} else if (strstr(frequency, "monC") != NULL) {
frequency_code = 6;
```

**Comment by durack1** [comment]
@dnadeau4 is this to be labeled against `3.2.6` or a later release?

**Comment by dnadeau4** [comment]
Done in 3.2.6.
