### ISSUE TITLE
difference of cmor2 and cmor3

### ISSUE THREAD

**Issue by cym263** [PCMDI/cmor#228]
Hi, I am wondering how the cmor3 is different from cmor2, and how to be sure which cmor version should be used for processing a specific data set?

**Comment by durack1** [comment]
@cym263 the most up-to-date version of CMOR is CMOR3, you will find comprehensive documentation at https://cmor.llnl.gov/ and can peruse the code base, submit issues against this etc within this repo.

CMOR3 is being actively developed for users to write data for the CMIP6, obs4MIPs and input4MIPs projects.

The CMOR 2.9.3 is a deprecated package which is no longer supported.

**Comment by taylor13** [comment]
And just to note, CMOR2 cannot satisfy the specifications for CMIP6, obs4MIPs, and input4MIPs.  If you rely on CMOR, you must use CMOR3.

**Comment by cym263** [comment]
Thank you very much for your answer!
Best regards,Youmin
 

    On Tuesday, September 5, 2017 11:09 PM, taylor13 <notifications@github.com> wrote:
 

 And just to note, CMOR2 cannot satisfy the specifications for CMIP6, obs4MIPs, and input4MIPs. If you rely on CMOR, you must use CMOR3.—
