### ISSUE TITLE
Climatology fields

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#23]
From: Karl Taylor
Date: Thursday, April 30, 2015 at 8:06 AM
To: "Doutriaux, Charles"
Cc: "Paul J. Durack"
Subject: CMOR climatology fields

Hi Charles,

What does CMOR do special when the time-coordinate is labeled "climatology" (in the CMOR table -- "climatology: yes")?

How does it assign the coordinate value (is it based on the mid-point of the bounds, which would not be the right thing to do), or do we just store the coordinates the user sent us?  Are any checks done?

Do we have a sample test case where we've checked CMOR treats climatologies correctly?

thanks,
Karl

**Comment by doutriaux1** [comment]
@durack1 I had a look the other day with @taylor13  we trust the user bounds... Probably not wise but I don't think there's much more we can do about it. I think we still check the value is within the bounds though.
