### ISSUE TITLE
CMOR generates cell_measures and external_variable attributes even when there is no areacell* file.

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/cmor#233]
Area files are not required for regular grids in obs4MIPs. When producing an obs4MIPs output that is on a regular lat/lon grid, the output contains cell_measures and external_variable attributes even though there will be no areacello file.

**Comment by taylor13** [comment]
In this case, the CMOR table entry for the obs4MIPs variable(s) of interest will need to be modified to eliminate the "cell_measures".  I think that will also eliminate the external_variable global attribute (but I'm not positive about that).

**Comment by JimBiardCics** [comment]
Is that something I need to do in my code?

**Comment by taylor13** [comment]
Good question.  @durack1 ?
(Maybe the table containing the variables is maintained by PCMDI)

**Comment by durack1** [comment]
@JimBiardCics what is the variable/table that you're using?

From [Amon/ccb](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/Tables/obs4MIPs_Amon.json#L18-L34) you get:
```
    "variable_entry":{
        "ccb":{
            "cell_measures":"area: areacella",
            "cell_methods":"area: time: mean",
            "comment":"Where convective cloud is present in the grid cell, the instantaneous cloud base altitude should be that of the bottom of the lowest level containing convective cloud. Missing data should be reported in the absence of convective cloud. The time mean should be calculated from these quantities averaging over occasions when convective cloud is present only, and should contain missing data for occasions when no convective cloud is present during the meaning period.",
            "dimensions":"longitude latitude time",
            "frequency":"mon",
            "long_name":"Air Pressure at Convective Cloud Base",
            "ok_max_mean_abs":"",
            "ok_min_mean_abs":"",
            "out_name":"ccb",
            "positive":"",
            "standard_name":"air_pressure_at_convective_cloud_base",
            "type":"real",
            "units":"Pa",
            "valid_max":"",
            "valid_min":""
},
```
And as @taylor13 points out this includes the `cell_measures` entry, and consequently the `external_variable` `areacella` is written to the file

**Comment by taylor13** [comment]
Since as Jim points out areacella doesn't need to be provided for regular latxlon grids, if it isn't provided then both cell_measures and external_variable should not be included as global attributes.  The variable_entry must therefore be edited and the line "cell_measures ...." removed.  At least I think that should work.  I don't know whose responsibility it is to edit the variable_entry.  Note some other obs4MIPs contributor might supply ccb data on some weird grid in which case the cell_measures line should be retained.

**Comment by durack1** [comment]
@JimBiardCics @taylor13 just FYI, for the PCMDI AMIP datasets, which is on a vanilla 360 (lon) x 180 (lat) grid, we were requested to provide a corresponding `areacello` file to make it easy for data users. So even though it may be trivial to generate such area weights, I think it should still be included in the standard tables.

**Comment by JimBiardCics** [comment]
@durack1 @taylor13 @gleckler1 The [ODSv2.x](https://docs.google.com/document/d/1FXXBhUh71Hjus557ZTD3EKPi_2zxeLvi1aICXOjVYPc/edit?pli=1#heading=h.gjdgxs) document states that area files are **not** required if bounds are provided (both in the table entry for external_variables and in Appendix 1).

I want to understand the most straightforward way to handle this. I hate the idea of editing the table files, so I would like to know if there is a way to remove the cell_measures attribute through the CMOR API.

**Comment by taylor13** [comment]
I'm pretty sure the answer is "no".  If CMOR finds cell_measures in the table, then it writes cell_measures into the file along with external_variables.  This is the desired behavior for CMIP, but it isn't a requirement for obsMIPS (and I'm happy about that).  
@dnadeau4 may know of a way to suppress writing cell_measures and external_variables in CMOR through some other configuration option (or user intervention).  If he does, I trust he'll respond.

**Comment by durack1** [comment]
@JimBiardCics was this an issue with the current `3.2.7`? Just checking

**Comment by JimBiardCics** [comment]
@durack1 Yes. It appears that the problem is currently connected to the fact that the Aday table file has areacella in seemingly every entry, but no other file has an areacell* entry.

**Comment by durack1** [comment]
@JimBiardCics yep, so this is not a CMOR issue, rather an obs4MIPs input tables (well `Aday`) issue, so will close this as you've opened up PCMDI/obs4MIPs-cmor-tables#120 - and where the problem will need to be solved
