### ISSUE TITLE
Append mode

### ISSUE THREAD

**Issue by dnadeau4** [PCMDI/cmor#235]
https://github.com/PCMDI/cmor3_documentation/issues/36#issuecomment-331323485

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/cmor/compare/CMOR-3.2.8

**Comment by wachsylon** [comment]
If data from a variable with a hybrid axis is appended to a file, the time value of the last record of the chunk file is changed to a wrong value.

**Comment by taylor13** [comment]
To be clear, is this what is done?
1) open a new file and write time slice(s) of data plus, for example, the corresponding time-slice(s) for surface pressure (needed by the hybrid vertical coordinate)
2) close the file
3) reopen the file in append mode and write additional time slice(s) of data plus surface pressure.
4) close file
5) examine file and find the time-coordinate for the last time-slice written is wrong?

Is the filename also incorrect (i.e., is the time range appearing in the filename wrong?

For files not involving hybrid vertical coordinates, does append mode work correctly?

**Comment by wachsylon** [comment]
Yes, correct. For  example data for cli, Amon, 1851 is appended to 
cli_Amon_MPI-ESM-1-2-HR_historical_r1i1p1f1_gn_185001-185012.nc
The resulting file is named correctly:
cli_Amon_MPI-ESM-1-2-HR_historical_r1i1p1f1_gn_185001-185112.nc
The time values however are:
 time = 15.5, 45, 74.5, 105, 135.5, 166, 196.5, 227.5, 258, 288.5, 319, 
    349.5, 7.50876857923353e-315, 410, 439.5, 470, 500.5, 531, 561.5, 592.5, 
    623, 653.5, 684, 714.5 ;

**Comment by wachsylon** [comment]
As far as I know, this only occurs for hybrid vertical axes so it may be a problem with the auxiliary pressure variable. The same problem occurs in CMOR2 versions.

**Comment by taylor13** [comment]
I don't see that this has been addressed.  Was it closed by mistake?

**Comment by wachsylon** [comment]
I am right now working on a test based on `test_grid` again.  Hope to finish it today.

**Comment by mauzey1** [comment]
@wachsylon @taylor13 Has this bug already been fixed by #404?  Can we close this issue?

**Comment by mauzey1** [comment]
@wachsylon @taylor13 If there are any other concerns about "append mode" then you can reopen this issue.  I will close this now.
