### ISSUE TITLE
CMOR 3.2.7 output does not match ODS v2.1 spec

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/cmor#236]
@gleckler1 @durack1 @dnadeau4 @scott-stevens

I built an obs4MIPs file using CMOR 3.2.7 and obs4MIPs tables 2.0.0 (tag value in git after pull from origin/master). The CMOR config file is attached. I've also attached the output of ncdump -h from the output file.

I found discrepancies with the ODS v 2.1 spec as listed below.

- further_info_url - The URL contains the string experiment_idsub_experiment_id
- history - The message states, "CMOR rewrote data to be consistent with CF standards." The input was already CF compliant. It was rewritten to be consistent with obs4MIPs standards.
- tracking_id - The ODS v 2.1 spec states that there should be a prefix of "hdl:21.14102/", but it's not present.

There are a few attributes added by CMOR that aren't mentioned in ODS v 2.1. I don't think this is a problem, since extra attributes are likely OK. I thought I'd mention them in case you want to add them to the spec. The extra global attributes are:
- table_id
- table_info
- cmor_version

[cmor_NDVI.json.txt](https://github.com/PCMDI/cmor/files/1337839/cmor_NDVI.json.txt)

[dump.txt](https://github.com/PCMDI/cmor/files/1337834/dump.txt)

**Comment by JimBiardCics** [comment]
@dnadeau4 When I stop and thing about it, the history attribute isn't actually out of agreement with the ODS v 2.1 spec. But it isn't stating correctly what CMOR has done.

**Comment by durack1** [comment]
@JimBiardCics I'd make sure that you are in fact using the `master` branch when attempting to generate these files, you'll see that the [PCMDI/obs4MIPs-cmor-tables/demo/rssSsmiPrw-input.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/compare/2.0.0...master#diff-eeb8396de6eae2e004385da833c02488) has changed considerably, and so will the global attributes written to a file

Following the `master` changes, the `further_info_url` should be:
```
https://furtherinfo.es-doc.org/<activity_id><institution_id><source_label><source_id><variable_id>
```
Which maps to (in the demo):
```
:further_info_url = "https://furtherinfo.es-doc.org/obs4MIPs.RSS.REMSS-PRW.REMSS-PRW-6-6-0.prw" ;
```
For the ncdump output from the current `master`, see [here](https://github.com/PCMDI/obs4MIPs-cmor-tables/pull/92#issuecomment-331236751)

**Comment by durack1** [comment]
@JimBiardCics just to note the first entry (No. 1) in the table in the [ODS-2.1 google doc](https://goo.gl/jVZsQl) is a description of `cmor_version`

If you use the latest `master` (rather than the `2.0.0` tag point which was generated back in July, are most of the points [above](https://github.com/PCMDI/cmor/issues/236#issue-261025378) dealt with? If yes, then I think we can close out this issue

**Comment by JimBiardCics** [comment]
@durack1 I am on the master branch for obs4MIPs-cmor-tables, and pulled the latest. The latest commit that I have is 06cc4883c4f61406e59d9eded45dba6dde998811, from Sept 25, 2017. I think that most of these problems are not table-based.

**Comment by JimBiardCics** [comment]
@durack1 The first entry in the table in the ODSv2.1 doc is activity_id. The data_specs_version attribute is intended to be somehow related to the Tables version, but not the CMOR version.

As I look, I see that the demo CMOR config file has new entries! tracking_prefix and _further_info_url_tmpl. Adding those takes care of those discrepancies.

That leaves the history attribute and the question of whether or not the unlisted attributes ought to be added to the ODSv2.1 doc.

**Comment by durack1** [comment]
@JimBiardCics my mistake, I omitted the word "NOTES" added to the comment above - take a peek at the table NOTES (p10) it's the first entry.

With regard to these issues, I believe you haven't updated your `input.json` (in the demo this is called [rssSsmiPrw-input.json](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/rssSsmiPrw-input.json)), which once you've updated your entries most of the problems (apart from `history` described above) will be resolved

**Comment by JimBiardCics** [comment]
Yep!

**Comment by durack1** [comment]
@JimBiardCics great, thanks for closing..

As an aside, if it satisfies you, in the [demo `input.json` file there is a placeholder `history` variable](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/rssSsmiPrw-input.json#LL26), if you do:
```python
"history": "Does this override the CMOR default history?",
```
You get in the output file:
```
:history = "Does this override the CMOR default history? ; 2017-09-27T21:39:44Z CMOR rewrote data to be consistent with CF standards." ;
```
The corresponding CMOR code is found [here](https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L2665-L2671), with the recent 3.2.7 change [here](https://github.com/PCMDI/cmor/pull/232/files#diff-038204a94c57f8deea5747661ee23c31), so feel free to make suggestions, however with so many projects using CMOR a solution will have to work for all of these separate projects
