### ISSUE TITLE
CMOR writes confusing history message

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/cmor#238]
CMOR 3.2.7 writes a global attribute to an obs4MIPs output with the message
>CMOR rewrote data to be consistent with CF standards.

The inputs to CMOR that I am using are all highly CF compliant already. A more correct statement would be
>CMOR rewrote data to be consistent with CMIP6 standards.

or
>CMOR  rewrote data to be consistent with obs4MIPs standards.

or
>CMOR rewrote data to be consistent with CF-1.7 and ODS-2.1 standards.

In that last case, the values in the Conventions attribute could be substituted into the string, making it adaptable to whatever is written there.

**Comment by taylor13** [comment]
Note that you can provide a fuller description of "history" in defining your variable (through the cmor_variable or variable function).  CMOR will tack on the end something hardwired (I guess currently it tacks on "CMOR rewrote data to be consistent with CF standards".  If CMOR is going to be applied to lots of different projects, then perhaps we should say something generic like:
"CMOR was used to write this data consistent with the data standards defined by the sponsoring project."

**Comment by durack1** [comment]
Commented copied from PCMDI/cmor#236

The corresponding CMOR code is found [here](https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L2665-L2671), with the recent 3.2.7 change [here](https://github.com/PCMDI/cmor/pull/232/files#diff-038204a94c57f8deea5747661ee23c31), so feel free to make suggestions, however with so many projects using CMOR a solution will have to work for all of these separate projects

**Comment by JimBiardCics** [comment]
@durack1 The older code looks to be superior. I think perhaps my last suggestion in my original issue might be the best solution.
@taylor13 I raised an issue about problems with the current CMOR approach to history chaining in #239.

**Comment by durack1** [comment]
@dnadeau4 how hard would it be to implement the following, provided through either the `<project>_CV.json` file, or the `userinput.json` file?:
```
obs4MIPs

%s ; CMOR rewrote data to be consistent with obs4MIPs, CF-1.7 ODS-2.1 and CF standards
%s ; CMOR rewrote data to be consistent with <activity_id>, <Conventions> and CF standards


CMIP6

%s ; CMOR rewrote data to be consistent with CMIP6, CF-1.7 CMIP-6.2 and CF standards
%s ; CMOR rewrote data to be consistent with <mip_era>, <Conventions> and CF standards

input4MIPs

%s ; CMOR rewrote data to be consistent with input4MIPs, CF-1.7 CMIP-6.2 and CF standards
%s ; CMOR rewrote data to be consistent with <activity_id>, <Conventions> and CF standards
```

**Comment by JimBiardCics** [comment]
The last bit about 'CF standards' in each case is redundant and should be removed.

**Comment by dnadeau4** [comment]
@durack1 I would have to pass the history string into my template creation.  I thought of this for filename and path, but never for anything else.  Not sure about the behavior.  As well the separator is usually `_` and `/` for filename and path. It seems that a new separator `,` is needed.  

There is also a function called cmor_update_history() for `variable` history attribute that is called quite often in the code.  String management is not easy in C but can be done.

**Comment by dnadeau4** [comment]
@durack1 we could do your https://github.com/PCMDI/cmor/issues/238#issuecomment-332903750, however this will require a reorganization of the variable declarations in CMOR. Once the reordering occurs, all these variables (which will be written to the netcdf file global attributes) are available for use in the `userInput.json`, such as `<Conventions>`, `<mip_era>` or `<activity_id>`. However, I will note that how these strings are concatenated (the separator, so spaces, `;\n`, `,` etc) will need to be rethought so that it will work for all examples above (and potentially other uses)

**Comment by JimBiardCics** [comment]
@dnadeau4 Would your suggestion require a new template entry in the userInput.json file? It seems that the message written by CMOR into the history should be entirely under CMOR's control. There should at least be a default that could possibly be overwritten by a template entry, but don't require the userInput.json file to have an entry.

**Comment by durack1** [comment]
@JimBiardCics our current thinking is that we want to have a history attribute that correctly reflects the "CMORization" for the three projects that are currently using the software, each of these is following similar, but subtly different specs, so having this info reflected (and the specs that the files conform to e.g. ODS-2.1.0) is an important part of the history.

We're trying to figure out the best way to implement this, along with preserving the existing file `:history` so will have to test this out across CMIP6, obs4MIPs and input4MIPs before the solution is merged. I have also taken a look at the behaviour of NCO and CDO to see how other packages compare (with regard to `:history` preservation), and you've correctly noted that CMOR doesn't read a file (unlike NCO/CDO), and rather is handed a matrix to write, so how this is implemented, cleanly requires a bit of thought.

**Comment by durack1** [comment]
@JimBiardCics, @dnadeau4 implemented these changes which are [now available in the conda nightly releases](https://anaconda.org/PCMDI/cmor/files?channel=nightly), the `osx-64/cmor-2017.10.05.3.2.8-*` and `linux-64/cmor-2017.10.04.3.2.8-*` variants should both work. I will pull these down myself and run a test and prepare a PR augmentation to the demo captured in PCMDI/obs4MIPs-cmor-tables#128

**Comment by dnadeau4** [comment]
Need to fix test_python_history.py which is now broken due to this change.

**Comment by durack1** [comment]
@dnadeau4 can you point me at some code that explains/demos how I go about controlling the history attribute written?

**Comment by dnadeau4** [comment]
You need to create an attribute in your `user_input.json` file.   Look at the 2 following updates.

last line in this file
https://github.com/PCMDI/cmor/blob/CMOR-3.2.8/Test/common_user_input.json#L70
custom definition:
https://github.com/PCMDI/cmor/blob/CMOR-3.2.8/Test/test_python_history.py
