### ISSUE TITLE
CMOR 3.2.7 doesn't deal well with the history attribute.

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/cmor#239]
CMOR 3.2.7 doesn't deal well with the global history attribute. An existing history attribute in the input is not passed through to the output. If a history attribute and corresponding value string is specified in the CMOR config JSON file, the output has the form

`<config history value> <date stamp> CMOR rewrote data to be consistent with CF standards.`

This makes it hard to build good history audit trails. A better approach, which would be consistent with NCO and other packages, would be to put newest entries first, end each message it adds with a newline (\n), and to always begin with a time stamp. CMOR should preserve any history from the input, prepending any messages it adds.

If the user has specified a history attribute value in the CMOR config file, it should either replace the default CMOR history message or be given its own time stamp for consistency.

If there is no history attribute in the config file, the form should be

`<date stamp> <CMOR default message>\n<history from input>`

If there is a history attribute in the config file, the form should be one of the three options below.

`<date stamp> <config file message>\n<history from input>`
`<date stamp> <CMOR default message> <config file message>\n<history from input>`
`<date stamp> <CMOR default message>\n<date stamp> <config file message>\n<history from input>`

The order of the CMOR default message and config file message in the last two options is not important.

**Comment by durack1** [comment]
Commented copied from PCMDI/cmor#236 and also ref #238 

The corresponding CMOR code is found [here](https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L2665-L2671), with the recent 3.2.7 change [here](https://github.com/PCMDI/cmor/pull/232/files#diff-038204a94c57f8deea5747661ee23c31), so feel free to make suggestions, however with so many projects using CMOR a solution will have to work for all of these separate projects

**Comment by durack1** [comment]
@JimBiardCics this is really a dupe of #328, did you want to migrate the conversation into this single (#328) issue?

**Comment by JimBiardCics** [comment]
@durack1 They are two issues. #238 relates to the specific verbiage about conformance to CF. This issue is about the way CMOR handles chaining of history messages and how it loses history coming out of input files.

**Comment by durack1** [comment]
@JimBiardCics we're going to deal with the `history` discussion as a single, issue and will keep dialogue appended to #238 rather than both here and there. The code changes required are in the same code block.

**Comment by JimBiardCics** [comment]
As I noted in another issue regarding valid_min and valid_max, it **finally** dawned on me that CMOR never sees the input file directly. My code must always transfer important attributes from the input file to CMOR.
