### ISSUE TITLE
Importing CMOR from a Python session prints 'No module named cdms2'

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#24]
When I import CMOR from a Python session, the message ```No module named cdms2``` is printed:
```
% python
Python 2.7.6 (default, Jan  3 2014, 16:42:21) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cmor
No module named cdms2
>>>
```
I can confirm that I don't have ```cdms2``` installed:
```
>>> import cdms2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cdms2
>>>
```
The ```import cdms2``` in ```pywrapper.py``` is in a try-except block but the```import cdms2``` in ```check_CMOR_compliant.py``` is not. ```__init__.py``` contains:
```python
try:
  from check_CMOR_compliant import checkCMOR
except Exception,err:
  print err
  pass
```
My concern is that this message could cause unnecessary worry for some users. Is there a way to suppress this message?

**Comment by doutriaux1** [comment]
@ehogan you[re right I should take out the print statement at least, I will look and try to see if this block is even needed at all.

**Comment by jmcgove** [comment]
Hi
Saw this thread, which is about the same error I'm getting.
I started to use ece2mor3 and cmor. I built cmor ok, When I then run ece2cmor.py in ece2mor3 I get
File "/data/jmcgovern/p-process-ECEarth/other/ece2cmor3-master/ece2cmorlib.py", line 1, in
import cmor
ImportError: No module named cmor
Do I need to specify the cmor path in ece2morlib (but there is no place to set it) or elsewhere?
Thanks
