### ISSUE TITLE
_further_info_url_tmpl: variable_id not being updated

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/cmor#241]
The new obs4MIPs user_input.json defines the ``_futher_info_url_tmpl`` attribute, for example:

    "_further_info_url_tmpl": "http://furtherinfo.es-doc.org/<variable_id>"

When rewriting multiple variables consecutively, CMOR does not seem to update the ``variable_id`` after the first variable has been written so that the ``further_info_url`` validation of the second variable fails. Here is a code example:

    import cmor
    import numpy as np

    cmor.setup(netcdf_file_action=cmor.CMOR_REPLACE)
    cmor.dataset_json('obs4MIPs_user_input.json')
    cmor.load_table('tables/obs4MIPs_Amon.json')

    # Generate dummy data
    time_resol = 1
    time = np.arange(0, 10, time_resol)
    time_bounds = np.vstack((time, time+time_resol)).transpose()

    grid_resol = 1
    lon = np.arange(-180, 180, grid_resol)
    lon_bounds = np.vstack((lon, lon+grid_resol)).transpose()
    lat = np.arange(-90, 90, grid_resol)
    lat_bounds = np.vstack((lat, lat+grid_resol)).transpose()

    data = np.ones((time.size, lat.size, lon.size))

    # Define axes
    cmor_time = cmor.axis(table_entry='time',
                          units='days since 1970-01-01 00:00')
    cmor_lon = cmor.axis(table_entry='longitude',
                         units='degrees_east',
                         length=lon.size,
                         coord_vals=lon,
                         cell_bounds=lon_bounds)
    cmor_lat = cmor.axis(table_entry='latitude',
                         units='degrees_north',
                         length=lat.size,
                         coord_vals=lat,
                         cell_bounds=lat_bounds)

    for variable in ('ccb', 'cct'):
        print variable

        # Define variable
        cmor_var = cmor.variable(table_entry=variable,
                                 units='Pa',
                                 axis_ids=[cmor_time, cmor_lat, cmor_lon])

        # Write data
        for i in range(time.size):
            cmor.write(var_id=cmor_var,
                       data=data[:].astype('f4'),
                       ntimes_passed=1,
                       time_vals=time[i],
                       time_bnds=time_bounds[i])
        filename = cmor.close(cmor_var, file_name=True)

It fails with the following error:

    C Traceback:
    In function: cmor_setGblAttr
    ! called from: cmor_write
    ! 
    
    !!!!!!!!!!!!!!!!!!!!!!!!!
    !
    ! Warning: The further info in attribute does not match the one found in your Control Vocabulary(CV) File. 
    ! We found "http://furtherinfo.es-doc.org/ccb" and 
    ! CV requires "http://furtherinfo.es-doc.org/cct" 
    ! Check your Control Vocabulary file "tables/obs4MIPs_CV.json".
    ! 
    !
    !!!!!!!!!!!!!!!!!!!!!!!!!
    
    
    C Traceback:
    ! In function: 
    
    !!!!!!!!!!!!!!!!!!!!!!!!!
    !
    ! Error: Cannot continue until you fix the errors listed above: -1
    !
    !!!!!!!!!!!!!!!!!!!!!!!!!
    
    Traceback (most recent call last):
      File "test.py", line 49, in <module>
        time_bnds=time_bounds[i])
      File "/cmsaf/nfshome/routcm/Modules_CentOS/cmor/3.2.6/lib/python2.7/site-packages/CMOR-3.2-py2.7-linux-x86_64.egg/cmor/pywrapper.py", line 800, in write
        time_vals, time_bnds, store_with)
    _cmor.CMORError: Problem with 'cmor.write'. Please check the logfile (if defined).

**Comment by dnadeau4** [comment]
The issue is in your `CV` file.  You should change `http://furtherinfo.es-doc.org/cct` to `http://furtherinfo.es-doc.org/.*`  You have `cct` and not `ccb`.

**Comment by taylor13** [comment]
Two quick points:
1) Here are the specs for further_info_url given in the ODSv2.1:
```
further_info_url has the form 
https://furtherinfo.es-doc.org/<activity_id><institution_id><source_label><source_id><variable_id>

(e.g., “https://furtherinfo.es-doc.org/obs4MIPs.RSS.REMSS-PRW.REMSS-PRW-6-6-0.prw”). 
The further_info_url page will be maintained by the ES-DOCs project and will simply 
be a rendering by the Viewer tool of information provided by modeling groups and 
recorded in so-called CIM documents.
```
so I think the template specified is wrong.

2)  Since the further_info_url is a global attribute, I'm not sure how it gets updated to include variable name information.  For CMIP6 the variable wasn't included, so this case wasn't encountered.  You *might* have to include in your loop over variables calls to one or more of the following:
```
cmor.setup(netcdf_file_action=cmor.CMOR_REPLACE)
cmor.dataset_json('obs4MIPs_user_input.json')
cmor.load_table('tables/obs4MIPs_Amon.json')
```
Perhaps @dnadeau4 can advise.

**Comment by dnadeau4** [comment]
The attribute value is checked against a regular expression found in the [CMIP6_CV](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L7365-L7367).   

The `_cmip6_option` attribute should not be set for `obs4MIPs`.

**Comment by durack1** [comment]
@Funkensieper this may be solved if you bring your CMOR file collection up-to-date with the files contained in the current [PCMDI/obs4MIPs-cmor-tables/demo](https://github.com/PCMDI/obs4MIPs-cmor-tables/tree/master/demo) directory - in particular the [PCMDI/obs4MIPs-cmor-tables/demo/Tables](https://github.com/PCMDI/obs4MIPs-cmor-tables/tree/master/demo/Tables) files which includes `obs4MIPs_CV.json`, along with the userInput.json (in the demo this is called `rssSsmiPrw-input.json`)

**Comment by Funkensieper** [comment]
@dnadeau4 The CV contains neither ``cct`` nor ``ccb`` but literally ``<variable_id>`` in order to let CMOR substitute this placeholder with the current global attribute.
@durack1 I used the most recent obs4MIPs demo.
@taylor13 1.) I know the template is incomplete, I just wanted to provide a minimal example. 2.) Your suggestion solves the problem and CMOR generates the correct ``further_info_url`` attributes. But that means I have to do the whole CMOR setup for each variable:

    for variable in ('ccb', 'cct'):
        print variable
    
        # Setup CMOR
        cmor.setup(netcdf_file_action=cmor.CMOR_REPLACE)
        cmor.dataset_json('obs4MIPs_user_input.json')
        cmor.load_table('tables/obs4MIPs_Amon.json')
    
        # Define axes
        cmor_time = cmor.axis(table_entry='time',
                              units='days since 1970-01-01 00:00')
        cmor_lon = cmor.axis(table_entry='longitude',
                             units='degrees_east',
                             length=lon.size,
                             coord_vals=lon,
                             cell_bounds=lon_bounds)
        cmor_lat = cmor.axis(table_entry='latitude',
                             units='degrees_north',
                             length=lat.size,
                             coord_vals=lat,
                             cell_bounds=lat_bounds)
    
        # Define variable
        cmor_var = cmor.variable(table_entry=variable,
                                 units='Pa',
                                 axis_ids=[cmor_time, cmor_lat, cmor_lon])
    
        # Write data
        for i in range(time.size):
            cmor.write(var_id=cmor_var,
                       data=data[:].astype('f4'),
                       ntimes_passed=1,
                       time_vals=time[i],
                       time_bnds=time_bounds[i])
        filename = cmor.close(cmor_var, file_name=True)

I can live with that, but it's not very intuitive.

**Comment by durack1** [comment]
@Funkensieper are you happy for this issue to be closed?

**Comment by Funkensieper** [comment]
Sure, the workaround is fine.
