### ISSUE TITLE
Extend cmor.set_variable_attribute to include attribute type

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#244]
It's become clear that the type of all attributes set by the python cmor bindings is ignored by [`cmor.set_variable_attribute`](https://cmor.llnl.gov/mydoc_cmor3_api/#cmor_set_variable_attribute), so that in the [PCMDI/obs4MIPs-cmor-tables/demo/runCmorDemo.py](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/master/demo/runCmorDemo.py#L63-L65):
```
cmor.set_variable_attribute(varid,'valid_min',2.0)
cmor.set_variable_attribute(varid,'valid_max',3.0)
```
Is written to the file as:
```
netcdf prw_mon_REMSS-PRW-6-6-0_BE_gn_198701-198812 {
dimensions:
	time = UNLIMITED ; // (24 currently)
	lat = 72 ;
	lon = 144 ;
	bnds = 2 ;
variables:
...
	float prw(time, lat, lon) ;
...
		prw:valid_min = "2.0" ;
		prw:valid_max = "3.0" ;
...
```
So the `float` type is then converted to a `string` type. Adding an additional `type` argument to `cmor.set_variable_attribute` would fix this issue.

The input ***should*** be:
```
cmor.set_variable_attribute(varid,attName='valid_min',type=float32,attVal=2.0)
cmor.set_variable_attribute(varid,attName='valid_max',type=float32,attVal=3.0)
```

The output ***should*** be:
```
netcdf prw_mon_REMSS-PRW-6-6-0_BE_gn_198701-198812 {
...
	float prw(time, lat, lon) ;
...
		prw:valid_min = 2.0f ;
		prw:valid_max = 3.0f ;
...
```

PCMDI/obs4MIPs-cmor-tables#113
#237 
#243 
@JimBiardCics @taylor13 @dnadeau4

**Comment by dnadeau4** [comment]
I will add the type into the API and warn the user if the attribute type does not match the variable type except for `string`

**Comment by durack1** [comment]
@JimBiardCics, @dnadeau4 implemented these changes which are [now available in the conda nightly releases](https://anaconda.org/PCMDI/cmor/files?channel=nightly), the `osx-64/cmor-2017.10.05.3.2.8-*` and `linux-64/cmor-2017.10.04.3.2.8-*` variants should both work. I will pull these down myself and run a test and prepare a PR augmentation to the demo captured in PCMDI/obs4MIPs-cmor-tables#128

**Comment by durack1** [comment]
@dnadeau4 I just checked `cmor-2017.10.26.3.2.8-np19py27hca1bf6f_0`, and didn't get the behaviour that I expected.

The [`runCmorDemo.py`](https://github.com/PCMDI/obs4MIPs-cmor-tables/blob/c7a7f126c8f51c31419a7c3f470462eccdf2ed6d/demo/runCmorDemo.py) includes:
```
cmor.set_variable_attribute(varid,'valid_min','f',2.0)
cmor.set_variable_attribute(varid,'valid_max','f',3.0)
```
Yet, the output file includes:
```
netcdf prw_mon_REMSS-PRW-6-6-0_BE_gn_198701-198812 {
dimensions:
	time = UNLIMITED ; // (24 currently)
	lat = 72 ;
	lon = 144 ;
	bnds = 2 ;
variables:
...
	float prw(time, lat, lon) ;
		prw:standard_name = "atmosphere_water_vapor_content" ;
		prw:long_name = "Water Vapor Path" ;
		prw:comment = "vertically integrated through the atmospheric column" ;
		prw:units = "kg m-2" ;
		prw:cell_methods = "area: time: mean" ;
		prw:missing_value = 1.e+20f ;
		prw:_FillValue = 1.e+20f ;
		prw:valid_min = 0.f ;
		prw:valid_max = 0.f ;
...
```
When it should be:
```
		prw:valid_min = 2.0f ;
		prw:valid_max = 3.0f ;
```
Ref PCMDI/obs4MIPs-cmor-tables#130

**Comment by durack1** [comment]
@dnadeau4 are the updates that fix this issue in the latest nightly? [`cmor-2017.11.01.3.2.8-*`](https://anaconda.org/PCMDI/cmor/files)

**Comment by dnadeau4** [comment]
They should be.  That file was created automatically with travis without testing after I pushed to github.

**Comment by dnadeau4** [comment]
Actually it does run the tests that are in the Makefile.in

**Comment by durack1** [comment]
@dnadeau4 great, I can confirm that for the nightly (`2017.11.01.3.2.8-np19py27h1e94580_0`) these changes work great
```
netcdf prw_mon_REMSS-PRW-6-6-0_BE_gn_198701-198812 {
dimensions:
	time = UNLIMITED ; // (24 currently)
	lat = 72 ;
	lon = 144 ;
	bnds = 2 ;
variables:
...
	float prw(time, lat, lon) ;
		prw:standard_name = "atmosphere_water_vapor_content" ;
		prw:long_name = "Water Vapor Path" ;
		prw:comment = "vertically integrated through the atmospheric column" ;
		prw:units = "kg m-2" ;
		prw:cell_methods = "area: time: mean" ;
		prw:missing_value = 1.e+20f ;
		prw:_FillValue = 1.e+20f ;
		prw:valid_min = 2.f ;
		prw:valid_max = 3.f ;

// global attributes:
...
		:cmor_version = "3.2.8" ;
...
```
