### ISSUE TITLE
license attribute validation 

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [PCMDI/cmor#248]
PREpare complains about our  license attribute. But, it looks correct. No? 
Suggestions? 

Do we disregard this error and proceed? 

C Traceback:
! In function: _CV_ValidateAttribute
! called from: _CV_checkGblAttributes
!

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The attribute "license" could not be validated.
! The current input value is "CMIP6 model data produced by NOAA-GFDL is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file). The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." which is not valid
! Valid values must match the regular expression:
! 	["^CMIP6 model data produced by .* is licensed under a
!
!!!!!!!!!!!!!!!!!!!!!!!!!

C Traceback:
! In function: _CV_checkGblAttributes

**Comment by dnadeau4** [comment]
You have a "/" at the end of "/licenses"  in the link above.  We are revising the Google document to get rid of it since people have already start to create their file and changing the CMIP6_CV make PrePARE fail.

**Comment by dnadeau4** [comment]
Finally, we will change the CMIP6_CV to match `/licenses/` or `/license` without revising the Google document.

**Comment by dnadeau4** [comment]
@aradhakrishnanGFDL Did this work for you?
