### ISSUE TITLE
Question on PrePARE checking long_name, CF, units

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [PCMDI/cmor#251]
Does/Will PrePARE validate CF, long names and units in the input file for ESGF publishing?

**Comment by dnadeau4** [comment]
Yes they are.  All variable attributes that `cmor` would write in the file are validated by `PrePARE` including `units` and `long_names` if present.

For example in `Omon` table `htogyre` these  is validated.  (Float are a bit different). 

```
'comment': 'From all advective mass transport processes, resolved and parameterized.'
'_FillValue': 0.0
'long_name': 'Northward Ocean Heat Transport due to Gyre'
'standard_name': 'northward_ocean_heat_transport_due_to_gyre'
'cell_methods': 'longitude: mean time: mean'
'cell_measures': 'area: areacella'
'units': 'W'
'missing_value': 0.0
```

Here is the code....

https://github.com/PCMDI/cmor/blob/master/LibCV/PrePARE/PrePARE.py#L326-L352

**Comment by taylor13** [comment]
in CMIP6, aren't missing_value and _FillValue supposed to be 1.e20??? (rather than 0., as in the example).

**Comment by dnadeau4** [comment]
I looked ant these 2 are not validate by PrePARE since they are not initialized.   

```python
                if isinstance(table_value, float):
                    if(table_value / file_value < 1.1):
                        table_value = file_value
```

**Comment by taylor13** [comment]
So in your "Omon" table example above, which attributes are checked by PrePARE?

**Comment by dnadeau4** [comment]
All the strings one, which include `units` and `long_name` as asked by @aradhakrishnanGFDL

**Comment by dnadeau4** [comment]
if isinstance(table_value, float):
                    if(file_value == 0):
                        if(table_value != file_value):
                            file_value = False
                    else:
                        if(1-(table_value / file_value) < 0.00001):
                            table_value = file_value
