### ISSUE TITLE
Add more links to the CMIP6 CMOR tables repo from the web site?

### ISSUE THREAD

**Issue by jypeter** [PCMDI/cmor#253]
@dnadeau4 it took me some time to find https://github.com/PCMDI/cmip6-cmor-tables from the CMOR web site. Would it be possible to add links to it from several sections of the CMOR web site?

- **Getting started** page: eg For metadata, different MIPs may have different requirements, but these are accommodated by CMOR, within the constraints of the CF convention and as specified in the MIP tables (e.g. [CMIP6 MIP tables](https://github.com/PCMDI/cmip6-cmor-tables))
- [CMIP6 Table Excerpt](https://cmor.llnl.gov/mydoc_cmip6_table_excerpt/)
- ... and other places where the user may want to have a look at a MIP table

Also, on https://github.com/PCMDI/cmip6-cmor-tables, would it be possible to have links to a human readable version of the tables, like the links at the bottom of https://github.com/WCRP-CMIP/CMIP6_CVs ?

Thanks!

**Comment by dnadeau4** [comment]
@jypeter I will add it to the documentations.  I work only on this project on Wednesdays now.  
Thanks a lot for this issue!

**Comment by jypeter** [comment]
Yes, no rush, that's just a minor request!
