### ISSUE TITLE
Problems with "Conventions" when using the 01.00.16 version of the MIP tables

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#254]
If I run the usual [example](https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_experimentID.py) using CMOR 3.2.7 and version `01.00.15` of the MIP tables, I have no problems, but if I use version `01.00.16` of the MIP tables I get the following error:

```
! Error: The attribute "Conventions" could not be validated. 
! The current input value is "CF-1.7 CMIP-6.2" which is not valid 
! Valid values must match the regular expression:
! 	["^CF-1.7 CMIP-6.0\( UGRID-1.0\)\{0,\}$"  ...] 
! 
! Check your Control Vocabulary file "01.00.16/CMIP6_CV.json".
```
The regular expression used in the `CMIP6_CV.json` files for `Conventions` are the same between the versions (see [01.00.15](https://github.com/PCMDI/cmip6-cmor-tables/blob/01.00.15/Tables/CMIP6_CV.json#L8557) and [01.00.16](https://github.com/PCMDI/cmip6-cmor-tables/blob/01.00.16/Tables/CMIP6_CV.json#L7346)), but these regular expressions do not match with the regular expression in the error message (there are some backslashes missing). I'm pretty confused by this error, since I'm seeing differences between using the same version of CMOR and the same regular expression!

**Comment by dnadeau4** [comment]
@ehogan they change CMIP-6.0 to CMIP-6.2 without telling me.  Somebody else noticed about 1 month ago and told said that `PrePARE` was inconsistent with the Google Document.  (We know that song...)   It is in version 3.2.8 of the CMIP6_CV cron script.  For now, just change 6.0 to 6.2 in CMIP6_CV.json

**Comment by ehogan** [comment]
Ok, thanks @dnadeau4 :)
