### ISSUE TITLE
further_info_url throws segfault if not specified

### ISSUE THREAD

**Issue by KristianJS** [PCMDI/cmor#269]
If I set "further_info_url":"" in my metadata-template.json file, I get a segmentation fault with no error message. This is version 3.2.7.

Once I set it to an actual http address matching the regular expression being looked for it works OK. But, being unfamiliar to C (and familiar with Python where empty strings aren't an issue), it was very confusing to me where this segfault was coming from until I finally guessed right.

It would be good if there were an actual error message indicating what the problem was.

**Comment by durack1** [comment]
@KristianJS I have just tested this problem with [`CMOR 3.2.8`](https://anaconda.org/PCMDI/cmor) and don't generate a segfault.

Can you update your CMOR to the latest version and re-check? If the problem no longer occurs please close this issue.

With `CMOR 3.2.8` you are also able to use a template for this attribute, following the [CMIP6 guidance document](http://goo.gl/v1drZl):
```
"further_info_url":"",
```
will become
```
"_further_info_url_tmpl": "https://furtherinfo.es-doc.org/<mip_era><institution_id><source_id><experiment_id><sub_experiment_id><variant_label>"
```

**Comment by KristianJS** [comment]
I tried with 3.2.8 and still got a segfault.

However, I am testing this via ece2cmor3, so it is possible that there is some mismatch going on between this software and cmor3. I traced the error to taking place when the first call to the cmor code is called in ece2cmor3, namely a call to cmor_write(). This made me believe the issue was with cmor3 itself. But based on this non-reproducibility that's probably not the case.

This may be an issue for the ece2cmor3 github instead in which case I'm happy to close it for now.

**Comment by durack1** [comment]
@KristianJS what platform are you running on? My test was on OSX-64, I’d be surprised if the behaviour was different on Linux-64

**Comment by KristianJS** [comment]
GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)

**Comment by durack1** [comment]
@KristianJS yep, just checked on redhat6.9 `Linux 2.6.32-696.13.2.el6.x86_64 #1 SMP Fri Sep 22 12:32:14 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux` and I have no problem, so it's likely an issue with ece2cmor3
