### ISSUE TITLE
nominal_resolution

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#270]
Hi,
the CV in the CMOR directory Tables does not contain the complete information given in the CVs from https://github.com/WCRP-CMIP/CMIP6_CVs.  For example, in CMIP6_source_id.json for all sources there is the attribute:
```
"model_component":{
                "aerosol":{
                    "description":"none",
                    "nominal_resolution":"none"
},
```
linking a `nominal_resolution` to all submodels. I think this is the resolution the submodel has on its native grid. Is the `nominal_resolution` to specify in dataset.json the resolution of the 'output producing' (I know the exact definition is more extensive) model the same?

Is it then possible to include this information in the CMOR CV and to enable CMOR to use it? In https://goo.gl/v1drZl it says it is user-input but the user is probably not always aware of the nominal_resolution of the used submodel. Also, if the user specifies an allowed but different nominal_resolution than registered in source_id.json and if the information about the correct n_r is not available to CMOR,  CMOR will proceed.
Best regards,
Fabi

**Comment by dnadeau4** [comment]
@durack1 @taylor13 can you answer this?

**Comment by durack1** [comment]
@wachsylon thanks for raising this question. The `nominal_resolution` attribute included in CMIP6 output files, is representative of the output grid that the data is written on, and therefore it may differ from the `nominal_resolution` that is reported in [WCRP-CMIP/CMIP6_CVs/CMIP6_source_id.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_id.json), the registered content.

In the case of a model reporting on the native (original model simulation) grid, which has the `grid_label = gn`, then the `nominal_resolution` will be identical to the registered content, however, we are not making any assumptions for the CMIP6 output, and require modeling groups to specify this information for each output product.

For additional background, please take a look at the [CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV’s document](http://goo.gl/v1drZl).

I'll close this issue, please feel free to respond to this issue if you have further questions
