### ISSUE TITLE
hdf5 dependence in cmor > 3.2.6

### ISSUE THREAD

**Issue by goord** [PCMDI/cmor#272]
Hi, would it be possible to continue support for the hdf5-1.8.17 dependence for the newer releases of your conda package? We combine your software in a conda environment with netcdf4 and cdo, and the upgrade to hdf5-1.8.18 makes it at the moment impossible to do this (especially cdo). If you do not use any features of this new hdf5 version, I believe it is quite easy to list it in the meta.yml file as a valid substitute for the new hdf5.

Thank you,
Gijs van den Oord (knmi, ec-earth consortium)

**Comment by goord** [comment]
Another way would be to allow hdf5 1.10.* as well...

**Comment by dnadeau4** [comment]
@goord We already encountered the same conflict with `UV-CDAT` using hdf5-1.8.18 and `CMOR` using hdf5-1.8.17.

https://github.com/PCMDI/cmor/issues/138

BTW, some `libnetcdf` version are now in the `broken` channel on conda-forge. 
     https://anaconda.org/conda-forge/libnetcdf/files

I am not sure how to solve this issue just yet.

**Comment by goord** [comment]
The problem I encountered seems to be an issue with CDO btw, the conda forge build does not list the hdf5 dependence, which yielded a linker error after installing it next to cmor. 

But in any case does cmor depend upon hdf5 for any other reason than its libnetcdf dependence?

**Comment by dnadeau4** [comment]
`CMOR` only depends upon `hdf5` due to `libnetcdf` dependences.  `CMOR` uses `linetcdf` calls to create the output file.

I have update cmor with version 3.2.8 which use hdf5 1.8.18.* 
* https://github.com/PCMDI/cmor/blob/master/recipes/cmor/meta.yaml

You can always force a pinned hdf5 which should work when you install `CMOR`.
* `conda install -c conda-forge "hdf5=1.8.18=1" -f`

CMOR use standard API from a very old version and is back compatible with netcdf4 version.

**Comment by dnadeau4** [comment]
I will try to make the dependency to `libnetcdf 4.4.*` and delete `hdf5 1.8.18`.  Let see if this work.

**Comment by goord** [comment]
Hi, we finally managed to compile an anaconda stack without conflicts, but nevertheless I think it's a good idea to try to have such a flexible dependency tree.

**Comment by durack1** [comment]
@goord this issue seems resolved and so I will close. If you continue to have issues, please reopen and provide additional info for us to track down
