### ISSUE TITLE
A number of issues when installing using build.sh ( + solutions )

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmor#277]
When trying to install version 3.3.0 using build.sh : 

  - hdf5 location is not working. Should use `wget https://support.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-1.8/hdf5-1.8.17/src/hdf5-1.8.17.tar`

 - udunits version 2.2.20 is no more available on line, should use `wget ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.24.tar.gz`

  - the CMOR version git checkout command has a typo, it should read : `git checkout cmor-3.3.0`

  - the configure command for CMOR doesn't take care for udunits and
  uuid libraries, it shoud read  : `./configure --prefix=$PREFIX --with-python --with-uuid=$PREFIX --with-udunits2=$PREFIX --with-netcdf=$PREFIX/ `

  - cmor/Makefile.in unduly assumes (under rule 'python') that PYTHONPATH's value is a single directory; in most user's environments, it can be a list of directories (separated by ":")

  - when PYTHONPATH has a single dir value, the 'make python' rule lead to writing CMOR eggs in $PYTHONPATH; this leads to a comment in build.sh stating "My pyhton 2.7 is located in /usr/local/lib so I need sudo"   ; it would be morer struingetn to warn the user : "For installing egg without su, temporarily set PYTHONPATH to a dir where you wnat to install it, such as e.g. "$HOME/.local/lib/python2.7/site-packages"

**Comment by dnadeau4** [comment]
- [ ]  hdf5 location is not working. Should use `wget https://support.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-1.8/hdf5-1.8.17/src/hdf5-1.8.17.tar`
    - done in cdms3_documentation (installation branch)

- [ ] udunits version 2.2.20 is no more available on line, should use `wget ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.24.tar.gz`
    - done in cdms3_documentation (installation branch)

- [ ] the CMOR version git checkout command has a typo, it should read : `git checkout cmor-3.3.0`

- [ ] the configure command for CMOR doesn't take care for udunits and
  uuid libraries, it shoud read  : `./configure --prefix=$PREFIX --with-python --with-uuid=$PREFIX --with-udunits2=$PREFIX --with-netcdf=$PREFIX/ `
    - Actually the codes in configure.ac shows that it cares for it.   It add this:
```
with_udunits2b="-"${with_udunits2}
if [ test ${with_udunits2b} != "-yes" ] ; then
  if [ test ${with_udunits2b} != "-no" ] ; then
   UDUNITS2FLAGS=" -I${with_udunits2}/include"
   if [ test ${RTAG} != "none" ] ; then
     UDUNITS2LDFLAGS=" -L${with_udunits2}/lib  ${RTAG}${with_udunits2}/lib -ludunits2 -lexpat"
   else
     UDUNITS2LDFLAGS=" -L${with_udunits2}/lib -ludunits2 -lexpat"
   fi
  else
    UDUNITS2FLAGS="-ludunits2"
    UDUNITS2LDFLAGS=""
  fi
```
- [ ] cmor/Makefile.in unduly assumes (under rule 'python') that PYTHONPATH's value is a single directory; in most user's environments, it can be a list of directories (separated by ":")

- [ ] when PYTHONPATH has a single dir value, the 'make python' rule lead to writing CMOR eggs in $PYTHONPATH; this leads to a comment in build.sh stating "My pyhton 2.7 is located in /usr/local/lib so I need sudo"   ; it would be morer struingetn to warn the user : "For installing egg without su, temporarily set PYTHONPATH to a dir where you wnat to install it, such as e.g. "$HOME/.local/lib/python2.7/site-packages"

**Comment by senesis** [comment]
> - where is the typo? It should be cmor-3.3.0 or CMOR-3.3.0

The command reads as `git checkout cmor3`

**Comment by senesis** [comment]
Regarding the configure command for cmor, it reads in build.sh as 
`./configure --prefix=$PREFIX --with-python --with-uuid --with-udunits --with-netcdf=$PREFIX/ `
which does not tell configure that libraries uuid and udunits have been installed in dir $PREFIX. So the install do not succeed; just give it a try on a fresh install without any udunits lib around
The other writing works fine :
`./configure --prefix=$PREFIX --with-python --with-uuid=$PREFIX --with-udunits2=$PREFIX --with-netcdf=$PREFIX/`

**Comment by senesis** [comment]
>  If you use anaconda, that would save your a lot of issues.
I know, but I can't for now.

**Comment by dnadeau4** [comment]
Thanks for your help on fixing all these issues.   The current build scripts I am using for conda can be found here.
https://github.com/PCMDI/cmor/blob/master/recipes/cmor/build.sh

and the dependencies are here:

https://github.com/PCMDI/cmor/blob/master/recipes/cmor/meta.yaml

In your case you will have to compile each one manually.

**Comment by senesis** [comment]
Because I moved to conda, I cannot say for sure that the build.sh script is fine now. But, as far as I am concerned, the issue can be closed.

**Comment by durack1** [comment]
@dnadeau4 it seems you have one last tweak noted above https://github.com/PCMDI/cmor/issues/277#issuecomment-355160866 - then I think this is good to close?

**Comment by dnadeau4** [comment]
@durack1 @senesis the build script is no longer working.  I will delete the github sections from the documentation.

**Comment by dnadeau4** [comment]
cmor.llnl.gov
