### ISSUE TITLE
PrePARE doesn't work in version 3.3.0 :  cdms2.Cdunif is missing 

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmor#278]
Once build.sh for CMOR 3.3.0 is fixed as stated #277 , I end up with the following problems when using PrePARE :

script PrePare.py includes a line
   `sys.path.insert(0,sys.prefix+"/lib/python2.7/site-packages/cdms2")`
which does not match the set of libraries which is installed using build.sh

It also includes an :
   `import Cdunif`
which, as far as I understand, should be satisfied by CDMS, which is not installed   

Cdunif is actually used at runtime by class CDMSAction and by main, so PrePARE can't work as is. 

Could you advise for a fix ?

**Comment by doutriaux1** [comment]
can prepare even work without cdms2?

**Comment by senesis** [comment]
Reading again the release notes , I discover : 

> Accelerate PrePARE from 2s to 0.1s (IPSL request).
>   Fix PrePARE/CMOR memory issue.
>   **Call Cdunif.so(C) library directly instead of cdms2**.

but there is no guideline for building this library, and I am not sure whether the code lines quoted above are to be kept for such a 'direct library call'

**Comment by doutriaux1** [comment]
this means that it's calling the guts of cdms2 (cdunif) directly, w/o the extra bell and whistles, but it's still part of cdms2.

**Comment by doutriaux1** [comment]
@dnadeau4 I guess you need to make cdms2 a dependency for prepare.

**Comment by dnadeau4** [comment]
@doutriaux1 Sebastian is not using anaconda.

**Comment by dnadeau4** [comment]
You need to follow the script found in the conda-recipe to build cdms2.  That is the easiest way.
* CDMS2
  * [dependencies](https://github.com/UV-CDAT/conda-recipes/blob/master/libcdms/meta.yaml.in)
  * [build](https://github.com/UV-CDAT/conda-recipes/blob/master/libcdms/meta.yaml.in)

Each dependency build can be found in the following directory.
* https://github.com/UV-CDAT/conda-recipes

**Comment by dnadeau4** [comment]
We usually use `conda build` for each recipe.  `conda build libcdms` or `conda build libcf` and so on.    conda build takes care of the dependencies and run the build script for us.  If a dependency is missing, we just build it from the recipe and `conda` finds the tarball locally.  

That saves a lot of time.  

You can also get the precompile `tarball` from the `anaconda cloud` and install it in your python environment.
* https://anaconda.org/conda-forge/cdms2/files
* https://anaconda.org/conda-forge/libcdms/files

**Comment by senesis** [comment]
OK. I moved to conda for installing cdms2 and include that in PrePARE.py:
`sys.path.insert(0,"/home/gmgec/mrgu/senesi/miniconda2/lib/python2.7/site-packages/cdms2")`

I know get a runtime error : 
`
  File "/home/gmgec/mrgu/senesi/build/cmor-3.3.0/lib/python2.7/site-packages/CMOR-3.3-py2.7-linux-x86_64.egg/cmip6_cv/PrePARE/PrePARE.py", line 23, in <module>
    import Cdunif
ImportError: /usr/lib64/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /home/gmgec/mrgu/senesi/miniconda2/lib/python2.7/site-packages/cdms2/Cdunif.so)
`
When checking conda installed package (using `conda list`), I have :
libgfortran               3.0.0  

1- Does this mean that CDMS dependecies are wrong regarding gfortran ? How to fix that ?
2- It seems that, albeit conda is activated, the locations searched for the gfortran library (/usr/lib64) does not include the conda libraries directory (~/miniconda2/lib). What should drive that ?

**Comment by dnadeau4** [comment]
@senesis I think that your libgfortran in `/usr/lib64` is older than the one in /home/gmgec/mrgu/senesi/miniconda2/lib/

You might have to set you LD_LIBRARY_PATH or update you libgfortran.so.3 in /usr/lib64

Can you try this commands?
`nm  -D /usr/lib64/libgfortran.so.3 | grep GFORTRAN`
`nm  -D /home/gmgec/mrgu/senesi/miniconda2/lib/libgfortran.so.3 | grep GFORTRAN`

You should get this:
```
0000000000000000 A GFORTRAN_1.0
0000000000000000 A GFORTRAN_1.1
0000000000000000 A GFORTRAN_1.2
0000000000000000 A GFORTRAN_1.3
0000000000000000 A GFORTRAN_1.4
0000000000000000 A GFORTRAN_1.5
0000000000000000 A GFORTRAN_C99_1.0
0000000000000000 A GFORTRAN_C99_1.1
```

**Comment by senesis** [comment]
Adding the conda lib dir in LD_LIBRARY_PATH was useful
I also had to add the conda python packages dir in my PYTHONPATH
I am quite surprised that activating conda did not take care of both settings. Is it normal, or should I look for an issue in my conda install ?
Anyway, thanks

**Comment by dnadeau4** [comment]
Actually when you activate `conda` your `PATH` should change and `python` will be called from the `env/bin` directory.  `python` knows where the python libraries are due to 'sys.path'.  You should not have to set your `PYTHONPATH` unless it point to a directory outside the `conda environment`. 

Normallly all libraries should be under `<yourenv>/lib`.
I have to set `LD_LIBRARY_PATH` when I create my own `python extension`, using new libraries unknown to `python`.

Try this:
```
source activate <yourenv>
echo $PATH
which python
python -c 'import sys; print sys.path'
```

**Comment by senesis** [comment]
OK. My conda-dummy mistake. Sorry

**Comment by durack1** [comment]
@senesis I believe this issue should be closed, can you confirm?

**Comment by senesis** [comment]
Yes, sure. Thanks
