### ISSUE TITLE
check climatology files

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#283]
frequency = "monC" (and time coordinate entry "time2") or frequency = "3hrCM" (and time coordinate entry "time3" imply that the file contains climatological data.  For these frequencies, a "climatology" attribute should be attached to the time coordinate instead of the "bounds" attribute.  Please check that CMOR3 is doing this correctly.  I am a bit worried by the fact that in the CMIP6_coordinates.json file, must_have_bounds = "yes" for time2 and time3.  Because climatology="yes" for these 2 coordinates, I think CMOR interprets this correctly as meaning include *climatological* bounds, but we should make sure we have a "test" that can be used to confirm this.

**Comment by dnadeau4** [comment]
I was able to fix this adding `Clim` for the variable name if the table is `Amon` and if the file has `-clim` at the end of the filename.

For other files, if the output variable name "`out_name`" as the same attributes as the input variable name "`entry`" that it will work.   (`ua` and `ua7h` in [CMIP6_6hrPlevPt.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_6hrPlevPt.json#L484-L512) is a good example.  The out_name is used `ua` for both files, so I cannot now that `ua7h` was used to create this file)

If any attribute changes between 2 variables in the table with the same `out_name`,  PrePARE will fail since PrePARE will find the wrong variable name "`out_name`" and use "`entry`" to compare.   We did not record the `entry` variable name, so that is a problem.   The user will have to pass the argument --variable to PrePARE to force the program to retrieve that variable `entry` information from the table instead of the one found in the filename.   I have not had time to find if this situation will occur yet.

df7c2b964bb52d42779de9a0e6bfaa878705f9c9

**Comment by taylor13** [comment]
I have reviewed the entire data request and find 60 variables that have an "out_name" different from the "entry" name.  There are 4 categories:
1)  in Amon 7 variables have a "clim" version in addition to the full time-series version.  You're now handling that correctly I think.
2)  In Oclim and Omon there are variables with both a 2-d and 3-d version.  If PrePARe doesn't check the shape of the variable, then we're o.k. checking the 2-d versions using the 3-d entry names.
3)  In CFsubhr there are "lat" and "lon" with entry names "latitude" and "longitude".  These will not pass PrePARe unless PrePARe can find the variables using "out_name" rather than "entry".
4)  In 6hrPlev, 6hrPlevPt, E1hr, E2hrPt, and Emon, there are entries that indicate how many vertical levels are being requested (e.g. "wap4" is the entry for out_name "wap").  Sometimes PrePARe will find an entry name that will work in checking these variables, but sometimes PrePARe will need to look through the table's "out_names" to find the variable it needs.

I think 3 & 4 above can be handled in the same way, and I think you've already addressed 1 & 2.  Let's talk about this before deciding how to proceed.

**Comment by dnadeau4** [comment]
@taylor13 
In 3.  
I don't think `PrePARE` will check `"latitude"`, `"longitude"` variables.   The variable used by `PrePARE` is retrieve by the filename.  `PrePARE` does not check dimensions.

**Comment by dnadeau4** [comment]
@taylor13 
In 4:
@taylor13 `PrePARE` cannot **guess** the out_name.  If I to read the "JSON" table and try to find the `out_name` parent(s) (entry(s)), that will slow down `PrePARE` a lot.    They might be more than 1 `entry` name matchint the same `out_name`

This search needs to be done before calling `cmor_variable()` in Python.  `cmor_variable()` function retrieves all metadata for that variable from the loaded table.   

**NOTE**: Variable metadata are not used as ESGF facets for the search engine.

**Comment by dnadeau4** [comment]
PrePARE needs the variable name to create the output filename.   We might not be able need to check the variable attributes in some cases.

**Comment by taylor13** [comment]
regarding  3),  "latitude" and "longitude" in table CFsubhr, these are regular variables and are functions of "site",  so PrePARE will try to check them.  Their "out_names" are "lat" and "lon" (just like when they are coordinate variables).  
Regarding 3) and 4), there appears to be no easy way to handle these cases.  One option might be to somehow skip variables where out_name isn't the same as the table entry label, but there are only a subset of such variables that PrePARE can't check.  Another option is to write some code that would search for out_names, but only if the variable name doesn't appear in the table.  I'm not sure this will be fail-safe though, so let's give it more thought.

**Comment by dnadeau4** [comment]
Solution 4 will slow down PrePARE by a lot.  (I have to read the JSON file in Python.)

As for 3, the filename does not have "latititude_.....nc" so PrePARE will not check "latitude", but the variable name found in the filename.

**Comment by dnadeau4** [comment]
@taylor13 I think @glevava solves all your points.
https://github.com/PCMDI/cmor/blob/master/LibCV/PrePARE/out_names_tests.json

**Comment by taylor13** [comment]
@glevava @doutriaux1 Do you agree that this issue has been fully addressed?  If so, we can close.

**Comment by glevava** [comment]
Yes using a kind of "unit test" into "out_names_tests.json"
