### ISSUE TITLE
Prepare exit status is not meaningful

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmor#284]
PrePARE actually has exit status = 0 for non compliant files
This is not helpful for automated the QC workflow

**Comment by dnadeau4** [comment]
What do you call `non compliant` file, you mean when there is an metadata issue?

**Comment by dnadeau4** [comment]
Looking at the code, when an `exception` is raised, PrePARE return `non-zero`.  When does this happen to you?

Note that `PrePARE` means (Pre-Publication Attribute Reviewer) following this [document](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit).  If the netcdf file  CF-1 compliant, `PrePARE` does not check this. `CMOR` is the other tool we have to validate CMIP6 and CF-1 compliance.

You also should pass your files through CF-Checker. 

Here is the code I found showing that  `0` return value is sent only when `PrePARE` succeed.
```
    try:
        args = parser.parse_args()
    except argparse.ArgumentTypeError as errmsg:
        print >> sys.stderr, str(errmsg)
        return 1
    except SystemExit:
        return 1
```
```
if(__name__ == '__main__'):
    try:
        sys.exit(main())

    except KeyboardInterrupt:
        print bcolors.FAIL
        print "!!!!!!!!!!!!!!!!!!!!!!!!!"
        print "! Error:  The input file is not CMIP6 compliant"
        print "! Check your file or use CMOR 3.x to achieve compliance for ESGF publication."
        print "!!!!!!!!!!!!!!!!!!!!!!!!!"
        print bcolors.ENDC
        sys.exit(-1)
    except BaseException:
        sys.exit(-1)
```

**Comment by senesis** [comment]
The exit status of command PrePARE can be zeo in such a (real, but shortened) case : 
`
+ cmor-3.3.0//bin/PrePARE ./Tables/CMIP6_Ofx.json ./basin_Ofx_CNRM-CM6-1_1pctCO2_r1i1p1f2_gn.nc
processing:  ./basin_Ofx_CNRM-CM6-1_1pctCO2_r1i1p1f2_gn.nc
...
===========================================================
You file contains "missing_value":"-10000.0" and
CMIP6 tables requires "missing_value":"16384.0".
===========================================================
#echo rep=$?
+ echo rep=0
`

**Comment by dnadeau4** [comment]
@senesis This is a warning, not a critical error this is why PrePARE returns 0.
@taylor13 @durack1 should PrePARE returns a critical error when missing_value is different.

**Comment by taylor13** [comment]
Several comments:
1) the missing_value defined for the integer "basin" data must be type integer (not float or real or double).  
2) your data should be integers and should not have any missing values.  Every grid cell should be assigned to one of the basins listed in goo.gl/neswPr . 
3)  this variable is a special case requiring both the flag_values and flag_meanings attributes to be defined (attached to the variable).  See goo.gl/neswPr .
4) CMOR and PrePARe seem to be having problems with this check and need to be debugged.

**Comment by senesis** [comment]
Thanks, the first three points were quite clear for me.

**Comment by dnadeau4** [comment]
01007a55f72a7e37c795c4c34d608c359ca2c4de
