### ISSUE TITLE
pl700 vs p700

### ISSUE THREAD

**Issue by slavakharin** [PCMDI/cmor#286]
I am not sure if this is the right place to comment but I noticed two entries in the [CMIP6_coordinate.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_coordinate.json) file for 700 hPa level, `pl700` and `p700`. Is it intentional or just mis-spelling? I see other entries `p###` for various pressure levels but only a single `pl700` entry which suggests that the latter is just a mis-spelled coordinate in the data request.

**Comment by taylor13** [comment]
I noticed that you also queried Martin about this, which is the right place to post.  I think this issue can be closed here on the CMOR site.  Any changes Martin makes in response will be reflected in updates of the CMOR tables.  
thanks for raising this issue.
