### ISSUE TITLE
PrePARE (or CMIP6 spec) issue with frequency 1hrCM

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmor#288]
According to https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit,  and specifically to this sentence 

> Label 1hrCM files with the beginning of the first hour and the end of the last hour contributing to climatology (rounded to the nearest minute);

a data file for frequency 1hrCM which has averaged data over a full month (say 197901) should have a date segment in its name such as : `197901010000-197902010000`, and have time bounds which encompass the full month

I used a file which has 
double time(time) ;
		time:axis = "T" ;
		time:standard_name = "time" ;
		time:long_name = "Time axis" ;
		time:calendar = "gregorian" ;
		time:units = "days since 1850-01-01 00:00:00" ;
		time:time_origin = "1850-01-01 00:00:00" ;
		time:bounds = "time_bounds" ;
data:
 time_bounds =
  47116, 47147 ;

Prepare 3.3.0 then reports 

> ! Your output filename should be: 
> ! "rlut_E1hrClimMon_CNRM-CM6-1_amip_r1i1p1f2_gr_185001010000-185001010000-clim.nc"

which is wrong : year is false (PrePARE used the time units origin), and begin date ==end date

I will send the file by separate email to @dnadeau4. But I welcome any of your test file (or any example file) for such a frequency, because I am missing detailed specs for such a file

**Comment by taylor13** [comment]
email from @senesis:  I read this morning the CF convention for climatologies, and I realized that this convention is much less obvious/sensible than what I expected, regarding time. Hence, the data file I produced does not comply and the behaviour of PrePare can here be normal and you probably can close the issue

**Comment by dnadeau4** [comment]
@senesis I will close this, re-open if needed.
