### ISSUE TITLE
Incorrect setting of "external_variables" global attribute depending on order of processing

### ISSUE THREAD

**Issue by matthew-mizielinski** [PCMDI/cmor#289]
When processing two variables, such as `Omon/thetao` and `Omon/uo`, the order in which they are processed can have an impact on the metadata they are produced with.

For example if `Omon/thetao` is processed before `Omon/uo` the latter will be incorrectly produced with the global attribute `external_variables` set to `areacello volcello`. If `Omon/uo` is processed first this attribute is not set in the corresponding output file.

I'm using CMOR version 3.3.0 with the PCMDI/cmip6-cmor-tables version 01.00.16

**Comment by taylor13** [comment]
This is definitely a bug.

**Comment by dnadeau4** [comment]
@matthew-mizielinski looking a the code, I do reset the external_variables metadata between each process.   

https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L2867-L2899

After looking at the table, there is optional `cell_measures` for `uo`

* uo
   * ["cell_measures": "--OPT"](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Omon.json#L4378)
* thetao (is fine)
   * ["cell_measures": "area: areacello volume: volcello"](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Omon.json#L4234)

**Comment by ehogan** [comment]
@dnadeau4, I've produced an example using `ua` and `ta` (from `6hrLev`, where `ua` has ["cell_measures": "--OPT"](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_6hrLev.json#L124)), and version `01.00.20` of the MIP tables to demonstrate the issue (this example code doesn't do anything special with regards to the `--OPT` value):

```
# If this example is not executed from the directory containing the
# CMOR code, please first complete the following steps:
#
#   1. In any directory, create 'Tables/', 'Test/' and 'CMIP6/'
#      directories.
#
#   2. Download CMIP6_6hrLev.json, CMIP6_CV.json,
#      CMIP6_coordinate.json and CMIP6_formula_terms.json from
#      https://github.com/PCMDI/cmor/blob/master/TestTables/ to the
#      'Tables/' directory.
#
#   3. Download common_user_input.json from
#      https://github.com/PCMDI/cmor/blob/master/Test/ to the 'Test/'
#      directory.

import numpy

import cmor


def main():
    cmor.setup(inpath='Tables', netcdf_file_action=cmor.CMOR_REPLACE,
               logfile='cmor.log')
    error_flag = cmor.dataset_json('Test/common_user_input.json')
    table_id = cmor.load_table('CMIP6_6hrLev.json')
    time = cmor.axis(table_entry='time1', units='days since 2000-01-01',
                     coord_vals=numpy.array(range(1)),
                     cell_bounds=numpy.array(range(2)))
    latitude = cmor.axis(table_entry='latitude', units='degrees_north',
                         coord_vals=numpy.array(range(5)),
                         cell_bounds=numpy.array(range(6)))
    longitude = cmor.axis(table_entry='longitude', units='degrees_east',
                          coord_vals=numpy.array(range(5)),
                          cell_bounds=numpy.array(range(6)))
    plev3 = cmor.axis(table_entry='plev3', units='Pa',
                      coord_vals=numpy.array([85000., 50000., 25000.]))
    axis_ids = [longitude, latitude, plev3, time]
    ua_var_id = cmor.variable(table_entry='ua', axis_ids=axis_ids,
                              units='m s-1')
    ta_var_id = cmor.variable(table_entry='ta', axis_ids=axis_ids,
                              units='K')
    data = numpy.random.random(75)
    reshaped_data = data.reshape((5, 5, 3, 1))
    
    # This works:
    cmor.write(ua_var_id, reshaped_data)
    cmor.write(ta_var_id, reshaped_data)

    # This doesn't:
    #cmor.write(ta_var_id, reshaped_data)
    #cmor.write(ua_var_id, reshaped_data)

    cmor.close()

if __name__ == '__main__':
    main()
```

If you run the code above, then check the output netCDF files:

```
% ncdump -h ua_6hrLev_PCMDI-test-1-0_piControl-withism_r11i1p1f1_gr_200001011200-200001011200.ncta/gr/v20180125/ta_6hrLev_PCMDI-test-1-0_piControl-withism_r11i1p1f1_gr_200001011200-200001011200.nc | grep external_variables
% ncdump -h ta_6hrLev_PCMDI-test-1-0_piControl-withism_r11i1p1f1_gr_200001011200-200001011200.nc | grep external_variables
		:external_variables = "areacella" ;
```

Then if you comment out the two lines under `# This works:`, uncomment the two lines under `# This doesn't:`, run the code again, then check the output netCDF files:

```
% ncdump -h ua_6hrLev_PCMDI-test-1-0_piControl-withism_r11i1p1f1_gr_200001011200-200001011200.nc | grep external_variables
                :external_variables = "areacella" ;
% ncdump -h ta_6hrLev_PCMDI-test-1-0_piControl-withism_r11i1p1f1_gr_200001011200-200001011200.nc | grep external_variables
		:external_variables = "areacella" ;
```
I hope this helps? :)

**Comment by dnadeau4** [comment]
@ehogan your example was very useful.   I really appreciate your help. 😄 

That was hard to solve, since there exist no API to delete a Global Attribute.  You can ovewrite and set it to `'\0'`, but the attribute was still created in the netCDF file with `""`.

 I finally found where to add some code for those special cases.

I added your test  to: 
[Test/test_python_CMIP6_CV_externalvariables.py](https://github.com/PCMDI/cmor/blob/PrePARE/Test/test_python_CMIP6_CV_externalvariables.py#L103-L145)


commit 7c1ffc0720cce6e60d5e9a5802fe66725d49ccf8 (HEAD -> PrePARE, origin/PrePARE)
Author: Denis Nadeau <dnadeau4@users.noreply.github.com>
Date:   Wed Jan 31 17:44:11 2018 -0800

    fix external variable issue

**Comment by dnadeau4** [comment]
I am still working on the PrePARE branch.

**Comment by ehogan** [comment]
> @ehogan your example was very useful. I really appreciate your help. 😄

No problem at all! Thanks for solving this :)

**Comment by durack1** [comment]
@matthew-mizielinski @ehogan I think we're fixed here, correct? If so, we can close
