### ISSUE TITLE
Consistency between CMIP6_CV.json and and CMIP6_CV

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmor#290]
At some stage, when using PrePARe 3.3.0, there is some check of active components against the content of file cmor-cmor-3.3.0/Tables/CMIP6_CV.json which is distributed with this version of PrePARe
The "amip" entry of this file reads
  ```
           "amip":{...
                "additional_allowed_model_components":[ "AER",  "CHEM" ] ...
```
This is not in line with the content of CMIP6_CV at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json, which is also in version CMOR-3.3.0 and reads
 ```
       "amip":{...
            "additional_allowed_model_components":[ "AER",    "CHEM",   "BGC" ],

```

**Comment by senesis** [comment]
@taylor13 : I assume that only the technical consistency around CMIP6-CV should be discussed here; 

nevertheless : we feel there is some ambiguity on what BGC really implies (i.e. whether it should apply only to the case where both biological AND carbon-chemical is included); we would like it to e.g. carry the meaning : "in the land component, the vegetation (and its carbon aspects) is not prescribed , but fully interactive"; do you think that CMIP6 convention is very clear on this matter ? did we miss to read a basic document there ?

**Comment by durack1** [comment]
@senesis each of the `source_type` entries for CMIP6 are listed in the CMIP6_CV documents, with the `BGC` entry [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_type.json#L6)

**Comment by senesis** [comment]
Thanks. It reads :

> "BGC":"biogeochemistry model component that at the very least accounts for carbon reservoirs and fluxes in the atmosphere, terrestrial biosphere, and ocean",

which still has to be interpreted for the case of an atmosphere+land-only simulation which accounts for that fluxes, but which, by design, lacks any ocean component, be it physical or biogeo one

**Comment by taylor13** [comment]
@senesis  A more complete description of the use of "BGC" is provided in http://goo.gl/v1drZl where it states, in part:
```
BGC (for a model component that includes a biogeochemical treatment which  at the 
very least can account for carbon reservoirs and fluxes in the atmosphere, terrestrial 
biosphere, and ocean; for some model configurations, only part of the BGC component 
will be active.  For example, in a BGC model coupled to an AGCM, the ocean component 
of the BGC might be inactive, but the source_type would be “AGCM BGC”.   For a BGC 
model run coupled to an AOGCM, the source_type should include “AOGCM BGC”  both 
when atmospheric concentrations are calculated and when they are  prescribed)
```
This description was revised in December 2017, as recorded in the Appendix: https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit#bookmark=id.gdszdv3dm9pv .

Perhaps we should revise the CV (https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_source_type.json#L6) to read:
```
"BGC":"biogeochemistry model component that accounts for carbon 
reservoirs and fluxes in the atmosphere, terrestrial biosphere, and ocean 
except the ocean carbon component is not included if sea surface 
temperatures are prescribed",
```

**Comment by dnadeau4** [comment]
Should be in 3.3.1 release today 2-14-2018.  @senesis can you verify that it work?

**Comment by senesis** [comment]
Sorry, but embarking with 3.3.1 has low priority here.

**Comment by taylor13** [comment]
I thought the issue raised was that CMIP6_CV.json was not consistent with  https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json.  It now should be.  If that wasn't the issue (related to CMOR), what is?

**Comment by senesis** [comment]
1- sorry, I misunderstood the request, as I was distracted by the side discussion which occurred in this thread
2- I can see that the issue is fixed in the head github version of CMIP6_CV.json (https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json) so I assume it is OK for further CMOR releases; 

Thanks

**Comment by dnadeau4** [comment]
@senesis I did not sent the Release Note for CMOR 3.3.1 so I though it was important for you to know that it is out there.  I should have been more specific about the update CMIP6_CV.json file with the release.

**Comment by taylor13** [comment]
I think this issue can be closed.
