### ISSUE TITLE
"branch_time_*" global attribute seems not to be checked by PrePARE

### ISSUE THREAD

**Issue by glevava** [PCMDI/cmor#296]
During ESGF DC1, IPSL data successfully passed PrePARE with `branch_time_*` attribute as strings.

For instance:
`branch_time_in_parent = "365.0"`

But `cdf2cim` fails to ingest the data during publication because this doesn't follow CMIP6 specifications as `branch_time_*` attribute should be "float".

IPSL should failed PrePARE during publication.

**Comment by taylor13** [comment]
Actually, according to http://goo.gl/v1drZl (see footnote 5 after table 1 or see table 3), both of these should be double precision.  Note also that there are some indexes (like realization_index) that must be integers (not strings).  Please check these too.  
Also, I think CMOR should allow users to define additional global attributes (not called for by CMIP6), and they should be able to specify what "type" these attributes are.  Is that option working?

**Comment by dnadeau4** [comment]
This is @taylor `parent_experiment_id` thing that I program about 2 years ago during the summer of 2016.   The logic is complicated and @taylor13 can explain it to you.   Most of these are set if `parent_experiment_id` is not `no parent`.  I do ensure that `branch_time_*` is set to `double`.

https://github.com/PCMDI/cmor/blob/master/Src/cmor_CV.c#L1054-L1341

**Comment by dnadeau4** [comment]
All `branch_time_*` are written as double value by`cmor3`
https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L3126-L3146

**Comment by taylor13** [comment]
That's great.
Can we also get PrePARe to check that the type of these and the index attributes are correct?  Would that be difficult?

**Comment by dnadeau4** [comment]
I can hack PrePARE to do that the same way I did for `realization_index` and other `*_index` directly.   No C code necessary for this.   

https://github.com/PCMDI/cmor/blob/master/LibCV/PrePARE/PrePARE.py#L323-L350

**Comment by taylor13** [comment]
Good to hear.

**Comment by taylor13** [comment]
Note, also, the discussion at  #244  .  Does CMOR now correctly maintain the attribute type for both global attributes (like branch_time*) but also varibles (e.g., missing_value, valid_max)?

**Comment by dnadeau4** [comment]
done
fed9d003100cc37b28c65b7de200d1dad28618bb
