### ISSUE TITLE
Can't make install cmor3  

### ISSUE THREAD

**Issue by iaplasg** [PCMDI/cmor#298]
make install
r - cmor.o
r - cmor_axes.o
r - cmor_CV.o
r - cmor_variables.o
r - cmor_tables.o
r - cdTimeConv.o
r - cdUtil.o
r - timeConv.o
r - timeArith.o
r - cmor_grids.o
r - cmor_md5.o
r - arraylist.o
r - json_c_version.o
r - json_object_iterator.o
r - json_util.o
r - linkhash.o
r - random_seed.o
r - debug.o
r - json_object.o
r - json_tokener.o
r - libjson.o
r - printbuf.o
r - cmor_cfortran_interface.o
r - cmor_fortran_interface.o
mkdir -p /disk2/cmor/cmor/lib
mkdir -p /disk2/cmor/cmor/include
mkdir -p /disk2/cmor/cmor/include/cdTime
mkdir -p /disk2/cmor/cmor/include/json-c
mkdir -p /disk2/cmor/cmor/include/cdTime/cdunifpp
cp -p libcmor.a /disk2/cmor/cmor/lib
cp -pr ./include/*.h cmor_users_functions.* /disk2/cmor/cmor/include
cp: `./include/cmor_func_def.h' and `/disk2/cmor/cmor/include/cmor_func_def.h' are the same file
cp: `./include/cmor.h' and `/disk2/cmor/cmor/include/cmor.h' are the same file
cp: `./include/cmor_locale.h' and `/disk2/cmor/cmor/include/cmor_locale.h' are the same file
cp: `./include/cmor_md5.h' and `/disk2/cmor/cmor/include/cmor_md5.h' are the same file
make: *** [install] Error 1

**Comment by dnadeau4** [comment]
You installation directory in configure `--prefix` is the same as your current directory.  
Try:
```bash
head ./config.log
```
