### ISSUE TITLE
Question about CMOR variable type

### ISSUE THREAD

**Issue by martinjuckes** [PCMDI/cmor#299]
I've had a question asked about the use of `integer` for the `type` of variable `basin`. This is the same as used in CMIP5, but the NetCDF code for integer variables is `int`, so, the question raised (https://github.com/cmip6dr/Request/issues/66 ) is whether we can change `integer` to `int`? I don't think this is a priority, but I'm passing on the question.

**Comment by taylor13** [comment]
See my answer at #66.  I will close this issue.

**Comment by taylor13** [comment]
oops.  above reference should have been to: https://github.com/cmip6dr/Request/issues/66
