### ISSUE TITLE
CMOR 3.3 anaconda package version for MAC OS

### ISSUE THREAD

**Issue by treerink** [PCMDI/cmor#300]
The latest CMOR anaconda package version for MAC OS seems to be cmor=3.2.7, where we would like to have version 3.3 for MAC OS. Is this possible?

**Comment by dnadeau4** [comment]
@treerink All files are there for Linux and OSX.  
https://anaconda.org/PCMDI/cmor/files?channel=main

**Comment by dnadeau4** [comment]
What is you command?

**Comment by treerink** [comment]
Hi, thanks the link https://anaconda.org/PCMDI/cmor/files?channel=main was quite useful via the **i** info I could trace which specific package we need to use in our package (in our case: cmor=3.3.0=py27hd3cfe68_0). Usually, eg. for linux, I get this info via
 conda info cmor
But on mac os this returns nothing, so maybe there is something to improve on that.

Anyway via the given link I am able to update, also next times.
So I close the issue, because the packages are there.
Regards Thomas

**Comment by taylor13** [comment]
@treerink There are important bug fixes in 3.3.1, just released.  Would it be a problem to install the latest?

**Comment by treerink** [comment]
Ok, I will have a look

**Comment by dnadeau4** [comment]
@treerink This is the command I use on OSX.
```
conda create -n cmor-3.3.1 -c conda-forge -c pcmdi cmor
```

`conda info` only tells you information on packages you have on your machine.

`conda search` is what you want.
```
conda search -c pcmdi cmor
```

**Comment by treerink** [comment]
Ok thanks. Though I need to check the dependencies (so need actually the conda info, but the info button on that website works fine for that, so I am ok).

I updated our package for the CMOR 3.3.1 update, both on linux and on mac os, and all seems to work fine.
