### ISSUE TITLE
segfault in cmor.write

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#302]
I am able to reproduce a segfault in cmor.write (as noted in https://github.com/PCMDI/cmor/issues/297#issuecomment-365391642). I will generate a little test case for use in bug fixing and attach it to this issue.

**Comment by dnadeau4** [comment]
@durack1 do you have code for this?

**Comment by durack1** [comment]
@dnadeau4 I have tried a number of the scripts that generated this error, I believe with a `nightly` generated on the 13th Feb. I can't reproduce this with the `3.3.1` release, so will close, and reopen if I can get it reproducing.
