### ISSUE TITLE
2 scalar coordinates for one variable

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#305]
There are half dozen variables that have two scalar coordinates (besides being functions of lat, lon, and time).  I don't think CMOR has ever faced variables like that.  We need to confirm that it can handle it correctly.  see https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/303

**Comment by senesis** [comment]
The issue referenced above also calls for a change in CMOR tables regarding out_name of dimensions typec3pft and typec4pft

**Comment by taylor13** [comment]
Yes, I agree.  Before implementing the changes, we need to determine whether CMOR can even handle two scalar coordinates.  I don't think it can at this point.

**Comment by senesis** [comment]
OK. I will post the same remarks in the CMIP6-CMOR-tables repository. because in that context, the question of CMOR capability to use handle two scalar coordinates is not a pre-requisite for implementing the out_name change

**Comment by wachsylon** [comment]
What is the reason for individual variables for these tiles? I mean pastureFracC3(lat,lon,time) and pastureFracC4(lat,lon,time) instead of something like pastureFrac(lat,lon,time,type).

Additionally,
in table Emon we have variable "fracLut" using dimension landUse which requests "pastures".
In table Lmon we have variable "pastureFrac" using dimension "typepasture" which has the value "pastures". 
"fracLut" is also requested in Eyr for frequency "yrPt". According to this, in Emon it needs to be "monPt", right?

**Comment by taylor13** [comment]
Please copy your inquiry into an new issue at https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues  
That's where all issues concerning the data request should be raised.  the CMOR site is for issues related to discrepancies between the CMOR tables and the data request or problems with the CMOR or PrePARE codes.
To answer your first question, the MIP leaders requesting the output thought it was better to have a single variable for each type.  I argued against this, but consensus supported a single variable approach.

**Comment by wachsylon** [comment]
Ok thanks.

**Comment by dnadeau4** [comment]
@doutriaux1 if you do this in CMOR2 I could probable merge your code in CMOR3.

**Comment by taylor13** [comment]
Note that in the first entry above for this issue I claimed there were perhaps a half dozen variables where this might be a problem.  At least one of those was eliminated in the data request by defining a new "type".  see e cmip6dr/CMIP6_DataRequest_VariableDefinitions#303 .   Will need to check what the other exceptional cases are before closing.

**Comment by taylor13** [comment]
Have checked the 6 variables that were functions of two scalar dimensions.  These all now have only a single scalar dimension, so this issue may be closed.

**Comment by senesis** [comment]
except maybe for those who were allowed to use DR01.00.21, isnt'it ?
