### ISSUE TITLE
Update test suite to reflect changes to PCMDI-test-1-0 revised descriptions

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#308]
Changes made in WCRP-CMIP/CMIP6_CVs#463 may have caused some issues with the test suite

**Comment by dnadeau4** [comment]
@durack1 I just run my tests with latest `CMIP6_CV.json` and everything works.
Thanks for the issue to remind me to test things.

**Comment by durack1** [comment]
@dnadeau4 great, I'm glad it was painless!
