### ISSUE TITLE
possible error in zfactor

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#310]
@taylor13 and I ran Test/test_site_ts.py

A few things seem odd:

* no a factor was passed (and therefore not stored), shouldn't CMOR have caught this and ask for `a` factor
* b_bnds are passed as `zfactor_bounds=[[x - 0.5, x + 0.5] for x in range(2)])` but appear in cdump as follow:

```
 b_bnds =
  -4.62069321768213e+18, 4.60267881917265e+18,
  4.60267881917265e+18, 4.6094342186137e+18 ;
```

**Comment by dnadeau4** [comment]
You need to pass the values as float64.

```python

+             'coord_vals': numpy.array(range(2), dtype=numpy.float64),
```
```python
     cmor.zfactor(axis_ids[2], 'b', axis_ids=[axis_ids[2]],

+                 zfactor_values=numpy.array(range(2), dtype=numpy.float64), 
                  zfactor_bounds=[[x - 0.5, x + 0.5] for x in range(2)])
```
