### ISSUE TITLE
"site" coordinate

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#311]
Does CMOR currently write the longitude and latitudes as auxiliary coordinates in table CFsubhr, which contains variables that are a function of "site"?

**Comment by taylor13** [comment]
are the variables containing longitudes and latitudes named "lon" and "lat" or "longitude" and "latitude"?

**Comment by dnadeau4** [comment]
They are named "longitude" and "latitude".
https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_grids.json#L117-L151
