### ISSUE TITLE
attribute string length limits

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#319]
(I think I was supposed to report this issue, but perhaps it's already been reported  by someone else, in which case I suppose this can be merged): 

the "comment" attribute (attached to the variable) is declared to have a maximum length of 1024 (which is also the maximum length allowed for nearly all other string attributes).  Recently "comments" have been added to the data request that exceed 3000 characters (as I recall). CMOR needs modification to handle in some way these longer strings.  Immediate options are:

1) truncate the CMOR table's comments at 1024 characters when they are read in., or
2) declare "comment" to have a maximum length large enough to accommodate the longest comment in the CMOR tables.

If option 2 is implemented, it isn't as easy as setting a parameter to a larger value because the parameter is used for most other string variables and increasing it would unacceptably expand the memory footprint.

In the longer term, we should either define several different "max_lengths" for strings (as we did in CMOR1) or dynamically allocate the strings.  Since this won't be trivial, it cannot be a high priority at this time, even though CMOR wastes a lot of memory space with strings that are mostly blank.  I"m pretty sure we could substantially reduce the portion of memory occupied by CMOR variables (other than the data itself) by this means.

**Comment by taylor13** [comment]
Note that in the the "global attributes" section of the output requirements document (https://goo.gl/neswPr), we specify that the maximum length of strings must not exceed 1024 characters, so maybe we should require changes in the data request to meet this limit.

**Comment by taylor13** [comment]
I understand that as a stop-gap measure, the long strings are being truncated (ending at a ".") before the 1024 limit.  This is a good solution for now, but lets keep this issue open and try to improve handling of strings in a later release.

**Comment by dnadeau4** [comment]
I truncated to 1024 characters and stop at a sentence when creating the table.
