### ISSUE TITLE
time axis with varying approx_interval's

### ISSUE THREAD

**Issue by markcollier** [PCMDI/cmor#320]
In my cmor'ising python tool I can write out seasonal averages e.g. DJF simply by increasing the approx_interval value. However, if I want to write out each separate month (ie. broadcast the elements) of the season e.g.

year 1, D, J and F
year 2, D, J and F
...
year n,D,J and F

for where the months are available, I cannot do this as it would require two intervals, one between each month and another between the years (something like 35, 400). 

Whilst I could probably use two different tables and apply them within my loop, it would be messy.

Is there someway around this? For example, it would sometimes be good to ignore cmor_axis errors.

Understandably the output netCDF files may not be CF conformant, however, it can be very useful to be able to generate these kinds of files...

**Comment by durack1** [comment]
@markcollier it's not 100% clear what you're trying to do. It seems from my reading of the above that you're trying to generate climatology outputs - so seasonal climatologies per year. The way that I have achieved this for the 1955-2012 salinity climatologies (WOA13v2) can be viewed [here](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/demo/MRI-JMA-JRA55-do-1-3/runCmorDemo.py#L188-L220). As CMOR is a rewriter, rather than a data preprocessor and writer, it's beyond the scope of what the software aims to achieve.

@taylor13 can chime in if I've missed something

**Comment by markcollier** [comment]
I have no problems writing out regular climatologies. The problem is in essence, writing out monthly data with gaps as cmor checks for time gaps and raises an exception if they do not all approximate the approx_interval value found in the cmor table. I assume something similar would occur for other frequencies.

**Comment by markcollier** [comment]
I should mention that in this case I am not using cmor to generate datasets for submission to CMIP6. My philosophy is that when rewriting model data, where possible output datasets should be reduced in size wherever possible. From this point of view, if someone only wants selected months from a time-series (rather than a continuous set) then it should be possible. I'll try to take a look at some of the code that disallows what I am doing and perhaps turn it off for this application.

**Comment by markcollier** [comment]
Think it is a good sign when tools like cmor are being used successfully beyond their designed/resourced scope. All good Karl/Paul.

**Comment by durack1** [comment]
No problem @markcollier did you want to close this issue then?

**Comment by markcollier** [comment]
I should have mentioned, that my issue was in trying to write these months to a single file, I can, write out the required months to separate files (for little resources), and then have a "merge" tool that does the combining of the files, if required. I think that is more than satisfactory.
