### ISSUE TITLE
Naming of coordinate variables, dimensions and labeled axes

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#321]
Hi,
what is the detailled procedure of how CMOR names coordinate variables and dimensions? I thought that the attribute "out_name" of the respective coordinate variable contains the name, which is later in the output. E.g., variable "tas" from CMIP6_Amon.json has dimension "height2m" which is in CMIP6_coordinates.json. The out_name of "height2m" is "height".  However I can see that this is not the general method, e.g. for output of CMOR for variables with labeled axes.

From the source code I have learned until now that the program searches for the attribute "coordinates" - similar to the procedure in CMIP5 (coord_att). However, except for one, I can not find such an attribute in the MIP tables. In CMIP6_grids.json there is one for the grid_mapping parameter which has the values "rlat,rlon" - but "grid_latitude"  has also out_name "rlat". Furthermore, the "coordinates" attribute of the variable using this grid will not have values "rlat,rlon" but "latitude, longitude".

Additionally, from [the document](https://goo.gl/neswPr) I would like to point out once again that there can be two labeld axes, which according to the rules should both be called "sector". In CMIP6_Emon we have "grassFracC4" which requires two labeled axes "typec4pft typenatgr". How can they both be called "sector"? I'll try and see how the program reacts.

Thanks for helping and best regards,
Fabi

**Comment by durack1** [comment]
@wachsylon have you reviewed the registered details found in https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_coordinate.json?

**Comment by wachsylon** [comment]
Do you mean the latter point? Yes, grassFracC4 in Emon with "typec4pft typenatgr" dimensions which are listed in coordinate.json.
Do you think it is better to post it in that context?

**Comment by durack1** [comment]
@wachsylon I am having a hard time ascertaining what your question(s) are. Could you try posing these again. If there are two, can you separate them into more defined single questions?

**Comment by wachsylon** [comment]
Ok, I am sorry for confusing you, I try to clearify.
Thx for the fast response.

1. My main question is: Where does CMOR take the names from for the coordinate variables? Is there a general rule?
For singleton dimensions, we have:
Line 1659 following in cmor_variables.c:
`            if (cmor_has_variable_attribute(vrid, "coordinates") == 0) {
                cmor_get_variable_attribute(vrid, "coordinates", &msg[0]);
            } else {
                strncpy(msg, "", CMOR_MAX_STRING);
            }
            if (cmor_tables[cmor_axes[laxes_ids[i]].ref_table_id].axes
                [cmor_axes[laxes_ids[i]].ref_axis_id].out_name[0] == '\0') {
                snprintf(ctmp, CMOR_MAX_STRING, "%s %s", msg,
                         cmor_tables[cmor_axes[laxes_ids[i]].ref_table_id].axes
                         [cmor_axes[laxes_ids[i]].ref_axis_id].id);
            } else {
                snprintf(ctmp, CMOR_MAX_STRING, "%s %s", msg,
                         cmor_tables[cmor_axes[laxes_ids[i]].ref_table_id].axes
                         [cmor_axes[laxes_ids[i]].ref_axis_id].out_name);
            }
            cmor_set_variable_attribute_internal(vrid,
                                                 VARIABLE_ATT_COORDINATES, 'c',
                                                 &ctmp[0]);`
So the name seems to be out_name if available, otherwise axis name. Why can we not use that procedure (or another) everytime?

2. In cmor.c 3488 following:
`strcpy(ctmp,
                   cmor_tables[pAxis->ref_table_id].axes[pAxis->ref_axis_id].
                   cname);
            if (ctmp[0] == '\0') {
                strcpy(ctmp, "sector");
            }
            if (cmor_has_variable_attribute(var_id, "coordinates") == 0) {
                cmor_get_variable_attribute(var_id, "coordinates", msg);
                l = 0;
                for (j = 0; j < strlen(msg) - strlen(ctmp) + 1; j++) {
                    if (strncmp(ctmp, &msg[j], strlen(ctmp)) == 0) {
                        l = 1;
                        break;
                    }
                }
                if (l == 0) {
                    strncat(msg, " ", CMOR_MAX_STRING - strlen(msg));
                    strncat(msg, ctmp, CMOR_MAX_STRING - strlen(msg));
                }
            } else {
                strncpy(msg, ctmp, CMOR_MAX_STRING);
            }
            cmor_set_variable_attribute_internal(var_id,
                                                 VARIABLE_ATT_COORDINATES,
                                                 'c', msg);`
CMOR uses "cname" which is AXIS_ATT_COORDSATTRIB (cmor_axes.c) which again is "coords_attrib" (cmor.h). However, this attribute does not exist in the MIP-tables.

3.  In CMIP6_Emon we have "grassFracC4" which requires two labeled axes "typec4pft typenatgr". The latter are two labeled axes which will be processed with the code under (2.). So both would be named "sector" what probably wont work however I have not tested it yet.

So all in all, we need an understanding what CMOR takes for naming axes and dimensions in which cases.

**Comment by taylor13** [comment]
I will try to provide a definitive explanation soon (perhaps not tomorrow, but soon).  We are well aware of the 2-scalar coordinates issue, and that currently this still needs to be addressed.  I think other threads also raise this (both on github and as comments in google docs).

**Comment by wachsylon** [comment]
Great, thanks. Just to be clear, not only 2-scalar coordinates but also 2 labeled axes may be possible according to the MIP-tables. I think this would end up in two dimensions "strlen" and maybe "strlen2".

**Comment by taylor13** [comment]
Forgive the delay in getting back to this.  In what follows, I describe how CMOR is *supposed* to work, but I'm not absolutely possible that this is actually the way it works; there may be bugs.  

Let me specifically address two of your implied questions above (and I'll try to add more tomorrow): 
```
I thought that the attribute "out_name" of the respective coordinate variable 
contains the name, which is later in the output. .... The out_name of "height2m" is 
"height". However I can see that this is not the general method, e.g. for output 
of CMOR for variables with labeled axes.
```
 "Labeled" axes are axes where the coordinate values are in fact consecutive integers (an "index axis").  The index axis name is defined by "out_name".  In the case of labeled axes, the field of interest must have a coordinates attribute attached that points to the variable containing the "labels" (stored in an "auxiliary coordinate" which is a function of the "index" axis.).  In CMIP6, the labels for such axes are invariably stored in a variable named "sector".  

 As an example, the variable  "mfo" has dimensions specified as "oline time".  If you look up "oline" in the CMOR coordinates table, you find the "out_name is "line", so in the netCDF file you'll see "mfo(line, time)".   Because this coordinate has associated labels, you'll also find a "coordinates" attribute attached to "mfo" and like other such variables it invariably indicates that the labels are stored in a variable named "sector" (where "sector" is a function of "line")  

Singleton coordinate variables with labels are treated similarly except, of course, the variable is *not* an explicit function of the coordinate.  As an example, the variable "treeFrac" has dimensions, as defined under the CMOR table entry (key): "longitude latitude time typetree".   Since typetree is a singleton dimension, the variable found in the netCDF output file wll be only a function of (lon, lat, time), and it will have a  "coordinates" attribute attached which will include "sector".  In this case the string "trees" will be recorded in the variable named "sector".  

So labels are treated similarly, whether or not they are scalars.

You also say:
```
From the source code I have learned until now that the program searches for the
 attribute "coordinates" - similar to the procedure in CMIP5 (coord_att). However,
 except for one, I can not find such an attribute in the MIP tables. 
```
A coordinates attribute is needed in the cases listed under item 13c of the Requirements for output variables" section of https://goo.gl/neswPr

Note that the "coordinates" item found in CMIP6_grids.json is, I think, extraneous and probably could be removed.  [@denis could you check this last statement please?]

**Comment by wachsylon** [comment]
Thanks for the detailed answer. It is difficult for me to comprehend the entire connections beginning with the variable entry "dimensions" which is not necessarily the name of netCDF dimension:

> As an example, the variable "mfo" has dimensions specified as "oline time". If you look up "oline" in the CMOR coordinates table, you find the "out_name is "line", so in the netCDF file you'll see "mfo(line, time)".

Can I deduce the general rule from this: "The value of "out_name" of an entry in the Coordinates table defines the dimension name in the netCDF file"? And is there a rule for naming the coordinate variable besides the "sector" exception? 

> Singleton coordinate variables

Does "Singleton" mean scalar? Or does "scalar" comprise the index axes with consecutive integers as well?

> So labels are treated similarly, whether or not they are scalars.

Yes, but differently to e.g. "height2m" because "height2m" has not a dimension in the netCDF file (strlen).

**Comment by wachsylon** [comment]
OK I finally (unfortunately only recently) realized:
All label coordinates named "type*" are singleton. One reason why I overlooked it is: I mistakenly expected to have exactly one value for the coordinate entry "requested" since it is a label axis. Maybe it could be an idea to merge both "value" and "requsted" entries to "requested_values" some day?

The variable
"nwdFracLut"  in table Emon remains with dimensions:    "typenwd,landUse" which are both labeled axes (one singleton). At least here, we have the problem that two "sector" coordinate variables will be in the netCDF file. Since "landUse" include 4 requested values it is a different problem compared to two singleton labeled axes with values <singleton1> and <singleton2> where it could be an idea to have "sector": "<singleton1> <singleton2>" in the netCDF file.

**Comment by wachsylon** [comment]
> From the source code I have learned until now that the program searches for the
>  attribute "coordinates" - similar to the procedure in CMIP5 (coord_att). However,
>  except for one, I can not find such an attribute in the MIP tables. 

I was slightly wrong. CMOR takes "coords_attrib" which is not in any MIP-table. Notwithstanding, I agree with

> Note that the "coordinates" item found in CMIP6_grids.json is, I think, extraneous and probably could be removed

**Comment by taylor13** [comment]
In an above comment I said:
```
Singleton coordinate variables with labels are treated similarly except, of 
course, the variable is not an explicit function of the coordinate. As an example, 
the variable "treeFrac" has dimensions, as defined under the CMOR table entry (key):
 "longitude latitude time typetree". Since typetree is a singleton dimension, the
 variable found in the netCDF output file wll be only a function of (lon, lat, time), and
 it will have a "coordinates" attribute attached which will include "sector". In this case
 the string "trees" will be recorded in the variable named "sector".
```
I'm not absolutely sure this is correct.  I'll check whether it is recorded under "out_name" or "sector" for scalar coordinates.

**Comment by taylor13** [comment]
First a small correction to one of your assertions.  You said:
```
All label coordinates named "type*" are singleton.
```
Actually, "vegtype" has out_name "type" and it is a vector, not a scalar.  The definition of the labels in this case up to the user (there is no controlled-vocabulary or "requested" values).  The labels in this case should be stored in a variable named "sector"

I think the best way to determine if a label coordinate is a vector or scalar is to check whether "value" is defined.  If it is, then the label coordinate is a scalar.

Now to confirm that I was mistaken as indicated in my previous comment.  For scalar labels, the "coordinates" attribute will include the name of the variable containing the label, and that name should be set to the "out_name" for that coordinate.  I think for all CMIP6 scalar labels of this kind the out_name is "type".

By the way, CMOR generates the "coordinates" attribute from information in the table, even though the table itself does not define the "coordinates" attribute. 

Be happy to address additional questions.

**Comment by taylor13** [comment]
@wachsylon Have we adequately addressed your questions?  Can we close this, or is there something more to be done?

**Comment by wachsylon** [comment]
Lets close it. Right now I do not remember anymore what I wanted to say in 50% of the above comments. Maybe I will come back to that later.
