### ISSUE TITLE
Installation Error: Could not get a working udunits2

### ISSUE THREAD

**Issue by delong260** [PCMDI/cmor#324]
I am attempting to install CMOR3 on a 64-bit Ubuntu virtual machine, but I am getting the following errors after running the configure script.  I was not able to find the Udunits installation in /usr/local where it's supposed to be by default, but I noticed that the makefile for Udunits was updating files in the build directory since I was using Cmake.  As you can see, using that target for the --with flag didn't work.  Any help is appreciated.

`$./configure --prefix=/usr/local --with-netcdf=/usr/local --with-udunits2=/jakob/home/udunits-2.2.26/build

checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
TARGET: linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking for a sed that does not truncate output... /bin/sed
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for ranlib... ranlib
checking for gfortran... gfortran
checking whether we are using the GNU Fortran compiler... yes
checking whether gfortran accepts -g... yes
checking how to get verbose linking output from gfortran... -v
checking for Fortran libraries of gfortran...  -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. -lgfortran -lm -lquadmath
checking for uuid_create in -luuid... yes
checking for ut_parse in -ludunits2... no
configure: error: Could not get a working udunits2
`

**Comment by dnadeau4** [comment]
It seems that your udunits library cannot be found.  Can you make sure that the `include` and `lib` directories are under build.

Here is my configure:

```
./configure --prefix=/software/anaconda2/envs/cmor3/ 
--with-python=/software/anaconda2/envs/cmor3/ 
--with-uuid=/software/anaconda2/envs/cmor3/ 
--with-udunits=/software/anaconda2/envs/cmor3/ 
--with-netcdf=/software/anaconda2/envs/cmor3/
```

I would suggest you install anaconda2 and follow these instructions:

`https://cmor.llnl.gov/mydoc_cmor3_conda/`

(Note: we are getting a new certificate that will be installed tomorrow).

**Comment by dnadeau4** [comment]
@delong260 Where you able to compile cmor?

**Comment by taylor13** [comment]
@delong260 Please let us know whether you have been able to use CMOR.  Can we close this issue?

**Comment by delong260** [comment]
I'm sorry, I've been sidetracked on other issues and we've moved on from this part of the project.  Feel free to close the issue for the time being.
