### ISSUE TITLE
web site: slight errors on the Contact page

### ISSUE THREAD

**Issue by jypeter** [PCMDI/cmor#329]
@dnadeau4 The following line is missing a `mailto`
`To send an email to the list: CMOR@LISTS.LLNL.GOV`

Some commands you can send to the list server are surrounded by `?`. Is this correct or a typo?

- `?SIGNOFF CMOR?`
- `?Review CMOR?`

You could use a `?body` tag. See how I have done it in the _List server commands_ links of [PMIP 2 Mailing Lists](https://pmip2.lsce.ipsl.fr/lists.shtml)

**Comment by dnadeau4** [comment]
thanks @jypeter.  I just cut/paste the info from the lab mailing list.  These `?` character are must be wrongly converted by "jekyll" when I build the site.  I'll look at them.

**Comment by dnadeau4** [comment]
It looks better now. 😄
