### ISSUE TITLE
obs4MIPs restructuring

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#33]
There is a need to generalise CMOR so that it is easier for a user to "once off" write their observational data following the CF and CMIP5 conventions (this will require a consideration of existing usage by the CMIP community - tradeoffs will need to be carefully considered).

`global_attributes` will likely be MIP-dependent.

New obs4MIPs tables will likely need to be created.

Some of this information is presented on the [ESGF-CoG](https://www.earthsystemcog.org/projects/obs4mips/how_to_contribute)

Specifically there are a number of working documents which outline `global_attributes` and `identifiers`:
[obs4MIPs Dataset Requirements](https://www.earthsystemcog.org/site_media/projects/obs4mips/obs4MIPsDatasetRequirements_v1.2.pdf)
[obs4MIPs Global Attributes Requirements](https://www.earthsystemcog.org/site_media/projects/obs4mips/obs4MIPsGlobalAttributesRequirements_v1.1.pdf)

Further information about getting a users data into `netcdf` can be added on a wiki page - potentially at the [PCMDI_metrics page](https://github.com/PCMDI/pcmdi_metrics/wiki)

Pinging @taylor13 @gleckler1 @doutriaux1 @durack1

**Comment by durack1** [comment]
@gleckler1 @durack1 to work on this - to finalise using [input4MIPs-cmor-tables](https://github.com/PCMDI/input4MIPs-cmor-tables) as an example.

[obs4MIPs-cmor-tables](https://github.com/PCMDI/obs4MIPs-cmor-tables) repo is ready for use

**Comment by dnadeau4** [comment]
This seems good,  we need to work on the new Control Vocabulary file especially for grid_label and grid_resolution.  I will have to change cmor_CV.c to handle the new data structure.

**Comment by durack1** [comment]
@dnadeau4 let's sit down with @gleckler1 and @taylor13 tomorrow and see if there's anything else that needs to be clarified.. I think we're in pretty good shape across the `CMOR3`, `obs4MIPs` and `input4MIPs` tables now..
