### ISSUE TITLE
"warnings" by PrePARE

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#334]
@senesis @glevava @dnadeau4 

Some warnings produced by PrePARE are really errors and datasets that raise these warnings should not be published on ESGF.  Denis has found a way, I think, to make sure these warnings can be "seen" in the ESGF publication pipeline.  Perhaps @dnadeau4  can briefly say what he has done.  This fix should be in the next release. 

Here is the background: 

PrePARE relies on some of the checks performed by CMOR during CMOR's normal the execution, and in that mode, CMOR actually corrects some of the problems identified and then issues a "warning" to the user describing what corrections it has made.  When PrePARE is run on already created files, the same parts of the CMOR code are executed, but CMOR *can't* correct the problems; it just issues the "warning" (which is somewhat misleading because it describes what fix would have been done under CMOR).  

Because these are warnings, not errors, they are not transmitted to the upper levels of PrePARE and excecution isn't halted.  Thus, ESGF will be unaware that the files don't meet CMIP6 specs.  As said earlier, this must be fixed and Denis has found a way to fix it in the next release.

**Comment by glevava** [comment]
In addition could you provide an example of warning silently detect by CMOR methods behind PrePARE? Just to clearly understand how to solve this on our side if needed.

**Comment by dnadeau4** [comment]
@glevava I have addressed this in `PrePARE-fix` branch.

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/cmor/compare/PrePARE-fix

**Comment by glevava** [comment]
Arf, ok so ignore my PR I'll review it according your changes. Basically, I copy-past my whole tested PrePARE on a pull from PrePARE-fix to ensure no conflicts but I didn't focus on what you have changed.

**Comment by dnadeau4** [comment]
@glevava   that is fine, I can merge both, and resolve conflicts if needed.  It happens all the time,   not a problem...

**Comment by glevava** [comment]
ok thanks a lot @dnadeau4 !!
Hope it will be not a huge piece of work, let me know if I can help.

**Comment by glevava** [comment]
Oh yes I saw I added this... just when I pull my request -_- damned. Sorry for that.

My contribution is ok, that's part of my job in the ESGF community ; )

A pleasure to work with you and Karl.

**Comment by taylor13** [comment]
likewise.  You and Denis are critical to the success of CMIP6

**Comment by dnadeau4** [comment]
@glevava I merged the branch into master, so now Warnings becomes error in PrePARE.
