### ISSUE TITLE
PrePARE and time_counter name 'time1' for instant fields

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmor#336]
When using time_counter name 'time' for all kind of fields (either average or instant fields), PrePARE doesn't complain

When using name 'time1', as requested by the DREQ, I got :

> CDMS error: Error on character time conversion, string = ?
> ...
> ! Error: Your filename 
> ! "cct_CFsubhr_CNRM-CM6-1_amip_r98i1p1f2_gn_20080101001500-20080102000000.nc" 
> ! does not match the CMIP6 requirement.
> ! 
> ! Your output filename should be: 
> ! "cct_CFsubhr_CNRM-CM6-1_amip_r98i1p1f2_gn_00000101000000-00000101000000.nc"
> 

The file structure is as follows :

> netcdf cct_CFsubhr_CNRM-CM6-1_amip_r98i1p1f2_gn_20080101001500-20080102000000 {
> dimensions:
> 	axis_nbounds = 2 ;
> 	site = 126 ;
> 	nvertex = 4 ;
> 	time1 = UNLIMITED ; // (96 currently)
> variables:
> 	double time1(time1) ;
> 		time1:axis = "T" ;
> 		time1:standard_name = "time" ;
> 		time1:long_name = "Time axis" ;
> 		time1:calendar = "gregorian" ;
> 		time1:units = "days since 1850-01-01 00:00:00" ;
> 		time1:time_origin = "1850-01-01 00:00:00" ;
> 		time1:bounds = "time1_bounds" ;
> 	double time1_bounds(time1, axis_nbounds) ;
> 	float cct(time1, site) ;
> 

Which is the best way forward ?

**Comment by taylor13** [comment]
The out_name for "time1" is "time" (as is also the case for "time2" and "time"), so the name of your time coordinate should be "time", not "time1".  This may not be the only problem, but I suspect if you fix it, PrePARE will approve of you filename (which looks correct to me for the 96 samples spaced 15 minutes apart starting at 15 minutes past midnight on 1850-01-01 and ending with midnight).

Perhaps PrePARE could provide a better error message.  

By the way is realization=98 really correct?  You can assign any positive integer you want here, of course, but most groups will start with 1.  

Also, to be sure, is "time_counter" the same as "time coordinate", or does it have a special interpretation?

**Comment by taylor13** [comment]
If you provide an ncdump of the entire header (and perhaps everything in the file except the data values of "cct", I could check whether I see any other issues.

**Comment by senesis** [comment]
OK. I got caught once more by the difference between dimension label and dimension out_name (or altLabel, in DREQ parlance)
Everything is fine with PrePARE for most files when using out_name 'time'
Realization number 98 was used on purpose when providing a dateset for ESGF Data Challenges, in order to avoid non-final data to be mistakenly interpreted as really published data. By the way, using two digits allowed to identify a weaknes in cdf2cim (ES-doc feed by datafiles)
Thanks

**Comment by taylor13** [comment]
That's our objective ... see if we can trip you up with obscure specifications.   (just kidding)   I understand that specifying a 2 digit realization was not for the same purpose, but  produced an excellent result.
