### ISSUE TITLE
CMOR 3.3.2 missing on OSX anaconda channel

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#338]
I just went to create a new conda environment on my Mac, and I got 3.3.1 with
```
[durack1ml:~] durack1% conda create -n cmor332 -c pcmdi -c conda-forge cmor
```
It seems only the linux-64 package is available:
https://anaconda.org/PCMDI/cmor

**Comment by dnadeau4** [comment]
I just uploaded the mac OSX 3.3.2

**Comment by durack1** [comment]
@dnadeau4 perfect thanks!
