### ISSUE TITLE
Test/cmor_speed_and_compression.py points to wrong location

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#34]
sample_data moved in uvcdat see:
https://github.com/UV-CDAT/uvcdat/pull/1390

**Comment by doutriaux1** [comment]
also: Test/cmor_speed_and_compression_01.py

**Comment by durack1** [comment]
@doutriaux1 is this still relevant for 3.x? If not please close (@dnadeau4 pinging you here)

**Comment by dnadeau4** [comment]
Test/cmor_speed_and_compression_01.py is working.
