### ISSUE TITLE
source not defined cause segmentation fault

### ISSUE THREAD

**Issue by dnadeau4** [PCMDI/cmor#343]
When source is defined to "" or not defined at all, it cause a `segmentation fault` due to the new tree architecture for CMIP6_CV for `source_id`.  

CMOR needs to loop in every branch to retrieve the `source` node.  This cause "source_check" to display a erroneous warning as well.

**Comment by durack1** [comment]
@dnadeau4 thanks for catching this, it's likely one of the reasons I hit segfaults in earlier versions

**Comment by dnadeau4** [comment]
Fix with commit
67585f58971aedae15441bb1b5e3df2cb5120570

**Comment by durack1** [comment]
@dnadeau4 nice - can this be closed, or is it yet to be merged?

**Comment by dnadeau4** [comment]
yet to be merged.

**Comment by doutriaux1** [comment]
fixed in #352
