### ISSUE TITLE
<realm> incorrectly defined from table and input.json in output path

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#345]
I'm attaching an example where the `<realm>` as defined in the input json (table and user input) files is incorrectly generated.

The `user_input.json` file contains:
```
"output_path_template": 
"<activity_id><mip_era><target_mip><institution_id><source_id><realm><frequency><variable_id><grid_label><version>",
```
And the table file `input4MIPs_SImon.json` contains:
```
"Header":{
  "Conventions":"CF-1.7 CMIP-6.2",
  ...
  "realm":"seaIce",
```
and
```
"siconcbcs":{
  "cell_measures":"area: areacello",
  ...
  "modeling_realm":"seaIce",
```
So I have no idea why `ocean` (defined as `<realm>`) is in the output path:
```
..input4MIPs/CMIP6/CMIP/PCMDI/PCMDI-AMIP-1-1-4/ocean/mon/siconcbcs/gn/v20180424/siconcbcs_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-4_gn_187001-201712.nc
```
Is being defined. @dnadeau4 can you please work through this with me, all the code required is included in the attached file, and the input file can be downloaded [here](https://oceanonly.llnl.gov/durack1/dump/180424_CMOR3/amipbc_siconc_360x180_v1.1.4_187001-201712.nc)
[CMOR-oceanRealmBug.zip](https://github.com/PCMDI/cmor/files/1945132/CMOR-oceanRealmBug.zip)

**Comment by dnadeau4** [comment]
This is overwritten by your `Control Vocabulary` file.  

The `source_id` section `PCMDI-AMIP-1-1-4` has a `"realm"`:`"ocean"` definition.  

`source_id` is a special case for `obs4MIPs` where every `key`:`value` is set in the output `netCDF` file.

**Comment by durack1** [comment]
@dnadeau4 thanks, so the `source_id`:`realm` definition then clobbers the table `realm` or `modeling_realm` definition as one of the last elements checked. I will need to delete the `realm` definition in the registered content [here](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/input4MIPs_source_id.json#L20)

Ref: PCMDI/input4MIPs-cmor-tables#51
