### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#346]
Hi,
right now I am improving the error handling of the CMOR application in CDO. I installed a signal handler at a point before `cmor_setup` is called. This did not work and the program ignored termination signals from CMOR.
1. Am I right that this is due to
```
    struct sigaction action;
    memset(&action, 0, sizeof(struct sigaction));
    action.sa_handler = terminate;
    sigaction(SIGTERM, &action, NULL);
```
in lines 757-760 cmor.c? If I set the signal handler AFTER calling `cmor_setup`, it will work, correct?

2. I actually thought I could use the return value of CMOR functions to evaluate whether CMOR works correctly. This would provide me with an idea which user-side function did not work. I know that the Traceback gives information, however, right now I have a message on the screen:

> C Traceback:
> ! In function: cmor_write_var_to_file
> ! 

which is not a user-side available function. Since `return` is not used regularly in the function sources, I cannot use this method for error handling. However, there are lines 1060-1064 in cmor_variables.c for example
```
    if (cmor_nvars == CMOR_MAX_VARIABLES - 1) {
        cmor_handle_error("Too many variables defined", CMOR_CRITICAL);
        cmor_pop_traceback();
        return (1);
}
```
which suggest that my method is valid. Maybe it could be an idea to remove all `return` calls or add the missing ones.

**Comment by wachsylon** [comment]
3. I have a memory fault for "zooc" in Omon for a wrong configuration: A grid is registered and the resulting `grid_id `is in the integer array `axis_ids `provided as the fifth parameter of cmor_variable. Additionally, only a time axis is registered. Therefore, the cmor_variable call looks like this:
`cmor_variable(&cmorvarID, (char *)"zooc", (char *)"mol m-3", 2, axis_ids, ...`
If I instead call
`cmor_variable(&cmorvarID, (char *)"zooc", (char *)"mol m-3", 3, axis_ids, ...`
, a memory fault occurs. This is a trap for CMOR beginner because the combination (`...2, axis_ids...`) is not easy to comprehend.

**Comment by wachsylon** [comment]
4. If `cmor_write` fails there will be empty files like sfcWind_day_EMAC-2-53-AerChem_piControl_r1i1p1f1_gnufkphd9509.nc . Is there a reason why CMOR does not remove these files? I think CMOR should..

**Comment by wachsylon** [comment]
Thank you for your fast responses.

@taylor13 Yes, I program in C and use the C functions. CMOR is not the problem here, I just need to know how to use its error signal submitting correctly.

@dnadeau4  
1 and 2. Yes, `C` it is.  I put a signal function in my program after `cmor_setup` which probably overwrites your signal handler. It seems to me that this is similar to use stop. When I put it before `cmor_setup`, your signal handler probably overwrites mine and CMOR never stops.  
3. 

> You could try to pass "sizeof(axis_id)/sizeof(int)"

This is actually the way to go and I forgot this option, thank you! I have the entire code and will post it here.

4. 

> It tells people that this variable was not processed correctly. I changed this behavior last year and got some complaints from users, saying that they did not know that the files were bad.

Funny. People recognize that a variable was NOT processed correctly if a file for it exists... However, it is just a matter of agreement.

**Comment by wachsylon** [comment]
```
static int *
new_axis_id(int *axis_ids)
{
  int i;
  for (i = 0; axis_ids[i] != CMOR_UNDEFID; i++)
    ;
  axis_ids[i + 1] = CMOR_UNDEFID;
  return &axis_ids[i];
}

int cmf = cmor_dataset_json("cdocmorinfo_CMIP6_MPI-M_MPIESM-1-2-HR_historical.json");
if (cmf != 0)
  {
 printf("ERROR! Function cmor_dataset_json failed!");
exit(1);
  }
cmor_load_table((char *)"/home/Tables/CMIP6_Omon.json", &table_id);
cmor_set_table(table_id);
cmor_axis(new_axis_id(axis_ids), (char *)"time ", (char *)"days since 1850-01-01 00:00:00", 0, NULL, 0, NULL, 0, NULL);
cmor_load_table((char *)"/home/Tables/CMIP6_grids.json", &gridtable_id);
cmor_set_table(gridtable_id);
cmor_axis(&grid_axis[0], (char *) "j_index", (char *) "1", ylength, (void *) yncoord_vals, 'd', 0,
                              0, NULL);
cmor_axis(&grid_axis[1], (char *) "i_index", (char *) "1", xlength, (void *) xncoord_vals, 'd', 0,
                              0, NULL);
cmor_grid(&grid_ids[0], 2, grid_axis, 'd', (void *) ycoord_vals, (void *) xcoord_vals, 4,
                              (void *) ycell_bounds, (void *) xcell_bounds);
int *tmp_id = new_axis_id(axis_ids);
*tmp_id = grid_ids[0];
cmf = cmor_variable(&cmorvarID, (char *)"zooc", (char *)"mol m-3", 3, axis_ids, 'd',
                         (void *) "", &tolerance, (char *)"", NULL, NULL, NULL); 
```

**Comment by doutriaux1** [comment]
@wachsylon I just took over CMOR from @dnadeau4 I will look into this, please post the whole source as well it can't hurt 😉

**Comment by taylor13** [comment]
@wachsylon Can this issue be closed or is it still unresolved?
