### ISSUE TITLE
input source in dataset_json file leads to seg fault

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#349]
using a common_input_file with empty string for source leads to seg fault...
```json
   "source":                 "",
```

**Comment by dnadeau4** [comment]
That is the issue I was working on last Wednesday.

**Comment by doutriaux1** [comment]
@dnadeau4 I got it sorted out. You actually print a message but return CMOR_NORMAL or soemthing error, so it keeps going and then seg fault before the message gets to the log

**Comment by doutriaux1** [comment]
@dnadeau4 I'm on it, will fix shortly

**Comment by doutriaux1** [comment]
@taylor13 the fact that this is empty is actually caught but triggers a `CMOR_NORMAL` error, hence the program continues and seg fault a bit later. I think we need to return a `CMOR_CRITICAL`

**Comment by doutriaux1** [comment]
@taylor13 @dnadeau4 alternatively I can catch it also where it creates the seg fault and return another `CMOR_NORMAL` error there.

**Comment by doutriaux1** [comment]
@taylor13 now that it keeps doing I see that later it says:
```
! Warning: Your input attribute "sub_experiment" was not defined and 
! will be set to "none" 
! as defined in your Control Vocabulary file "/Users/doutriaux1/Karl/Tables/CMIP6_CV.json".
```

What do we want

* critical error if attribute is required and not defined
* critical error if empty ? (caught a bit later)
* normal error if empty (won't be defined I guess)
* error and set to `none` (or just warning?)

**Comment by taylor13** [comment]
That warning for "sub_experiment" is unrelated to "source".  

Also, @dnadeau4 says that some of the code is no longer needed.  If we eliminate it, it might fix the problem.

The user doesn't have to define all the "required" attributes.  CMOR can define some of them by looking at the CV's.  For example, given source_id, CMOR can generate the "source".  Given the institution_id, CMOR can generate the "institution".  So we don't want a critical error to be raised if the user fails to define some of the "required" attributes.  

I think we should eliminate "source", "institution", and "sub_experiment" from our common_input_file (or whatever the user's input json file is called).  That is elminate: 
```
“#note”:                  “ **** The following will be obtained from the CV and do not need to be defined here”, 

   "sub_experiment":         "",
   "institution":            "",
   "source":                 "",
```
Questions:

1) what would happen if the user set any of the other specified parameters in the file to an empty string?  Would we get a segmentation fault?

2) What would happen if the user tried to define an unrecognized parameter.  For example:
```
  "gobbly-gook":         "lots of gobbly-gook",
```

**Comment by doutriaux1** [comment]
@taylor13 I will run some tests to answer these questions. Back soon 😉
