### ISSUE TITLE
check new tables

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#355]
(This is a copy of an email exchange.  Karl's text is in normal font, while Martin's comments are in bold italic font.)

I note the following changes to the data request might need our attention:

1) long comments: I think we should try to avoid the "long comments".  They clutter up the ncdumps of files and I think CMOR can only handle up to 1024 characters.  

**_There are 49 variables with long comments .. a brief review suggests that they mainly result from using the standard name comment (we decided that this was better than having a blank value). I can shorten them, but probably not this week._**

2) I noticed the change of one coordinate from latitude to grid_latitude.  Is this correct?  Also, it appears that grid_latitude seems to have been removed from the  cmip_grids file. Need to check this is o.k.

**_I changed "latitude" to "grid_latitude" for one variable which is required on the model grid, and only when it is a rotated grid ... i.e. so grid_latitude is the correct coordinate. I don't know about the "cmip_grids" file._**

3)   I don't think CMOR can handle 2 scalar dimensions, so introduction of 
"dimensions": "longitude latitude time lambda550nm scatter180"  with 2 scalar dimensions will break CMOR.  

**_Can you check this Charles? I know we had problems with two area type coordinates (which created a variable naming conflict in the CMOR output file), but here we really need independent coordinates for the wavelength and scattering angle. If absolutely necessary they could be left out, but it would make the metadata incomplete._**

4)  Need to check that any new "dimensions" added in this latest data request are harvested by CMOR into its tables.

5)  Looks like k_index has been removed from the coordinates table.  Is this o.k.? 

6) The corrections from "alevel" to "alevhalf" should not cause CMOR problems (once Charles implements recent changes).

**Comment by durack1** [comment]
@doutriaux1 I agree with your statement, the test suite will likely need to be augmented to make sure these changes above don't break anything..

**Comment by doutriaux1** [comment]
@taylor13 this done we can close once I sent the 3.3.3 annoucement

**Comment by taylor13** [comment]
Were all 6 items in  https://github.com/PCMDI/cmor/issues/355#issue-326554049 addressed?  I think we should make sure Martin knows about the 1st item before closing this.
