### ISSUE TITLE
Unstructured Grids

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#357]
Hi,
I have a file with a triangular mesh grid. It contains:
```
dimensions:
	ncells = 830305 ;
	nv = 16 ;
	nlinks_max = 8 ;
	Three = 3 ;
	ntriags = 1634526 ;
```
with
`	double lon_vertices(ncells, nv) ;
	double lat_vertices(ncells, nv) ;`

My approach, similar to Curvilinear-Grids, is:
```
          cmf = cmor_axis(&grid_axis[0], (char *) "i_index", (char *) "1", xlength, (void *) coord_vals, 'd', 0,
                          0, NULL);
          cmf = cmor_grid(&grid_ids[0], 1, grid_axis, 'd', (void *) ycoord_vals, (void *) xcoord_vals, nv,
                          (void *) ycell_bounds, (void *) xcell_bounds);
```
I received:
```
dimensions:
	time = UNLIMITED ; // (13 currently)
	lev = 46 ;
	i = 830305 ;
	bnds = 2 ;
	vertices = 830305 ;

```
with
`	float vertices_longitude(i) ;
	float vertices_latitude(i) ;`
Due to #162 I am confused: Should it be possible at all to process such a file with CMOR?

I am not sure about this and following [lines](https://github.com/PCMDI/cmor/blob/2083cb93a9c02005f0daa5175d7fc3c351349690/Src/cmor_grids.c#L974). I will test the code and give you a reply.
Best regards,
Fabi

**Comment by taylor13** [comment]
I know little about triangular mesh grids, but it seems odd that the number of vertices is declared to be 16, rather than 3 (for a triangular cell).  Also, I don't understand why ntriags (number of triangles in the mesh??) isn't the same as ncells (number of cells in the mesh??)   Is there some logical structure by which the triangles are grouped into cells?

**Comment by doutriaux1** [comment]
@wachsylon I'm not sure if this is a question for @taylor13 or a bug? Either way please provide us with a short sample code it will help move this faster.

**Comment by wachsylon** [comment]
For me it seems odd too and I am in contact with the grid description creator to clarify the structure first. In the mean time, I am trying to find out why CMOR does not process the second vertices dimension. I hoped you may already have experiences with triangular meshes in CMOR. But anyway, I try to find out what is happening at all - you do not need to do anything, thanks.

> Either way please provide us with a short sample code it will help move this faster.

Actually it is not that easy to provide the code because my CMOR-application script is very general and based on other library-functions. In this special case,
1. I decided to find the bug myself and provide a pull request (which I will do more often, especially if I have time for it)
2. think that the code I already posted is the main point of the problem and the rest does not simplify anything especially without access to the huge file which is processed with this code

**Comment by wachsylon** [comment]
This is the answer I received from the grid description creator:
We output all values on the nodes, not in the middle of triangles or tetrahedrons.

To calculate the area for which a node is representative, we need the centroids of the surrounding triangles and the medians of the edges of the surrounding triangles.

In the case of equilateral triangles we would have 6 surrounding triangles around each grid point. Of those we have 6 Centroids. In addition, we have 6 edges that lead from the grid point to the neighboring grid points. So 6 medians of these edges. Added together: 12.

But since sometimes more than 6 triangles can be around a grid point, if you do not consider equilateral triangles, which we do of course in our grid, you sometimes need more than 12 surrounding points (or less). The maximum in the present grid was 8 triangles, that is 16 points.

**Comment by wachsylon** [comment]
@taylor13 
1. Is there a CMIP standard for triangular meshes in general and for such a grid in particular?
2. Should CMOR be able to produce this? 

@doutriaux1 
In general, if a grid with one dimension and vertices for lat/lon should be produced with CMOR, the code needs to be slightly changed: If I call `cmor_grid` with only one dimension, the second dimension in the `cmor_variable` call of `vertices_longitude` and `vertices_latitude` in [cmor_grids.c](https://github.com/PCMDI/cmor/blob/2083cb93a9c02005f0daa5175d7fc3c351349690/Src/cmor_grids.c#L1034) is not processed and the length of the `vertices` dimension becomes wrong. I had success with a work around (which I could provide you as a pull request) however I do not know what happens if a grid has more than two dimensions.

**Comment by mauzey1** [comment]
@taylor13 @doutriaux1 Would passing the tests in this pull request resolve this issue?  https://github.com/PCMDI/cmor/pull/379

**Comment by mauzey1** [comment]
@taylor13 @wachsylon Can this issue be closed now?

**Comment by mauzey1** [comment]
@taylor13 @doutriaux1 After exploring this issue again, I noticed there was an error in the unstructured grid test for the indexing of the lon_coords and lat_coords arrays.  I've made a branch to fix this: https://github.com/PCMDI/cmor/tree/unstructured_grid_tests

I also made a test for 3d unstructured grids in the same branch.

**Comment by taylor13** [comment]
@mauzey1 What is the status of this?  Do you think CMOR is correctly treating unstructured grids?

**Comment by mauzey1** [comment]
@taylor13 @doutriaux1 
I made a test that expands the original unstructured grid test with two extra indexes.
https://github.com/PCMDI/cmor/blob/unstructured_grid_tests/Test/test_cmor_grid_unstructured_3d_fabi.c
It seems to be work correctly.  How else can I tests the unstructured grid behavior?

**Comment by doutriaux1** [comment]
@mauzey1 I think that's it. Just make sure your new test is in and close this.

**Comment by taylor13** [comment]
@mauzey1 Thanks for adding these tests.  Why don't I take a look at the output from the tests.  Are the netCDF files available?

**Comment by mauzey1** [comment]
@taylor13 His the output of the 3d unstructured grid test.
[hfls_Amon_PCMDI-test-1-0_piControl-withism_r3i1p1f1_gn_198001-198002.nc.zip](https://github.com/PCMDI/cmor/files/2881389/hfls_Amon_PCMDI-test-1-0_piControl-withism_r3i1p1f1_gn_198001-198002.nc.zip)

**Comment by taylor13** [comment]
Thanks.  I reviewed it and didn't see any critical problems.  Just one question.   I noticed that i, j, and k are identified as 1st, 2nd, and 3rd dimensions:
```
        int i(i) ;
                i:units = "1" ;
                i:long_name = "cell index along first dimension" ;
        int j(j) ;
                j:units = "1" ;
                j:long_name = "cell index along second dimension" ;
        int k(k) ;
                k:units = "1" ;
                k:long_name = "cell index along third dimension" ;
        float latitude(i, j, k) ;
```
It is true that i appears first in the C-ordering of indices, but in memory consecutive k-values occupy contiguous memory locations, so wouldn't "k" be considered the first dimension?  [The Fortran ordering makes more sense to me:  latitude(k,j,i) which makes the storage locations and the ordering of the dimensions consistent.  (i.e., the first dimension is stored contiguously.)

I realize this is a detail, but I wonder if instead of saying "cell index along first dimension", we might say "first index value for multi-dimensioned grid-cell longitudes and latitudes"  ?

**Comment by taylor13** [comment]
I've looked at the output again and noticed that the latitude and longitude coordinate values and the vertices are all "float" rather than "double".  After implementing the change discussed in https://github.com/PCMDI/cmor/issues/413 , we should rerun the test and make sure these variables are "double".

Also, I wasn't able to check thoroughly that data values were stored in the order we want them, and we didn't check whether CMOR could handle missing values for vertices.  Could you modify the test code so that latitudes, longitudes are defined as follows  (I've followed the C ordering of dimensions with indexing starting at 0, but the code is closer to a fortran code than a C code; it will need to be rewritten with correct syntax et al.)?
```
time (UNLIMITED)
indi=5
indj=4
indk=3
nvert=5   ! max. number of vertices per grid cell
ntimes=2
nb = 2    ! number of time bounds per time-slice

time(ntimes)
lat(indk, indj, indi)
lon(indk, indj, indi)

bnds_time(ntimes,nb)

vertices_latitude(indk, indj, indi, nvert)
vertices_longitude(indk, indj, indi, nvert)

field(time, indk, indj, indi)

dmiss = 1.d20  ! double precision

! generate 15 deg latitude grid from 82.5 to -82.5
! generate longitude cells 72 degrees wide offset by 6 degrees in each zone
do k=0,indk-1
	do 0=1,indj-1
		do i=0,indi-1

			lat(k,j,i) = 82.5 - k*60 - j*15
			lon(k,j,i) = i *72+ j*6 +k*18 + 36.0

			vertices_latitude(k,j,i,0) = lat(k,j,i) - 7.5
			vertices_latitude(k,j,i,1) = lat(k,j,i)
			vertices_latitude(k,j,i,2) = lat(k,j,i) + 7.5
			vertices_latitude(k,j,i,3) = lat(k,j,i)
			vertices_latitude(k,j,i,4) = dmiss

			vertices_longitude(k,j,i,0) = lon(k,j,i)
			vertices_longitude(k,j,i,1) = lon(k,j,i) + 36.0
			vertices_longitude(k,j,i,2) = lon(k,j,i)
			vertices_longitude(k,j,i,3) = lon(k,j,i) - 36.0
			vertices_longitude(k,j,i,4) = dmiss

		enddo
	enddo
enddo

vertices_latitude(0,0,0,4) =  81.0
vertices_longitude(0,0,0,4) =  1.0
vertices_latitude(indk-1,indj-1,indi-1,4) = -81.0
vertices_longitude(indk-1,indj-1,indi-1,4) = 341.0

do n=0,ntimes-1
	do k=0,indk-1
		do j=0,indj-1
			do i=0,indi-1
				field(n,k,j,i) = i+10*j+100*k+1000*n
			enddo
		enddo
	enddo
enddo
```

**Comment by taylor13** [comment]
When you have a chance, could the above test be run?

**Comment by mauzey1** [comment]
@taylor13 I modified [test_cmor_grid_unstructured_3d_fabi.c](https://github.com/PCMDI/cmor/blob/c8c18c61427f7fe3a429e928c0fd56417967a777/Test/test_cmor_grid_unstructured_3d_fabi.c) with your requested changes.

Here is the data it produces: 
[hfls_Amon_PCMDI-test-1-0_piControl-withism_r3i1p1f1_gn_198001-198002.nc.zip](https://github.com/PCMDI/cmor/files/3437253/hfls_Amon_PCMDI-test-1-0_piControl-withism_r3i1p1f1_gn_198001-198002.nc.zip)

**Comment by taylor13** [comment]
Thanks for running this test.  Looks good, I think.  I agree this issue can now be closed.
I've raised a suggestion  at https://github.com/PCMDI/cmip6-cmor-tables/issues/254 to modify the long-names for the indices.
