### ISSUE TITLE
Should we use cmor 3.3.3 already?

### ISSUE THREAD

**Issue by treerink** [PCMDI/cmor#366]
Hi,

Our ece2cmor3 package which relies on cmor is broken. We wonder whether we should update to the following cmor package: `linux-64/cmor-2018.06.28.master.npy1.14-py27h9ac9557_0` as it is not marked as `main`? Or do we better wait (is it coming in a few days for instance?).

A second question we have: Any idea when the cmor tables will be based on data request 01.00.26? Is this soon or is there always a bit longer delay?

**Comment by durack1** [comment]
@treerink did you need numpy 1.14? If so the latest CMOR 3.3.3 is available, see [here](https://anaconda.org/PCMDI/cmor/labels)

What do you mean by "broken"?

**Comment by treerink** [comment]
In fact I am looking for a "main" package for cmor 3.3.3 with the following dependencies:
hdf5 **1.10**.*, libnetcdf **>=4.4**, python >=2.7 and numpy 1.13.* but I think numpy 1.14 is not a problem.

I tried cmor-2018.06.28.master.npy1.13-py27h9ac9557_0 as its dependencies seem to be alright for us, but could not properly include it in my .yml file.

**Comment by goord** [comment]
Hi, the issue is that it seems that the newly released CMIP6 tables (drq 24) need the library version 3.3.3 to properly work, older versions crash when trying to load certain tables. However, the 3.3.3 release is only built with a 'nightly' label, which makes it difficult for us to include as a dependency (we cannot make conda find those builds...)

**Comment by matthew-mizielinski** [comment]
Can I advise caution with the latest version of the data request/mip tables -- as noted in PCMDI/cmip6-cmor-tables#184 and cmip6dr/Request#82 there is an error in the data request at version 01.00.24 (fixed in 01.00.26) that has propagated into the MIP tables leading to a faulty long name for the longitude coordinate.

**Comment by taylor13** [comment]
I'm on vacation (interrupted by a pathetic reluctance to let things play out without my input), but I might suggest that if you can possibly wait a week or two, the data request specifications will be pretty much finalized (standard names have now been all approved , but one), and any outstanding issues with CMOR3 should be resolved. 
If you can't wait, others will have to advise.

**Comment by treerink** [comment]
Thanks for informing us. Yes we will wait a couple of weeks - also here vacation time soon. In the mean while, fortunately, we have been able to fix `ece2cmor3` by using a cmor-3.3.3 "nighly" version. For us, because ece2cmor also relies on conda cdo (which requieres hdf5 1.10), it simplifies a lot that the latest cmor 3.3.3 packages depend on libnetcdf 4.6. So we are happy if a "main" version will appear in a couple of weeks. Moreover, as soon the cmor tables are based on **data request version 01.00.26** we get really out of trouble, and will have matching versions again for the various applications of our tool.

**Comment by doutriaux1** [comment]
@treerink I will release the new tables on wednesday (most likely, but maybe earlier). Any chance you can send us a small (python?) script that reproduces you issue, so I can add it to the test suite?

**Comment by treerink** [comment]
@goord Gijs do you think we can provide a kind of lookup loop which covers typically our cmor table - cmor library use? Because running ece2cmor3 tests won't be handy I guess, too much other dependencies and development dependency.

**Comment by goord** [comment]
Hi, the error occurs when loading the grids table under cmor-3.3.2 (python wrapper):
```
import cmor
cmor.setup(...some metadata...)
cmor.load_table("CMIP6_grids.json")
```
The code above crashes with a message:
```
Error: Reading table grids: axis name: 'alevhalf' for variable: 'a_half_bnds' is not defined in table. Table defines dimensions: 'alevhalf' for this variable
```
for the newest version of the cmip6-cmor-tables

**Comment by doutriaux1** [comment]
@treerink @goord thanks for this please also try to cmor available currently from conda-forge channel
```
conda create -n cmor -c conda-forge cmor
```

**Comment by doutriaux1** [comment]
@goord the above snippet seems to work I think we can close this. Feel free to re-open if necessary.

**Comment by treerink** [comment]
Hi, thanks for helping and solving. 

With the **nightly built** `linux-64/cmor-2018.06.28.master.npy1.14-py27h9ac9557_0` we are able to run our package now with the updated tables. Before closing this issue I just wondered if there will be a **main built** of this one (with hdf5 1.10 and netcdf 4.6) soon? If not, do you recommend that we use a more recent  **nightly built** or doesn't matter?

**Comment by doutriaux1** [comment]
I recommend you use the latest nightly, always.

**Comment by doutriaux1** [comment]
it's the same api for 14 and 15. I'm not sure about conda magic pinning inside. But both work 14 or 15.

**Comment by treerink** [comment]
Ok thanks
