### ISSUE TITLE
Tag CMOR 3.4.0

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#369]
- [x] Change configure.ac to `3.4.0` and rerun `autoconf`.  
- [x] Verify that optimization is disable from setup.py.in.
- [x] Review all issue lists and close all redundant issues (move unresolved issues to next milestone)
- [x] Validate version info is correctly written (CMOR version should be `3.4.0`)
- [x] Validate data_specs_version written ([`01.00.XX`](https://www.earthsystemcog.org/projects/wip/drq_release_01_00_27))
- [x] Validate that tables cmor_version is set to 3.4
- [x] Increment `CMOR 3.x.x` in INSTALL file to `CMOR 3.4.0`
- [x] Run all tests
- [x] Update `master` branch
- [x] Create `3.4.0` tag point (git tag -a <label> <commit> -f)
- [x] Run createCMIP6CV.py from cronjob to get the latest and greatest CV update.
- [x] Tag `3.4.0` in [PCMDI/cmor](https://github.com/PCMDI/cmor)
- [x] Tag `3.4.0` in [PCMDI/cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables)
- [x] Tag `3.4.0` in [PCMDI/xml-cmor3-database](https://github.com/PCMDI/xml-cmor3-database)
- [x] ~~Tag `3.4.0` in [WCRP-CMIP/CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs)~~
- [x] Set `3.4.0` tag point for PCMDI/cmor repo
- [x] Create conda-forge version 3.4.0 
        * https://github.com/cdat/cmor-feedstock/
        * https://github.com/conda-forge/cmor-feedstock/
- [x] Test cmor 3.4.0
        * conda create -n cmor3.4.0 -c conda-forge  cmor
- [x] Update conda env export > cmor_3.4.0.yaml file
- [x] Prepare and publish release notes to [website](http://cmor.llnl.gov) (e.g. [CDAT](http://cdat.llnl.gov/changelog.html) linked off the [release page](https://github.com/CDAT/uvcdat/releases/))
- [x] Create new Release `3.4.0` in [PCMDI/cmor](https://github.com/PCMDI/cmor)
- [x] Update [website](http://cmor.llnl.gov) so correct tag points (`3.4.0`) are noted for build notes
- [ ] Create PDF from website. (use jekylll build).  post new tag to cmor_documentation.
- [x] Obtain Zenodo DOI (not needed linked to latest release automatically)
- [x] Update `README.md` with updated `Stable version` info (should be `3.4.0`) and updated `Zenodo DOI` info
- [x] Increment `cmor-3.x.x` to `3.4.0` (odd minor [major.minor.patch] number indicating development version)
- [ ] Email mailing lists: `cmor@lists.llnl.gov, wgcm-wip@wcrp-climate.org, CDNOT@jiscmail.ac.uk, CMIP6-DATAREQUEST@JISCMAIL.AC.UK` including the text: `Please pass on this email to anyone you know who plans to prepare CMIP6 model output for the archive.` 
       * https://zenodo.org/record/61946#.V9b3z9Ey290

**Comment by durack1** [comment]
@doutriaux1 the `Tag 3.4.0 WCRP-CMIP/CMIP6_CVs` is now redundant as we have implemented the repo versioning independently, so it's been struckthrough above

**Comment by mauzey1** [comment]
@doutriaux1 How do we create the PDF version of the website?  Running `jekyll build` doesn't update pdf/mydoc.pdf.

**Comment by taylor13** [comment]
@mauzey1 @doutriaux1  What is the status of this?  Is the PDF version now being generated?

**Comment by taylor13** [comment]
@mauzey1 @doutriaux1  What is the status of this?  Is the PDF version now being generated?

**Comment by mauzey1** [comment]
I wasn't able to get the PDF to generate.

Looking at this [script](https://github.com/PCMDI/cmor3_documentation/blob/master/pdf-mydoc.sh), it looks like you need a program called Prince to generate the PDF.

Prince can be found at https://www.princexml.com/

@dnadeau4 Do you have this program?

**Comment by mauzey1** [comment]
@taylor13 @dnadeau4 I was able to create an updated version of the PDF.  It will be uploaded with the other changes to the documentation for CMOR 3.5.0.

https://github.com/PCMDI/cmor3_documentation/pull/69

I will close this issue now.
