### ISSUE TITLE
pep8 cmor code

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#37]

**Comment by dnadeau4** [comment]
I cannot pep C source code, I can try to pep8 all the tests, but they are 109 files...

**Comment by ehogan** [comment]
You could try [autopep8](https://pypi.python.org/pypi/autopep8)? I used it recently and it did a pretty good job :)

**Comment by doutriaux1** [comment]
@dnadeau4 pep8 is for python. @ehogan autopep8 works great. use `-ai` option it does a really good job. Just be careful of long line with string formating using `%` bcause `autopep8` will split these onto many lines and then the ending ` % (...)` will not be able to match the number of values.

**Comment by durack1** [comment]
@dnadeau4 this seems to be a fairly trivial step - want to assign it to `3.1.2`?

**Comment by dnadeau4** [comment]
@durack1 I used autopepe8 with CDMS2 and loved it. So yes I will do it for 3.1.2

**Comment by dnadeau4** [comment]
@dnadeau4  important!

**Comment by durack1** [comment]
@dnadeau4 another `3.2.0`er?

**Comment by dnadeau4** [comment]
autopep8 was done on tests,  I am working slowly on the C code.

**Comment by durack1** [comment]
@dnadeau4 should this be moved to the [3.2.4 milestone](https://github.com/PCMDI/cmor/milestone/12)?
