### ISSUE TITLE
license attribute again

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [PCMDI/cmor#372]
I notice an error in license attribute in this version of tables and PrePARE. I remember a similar one logged in here https://github.com/PCMDI/cmor/issues/248

:license = "CMIP6 model data produced by NOAA-GFDL is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file). The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." ;

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: The attribute "license" could not be validated.
! The current input value is "CMIP6 model data produced by NOAA-GFDL is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file). The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law." which is not valid
! Valid values must match the regular expression:
! 	["^CMIP6 model data produced by .* is licensed under a
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Are we missing something crucial here?

**Comment by doutriaux1** [comment]
@aradhakrishnanGFDL good catch, @dnadeau4 made some change to our cronjob and apparently we have a typo on the license now. I'll try to fix this right away. Will let you know.

**Comment by doutriaux1** [comment]
@aradhakrishnanGFDL ok I updated master of cmip6-cmor-tables, you should be good to go now. Thanks again for spotting this and apologies for the inconvenience this created.

**Comment by aradhakrishnanGFDL** [comment]
NP. Thank you @doutriaux1 for the quick fix! Works fine now.

**Comment by taylor13** [comment]
Please close this issue.
