### ISSUE TITLE
invalid path out_names_tests.json

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [PCMDI/cmor#373]
https://github.com/PCMDI/cmor/blob/master/LibCV/PrePARE/PrePARE.py#L371

This file seems to be expected for a successful run. Is that correct? Please let us know what we might be missing. 

/cmip6_cv/PrePARE/out_names_tests.json

Traceback (most recent call last):
  File "/home/pcmdi/.conda/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 898, in <module>
    main()
  File "/home/pcmdi/.conda/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 859, in main
    errors += sequential_process(source)
  File "/home/pcmdi/.conda/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 710, in sequential_process
    checker.ControlVocab(ncfile, variable)
  File "/home/pcmdi/.conda/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/PrePARE.py", line 484, in ControlVocab
    out_names_tests = json.loads(open(os.path.join(prepare_path, 'out_names_tests.json')).read())
IOError: [Errno 2] No such file or directory: '/home/pcmdi/.conda/envs/cmor/lib/python2.7/site-packages/cmip6_cv/PrePARE/out_names_tests.json'

**Comment by aradhakrishnanGFDL** [comment]
In the GitHub repo, the file seems to exist. When I did the installation from anaconda, I'm not sure its available. What route of installation is recommended? Can I just use this GitHub repo ..might be easier since we only use PrePARE bits.

**Comment by doutriaux1** [comment]
per @dnadeau4 

```
Aparna

IPSL in France added a lot of new arguments to PrePARE and I made sure that it was back compatible with the previous version.  
They add multiprocessing so that PrePARE can process many files a the same time. I used "Cdunif" directly to make things fast for them.


For example --max-processes will triggered parallelism.
PrePARE --max-processes -1  Tables CMIP6
Also "--all" shows all file status including "SUCCESS".

The file out_name_tests.json is used for duplicate variable between 2D and 3D and how to trigger some tests.  They are in the CMOR3 package, but can be found here:  https://github.com/PCMDI/cmor/blob/master/LibCV/PrePARE/out_names_tests.json.   I really appreciate the help from IPSL on solving this issue.
```

**Comment by doutriaux1** [comment]
@nadeau4 i think this is due to the prepare pr mergw, guillaume is using the egg resource thing i think. will take a look at the best way to fix this.

**Comment by doutriaux1** [comment]
i think we niw need to use something like bellow
```python
import pkg_resources

DATA_PATH = pkg_resources.resource_filename('<package name>', 'data/')
DB_FILE = pkg_resources.resource_filename('<package name>', 'data/sqlite.db')
share improve this answer
```

**Comment by aradhakrishnanGFDL** [comment]
CMOR conda nightly build doesn't have this problem
