### ISSUE TITLE
branch_time_in_parent global attribute

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [PCMDI/cmor#386]
Hi @doutriaux1 

If there is no parent experiment, is it correct that branch_time_in_parent can be omitted or set to the 0.  
per https://www.earthsystemcog.org/site_media/projects/wip/CMIP6_global_attributes_filenames_CVs_v6.2.6.pdf

Or, is this attribute mandatory for PrePARE? We ask because we ran into an issue with this recently (CIM expects omission I think)

https://github.com/PCMDI/cmor/blob/master/LibCV/PrePARE/PrePARE.py#L449

**Comment by doutriaux1** [comment]
@aradhakrishnanGFDL this is definitely a question for @taylor13, sorry about that. I think @taylor13 might be off today.

**Comment by doutriaux1** [comment]
@aradhakrishnanGFDL I chit-chatted with @durack1 about this. Our expectation is that it should. Please let me know if it doesn't.

**Comment by taylor13** [comment]
This is the same bug as identified 5 days ago in https://github.com/PCMDI/cmor/issues/375
If no parent, CMOR/PrePARE should be consistent with  https://www.earthsystemcog.org/site_media/projects/wip/CMIP6_global_attributes_filenames_CVs_v6.2.6.pdf

**Comment by doutriaux1** [comment]
@taylor13 thanks. Ok so it will be fixed shortly (hopefully today)

**Comment by aradhakrishnanGFDL** [comment]
@doutriaux1 A colleague of mine ran into an error when this attribute was omitted in the netCDF file (PrePARE on esgf). 
But, in the version of PrePARE I installed from conda (pcmdi/label/nightly) yesterday, I do not run into this error ..i.e. no complaints if the attribute  branch_time_in_parent is missing. In my test case, there is no parent. So, this seems like what we'd like at this time. I am still trying to understand why my colleague (also  Guillaume #375) may have run into this issue..checking versions and such so I am not missing anything
