### ISSUE TITLE
sending climo time axis to non climo var leads to seg fault

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#39]
When using uvcdat clt and computing annualcycle
trying to rewrite it using "clt" from AMon table
leads to seg fault.

**Comment by taylor13** [comment]
clt in Amon is no different (in terms of dimension information) than any 
other of the 2-d fields there (e.g., pr or tas), so do you also get a 
seg fault with those other fields?

**Comment by doutriaux1** [comment]
I will try. The issue is that I'm sending a "time2" dimension instead of "time" at the very least we should catch this.

**Comment by durack1** [comment]
@doutriaux1 @dnadeau4 should this issue be closed? And marked as a `wontfix` I can't imagine that `2.9.3` will ever see the light of day

**Comment by dnadeau4** [comment]
Karl and I have started to discuss about this.  We will work on climatology and z-factor in the in 3.2.0 or 3.2.1.

**Comment by dnadeau4** [comment]
Can we finalize the zfactor for `time1,` time2`, `time3` and `time4` dimension.  

## CMIP6 time definition. 
* time1: same as time, but no bounds necessary (instantaneous)
* time2:  Climatology
* time3: Found in E1hrClimMon (same as time2, but defined as diurnal cycle)

**Comment by dnadeau4** [comment]
@doutriaux1 Can you send me a example?

**Comment by durack1** [comment]
@dnadeau4 should this be moved to the [3.2.4 milestone](https://github.com/PCMDI/cmor/milestone/12)?

**Comment by dnadeau4** [comment]
Fix in 3.2.5
