### ISSUE TITLE
Shouldn't include/cmor_locale.h be in .gitignore?

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#392]
I've noticed that the file generated by include/cmor_locale.h.in is being committed every time it gets modified.  This header file contains the prefix path used to install CMOR.

**Comment by doutriaux1** [comment]
@mauzey1 yes, I keep meaning to do it. Yes please remove https://github.com/PCMDI/cmor/blob/master/include/cmor_locale.h from the repo and add it to .gitignore
