### ISSUE TITLE
PrePARE has troubles with experiments having multiple activities

### ISSUE THREAD

**Issue by senesis** [PCMDI/cmor#394]
According to https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json, experiment piClim-aer has  : 
`"activity_id":[ "RFMIP", "AerChemMIP" ]`

According to document [CMIP6 Global Attributes, DRS, Filenames, Directory Structure, and CV’s](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit), in CMIP6, 
> multiple activities may now be listed separated by single spaces.
with such an example :
> “LS3MIP LUMIP” 

However, PrePARE (as delivered with CMOR-3.3) report that error 
`
! Error: Your input attribute "activity_id" with value "RFMIP AerChemMIP" is not set properly and  has multiple possible candidates defined for experiment_id "piClim-aer".
`
IMHO, PrePARE should accept that activity_id value

**Comment by taylor13** [comment]
I think the relevant code starts at line 1423 of https://github.com/PCMDI/cmor/blob/master/Src/cmor_CV.c .  Since for experiment piClim-aer, @senesis apparently correctly specified "RFMIP AerChemMIP" for activity_id (according to the error message), PrePARE should not have thrown an error.

**Comment by senesis** [comment]
It would be useful to get an idea of when a fixed version of PrePARE will  be available : even if centers could avoid a delay for publishing by modifying the list of activities/MIP to have one single member, such a solution would be detrimental to data discovery on the ESGF; so, we have to make a trade-off between delaying and normal data discovery

**Comment by dnadeau4** [comment]
@senesis if you add the following experiment it should pass:
```"activity_id":[ "RFMIP", "AerChemMIP",``` ```"RFMIP AerChemMIP" ]```

@durack1 can you add every permutation acceptable in your `WCRP` file?
https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L6656

**Comment by dnadeau4** [comment]
@senesis prepare use [CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L7600) which is built from the [CMIP6_experiment_id.json]( https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_experiment_id.json#L6656) file above.

**Comment by senesis** [comment]
As far as I understand, proposal by @taylor13 above implies a change in PrePARE code, and some time to be included in a delivered CMOR package. For now, we will use the proposal of [#394 (comment) ](https://github.com/PCMDI/cmor/issues/394#issuecomment-416363934) to allow for going on publishing

**Comment by taylor13** [comment]
Yes, if you change the  activity_id listed for the experiment with 2 activities to: 
```
"activity_id":[ "RFMIP AerChemMIP" ]
```
PrePARE should not raise an error.  (I Don't think there is any reason to include the other 2 items in the list shown in https://github.com/PCMDI/cmor/issues/394#issuecomment-416363934 )

**Comment by senesis** [comment]
For information : for the table derived from DR01.00.21, the full list of experiments with such an issue is :
piClim-aer, piClim-control ssp370, dcppC-forecast-addPinatubo, land-hist

**Comment by taylor13** [comment]
It appears that folks are still having problems when activity_id can include multiple activities.  Here is a communication from @glevava: 
```
I'm back about the multiple activity_id allowed by the CMIP6_CV.json for some MIPs.
I'm checking some "piClim-control" files for RFMIP protocol at IPSL, PrePARE returns me 
an error about the activiy_id for each file:

<----------

! C Traceback:
! In function: _CV_checkExperiment
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Your input attribute "activity_id" with value 
! "RFMIP AerChemMIP" is not set properly and 
! has multiple possible candidates 
! defined for experiment_id "piClim-control".
! 
!  See Control Vocabulary JSON file.(/ccc/work/cont003/gencmip6/gencmip6/cmip6-cmor-tables/Tables/CMIP6_CV.json)
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!! 

---------->

Moreover, esgprep fails to built the directory structure as it finds several values for the
 <activity_drs> facet.

I don't remember exactly what should be the process to check and process the activity_id 
global attribute. I just remember that the publisher is able to deduce the "activity_drs" as 
the first value of the "activity_id" list for Solr facet search. Should we do the same for 
PrePARE and esgprep?
```
@glevava could you please check that you are using a recent version of "CMIP6_CV.json" .  In recent versions of that file at least, the list of activities appears as a single string (e.g., "RFMIP aerChemMIP", *not* as a comma-separated list of strings as it did in early versions of this file.  That was supposed to fix the problem. 

Also, is the problem with "building the directory structure" in PrePARE, or only esgprep?

thanks.

**Comment by glevava** [comment]
@taylor13 I confirm I don't have any issue if a merge both activity_ids into one string in the CMIP6_CV.json if the cmor table directory.
So it requires to change the CMOR CMIP6_CV.json translation from the WCRP json files for all DR tags.

The side-effect of the directory structu built by esgprep as been fixed in the latest release. Now esgprep automatically pickup the first item in the activity_id string (space-separated) and use it as the "activity_drs" value.
