### ISSUE TITLE
PrePARE aborts if source_type is incorrect

### ISSUE THREAD

**Issue by aradhakrishnanGFDL** [PCMDI/cmor#396]
@doutriaux1  I had a wrong source_type in one of my test files. PrePARE rightly identified that, but doesn't get past that error to check errors in other section as it normally would do for something.

I believe this section prints an "Abort" message and doesn't go further to display the error count, etc.
  self.errors += cmip6_cv.check_sourceID(table)
(sequential processing here)
Example

C Traceback:
! In function: _CV_checkSourceType
! called from: _CV_checkExperiment
!

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You source_type attribute contains invalid source types
! Your source type is set to "AOGCM".  The required source types
! are "AGCM " and possible additional source types are "AER CHEM BGC "
! Check your Control Vocabulary file "/home/a1r/gitlab/prepare/cmip6-cmor-tables/Tables/CMIP6_CV.json".
!
!
!!!!!!!!!!!!!!!!!!!!!!!!!

Abort

**Comment by taylor13** [comment]
Are you sure in other cases when PrePARE encounters an error, it continues on to check other things before aborting rather than aborting immediately?

**Comment by doutriaux1** [comment]
@mauzey1 do you mind looking into this. @taylor13 and I think it's probably ok, but I know there's a way to tell CMOR to ignore errors. Maybe we can add an option to prepare to run CMOR in "no error" mode and get all the possible errors to the user. @dnadeau4 what do you think?

**Comment by mauzey1** [comment]
@doutriaux1 @aradhakrishnanGFDL 
When tried reproducing the error using the example in #395, I was able to repeat the issues of #395 and #396 using a nightly conda build of CMOR I installed last week.  However, when I upgraded the nightly conda build the abort message and hanging went away even though I still get error messages about source type.

When I tried this with the regular conda install of CMOR I got the error message mentioned in #373.

**Comment by doutriaux1** [comment]
@mauzey1 that is good news, that means that I might have **fixed** it with the sigint change on Monday. @aradhakrishnanGFDL you might want to try the latest cmor from nightly then,

**Comment by aradhakrishnanGFDL** [comment]
Sure, I will try it out ASAP

**Comment by aradhakrishnanGFDL** [comment]
Pulled in latest changes. Now, there is no hanging behavior and the CMOR errors are "all" printed.

**Comment by durack1** [comment]
@aradhakrishnanGFDL excellent, this is great news - thanks for the feedback, closing
