### ISSUE TITLE
inconsistency between data request and CMOR tables

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#406]
Unless I've misinterpreted something, this issue needs to be addressed immediately (because the CMOR tables don't seem to accurately reflect what's in the data request):

It appears that the long_name for some variables is incorrectly recorded in the CMOR tables.  The long_name should be the same as the "title" of the variable in the data request.  For example, the "title" of O3ste in table  AERmon  of data request 01.00.28b1  is "Stratospheric Ozone Tracer Volume Mixing Ratio" (see http://clipc-services.ceda.ac.uk/dreq/beta/u/218a6b28-8995-11e6-b63d-5404a60d96b5.html), but the CMOR table has long_name = "Ozone volume mixing ratio" (see https://github.com/PCMDI/cmip6-cmor-tables/pull/209/files).  

Again, this is a "must correct *now*", high priority issue.

I might check first whether something went wrong in the recent beta testing of release 28, and some of the CMOR tables created from 01.00.28b1 were skipped and old versions used instead.

**Comment by doutriaux1** [comment]
@mauzey1 please reach out if you need help with this.

**Comment by taylor13** [comment]
@mauzey1 @doutriaux1   This problem is apparently on Martin's end (i.e., in the data request, not CMOR's handling of it):  Martin said:
```
(3) OK, I'd made the change in the "var" record, to "Stratospheric Ozone Tracer Volume
 Mixing Ratio" (http://clipc-services.ceda.ac.uk/dreq/beta/u/218a6b28-8995-11e6-b63d-5404a60d96b5.html ), but not in the CMORvar record ... I'll bring the CMORvar 
record into line. The aim is to make it clear that this is "ozone tracer", not "ozone".
```
I don't think we need to do anything at this time, but let's leave this issue open until the data request has been corrected.

**Comment by taylor13** [comment]
@martinjuckes :  I note that now o3ste has the correct long_name in release 01.00.28.  Thanks.
Have you checked whether in the rest of the archive a change in the "var" record has been changed but not in the CMORvar record?  Could you check the consistency of all "var" and "CMORvar" records to eliminate in general errors of this kind?  Thanks.

**Comment by taylor13** [comment]
Let's leave open, but no action is required at this time.
