### ISSUE TITLE
area: areacello OR areacella

### ISSUE THREAD

**Issue by goord** [PCMDI/cmor#407]
There are a few (sea ice) variables with the above cell_measures attribute. Can you explain whether we need to do something in particular when cmorizing these variables (e.g. choose on e of the above)? Now we end up with "areacello OR areacella" as netcdf metadata, which is rejected by the PrePARE tool...

**Comment by taylor13** [comment]
The CMOR tables are generated from the data request where some of the sea ice variables in release 01.00.27 (and earlier) have the wrong cell_measures.  This is discussed at https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/158 and https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/252.  I am hopeful that the needed corrections will be made to release 01.00.28 of the data request.  Once that happens the new CMOR tables can be corrected.  I think that might happen in the next few weeks, but it is out of our control here at PCMDI.

**Comment by taylor13** [comment]
It appears that at least in release 01.00.28 this problem has been fixed.
