### ISSUE TITLE
Hourly output time axis creation

### ISSUE THREAD

**Issue by tommibergman** [PCMDI/cmor#410]
I am trying to implement CMORizing hourly output and running cmor.axis from python for one year of data I get the following error:

> Error: approximate time axis interval is defined as 86400.000000 seconds (1.000000 days), for value 8765 we got a difference of 3599.999999 seconds (0.041667 days), which is 95.833333 % , seems too big, check your values

I do not understand what is wrong? Same code creates daily and monthly axes without errors.

**Comment by doutriaux1** [comment]
You are probably using tables created for **monthly** data. The 86400 is stored in the table. CMOR checks your frequency and noticed that is **hourly** hence the error. @taylor13 any hourly tables.

**Comment by durack1** [comment]
@tommibergman there are quite a number of `hourly` tables, see [https://github.com/PCMDI/cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables)

**Comment by tommibergman** [comment]
Thanks. Although, I found out that the interval for AERhr table was wrong (1.0). I made an issue on CMIP6-tables github.

**Comment by doutriaux1** [comment]
Thanks the cmip6 table is the correct repo to  report this. Closing here but linking to your report on cmip6 tables repo. See: https://github.com/PCMDI/cmip6-cmor-tables/issues/211
