### ISSUE TITLE
raise ValueError("No JSON object could be decoded")

### ISSUE THREAD

**Issue by iaplasg** [PCMDI/cmor#417]
When I tried to PrePARE to verify the data, an error occurred."IOError: [Errno 2] No such file or directory:out_names_tests.json',then I run" wget https://github.com/PCMDI/cmor/blob/master/LibCV/PrePARE/out_names_tests.json"to download this file to the directory,  then a newer error occurred:" File "/usr/local/conda/envs/esgf-pub/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded") "

who have any idea?

**Comment by iaplasg** [comment]
This is my command "PrePARE --table-path cmip6-cmor-tables/Tables/ /esg/data/CMIP6/CMIP/CAS/FGOALS-f3-L/amip/"

**Comment by doutriaux1** [comment]
@iaplasg you probably want to wget from: https://raw.githubusercontent.com/PCMDI/cmor/master/LibCV/PrePARE/out_names_tests.json

The URL you mentioned is the full html page, not a json file.

**Comment by iaplasg** [comment]
@doutriaux1 Great! I have passed the test successfully,Thank you
