### ISSUE TITLE
Longitude Bounds-Check and Regional Datasets

### ISSUE THREAD

**Issue by sfinkens** [PCMDI/cmor#418]
The longitude bounds check for regional datasets (where the longitude does not cover 0-360, but only a subset) fails with the following error message:

```
C Traceback:
In function: cmor_check_monotonic
! called from: cmor_treat_axis_values
! called from: cmor_axis
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: axis longitude (table: obs4MIPs_Amon) has bounds values that leave gaps
! (index 2600): 64.975000, 65.025000, 294.975000
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

Minimal example:
```python
import cmor
import numpy as np

# Create sample data
lons = np.round(np.arange(-65, 65 + 0.05, 0.05, dtype='f8'),
                decimals=2)
bnds = np.round(np.vstack((np.arange(-65.025, 65.025, 0.05),
                           np.arange(-64.975, 65.075, 0.05))).transpose(),
                decimals=3)

assert np.all(np.logical_and(lons >= bnds[:, 0],
                             lons <= bnds[:, 1]))
assert np.all(bnds[1:, 0] == bnds[:-1, 1])

# Initialize CMOR
cmor.setup(inpath='/cmsaf/cmsaf-ops3/obs4mips/tables')
cmor.dataset_json('obs4MIPs_user_input.json')
cmor.load_table('obs4MIPs_Amon.json')

# Create CMOR axis
cmor_ax = cmor.axis(table_entry='longitude',
                    units='degrees_east',
                    length=len(lons),
                    coord_vals=lons,
                    cell_bounds=bnds)
```
For the latitudes this snippet works just fine.

**CMOR Version:** 3.3.3

**Comment by doutriaux1** [comment]
I see. Looks like CMOR puts coordinates back between 0 and 360 first and then checks for monotonic.
@taylor13 should check for monotonic first, then change values to be 0/360? Does it even make sense in that case? @sfinkens I suggest you edit your table and change the longitude coordinate range from 0/360 to -180, 180. If it's allowed by obs4mips, Pinging @gleckler1 here.

**Comment by durack1** [comment]
@doutriaux1 this seems to be one of the first instances of problems with regional.. It's going to get more usage with regional data in obs4MIPs

**Comment by doutriaux1** [comment]
@durack1 @gleckler1 it might make sense to completely turn off lon range in tables for this variables then. Still pinging @taylor13 about checking monotonic before changing lon to correct range. But even if we did that the output would lok *funky*

**Comment by sfinkens** [comment]
Thanks for the workaround @doutriaux1, works fine!

**Comment by sfinkens** [comment]
@gleckler1 @taylor13 Is longitude range -180/180 allowed?

**Comment by taylor13** [comment]
This is a problem with the obs4MIPs_coordinate.json file and the discussion should be moved to: https://github.com/PCMDI/obs4MIPs-cmor-tables/issues/163 .  I am therefore closing this issue on the CMOR repo.
