### ISSUE TITLE
PrePARE: out of date compared to cmor version 3.4

### ISSUE THREAD

**Issue by h-dh** [PCMDI/cmor#427]
This is an issue to the conda cmor package. 
I guess, it is broken because the version legs behind the current cmor_version 3.4 .

I just installed PrePARE by
   conda create -n cmor -c conda-forge  cmor

and additionally installed the required cmor tables by
   git clone https://github.com/PCMDI/cmip6-cmor-tables.git

After the addition of file 'out_names_tests.json' by hand (issue #400 still unresolved), a routinely run of PrePARE 

/path_0/miniconda2/envs/cmor/bin/PrePARE 
   --variable tas 
   --table-path /path_1/cmip6-cmor-tables/Tables/CMIP6_day.json 
   /path_2/CMIP6/CMIP/IPSL/IPSL-CM6A-LR/1pctCO2/r1i1p1f1/day/tas/gr/v20180727/tas_day_IPSL-CM6A-LR_1pctCO2_r1i1p1f1_gr_18500101-19991231.nc

issued (among others) these unexpected items:

Error: Table  is defined for cmor_version 3.400000, this library version is: 3.3.2, 3.300000

CMOR Warning: Can't open/read JSON table /path/tables/cmip6-cmor-tables/Tables/CMIP6_day.json

The difference of CMIP6_day.json between the current and previous version is just:
<         "cmor_version": "3.4", 
---
>         "cmor_version": "3.3", 

<         "table_date": "14 December 2018", 
---
>         "table_date": "13 December 2018", 

BTW.: PrePARE runs fine for the above example with "cmor_version": "3.3"

Best regards,

H.-D. Hollweg, DKRZ

**Comment by doutriaux1** [comment]
@h-dh you're right I don't think the table need to be restricted to cmor 3.4. @taylor13 @mauzey1 we should probably relax that constraint. Also @mauzey1 shouldn't cmor 3.4 be up on conda-forge?

**Comment by mauzey1** [comment]
CMOR 3.4.0 is now on conda-forge.  Can we close this issue now?
