### ISSUE TITLE
time coordinate mis-match error for variable ps in 6hrLev table

### ISSUE THREAD

**Issue by prajeeshag** [PCMDI/cmor#432]
I am trying to cmor 6 hourly instantaneous model level variables in hybrid vertical coordinate. I am getting this error while defining variable 'ps'

Error: You defined variable 'ps' (table 6hrLev) with axis id 'time1' which is not part of this variable according to your table, it says: ( time latitude longitude )

However, from the CMIP6_6hrLev.json says 'ps' has dimension time1.

**Comment by taylor13** [comment]
@prajeeshag Just to be sure, could you confirm that you think CMOR is working correctly in this case?

**Comment by prajeeshag** [comment]
yes, its working. I changed the variable name to ps1, then it worked. 
thank you and sorry for not checking it thoroughly..

**Comment by taylor13** [comment]
Thanks.
