### ISSUE TITLE
Deflate level

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#438]
Hi,
there are about 700 variables which have an attribute `deflate_level : 0` in the DReq, for example `sivol` in `SImon`.
Could we integrate this into the MIP-tables so that CMOR is able to use the requested deflate level?
Best regards,
Fabi

**Comment by durack1** [comment]
@wachslyon I don’t believe a deflate level of 0 is ideal here. @martinjuckes does this deflate level have some logic behind it? With these variables that are mostly missing (globally) deflation will work really well.

@taylor13 @mauzey1 ping

**Comment by wachsylon** [comment]
We already found a file (e.g. `hus_Emon_IPSL-CM6A-LR_historical_r8i1p1f1_gr_185001-200912.nc`) in ESGF which is not compliant with the attribute `deflate_level : 0` requested by the DReq . Therefore, I suggest to remove the attribute from the DReq.

**Comment by durack1** [comment]
@wachsylon for dreq requests, these belong in a different repo - this repo is for the CMOR package.

dreq repo is https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions

As an FYI, the tables CMOR uses for cmip6 are at https://github.com/PCMDI/cmip6-cmor-tables/

**Comment by durack1** [comment]
@wachsylon @mauzey1 @taylor13 this issue is ready for closure unless there are any unresolved questions 

@martinjuckes ping

**Comment by taylor13** [comment]
Yes, I agree.  The CMOR "deflate" directive does not appear in the tables, so @wachsylon must be getting it directly from the data request, so this issue should be raised there (as Paul noted).  
By the way, @mauzey1, how does one set deflation and similar compacting parameters when running CMOR?

**Comment by doutriaux1** [comment]
@taylor13 according to: https://github.com/PCMDI/cmor/blob/master/Src/cmor_variables.c#L1909 it is intialized to 1/0 (deflate/defalte level) and then overwritten by table. @dnadeau4 is that still correct?

**Comment by mauzey1** [comment]
@taylor13 Deflation parameters are passed to CMOR using the function cmor_set_deflate
https://cmor.llnl.gov/mydoc_cmor3_api/#cmor_set_deflate

**Comment by wachsylon** [comment]
> it is intialized to 1/0 (deflate/defalte level) and then overwritten by table

Since there is no attribute in the tables, CMOR cannot read it from there.

> Yes, I agree

...that the attribute should be removed from DReq?

> for dreq requests, these belong in a different repo

I think that this topic covers all three repos: MIP-tables, CMOR and DReq.
However, we can move the discussion there.

**Comment by wachsylon** [comment]
see PCMDI/CMIP6dreq#5

**Comment by durack1** [comment]
@wachsylon just repeating myself, the DReq repo is https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions whereas the PCMDI/CMIP6dreq repo has not been touched for ~3 years and should be purged

**Comment by wachsylon** [comment]
OK thank you, sorry for that.
Instead,
see cmip6dr/CMIP6_DataRequest_VariableDefinitions#383

**Comment by durack1** [comment]
@wachsylon great, thanks for that.. We'll purge this duplicate repo (PCMDI/CMIP6dreq#5) as it's no longer supported.

**Comment by taylor13** [comment]
@doutriaux1 @mauzey1 I'm confused by what CMOR is doing.  From the discussion at https://github.com/PCMDI/cmor/issues/403#issue-361527528, I thought we determined that by default 
```
    cmor_vars[var_id].shuffle = 0;
    cmor_vars[var_id].deflate = 1;
    cmor_vars[var_id].deflate_level = 1;
```
which turns on deflation at level 1.  Of course the user can override this default by invoking cmor_set_deflate.  But Charles said above (https://github.com/PCMDI/cmor/issues/438#issuecomment-463278968) that CMOR sets deflate level to 0.   Can someone explain?

**Comment by mauzey1** [comment]
Here is the code linked in https://github.com/PCMDI/cmor/issues/438#issuecomment-463278968, https://github.com/PCMDI/cmor/blob/master/Src/cmor_variables.c#L1909

This is from the function cmor_init_var_def(), which initializes the variables before loading their attributes from a table.
https://github.com/PCMDI/cmor/blob/dc7562d984dd09c317ccbf681b08f2c6ba7d4242/Src/cmor_variables.c#L1908-L1910

The section from https://github.com/PCMDI/cmor/issues/403#issue-361527528 comes from the function cmor_reset_variable(), which is called when CMOR is set up, when a variable is closed, or when CMOR is closed.
https://github.com/PCMDI/cmor/blob/dc7562d984dd09c317ccbf681b08f2c6ba7d4242/Src/cmor.c#L720-L722
Both functions set shuffle=0, deflate=1, and deflate_level=1.

**Comment by taylor13** [comment]
O.K. That's good.  I'll close this, since there doesn't seem to be a problem with CMOR.
