### ISSUE TITLE
netcdf output configuration

### ISSUE THREAD

**Issue by bnlawrence** [PCMDI/cmor#44]
I believe we've decided that we should be able to use netcdf4 and compression, so being able to configure CMOR to do this would be more than helpful (although it's not a done deal until after various WGCM and WIP perambulations).

**Comment by doutriaux1** [comment]
@bnlawrence you can already do this in CMOR. These parameters are controlled from the tables:
https://github.com/PCMDI/cmor/blob/master/Test/speed_test_table_A#L621-L632
@dnadeau4 lets make sure this is not lost in the new tables.

**Comment by dnadeau4** [comment]
Good to know!  I'll keep that in mine for the CMIP6 tables.

**Comment by dnadeau4** [comment]
I created a new API which allows compression.  cmor.set_deflate(myvars[0], shuffle, 1, level)
[cmor_speed_and_compression_03.py](https://github.com/PCMDI/cmor/blob/master/Test/cmor_speed_and_compression_03.py)
