### ISSUE TITLE
Dependency of conventions and data_specs_version

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#442]
Hi,
CMIP6 standardized data include the attributes `conventions` and `data_specs_version`, e.g.:
`"conventions":"... CMIP6 6.2"`
as well as
`"data_specs_version": "1.00.27".`

We have a case where:
`"conventions":"... CMIP6 6.0"`
`"data_specs_version": "1.00.27"`
However, since PrePare checks the data with MIP-Tables which are built on at least three documents: CV, CMIP6 6.2 and DReq, these referenced documents can not be checked independently. Besides, it is hard to recreate the CMIP6 6.0 document.

In that specific case, the `further_info_url` attribute contains a "http:.." string which is not compliant to the new "https:..." regex. 

So how to proceed? Is there a document which has priority? E.g., if a data producer uses CMIP6 6.2, the data have to be compliant to DReq 1.00.27? Or is it the other way around?

Best regards,
Fabi

**Comment by taylor13** [comment]
Reviewing the notes at the end of the CMIP6 specifications document (https://goo.gl/v1drZl  ; current version 6.2.7)  I don't find any changes introduced after version 6.2.2 (23 March 2017) that should affect ESGF publication  (or PrePARE).  We were unaware of anyone writing CMIP6 output files before 2017, so we didn't think we would run into problems.  Do you really have datasets prepared prior to March 2017 that you want to publish?  

To answer your specific question, the latest CMIP6 6.2.7 specifications document is the reference.  Users should rely on the latest version of that document in preparing output.  PrePARE might find errors in data prepared prior to version 6.2.2 (released about 2 years ago).  [Note, however, PrePARE allows the Conventions attribute to have "CMIP-6.0", "CMIP-6.1" or "CMIP-6.2".]

Regarding the data request ... when running PrePARE, you should use CMOR table versions that are consistent with the version followed in preparing the data.

**Comment by wachsylon** [comment]
This problem occurs when modelers do not work with MIP-tables but with DReq and the CMIP-6.* documents. Standardized data suggest that this procedure is valid since it includes references to these documents but not to the MIP-table versions. However PrePare use MIP-tables and MIP-tables are not created for every combination of DReq, CV and CMIP6. PrePare cannot check CMIP-6.0 individually since PrePare uses the CMIP6_CV.json which is built on the CMIP-6.* version which was up to date when the CMIP6_CV.json was created.

So why could it not be the other way around? Data could include MIP-table versions and no reference to the CMIP-6.* and DReq versions. Anytime in the future of course (CMIP7).

>  Do you really have datasets prepared prior to March 2017 that you want to publish?

Yes (HighResMIP) but the agreement here is that data in the ESGF pool should be compliant to 1.00.27 so the modellers have to adapt the data to the recent standard. The questions is whether they also have to adapt to CMIP-6.2.

> Note, however, PrePARE allows the Conventions attribute to have "CMIP-6.0", "CMIP-6.1" or "CMIP-6.2".]

Yes, you can set it to CMIP-6.0 but PrePare will test against CMIP-6.2 when 1.00.27 is used. Do you say that the errors that will be given by PrePARE can be ignored since the data is actually compliant to CMIP-6.0? That means that the `further_info_url` will be unresolvable. And probably many other problems. And actually I thought that the only publication rule is that PrePare needs to be successfull.

In the document updates for 6.2.6 you write

> Corrected the example of further_info_url given in note 9 following Table 1.

I thought that this could be the change from
"http" to "https"
in the `further_info_url` . That would be 20.12.2017.  I saw that the change in the CMIP6_CV.json was way earlier. How have these documents been kept consistent? Is there any documentation of how the MIP-Tables are created? (see PCMDI/cmip6-cmor-tables#177)

**Comment by taylor13** [comment]
Thanks for the suggestions on how to reduce confusion.  For now, I'll try to answer some of the specific questions:

1. The rule is that certain global attributes need to be consistent with the latest CMIP6 specs document -- the ones that are checked by PrePARE.  Also certain other things must be consistent like the filename specs.  I think the publisher also requires that the directory structure is consistent.

2.  Some of the information in versions of the specs document prior to 6.2.2 is not consistent with what PrePARE and the publisher require.  So following earlier versions may lead to files that can't be published.

3.  The update in 6.2.6 of the example was, as I recall, to make the example consistent with the template (which appears just before the example in the same note 9).  When the template was modified, I forgot to modify the example until months later.  Shortly after the *template* was modified, the CMIP6_CV.json file was updated to be consistent with it.  

4.  I'll respond to  https://github.com/PCMDI/cmip6-cmor-tables/issues/177 on that issue.  In short, I am the editor of the CMIP6 specs document and whenever a change to it was made that could affect CMOR3, I would tell Denis to update the CMIP6_CV.json file .  We haven't made changes in the specs in some time that affect CMOR, but now Chris, who took over for Denis would be responsible  if an update were needed.

**Comment by wachsylon** [comment]
Thank you for the answers. We draw conclusions from that on how we treat these special, hopefully rare files and we will inform you about it.

I checked the releases of the MIP-tables and found that the first `CMIP6_CV.json` that includes `https` for `further_info_url` was the 6.0.17 from Nov 2017. According to the release tag that coincides with DREQ-01.00.16. The `specs_doc` info is not mentioned in the release.  

> I'll respond to PCMDI/cmip6-cmor-tables#177 on that issue

 I would be very glad about that. I would appreciate if we could work a manual about how to create and publish "official" MIP-tables for other projects so that CMOR could be used in a wider field. Maybe we could find a place where tables of other projects built on guidelines can be gathered instead of having multiple, uncoordinated and maybe hard to find repositories. For example, half way on CMIP6 I discovered that there are PRIMAVERA MIP-tables. Knowing about projects that use CMOR could help CMOR developer in turn to improve or extend the program.

**Comment by durack1** [comment]
@wachsylon I also note that in the earlier versions of DREQ, there were inconsistencies in the attributes long_names etc that are mostly fixed in the more recent (CMIP 6.2, >dreq 01.00.28) and so for this reason I would recommend writing all files to be contributed with the latest versions rather than those written earlier

**Comment by wachsylon** [comment]
I also saw that there is issue #256 which is similar to PCMDI/cmip6-cmor-tables#177 so that we might close one of both.

**Comment by taylor13** [comment]
@wachsylon Not sure if there are high priority actions required here.  Please advise.

**Comment by taylor13** [comment]
@wachsylon I'm a bit confused about what is needed.  Please advise.

**Comment by wachsylon** [comment]
No high priority actions. My problems arose when modelers focus on the DReq and more or less ignore MIP-tables which eventually leads to problems when it comes to the data standard. I sum up my ideas to prevent it:
1. We need a standard way to describe how MIP-Tables are created. see #256 Best thing would be a program that creates the tables based on the DReq.
2. Add MIP-Table version as a global attribute or replace the `data_specs_version` with a MIP-Table version since PrePare works with it.
3. Record the current releases of all other documents (including DReq, MIP-Tables, specs) that are needed to fully describe the CMIP6 data standard when a new release of one of these is published. Therefore, if one of the "documents" says "this is a necessary update" or "this makes other documents incompatible against ours", it will be easier to discard early or incompatible versions of the other documents.

On long term, it might help if either
MIP-Tables are the only documents that fully describe CMIP-Standard
or
CMOR reads information directly from DReq, specs and CV without needing MIP-Tables.

**Comment by durack1** [comment]
@wachsylon just pointing out for your comment above

> CMOR reads information directly from DReq, specs and CV without needing MIP-Tables.

This assumes that ***CMIP6 is the only project*** that CMOR is used for, and this is not a fair assumption (see [obs4mips-cmor-tables](https://github.com/PCMDI/obs4mips-cmor-tables) and [input4mips-cmor-tables](https://github.com/PCMDI/input4mips-cmor-tables))

Regarding ***1*** above, the relevant code can be found at [xml-cmor3-database](https://github.com/PCMDI/xml-cmor3-database) and also in [PCMDI/cmor/scripts)](https://github.com/PCMDI/cmor/tree/master/scripts).

Regarding ***3*** above, this is what the comment in the release notes for [3.5.0](CMIP6_CVs-6.2.35.3/DREQ-01.00.31/CMOR-3.5.0), with `CMIP6_CVs-6.2.35.3/DREQ-01.00.31/CMOR-3.5.0` noted

@mauzey1 can correct me if I'm wrong with anything here

**Comment by wachsylon** [comment]
> This assumes that CMIP6 is the only project that CMOR is used for, and this is not a fair assumption (see obs4mips-cmor-tables and input4mips-cmor-tables)

But these projects could also use the software and formats of DReq, specs and CV, couldn't they?

> Regarding 3 above, this is what the comment in the release notes for 3.5.0, with CMIP6_CVs-6.2.35.3/DREQ-01.00.31/CMOR-3.5.0 noted

Good, we have that already:) But the CMIP6 specification document seems to be missing.

Just another formulation of my argument: This means that data that is checked by PrePARE with MIP-Tables based on `CMIP6_CVs-6.2.35.3/DREQ-01.00.31/CMOR-3.5.0`, needs to fulfill the requirements of these versions of the documents. These versions cannot be set independently.

Therefore, I propose 2 options:
1. data should not have references to these versions by attributes `conventions` and `data_specs_version` but a reference to the MIP-Table version to avoid misleading modelers to work with different versions of DReq, CV and CMOR.
or
2. CMOR should read from the documents directly.

> Regarding 1 above, the relevant code can be found at xml-cmor3-database and also in PCMDI/cmor/scripts).

Thank you, this might be very helpful.

**Comment by durack1** [comment]
> But these projects could also use the software and formats of DReq, specs and CV, couldn't they?

No. Each project has it's own set of CVs that build on the CMIP6 standard that are defined in the CMIP6_CVs and DREQ for variable definitions.

> Good, we have that already:) But the CMIP6 specification document seems to be missing.

The CMIP6 specification document underpins the CMIP6_CVs, so if you take a look at the bottom of a CV, e.g. [CMIP6_realm.json](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_realm.json) you'll see the version of the specs doc that underpins the CVs is identified in the `specs_doc` attribute

Regarding 1. above, CMOR can only work with the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/) (or the equivalent tables for obs4mips or input4mips), and not the DREQ directly. This is the reason these tables exist, which merge registered information from the CMIP6_CVs along with variable information from the DREQ (which itself is dependent on the CMIP6_CVs).

Regarding 2. There is a need to quality control and merge information from multiple sources for CMOR to use for CMIP6, which is why the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables/) exist. The DREQ is not enough information by itself.

**Comment by durack1** [comment]
Another stale issue, closing
