### ISSUE TITLE
length of "comment" attribute

### ISSUE THREAD

**Issue by taylor13** [PCMDI/cmor#444]
https://github.com/cmip6dr/CMIP6_DataRequest_VariableDefinitions/issues/290#issuecomment-468691658 notes that some "comment" attributes in the CMOR tables are as long as 824 characters.  How does CMOR handle these.  I'm just curious, not asking for any change at this point.  What is the longest "comment" CMOR can handle?

**Comment by mauzey1** [comment]
The maximum string length in CMOR is 1024.
https://github.com/PCMDI/cmor/blob/806b41c4879935e36f367b5f6b4f835d20418df6/include/cmor.h#L11
This includes the length of variable comments.
https://github.com/PCMDI/cmor/blob/806b41c4879935e36f367b5f6b4f835d20418df6/include/cmor.h#L408

**Comment by taylor13** [comment]
O.K.  so that means we'll be able to handle the full comments in the data request.  Thanks!
