### ISSUE TITLE
Python API: cmor.grid does not take area as an argument

### ISSUE THREAD

**Issue by ashao** [PCMDI/cmor#445]
As requested in the GMD papers, the area of the grid cells (e.g. `areacello`) should be included for 2D and 3D fields. In the API documentation, this seems like it should be done via `cmor_grid`, however the Python interface cmor does not have `area` as an acceptable input. 

`pywrapper.py` has lines related to handling of the area commented out https://github.com/PCMDI/cmor/blob/806b41c4879935e36f367b5f6b4f835d20418df6/Lib/pywrapper.py#L214-L223 Making the necessary modifications to pass area as a 2D area through to `_cmor.grid`, returns: 

```TypeError: function takes exactly 8 arguments (9 given)```

1. At some point will this functionality be restored for Python API users of the CMOR library?
2. Is there an alternative way to include `areacello` along with the 2D/3D cmor variable?

Thanks in advance for any help you can provide.

**Comment by taylor13** [comment]
CMOR is designed for CMIP where grid cell areas (and volumes) are stored alone as *separate* variables in their own files.  Many CMIP variables (e.g., ta, the air temperature) should include a `cell_measures` attribute assigned the value`area: areacella`.  Because the variable named areacella exists *externally* (i.e., not in the same file as air temperature), a global attribute must be defined: `external_variables = areacella`.   When a CMOR user defines a variable, CMOR looks in the CMOR table where it extracts information it needs to record in the file, including `cell_measures` and `external_variables`.  There is no need to include the actual cell areas to CMOR when it is writing a variable like air temperature.

**Comment by ashao** [comment]
Thanks for the quick reply @taylor13. This way of specifying the `external_variables` is currently how we've been internally publishing our output from CCCma's CanESM5. However this is inconsistent with what is requested for OMIP, as specified in Appendix B of Griffies et al., [2016] (https://www.geosci-model-dev.net/9/3231/2016/gmd-9-3231-2016.pdf):
> Cell areas (areacello) should be stored in each data file (Table G1) in order to keep this important information within each diagnostic file.

Model output from IPSL for example includes an `area` variable in their output, though it looks like they may have done this post-CMORization. The question then becomes: Is there a way to include an _auxiliary_ variable via CMOR?

**Comment by taylor13** [comment]
(cc @durack1 )  I hadn't noticed that specification in Griffies, which as you noted is inconsistent with the CMIP6 specs.  For *all* variables the cell areas are important and we decided to avoid duplication of this information across 100's of variables in CMIP6 by recording area in its own file and then noting that with "external_variables".  CMOR cannot include an auxiliary variable of this kind.  I would recommend ignoring the Griffies et al. request for CMIP6 output.  If you *do* decide to somehow add it to cmorized files, you should check the ESGF publisher does not object before going into production.

**Comment by durack1** [comment]
I agree with @taylor13. The CMIP6 data model is for a single variable per file, and for these `fx` fields to be provided separately (as they can often be used across numerous simulations). The sentence in Griffies et al contravenes what was done in CMIP5, CMIP3 etc etc

**Comment by ashao** [comment]
Thank you again for the responses before I close this issue I'll pull in @StephenGriffies to allow him to comment and perhaps shed some insight into how GFDL handles this. 

I'll also note, if I recall correctly, that the IPSL file did pass both cfcheck and PrePARE.

**Comment by taylor13** [comment]
If IPSL didn't tweak things to pass, you'd probably be o.k. in adding areacello to your files, but very few groups will include it, so users won't be able to count on it and that won't make their lives any easier.

**Comment by StephenGriffies** [comment]
I am fine deferring to the experts, Karl and Paul. 

I believe we sought inclusion of areacello to ensure it would always be available. But I appreciate that including it in all files will increase the archive size.

**Comment by durack1** [comment]
The point of @StephenGriffies is a good one, adding a duplicated additional field in every output file will bloat the archive, which is the very reason the CMIP format, single variable per file was specified. I also note that it would be possible for e.g. for a single model configuration to produce all the `fx` files once, which can then be used for all instances (and all experiments) where this model (and grid) are used

**Comment by ashao** [comment]
Great, thanks Steve and I appreciate the discussion @durack1 @taylor13. We'll go forward suggested, without including areacello in our files.
