### ISSUE TITLE
Is Python 2.x a requirement of CMOR ?

### ISSUE THREAD

**Issue by jypeter** [PCMDI/cmor#449]
@dnadeau4 I have successfully installed CMOR into the Python 2.7 version of my _CDAT 8.1 with special JYP sauce_. But it takes forever (I have to `CTRL-C` the install) when I try to install it in the Python 3 version of the same environment with `conda install -n cdatm18_py3 -c conda-forge cmor`

Is Python 2.7 a requirement of CMOR? If that's the case, it should be specified somewhere in the [Anaconda installation](https://cmor.llnl.gov/mydoc_cmor3_conda/) page

**Comment by doutriaux1** [comment]
@jypeter CMOR is now maintained by @mauzey1 and yes currently CMOR is PY2.7 only, but @mauzey1  is working on the Py3 version as well.

**Comment by jypeter** [comment]
Thanks!
