### ISSUE TITLE
NOARCH conda build

### ISSUE THREAD

**Issue by sterlingbaldwin** [PCMDI/cmor#454]
Looking at the meta.yml, it doesnt look like there's anything stopping a noarch build.

**Comment by doutriaux1** [comment]
except that 99% of the code is C 😜 hence can't be noarch.

**Comment by sterlingbaldwin** [comment]
Then why can these guys do it? This is a cpp package with windows/osx/linux/noarch builds.

https://anaconda.org/conda-forge/parquet-cpp/files
