### ISSUE TITLE
Updating Numpy for Python 3.7

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#459]
The current nightly builds for Python 2.7, 3.6, and 3.7 use Numpy 1.12, 1.13, and 1.14.  However, Numpy 1.12 and 1.13 don't have support for Python 3.7 causing the 3.7 builds to error out.  Should we update our builds to use Numpy 1.14, 1.15, and 1.16?

Note: Numpy 1.16 will be the last version of Numpy to support Python 2.7.
https://github.com/numpy/numpy/blob/master/doc/release/1.16.0-notes.rst

**Comment by doutriaux1** [comment]
@mauzey1 let's drop older numpys. And yes we are planning to drop Python 2.7 in the future.

**Comment by doutriaux1** [comment]
@mauzey1 I don't think we need to build for each numpy anymore. @dnadeau4 is that true? Anything built against a nupmy grteater than 1.11 will be ok, right?
