### ISSUE TITLE
isinstance(var, str) breaks unicode

### ISSUE THREAD

**Issue by sterlingbaldwin** [PCMDI/cmor#466]
https://github.com/PCMDI/cmor/blob/11f7665d23e0780472e6d9d182a084d8b08f3ad6/Lib/pywrapper.py#L66

The checks for str, while it seams like a good idea, actually breaks any python 2.7 that uses unicode_literals. All these checks should be removed, or changed to make sure normal ASCII strings work too.

**Comment by dnadeau4** [comment]
This is what I have in CDMS2 to work on string compatibility between  py2 and py3.
```python 
from six import string_types
...
if isinstance(value, string_types):
...
```

https://github.com/CDAT/cdms/blob/master/Lib/dataset.py#L36
https://github.com/CDAT/cdms/blob/master/Lib/dataset.py#L131
