### ISSUE TITLE
vendorizing json-c

### ISSUE THREAD

**Issue by xylar** [PCMDI/cmor#469]
As posted on the [conda-forge feedstock](https://github.com/conda-forge/cmor-feedstock/issues/11), the latest cmor (3.4.0) seems to vendorize json-c. This may not be a problem outside of the conda-forge feedstock but on conda-forge it clobbers any installation of the conda-forge package json-c:

```
This transaction has incompatible packages due to a shared path.
  packages: conda-forge::json-c-0.13.1-h14c3975_1001, conda-forge::cmor-3.4.0-py27h17cb6a4_2
  path: 'include/json-c/arraylist.h'
If you'd like to proceed anyway, re-run the command with the `--clobber` flag.
.
This transaction has incompatible packages due to a shared path.
  packages: conda-forge::json-c-0.13.1-h14c3975_1001, conda-forge::cmor-3.4.0-py27h17cb6a4_2
  path: 'include/json-c/bits.h'
If you'd like to proceed anyway, re-run the command with the `--clobber` flag.
.
This transaction has incompatible packages due to a shared path.
  packages: conda-forge::json-c-0.13.1-h14c3975_1001, conda-forge::cmor-3.4.0-py27h17cb6a4_2
  path: 'include/json-c/debug.h'
If you'd like to proceed anyway, re-run the command with the `--clobber` flag.
...
```

I'm not completely sure if this is an issue that needs to be addressed here or in the `conda-forge` feedstock.

**Comment by dnadeau4** [comment]
They are many json-c reader out there and I was afraid that `json-c` package would disappear 2 years ago.  Do you know who won the "coke/pepsi" war for JSON-C?

**Comment by xylar** [comment]
Thanks for the info.  I'm sure this has been tricky.

According to the feedstock:
https://github.com/conda-forge/json-c-feedstock/blob/master/recipe/meta.yaml#L35
The source is:
https://github.com/json-c/json-c

Do you know if that's what you ended up vendorizing?

**Comment by dnadeau4** [comment]
Yes that is the same one I used.  Nice to see that it is on conda-forge now.

**Comment by dnadeau4** [comment]
Interesting to see that the meta.yaml takes the source from `amazon` and not `github`.

**Comment by xylar** [comment]
I thought that was odd, too, but it's what the Wiki suggests.  I wonder if the `json-c` developers aren't fully aware that GitHub does this for you so you don't have to host elsewhere...
