### ISSUE TITLE
Output coordinates potentially incorrectly named 'latitude' and 'longitude' for irregular grids

### ISSUE THREAD

**Issue by ashao** [PCMDI/cmor#470]
@npgillett notes that ESMValTool reported that CanESM5 has latitude/longitude labelled incorrectly for ocean and ice variables and expects them to be named `lat` and `lon.` In the controlled vocabulary, this would seem to be the case if the coordinate specified is `latitude` and `longitude`, however we report our fields on the native tripolar grid. We define this grid in the following way:
```
         # Ensure that longitude goes from 0-360
         lon_coords = np.mod(dr.vardata.nav_lon.values,360.)
         x = dr.vardata.x.values
         ilon = cmor.axis(table_entry= 'i_index', units= '1', coord_vals=x)   
         lat_coords = dr.vardata.nav_lat.values
         y = dr.vardata.y.values
         ilat = cmor.axis(table_entry= 'j_index', units= '1', coord_vals=y)
         # Data contains x & y dimensions and grid needs to be defined
         lat_vertices, lon_vertices = dr.calc_vertices(nemo_grid)
         lon_vertices = np.mod(lon_vertices,360)
         grid_id = cmor.grid([ilat, ilon], lat_coords, lon_coords, lat_vertices, lon_vertices)
```
The resulting coordinates in the file `cmor.write` (v3.4) produces though are `latitude` and `longitude.` Because we never specify the coordinate names, CMOR itself must be doing this under the hood. I'll note too that both PrePARE and cfcheck did not complain about the coordinate names. To further add to the confusion, latitude/longitude versus lat/lon distinction is not consistent within tripolar grid models: MIROC6 (also a tripolar grid) reports as `latitude` and `longitude`. In contrast, GFDL CM4 reports the variable names as `lat` and `lon`. In all three cases, the two coordinates are 2D arrays reflecting the irregular nature of the grid.

I recognize that ESMValTool is outside the scope of PCMDI, however we are seeking confirmation that this is the intended (or at least acceptable) behavior. We have published a significant amount of data on ESGF and are hesitant to retract those simply for a name change. Any guidance you could provide is much appreciated.

**Comment by mauzey1** [comment]
`cmor_grid` is setting the names of the coordinates as `latitude` and `longitude`.  Below is the segment of the `cmor_grid` function that does this.
https://github.com/PCMDI/cmor/blob/66cd98c178e16a848974fdccfaad2e7b908de4b7/Src/cmor_grids.c#L919-L957

@durack1 @taylor13 What are your thoughts on this behavior?

**Comment by ashao** [comment]
Thanks @mauzey1 for digging out the reference in the code pertaining to the issue.

**Comment by taylor13** [comment]
When latitude and longitude coordinates comprise a simple cartesian system identifying a grid cell, their names are "lat" and "lon".  When the grid structure is more complex such that latitude and longitude are functions of 2 or more indices, then these appear as auxiliary coordinates (identified by the "coordinates" attribute attached to the variable.  In this case, the names can be chosen by the data provider.  CMOR will name them "latitude" and "longitude" (not "lat" and "lon"), but the important thing is that they must have correct standard names and units and be pointed to by the "coordinates" attribute.  These requirements appear in the "CMIP6 Model Output Requirements:
File Contents and Format, Data Structure and Metadata" (goo.gl/neswPr) under item 9 of the  "Requirements for coordinate variables:":
```
9. When the coordinate variables for a horizontal grid are not longitude and latitude, it is 
required that the true latitude and longitude coordinates be supplied via the “coordinates” 
attribute. The coordinates attribute should include the names of the auxiliary coordinate 
variables (e.g.,  “latitude” and “longitude”), which contain the true latitudes and longitudes.  
Those variables must have the ‘standard_name’ attribute values “latitude” and “longitude” 
and have the units “degrees_north” and “degrees_east”, respectively.  In addition, those 
auxiliary coordinate variables must include “bounds” attributes, pointing to arrays containing 
the vertices that define the extent of each grid cell (e.g., bounds = “vertices_latitude” would 
be attached to the latitude variable).  The vertices should be stored in an order which traces 
the outside of a grid cell in a counterclockwise sense (i.e., moving from corner 1 to corner 2 
to corner 3, etc., the grid cell interior must always be to the left). The length of the “vertices”
 dimension of the auxiliary coordinate bounds should be just long enough to accommodate 
the maximum number of vertices needed to describe any cell in the grid.  If a cell has fewer 
than the maximum number of vertices, the remaining values should be set to 1.0d20, and 
missing_value and _FillValue attributes should be attached to both the latitude and longitude 
vertice variables and assigned the value 1.0d20. For the auxiliary coordinate case considered 
here (when the longitudes and latitudes are pointed to by the “coordinates” attribute), it is 
recommended that when possible, longitudes increase monotonically and be confined to the 
range -180 to 360 (with their span limited to a single cycle), but this is not a requirement of 
CF or of CMIP6.  In particular, it would usually be better to avoid jumps in adjacent longitudes 
(e.g., from 359.5 to 0.5) by adding or subtracting 360 (e.g., if adjacent longitudes were 359.5 
and 0.5, they might be redefined as -0.5 and 0.5). 
```
So I think CMOR, you, and GFDL are all compliant with the specs.  esmvaltool needs to be generalized to handle the case where the auxiliary coordinate name is not necessarily "lat" or "lon".

**Comment by ashao** [comment]
Yes that was my understanding having reviewed the document. Thank you @taylor13 for providing confirmation.

**Comment by bouweandela** [comment]
The example in the CF conventions suggests that the names should still be lat/lon instead of latitude/longitude, even for grids:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_two_dimensional_latitude_longitude_coordinate_variables

Can it be that the CMOR tables are in conflict with the CF conventions? Or am I missing something here?

**Comment by matthew-mizielinski** [comment]
> Can it be that the CMOR tables are in conflict with the CF conventions? Or am I missing something here?

The CF conventions document uses `lat` and `lon` throughout its examples, but I don't see anywhere that defines these variable names as a _requirement_ for data using two dimensional coordinates. Providing the `coordinates` attribute on the data variable is consistent with the name of the coordinate variables, i.e. files are self consistent, I don't think there should be a problem.

**Comment by taylor13** [comment]
That is also my understanding of the conventions.
