### ISSUE TITLE
Problem using CMOR with tripolar rotated grid

### ISSUE THREAD

**Issue by jxmaster** [PCMDI/cmor#472]

**Comment by jxmaster** [comment]
Hi,
  I have been using the CMOR for post-process of tripolar rotated lat-lon grid, in which the grid lat and lons are only given in 2d form (which means that the latitude and longitude are in (lat,lon) fashion). I wonder if the CMOR is supported for this grid.
I see for non-Cartesian grid, one has to use cmor_grid to predefine which also relies on the cmor_axis, but the input for these seems to be in 1d rather  than 2d, so I do not know how this may work and keep in models' original grid form, or do we have to simply transform to regular lat-lon grid to continue the post-process?

**Comment by taylor13** [comment]
@doutriaux1 @mauzey1 can one of you please advise?

Do we have an example (or test) where we use cmor_grid and the data is logically 2-d in the horizontal (e.g., function of i,j), with longitude(i.j) and latitude(i,j) pointed to by the coordinates attribute? If not, perhaps we should create one as this is probably a pretty common use case.  Might be good to first get a look at @jxmaster 's data.

**Comment by jxmaster** [comment]
dimensions:
        y = 218 ;
        x = 360 ;
        time = UNLIMITED ; // (1 currently)
variables:
        float lat(y, x) ;
                lat:long_name = "latitude (on T grids)" ;
                lat:units = "degrees_north" ;
        float lon(y, x) ;
                lon:long_name = "longitude (on T grids)" ;
                lon:units = "degrees_east" ;
This is a peak view of the data's dimension. The original data is on Tripolar grid, and thus the lat and lon are in 2d instead of 1d.
@taylor13

**Comment by matthew-mizielinski** [comment]
@jxmaster, @taylor13 ; We (MOHC) have been able to publish eORCA (i.e. tripolar) ocean data through CMOR 3.4.0  [e.g. Omon/tas from the UKESM historical r1 simulation](http://hdl.handle.net/hdl:21.14100/1dec29a2-a5ca-328c-95e3-fd99db997108). Our CMOR expert is on leave for a couple of weeks, but if you can give me specific questions I can see if I can unpick the relevant code.

**Comment by taylor13** [comment]
Would be nice to add an example showing the code used in producing the above eORCA output to the CMOR documentation at https://cmor.llnl.gov/mydoc_cmor3_python/ , so perhaps the expert can share when she/he returns

**Comment by iaplasg** [comment]
@matthew-mizielinski My code has not been debugged,Could you help me look at it?If can? I can send you the test data and code by email.Thanks.

**Comment by taylor13** [comment]
@iaplasg:   @matthew-mizielinski is not a primary CMOR developer and I'm guessing he won't have time to help with this.  I would suggest that you might have a  better chance of getting help  (from CMOR developers) if you post the code here (on github where you can attach files).

**Comment by matthew-mizielinski** [comment]
As @taylor13 notes, I'm not a CMOR developer, but I've dug the following out of the logs from our processing.

When processing a simple atmosphere variable on a lat-lon grid the sequence of calls to cmor appears to be 
```
cmor.axis (latitude)
cmor.axis (longitude)
cmor.axis (time)
cmor.variable
cmor.write (multiple times)
cmor.close
```
For a simple ocean variable on the ORCA grid the sequence appears to be
```
cmor.axis (j_index)
cmor.axis (i_index)
cmor.grid
cmor.axis (time)
cmor.variable
cmor.write (multiple times)
cmor.close
```
Note that the axis calls are setting up different spatial dimensions and the call to `cmor.grid`, which sets up the `latitude` and  `longitude` 2D dimensions and the corresponding `vertices_latitude` and `vertices_longitude` bounds variables. I'd therefore suggest having a look at the api docs for `cmor.grid`.

HTH,

M

**Comment by iaplasg** [comment]
@matthew-mizielinski @taylor13 When executing my code the prompt is:

> Traceback (most recent call last):
>   File "test.py", line 44, in <module>
>     varid = cmor.variable('zos', 'm', grid_id)
>   File "/home/esgf/.conda/envs/CMOR1/lib/python2.7/site-packages/cmor/pywrapper.py", line 498, in variable
>     "Error could not convert axis_ids list to a numpy array")
> Exception: Error could not convert axis_ids list to a numpy array

 I do not know why this error occurred? What do you think is wrong?

```
import cmor
import netCDF4 as net4
import numpy as np
import pdb
from itertools import chain
import operator
from functools import reduce
#from numpy import ndarray
fi= net4.Dataset('/disk2/CMIP6/MMEAN0124-01.nc','r')
z0_feild= fi.variables['z0'][:]
latitude = fi.variables['lat'][:]
i1=np.arange(360)
j1=np.arange(218)
longitude = fi.variables['lon'][:]
time = fi.variables['time'][:]
time_bounds=np.ndarray((1,2),int)
time_bounds[0,0] = time-100
time_bounds[0,1] = time+100
print("cmor setup")
cmor.setup(inpath='cmip6-cmor-tables/Tables',netcdf_file_action=cmor.CMOR_REPLACE_4,logfile='cmor_log.txt')
cmor.dataset_json("common_user_input.json")
cmor.load_table('CMIP6_grids.json')
ilat = cmor.axis(table_entry='i_index',
                 length=360,
                 units= '1',
                 coord_vals=i1)

ilon = cmor.axis(table_entry='j_index',
                 length=218,
                 units= '1',
                 coord_vals=j1)
print(i1)
axis_ids = [ilat,ilon]
print(axis_ids)
grid_id = cmor.grid(axis_ids, latitude, longitude)
varid = cmor.variable('zos', 'm', grid_id)
cmor.write(varid, z0_feild,time_vals='time',time_bnds='time_bounds')
outfile=cmor.close(varid, file_name=True)
print "File written: ",outfile
cmor.close()

```

**Comment by doutriaux1** [comment]
I'm guessing your variable also has time so when defining the variable you need to pass the time axis_id as well. No?

**Comment by jxmaster** [comment]
> As @taylor13 notes, I'm not a CMOR developer, but I've dug the following out of the logs from our processing.
> 
> When processing a simple atmosphere variable on a lat-lon grid the sequence of calls to cmor appears to be
> 
> ```
> cmor.axis (latitude)
> cmor.axis (longitude)
> cmor.axis (time)
> cmor.variable
> cmor.write (multiple times)
> cmor.close
> ```
> For a simple ocean variable on the ORCA grid the sequence appears to be
> 
> ```
> cmor.axis (j_index)
> cmor.axis (i_index)
> cmor.grid
> cmor.axis (time)
> cmor.variable
> cmor.write (multiple times)
> cmor.close
> ```
> Note that the axis calls are setting up different spatial dimensions and the call to `cmor.grid`, which sets up the `latitude` and `longitude` 2D dimensions and the corresponding `vertices_latitude` and `vertices_longitude` bounds variables. I'd therefore suggest having a look at the api docs for `cmor.grid`.
> 
> HTH,
> 
> M

Basicly, the idea seems to be just using a skeleton index (which does not neccessarily has to correspond to a specific lon or lat array) to pass on to cmor_write, and then we can add the 2d lat-lon info back when done processing?

**Comment by iaplasg** [comment]
@doutriaux1 The time variable is passed by cmor_write, which is ok? So I don't have to define the time variable.

**Comment by taylor13** [comment]
@doutriaux1 @mauzey1 :  perhaps there is a "test" code example already existing that would be helpful?

**Comment by doutriaux1** [comment]
@iaplasg no it is NOT ok, the call to cmor_variable is meant to defina a variable and all of its dimensions. Otherwise why bother with passing any dimension information to it, one colud just pass them at write time.

cmor_variable make sure that the variable you're trying to write id ok, that includes having a proper time axis. For example if your variable is in monthly table you shouldn't write time that are hourly.

Does this makes sense?

**Comment by iaplasg** [comment]
@doutriaux1 @matthew-mizielinski ,I've modified my code, but I  don't know how should  "The CMOR_grids.json and CMOR_Omon.json table" be loaded correctly? Could you check it for me?

```
import cmor
import netCDF4 as net4
import numpy as np
import pdb
from itertools import chain
import operator
from functools import reduce
fi= net4.Dataset('/disk2/MMEAN0124-01.nc','r')
z0_feild= fi.variables['z0'][:]
print z0_feild
latitude = fi.variables['lat'][:]
print latitude
i1=np.arange(360)
j1=np.arange(218)
longitude = fi.variables['lon'][:]
print longitude
time = fi.variables['time'][:]
time_bounds=np.ndarray((1,2),int)
time_bounds[0,0] = time-100
time_bounds[0,1] = time+100
print("cmor setup")
cmor.setup(inpath='cmip6-cmor-tables/Tables',netcdf_file_action=cmor.CMOR_REPLACE_4,logfile='cmor_log.txt')
cmor.dataset_json("common_user_input.json")
cmor.load_table('CMIP6_grids.json')
ilat = cmor.axis(table_entry='i_index',
                 length=360,
                 units= '1',
                 coord_vals=i1)

ilon = cmor.axis(table_entry='j_index',
                 length=218,
                 units= '1',
                 coord_vals=j1)
axis_ids = [ilat,ilon]
grid_id = cmor.grid(axis_ids, latitude, longitude)
itime = cmor.axis(table_entry='time',
                  units= 'days since 0001-01-01 00:00:00',
                  coord_vals=time,
                  cell_bounds=time_bounds)
cmor.load_table('CMIP6_Omon.json')
varid = cmor.variable('zos', 'm', axis_ids=[grid_id,itime])
cmor.write(varid, z0_feild)
outfile=cmor.close(varid, file_name=True)
print "File written: ",outfile
cmor.close()

```

**Comment by taylor13** [comment]
@iaplasg  Have you managed yet to get CMOR to store your tri-polar grid data?

**Comment by taylor13** [comment]
@iaplasg Any news on success/failure in storing your data?  Should this issue remain open?

**Comment by durack1** [comment]
This issue is stale - closing
