### ISSUE TITLE
Append mode for instantaneous variables

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#477]
Hi,
when I try to append data to a chunk of a variable with `cell_methods = "time: point"`, I receive:
```
C Traceback:
In function: cmor_validateFilename
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: NetCDF Error (-49: NetCDF: Variable not found) looking for time bounds
! of variable 'mrsol' in file: /work/bm0021/k204210/MPIESMTEST/cmip/archive//CMIP6/ScenarioMIP/MPI-M/MPI-ESM1-2-HR/ssp245/r1i1p1f1/6hrPlevPt/mrsol/gn/v20190506/mrsol_6hrPlevPt_MPI-ESM1-2-HR_ssp245_r1i1p1f1_gnDLFthZ26639.nc
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_write
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: time_vals and time_bounds must be passed through cmor_write when in append mode
!
!!!!!!!!!!!!!!!!!!!!!!!!!


```

Could we enable CMOR to append data of instantaneous variables?
Best regards,
Fabi

**Comment by taylor13** [comment]
@mauzey1 I think fixing this bug should be a high priority.

**Comment by taylor13** [comment]
@wachsylon  @mauzey1 As a note, I think this may be a false identification of the problem.  I can't believe no one has tried to append data for instantaneous variables with CMOR3.  There's lots of data of this kind in the archive.  Can the error be explained by anything else?

**Comment by mauzey1** [comment]
@taylor13 With the merging of #480, should we close this issue?

**Comment by taylor13** [comment]
Yes, thanks.  I'll close it.  If @wachsylon thinks the problem hasn't been solved by https://github.com/PCMDI/cmor/pull/480 , then he can reopen.
