### ISSUE TITLE
Issues when creating subhr variables

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#482]
Hi,
I created variable `ccb` of MIP-Table `CFsubhr` with CMOR. The output contains an unused dimension `bnds` which should be omitted.
Best regards,
Fabi

**Comment by taylor13** [comment]
@wachsylon Can you guess (or do you know) whether this error is likely associated with the "site" dimension or with the "time1" dimension?  I presume the same error would occur for all the other variables in that table.  
Is bnds simply defined as a dimension (with a value of 2?) and never actually used by any of the variables in the file, or does bnds appear as a coordinate for some variable?

**Comment by wachsylon** [comment]
>  Is bnds simply defined as a dimension (with a value of 2?) and never actually used by any of the variables in the file, or does bnds appear as a coordinate for some variable?

It is a dimension with value 2, there is no coordinate variable in the file. However, this dimension seems to enlarge the file size.

I would like to check e.g. `cli` in `CF-subhr` with
`dimensions": "alevel site time1", `
but a new issue emerged and stopped be. My actual problem is that the specific raw model output contains variables of one site in one file which is the opposite of what the DReq wants: all sites for one variable. That will cause A LOT post-processing in general.

The specific problem I have is that the surface pressure which is required for representing the vertical model axis is also saved without spatial dimensions. My question is: Is `ps1` which is defined with spatial dimension the correct surface pressure for variables using `site` as a dimension or should there be a different `ps` CMOR Variable with also uses `site` as a dimension? I think that the surface pressure right at the spot of the site is required, not a global grid, right?

**Comment by wachsylon** [comment]
As far as I can remember, I have not experienced any additional `bnds` dimensions when producing variables with dimension `time1`.

**Comment by taylor13** [comment]
Could you please attach a copy of the result of `ncdump -h` executed on the file that has the unused bnds dimension?

Regarding
```
The specific problem I have is that the surface pressure which is required for representing the 
vertical model axis is also saved without spatial dimensions. My question is: Is ps1 which is 
defined with spatial dimension the correct surface pressure for variables using site as a 
dimension or should there be a different ps CMOR Variable with also uses site as a dimension? 
I think that the surface pressure right at the spot of the site is required, not a global grid, 
right?
```
Yes, we only need ps at the defined "sites", not global.   So `ps` should be a function of `time` and `site`.   

@mauzey1  Could you please define new formula_term table entries for `psSite1` and for `orogSite` to handle this case?
```
        "psSite1": {
            "long_name": "vertical coordinate formula term: ps", 
            "units": "Pa", 
            "dimensions": "site time1", 
            "out_name": "ps", 
            "type": "real"
        }, 
        "orogSite": {
            "long_name": "Surface Altitude", 
            "units": "m", 
            "dimensions": "site", 
            "out_name": "orog", 
            "type": "real"
        },

**Comment by wachsylon** [comment]
```
ncdump -h .//CMIP6/CMIP/MPI-M/MPI-ESM1-2-HR/1pctCO2/r1i1p1f1/CFsubhr/ccb/gn/v20190520/ccb_CFsubhr_MPI-ESM1-2-HR_1pctCO2_r1i1p1f1_gn_18500101000000-18500131233000.nc
netcdf ccb_CFsubhr_MPI-ESM1-2-HR_1pctCO2_r1i1p1f1_gn_18500101000000-18500131233000 {
dimensions:
	time = UNLIMITED ; // (1488 currently)
	site = 121 ;
	bnds = 2 ;
variables:
	double time(time) ;
		time:units = "days since 1850-1-1 00:00:00" ;
		time:calendar = "proleptic_gregorian" ;
		time:axis = "T" ;
		time:long_name = "time" ;
		time:standard_name = "time" ;
	int site(site) ;
		site:long_name = "site index" ;
	float ccb(time, site) ;
		ccb:standard_name = "air_pressure_at_convective_cloud_base" ;
		ccb:long_name = "Air Pressure at Convective Cloud Base" ;
		ccb:comment = "Where convective cloud is present in the grid cell, the instantaneous cloud base altitude should be that of the bottom of the lowest level containing convective cloud. Missing data should be reported in the absence of convective cloud. The time mean should be calculated from these quantities averaging over occasions when convective cloud is present only, and should contain missing data for occasions when no convective cloud is present during the meaning period." ;
		ccb:units = "Pa" ;
		ccb:cell_methods = "area: point time: point" ;
		ccb:history = "2019-05-20T10:49:16Z altered by CMOR: replaced missing value flag (-9e+33) with standard missing value (1e+20)." ;
		ccb:missing_value = 1.e+20f ;
		ccb:_FillValue = 1.e+20f ;

// global attributes:

```

One additional question:
Is it allowed to only provide a subset of the 121 sites? Or additional sites?

**Comment by taylor13** [comment]
I just noticed that there is a test case that presumably successfully creates a file that is a function of site and alevel: https://github.com/PCMDI/cmor/blob/master/Test/test_python_cfmip_site_axis_test.py .  Could you check whether your code might be made more like the test case and be made to work without adding the new formula terms as suggested in https://github.com/PCMDI/cmor/issues/482 ?  

And to answer you specific question, I think from a scientific view, it shouldn't be an absolute requirement that data should only be reported at *all* or *only* the 121 sites, but is there a good reason why we should tolerate deviations from this specification?

The file above should contain a "coordinates" attribute assigned the value "lon lat", and the "lon" and "lat" variables should be defined as functions of "site".

**Comment by wachsylon** [comment]
> The file above should contain a "coordinates" attribute assigned the value "lon lat", and the "lon" and "lat" variables should be defined as functions of "site".

OK, then we use `ps1` for that.
However, if we use `longitude` and `latitude` to describe the `sites`, why do we need `site` at all?
I found a file in ESGF
```
cl_CFsubhr_CNRM-CM6-1_amip_r1i1p1f2_gn_19790101003000-19890101000000 {
dimensions:
	lev = 91 ;
	bnds = 2 ;
	site = 126 ;
```

In that file, there is no corresponding coordinate `site` for the dimension `site`.  I expected to have sth like
```
int site(site) ;
		site:long_name = "site index" ;
```

We do have:
```
	cl:coordinates = "latitude longitude" ;
	double latitude(site) ;
	double longitude(site) ; 
```

Since we have
	`site = 126` != `site = 121`
a specific site value does not correspond to a specific station anymore according to that file. E.g., the dimension index
`site = 2 `
could represent a station which is
`site = 3`
in another file.

**Comment by wachsylon** [comment]
So to redefine the topic of this issue in contrast to #499 , the one thing left that need to be cleared: Is `site` the same like any index, e.g. `i` or `j` of any grid?

**Comment by taylor13** [comment]
Yes, I think so.  You can think of it as a grid with a cell located at each of the sites and identified by an index (e.g., i or j), which isn't an actual coordinate value.  You can't rely on the index value to tell you which site, but you can rely on the "latitude" and "longitude" pointed to by the "coordinates" attribute.

For CMIP6, I think the intent was to include only and all of the specified sites, and if that is done to assign the sites according to the indexes specified in the text file available at https://www.geosci-model-dev.net/10/359/2017/gmd-10-359-2017-supplement.zip .  There are 121 sites listed there.

**Comment by wachsylon** [comment]
I agree. I looked into two different files and found 2 different numbers of sites - therefore, we better not restrict a file due to the number of sites.

I forgot that you may want to check the unused dimension bnds. If you have, we can close the issue.

**Comment by zklaus** [comment]
We are also experiencing the unused dimension issue. Here is the relevant ncdump output (omitting only the global attributes):
```
netcdf areacello_Ofx_EC-Earth3-Veg_historical_r1i1p1f1_gn {
dimensions:
        j = 292 ;
        i = 362 ;
        bnds = 2 ;
        vertices = 4 ;
variables:
        int j(j) ;
                j:units = "1" ;
                j:long_name = "cell index along second dimension" ;
        int i(i) ;
                i:units = "1" ;
                i:long_name = "cell index along first dimension" ;
        double latitude(j, i) ;
                latitude:standard_name = "latitude" ;
                latitude:long_name = "latitude" ;
                latitude:units = "degrees_north" ;
                latitude:missing_value = 1.e+20 ;
                latitude:_FillValue = 1.e+20 ;
                latitude:bounds = "vertices_latitude" ;
        double longitude(j, i) ;
                longitude:standard_name = "longitude" ;
                longitude:long_name = "longitude" ;
                longitude:units = "degrees_east" ;
                longitude:missing_value = 1.e+20 ;
                longitude:_FillValue = 1.e+20 ;
                longitude:bounds = "vertices_longitude" ;
        double vertices_latitude(j, i, vertices) ;
                vertices_latitude:units = "degrees_north" ;
                vertices_latitude:missing_value = 1.e+20 ;
                vertices_latitude:_FillValue = 1.e+20 ;
        double vertices_longitude(j, i, vertices) ;
                vertices_longitude:units = "degrees_east" ;
                vertices_longitude:missing_value = 1.e+20 ;
                vertices_longitude:_FillValue = 1.e+20 ;
        float areacello(j, i) ;
                areacello:standard_name = "cell_area" ;
                areacello:long_name = "Grid-Cell Area for Ocean Variables" ;
                areacello:comment = "Horizontal area of ocean grid cells" ;
                areacello:units = "m2" ;
                areacello:original_name = "areacello" ;
                areacello:cell_methods = "area: sum" ;
                areacello:missing_value = 1.e+20f ;
                areacello:_FillValue = 1.e+20f ;
                areacello:coordinates = "latitude longitude" ;
}
```
In our case it is unrelated to this `site` business. We have a short discussion on this in EC-Earth/ece2cmor3#506. Basically what I think is that the vast majority of files has at least one 1d coordinate with bounds (lat, lon, time, ...), often several and to ease the creation and reuse of dimensions cmor just always creates a bnds=2 dimension. However, in rare cases, such as tripolar ocean grids with instantaneous times, no bounded 1d coordinate appears and the 1d coordinate goes unused.

What do you think?

**Comment by taylor13** [comment]
I think this problem is fairly low priority, but it would be nice to eventually figure out why "bnds = 2" gets written to the file but isn't needed.  If not fixing this is holding anyone up, please say so.

**Comment by wachsylon** [comment]
As we discussed, I tried to define a grid with site as the index axis.  I did:
```
              cmf = cmor_load_table(gridtable, &gridtable_id);
              cmf = cmor_set_table(gridtable_id);
              cmf = cmor_axis(&grid_axis[0], (char *) "site", (char *) "1", xlength, (void *) coord_vals, 'd', 0,
                          0, nullptr);
              cmf = cmor_grid(&grid_ids[0], 1, grid_axis, 'd', (void *) ycoord_vals, (void *) xcoord_vals, 0, nullptr, nullptr);
```
First, I receive a warning
```
C Traceback:
In function: cmor_grid
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: it is recommended you pass the latitude bounds values when defining a grid
!
!!!!!!!!!!!!!!!!!!!!!!!!!
 
```
Then, during the `cmor_write` loop, CMOR fails and I receive:
```
C Traceback:
! In function: cmor_define_dimensions
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: NetCDF error (-54:NetCDF: NC_UNLIMITED size already in use) for dimension definition of
! axis:  (-1), for variable 2 (cct, table: CFsubhr)
!
!!!!!!!!!!!!!!!!!!!!!!!!!

```
I found 2 solutions for this:

1.  Call it in a different order:
```
      cmf = cmor_axis(&grid_axis[0], (char *) "site", (char *) "1", xlength, (void *) coord_vals, 'd', 0,
                          0, nullptr);
      cmf = cmor_load_table(gridtable, &gridtable_id);
      cmf = cmor_set_table(gridtable_id);
      cmf = cmor_grid(&grid_ids[0], 1, grid_axis, 'd', (void *) ycoord_vals, (void *) xcoord_vals, 0, nullptr, nullptr);
```
but I ask myself how `cmor_grid` is able to work without having information about `site` in `CMOR_grids.json` but with a `grid_axis` pointing at an entry `site`. Are you sure that this was always the procedure how `cmor_grid` should be applied? I can test this tomorrow with CMOR2. The second solution is more consistent with my other `cmor_grid` calls:

2. We could do these 3 major changes:

- Variables in `CFsubhr` need to be requested for
`"dimensions": "latitude longitude time"`
instead of
`"dimensions": "site time"`
Otherwise it would be possible to submit the data without coordinates. BUT, as we discussed, a `site` index does not correspond to a specific `longitude` `latitude` pair.
-  `CMIP6_coordinate.json` should not have an entry for `site`, but
-  `CMIP6_grids.json` should have an entry for `site` similar to `i_index`. @taylor13 also said:

>   You can think of it as a grid with a cell located at each of the sites and identified by an index (e.g., i or j),

If I do these changes, I am able to process, for example `cct` in `CFSubhr`, equally to the first solution.

**Comment by taylor13** [comment]
I think your 2nd solution is how we meant it to work.  Let's think about this for a day or two before proceeding though.

**Comment by taylor13** [comment]
There is some related discussion around https://github.com/PCMDI/cmor/issues/499#issuecomment-499637184

**Comment by taylor13** [comment]
I gave it another think, and recommend we consider making the following changes to the tables:

- In ``CFsubhr`` and in ``Esubhr``, replace all occurrences of "site" with "longitude latitude"
- Remove entry for "site" from CMIP6_coordinates.json.
- Add to CMIP6_grids.json:
```
        "site_index": {
            "standard_name": "", 
            "units": "", 
            "axis": "", 
            "long_name": "site index", 
            "out_name": "site", 
            "type": "integer"
        }, 
```

**_Before doing this, we must provide an example in the documentation showing how to write site data with CMOR._**

@mauzey1 @wachsylon  Do you agree?

**Comment by matthew-mizielinski** [comment]
@taylor13, will your suggested change here create confusion between 2D fields and site specific variables here and would it require data request changes too?

**Comment by durack1** [comment]
@wachsylon another stale issue, closing - again comment and reopen if required
