### ISSUE TITLE
Change "Control Vocabulary" to "Controlled Vocabulary"

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#488]
As mentioned in https://github.com/PCMDI/cmor3_documentation/issues/55, the documentation has used the term "Controlled Vocabulary" rather than "Control Vocabulary".  We should change mentions of "Control Vocabulary" to "Controlled Vocabulary" in CMOR to reflect the documentation.  This includes changing the parameter name of the CMIP6_CV.json path from `_control_vocabulary_file` to `_controlled_vocabulary_file`.

**Comment by taylor13** [comment]
sounds good to me, but not particularly urgent.
