### ISSUE TITLE
Corrected vertical coordinate

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#494]
Hi,

I have model output on a vertical coordinate which is based on the sleve coordinate formula but which is corrected in the end with another term in order to avoid cutting surfaces. The modelers did not enable to write out the factors of the sleve formula. What is the approach for the standardization of this kind of data? What model level coordinate could we take from `CMIP6_coordinate.json` for that? I thought of a general `altitude` coordinate but there is no, just specific ones like `alt40` e.g.

Best regards,
Fabi

**Comment by taylor13** [comment]
I don't understand the issue.  If the sleve coordinate is inconsistent with the description at http://cfconventions.org/cf-conventions/cf-conventions.html#_atmosphere_smooth_level_vertical_sleve_coordinate, then we can't write a valid CF-compliant output file.  If it is consistent, you need to obtain the formula_terms: a, b1, b2, zsurf1, and zsurf2.  We will also have to modify the formula_terms.json file to include these.  The sleve coordinate is already in the coordinates.json file (named smooth_level and smooth_level_half, but again we need to add some terms to the formula_terms.json file.

Also, is this CMIP6 output?  

@wachsylon  Related to this, do you see any problems making the changes suggested at the beginning of https://github.com/PCMDI/cmip6-cmor-tables/issues/250 ?

**Comment by wachsylon** [comment]
Thank you, we discussed the issue yesterday. The modeling group now thinks it is better to interpolate the output from these hard-to-construct model levels to an easier-to-understand vertical coordinate for which there is a standard description available. So it is not a CMOR issue anymore.

> Also, is this CMIP6 output?

What did you mean with that?

> @wachsylon Related to this, do you see any problems making the changes suggested at the beginning of PCMDI/cmip6-cmor-tables#250 ?

See my comment in PCMDI/cmip6-cmor-tables#250

**Comment by taylor13** [comment]
@wachsylon Regarding "is this CMIP6 output?", I was just curious whether a modeling group was planning to submit their ocean data on the "sleve" levels.  This would be somewhat surprising to me (but perfectly o.k.).  I would have been less surprised if for a different purpose (other than CMIP6), they might want to distribute data on "sleve" levels.  Anyway, you've answered my question: it's CMIP6 data.

I guess I can close this issue now.  Thanks for raising it.
