### ISSUE TITLE
TRUE and FALSE

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#508]
Hi,
I `exported` CMOR from the CMOR git repository and tried to install the exported CMOR version. When I try to compile it with gcc-7.1.0, the compiler gives errors:
```
FALSE not defined. 
TRUE not defined.
```
these are used, e.g. in line 1438 of cmor_CV.c:
https://github.com/PCMDI/cmor/blob/2e9f6b2f6acbd25d15b6c46a26176632c864ac8b/Src/cmor_CV.c#L1438

`TRUE` and `FALSE` were defined in `json_object.h` but in the json-c version I used (probably cloned from the repo), it ist not defined anymore. I needed to define these macros inside a `cmor.h` file to make the installation work. Can you see the issue or is it an installation mistake by me?

Best regards,
Fabi

**Comment by wachsylon** [comment]
I used the CMOR master Branch and the following config:
` ./configure --prefix=${cmorSubvers} --with-uuid=$libscmor --with-json-c=$libscmor --with-udunits2=${UDUNITS} --with-netcdf=${NETCDF} CC=gcc`

**Comment by mauzey1** [comment]
Interesting, the version of json-c we install from conda-forge still has `TRUE` and `FALSE` macros defined.

They were removed two years ago according to this commit: https://github.com/json-c/json-c/commit/0992aac61f8b087efd7094e9ac2b84fa9c040fcd

@doutriaux1 Should we replace `TRUE` with 1 and `FALSE` with 0?

**Comment by doutriaux1** [comment]
@mauzey1 yes it seems like the best option.
