### ISSUE TITLE
hourly climatology axis for CMIP6-CFMIP

### ISSUE THREAD

**Issue by martinjuckes** [PCMDI/cmor#52]
CFMIP have added a request for a set of variables with monthly averages of each hour of the day. This corresponds to a cell_methods value of "time: mean within days time: mean over days" as illustrated in Example 7.10 of the CF Convention. I propose to add a new time coordinate to the CMIP6 data request, with label "time3" which will be similar to the "time2" record specifying the monthly climatology time axis.

**Comment by durack1** [comment]
@dnadeau4 you sure this should be assigned to me?

**Comment by martinjuckes** [comment]
I've modified the tables ... but I raised the ticket in case changes were also needed in CMOR.

**Comment by dnadeau4** [comment]
time3 is now in the `coordinate_variables.json` file.
