### ISSUE TITLE
CMOR using incorrect frequencies for variables when closing programs with multiple frequencies.

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#520]
The Fortran test [test_sophie.f90](https://github.com/PCMDI/cmor/blob/master/Test/test_sophie.f90) is producing garbled file names.  This sometimes causes the test to fail when the names have forward slashes in them since they look like paths of non-existing directories.
```
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: could not rename temporary file: CMIP6/CMIP6/ISMIP6/PCMDI/PCMDI-test-1-0/piControl-withism/r3i1p1f1/Amon/cl/gn/v20190725/cl_Amon_PCMDI-test-1-0_piControl-withism_r3i1p1f1_gnaGUf9B15234.nc to final file
name: CMIP6/CMIP6/ISMIP6/PCMDI/PCMDI-test-1-0/piControl-withism/r3i1p1f1/Amon/cl/gn/v20190725/cl_Amon_PCMDI-test-1-0_piControl-withism_r3i1p1f1_gn_cmor_is_�y/�U-strncpyt�y/�U.nc
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

I found out that the function for building the file name was using the frequency of the last variable written by `cmor_write` stored in `GLOBAL_ATT_FREQUENCY`.  
https://github.com/PCMDI/cmor/blob/45c1496faffe210e16c11f32c90834e6f15f35b5/Src/cmor.c#L5813-L5815

The test program will first write `cl`,`ta`, and `ua` from `CMIP6_Amon` and then `sftof` from `CMIP6_Ofx`.  When `cmor_close` is called it will write all variables using the `fx` frequency, which causes garbage to be written to the file names of the `mon` frequency variables.  

The frequency should come from the current variable being written.
```
        strncpy(frequency, cmor_vars[var_id].frequency, CMOR_MAX_STRING);
```

**Comment by taylor13** [comment]
Thanks for finding this bug.  If I can help, let me know.
