### ISSUE TITLE
Add cmip6-cmor-tables as a submodule for the table directory

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#529]
@sterlingbaldwin suggested this to me a while ago.  This can make it easier to keep the tables in the CMOR repo updated.

**Comment by durack1** [comment]
@mauzey1 not sure I understand this, but I assume this means make a conda distro of the tables dir contents?

@taylor13

**Comment by mauzey1** [comment]
@durack1 What I meant was setting up a git [submodule](https://gist.github.com/gitaarik/8735255) of [PCMDI/cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables) inside of the CMOR repo.  That way when someone clones this repo they will have the CMIP6 tables repo already in the project.  This can allow someone to either pull the tables of the commit that the submodule is pointing to, or get the latest changes from the tables repo.

**Comment by durack1** [comment]
@mauzey1 right I get it, yes this would be ideal. If we can link the tables this way, it certainly would be a good thing to do so that a user that installs cmor has the tables at the ready. I wonder how it would be possible to also do this with the [input4MIPs-cmor-tables](https://github.com/PCMDI/input4MIPs-cmor-tables) and [obs4MIPs-cmor-tables](https://github.com/PCMDI/obs4MIPs-cmor-tables)?

**Comment by mauzey1** [comment]
It could be done for other CMOR table repos, but this is mainly focused on CMIP6 tables since they are the ones being used in CMOR's tests.

**Comment by mauzey1** [comment]
I am currently figuring out how to handle the tests that use CMIP6 tables that are different from the ones from cmip6-cmor-tables.  Some tests have custom tables for testing different scenarios (bad attributes, many variables, etc.).  I'm keeping these custom tables in the `TestTables` directory, however I also need to keep a copy of `CMIP6_CV.json`, `CMIP6_coordinate.json`, and `CMIP6_formula_terms.json` in this directory.  This is because when `cmor_load_table` is called for the custom table in `TestTables`, it will also try to find the other tables in the same directory.

The easiest solution would be to just leave the old copies of `CMIP6_CV.json`, `CMIP6_coordinate.json`, and `CMIP6_formula_terms.json` in the `TestTables` directory.  However, they would have to be manually updated with changes from cmip6-cmor-tables.  We could also replace these files with symlinks to their copies from `cmip6-cmor-tables/Tables`.

Alternatively, we could change or remove these tests and just get rid of `TestTables`.  Here are the tests that use custom tables:

- [test_python_CMIP6_CV_nomipera.py](https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_CV_nomipera.py)
- [test_lots_of_variables.c](https://github.com/PCMDI/cmor/blob/master/Test/test_lots_of_variables.c)
- [test_lots_of_variables.f90](https://github.com/PCMDI/cmor/blob/master/Test/test_lots_of_variables.f90)
- [test_cmor_grid_alejandro.f90](https://github.com/PCMDI/cmor/blob/master/Test/test_cmor_grid_alejandro.f90)
- [test_cmor_grid_time_varying.f90](https://github.com/PCMDI/cmor/blob/master/Test/test_cmor_grid_time_varying.f90)
- [test_python_bounds_request.py](https://github.com/PCMDI/cmor/blob/master/Test/test_python_bounds_request.py)
- [test_python_CMIP6_CV_hierarchicalattr.py](https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_CV_hierarchicalattr.py)
- [test_python_missing_values.py](https://github.com/PCMDI/cmor/blob/master/Test/test_python_missing_values.py)
- [test_python_bounds_request.py](https://github.com/PCMDI/cmor/blob/master/Test/test_python_bounds_request.py)

@durack1 @doutriaux1 Any input is welcome.
