### ISSUE TITLE
libgfortran conflict when cdms2 is installed during MacOS tests

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#537]
There is currently an issue on CMOR's MacOS CircleCI tests where installing cdms2 will downgrade the libgfortran library and cause errors with the CMOR, which was built with the latest version of libgfortran.
```
The following packages will be REMOVED:

  gfortran_impl_osx-64-7.3.0-hf4212f2_2

The following packages will be DOWNGRADED:

  gfortran_osx-64                          7.3.0-h22b1bf0_4 --> 4.8.5-h22b1bf0_8
  hdf5                           1.10.5-nompi_h15a436c_1103 --> 1.10.5-nompi_h0cbb7df_1103
  libgfortran                                       4.0.0-2 --> 3.0.1-0
  libopenblas                              0.3.7-h4bb4525_1 --> 0.3.7-hd44dcd8_1

```
We should get cdms2 for OSX built with the latest libgfortran so CMOR can also be built with the same version.  Currently, the nightly build for CMOR is built with gfortran 4.8.5.  We started using that version due to a [conflict with conda-forge's hdf5](https://github.com/PCMDI/cmor/issues/451).  However, the latest changes to CMOR's conda feedstock shows that it is now able to be built with gfortran 7.3.0.

@doutriaux1 @dnadeau4  Could you look into this?

**Comment by doutriaux1** [comment]
@dnadeau4 could it be the new libcf?

**Comment by doutriaux1** [comment]
@muryanto1 this might be linked to our issues

**Comment by mauzey1** [comment]
@doutriaux1 @muryanto1 @dnadeau4
It looks like esmf on conda-forge is causing cdms2 to be built with the older version of libgfortran.
```
esmf 7.1.0 h3ab5097_1007
------------------------
file name   : esmf-7.1.0-h3ab5097_1007.tar.bz2
name        : esmf
version     : 7.1.0
build       : h3ab5097_1007
build number: 1007
size        : 19.8 MB
license     : University of Illinois/NCSA (NCSA)
subdir      : osx-64
url         : https://conda.anaconda.org/conda-forge/osx-64/esmf-7.1.0-h3ab5097_1007.tar.bz2
md5         : c44642ec25561bc69bc8912cf5371a98
timestamp   : 2019-08-26 06:52:25 UTC
dependencies: 
  - hdf5 >=1.10.5,<1.10.6.0a0
  - libcxx >=4.0.1
  - libgfortran >=3.0.1,<4.0.0.a0
  - libnetcdf >=4.6.2,<4.6.3.0a0
  - mpich >=3.2.1,<3.3.0a0
  - netcdf-fortran >=4.4.5,<4.5.0a0
```

**Comment by mauzey1** [comment]
@doutriaux1 
I am now having issues with cdms2 where it is using libopenblas 0.3.6 but CMOR is using libopenblas 0.3.7.  This has caused the Python 2.7 and 3.6 builds of CMOR to get an older version of cdms2, which is built with gfortran 4 even though CMOR is built with gfortran 7.

Should we build CMOR with openblas=0.3.6, or build cdms2 with openblas >= 0.3.7?

**Comment by doutriaux1** [comment]
@mauzey1 it appears that cdms2 is in some sort of chaotic state due to the test suite being accidentally turned off a couple of months ago. If you could help @muryanto1 and @downiec to fix it. It would be awesome. The blas issue was likely introduced by the newest libcf (which requires blas). The main issue left with cdms2 is that opening any file for writing causes a seg fault: 
```python
import cdms2
f = cdms2.open("any_file.nc", "w")
```

**Comment by mauzey1** [comment]
The conda-forge versions of cdms2 for OSX use libgfortran 4.0.0 but use openblas 0.3.6.  The nightly OSX versions use openblas 0.3.7 but use libgfortran 3.0.1.  This causes an issue with the current OSX CMOR tests since the environment uses libgfortran 4.0.0 and the latest libblas and libcblas. 

We could use gfortran 4.8.5 for OSX to make the environment compatible with the nightly version of cdms2, or install openblas 0.3.6 to make it compatible with the conda-forge version.  Alternatively, we could put cdms2 as part of the environment creation step so that all of the libraries are compatible with cdms2.

Another solution is to build conda-forge versions of cdms2 that use openblas 0.3.7.

**Comment by muryanto1** [comment]
correct. still looking at why the cdms2 in cdat/label/nightly is using libgfortran 3.0.1.

**Comment by mauzey1** [comment]
The latest cdms2 is working correctly with CMOR on OSX but there has been another issue with the conda environment.  If we create the conda environment, activate it, and then install cdms2, it will cause the CircleCI test to fail.  The failure occurs after the command `conda install -q -n py$PYTHON_VERSION -c cdat/label/nightly -c conda-forge -c cdat cdms2` is executed and leaves the following message.
```
INFO: deactivate-gfortran_osx-64.sh made the following environmental changes:
-DEBUG_FFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
-F95=/Users/distiller/project/workspace/test_macos_cmor/miniconda/envs/py3.6/bin/x86_64-apple-darwin13.4.0-gfortran
-FC=/Users/distiller/project/workspace/test_macos_cmor/miniconda/envs/py3.6/bin/x86_64-apple-darwin13.4.0-gfortran
-FFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe
-FORTRANFLAGS=-march=nocona -mtune=core2 -ftree-vectorize -fPIC -fstack-protector -O2 -pipe
-GFORTRAN=/Users/distiller/project/workspace/test_macos_cmor/miniconda/envs/py3.6/bin/x86_64-apple-darwin13.4.0-gfortran
Exited with code 1
```
If we install cdms2 before activating the environment, then the above message doesn't appear and the test doesn't fail.  I'm not sure why this is the case.

I have made a branch where the CircleCI tests have a separate step for testing with cdms2.  It installs cdms2 before activating the conda environment and running the CMOR tests.
