### ISSUE TITLE
Help building CMOR with OSSP uuid

### ISSUE THREAD

**Issue by mathomp4** [PCMDI/cmor#538]
I think I might be doing something wrong. First, per https://cmor.llnl.gov/:

> Finally CMOR3 must also be linked against the uuid library see http://www.ossp.org/pkg/lib/uuid in order to produce a unique tracking number for each file.

Now, I think OSSP uuid is near-abandonware, but luckily I found a copy. The problem is, I don't think CMOR can even build against it anymore. When I try to build:
```
checking for uuid_generate in -luuid... no
```
Okay, let's check:
```
(1069)(master) $ nm ../x86_64-unknown-linux-gnu/ifort_18.0.5.274-intelmpi_18.0.5.274/Linux/lib/libuuid.a | grep -i uuid_generate
(1070)(master) $
```
Not in the library. In the source it only exists as an entry in a `ChangeLog`:
```
(1084)(master) $ grep -i uuid_generate -A3 uuid/* 
uuid/ChangeLog:   o INCOMPATIBILITY: Refactor the API and rename uuid_generate()
uuid/ChangeLog-     to uuid_make() and use a "uuid_t" pointer for the namespace
uuid/ChangeLog-     on UUID_VERSION3 generation. To allow access to the internal
uuid/ChangeLog-     pre-defined namespace UUIDs, provide a new uuid_load() function.
```
Looks like `uuid_generate` was renamed `uuid_make` in 2004 in OSSP uuid. I think util-linux libuuid does have `uuid_generate`, maybe?

Should I instead just abandon building CMOR from source and instead move to getting it through Anaconda? I already grab a lot from conda-forge in my Python stack, so adding one more entry probably won't hurt much.

**Comment by doutriaux1** [comment]
@mathomp4 conda is the preferred way to install cmor. Also I believe nightly builds already switch to another uuid.

**Comment by mathomp4** [comment]
@doutriaux1 Thanks. Makes my life easier. Still, in case someone here wants me to compile it as I have (but seeing as I moved from CMOR2 to 3 and no one said anything...probably not), do you know what UUID library you are using?

**Comment by mauzey1** [comment]
@mathomp4 We are using libuuid from conda-forge.
https://anaconda.org/conda-forge/libuuid

**Comment by mathomp4** [comment]
@mauzey1 Thanks! For now, I'll work toward adding it to our Anaconda-based stack. Plus it speeds up the build of our base libraries a second or two removing uuid (as I think cmor was the only one that needed it).

**Comment by mauzey1** [comment]
@mathomp4 Can this issue be closed?

**Comment by mathomp4** [comment]
Oop. Yes.
