### ISSUE TITLE
basin twice in file

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#54]
CMIP6 wants to be able to have mutliple character type dims

Attaching a test code that fakes this.

The issue at the moment is becaus ew euse NetCDF CLASSIC format for string variables we need to define the max_length of the strings, which is sadly hardcoded to the name `strlen` in cmor at the moment. This leads to a netcdf erorr trying to define the dimension strlen twice.

```
C Traceback:
In function: cmor_write


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                                                                                                                                      !
! Error: NetCDF error (-42: NetCDF: String match to name in use) for dummy 'strlen' dimension definition of axis: basin (2) in metafile, while writing variable htovgyre (table: Omon) !
!                                                                                                                                                                                      !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

[test_region_2_str_coord.f90.txt](https://github.com/PCMDI/cmor/files/165860/test_region_2_str_coord.f90.txt)
[CMIP5_Omon.txt](https://github.com/PCMDI/cmor/files/165862/CMIP5_Omon.txt)

**Comment by dnadeau4** [comment]
@doutriaux1 is this what you meant?  I ran [test_region.f90](https://github.com/PCMDI/cmor/blob/master/Test/test_python_region.py) with basin axis creating geo_region.

[htovgyre_Omon_piControl_NICAM_r1i1p1f1_gn_203001-203002.nc.txt](https://github.com/PCMDI/cmor/files/412122/htovgyre_Omon_piControl_NICAM_r1i1p1f1_gn_203001-203002.nc.txt)

**Comment by dnadeau4** [comment]
@doutriaux1

**Comment by doutriaux1** [comment]
@dnadeau4 run the code I provided as part of my original comment. You will see the error.

**Comment by dnadeau4** [comment]
@doutriaux1 I have fix this yet,  Your test is very old,  I will need to create a new one for a more recent version of cmor.

**Comment by durack1** [comment]
@dnadeau4 should this be moved to the [3.2.4 milestone](https://github.com/PCMDI/cmor/milestone/12)?
