### ISSUE TITLE
Error message mis-match

### ISSUE THREAD

**Issue by sterlingbaldwin** [PCMDI/cmor#542]
The error message [here](https://github.com/PCMDI/cmor/blob/2e9f6b2f6acbd25d15b6c46a26176632c864ac8b/Lib/pywrapper.py#L429) should match the if condition on the previous line.

**Comment by mauzey1** [comment]
@sterlingbaldwin The 'S' and 'U' in the line you linked refer to the byte and unicode types for strings in numpy arrays.  #581 changes the letters to int32, int64, float32, float64, and string.  Do you approve of these changes?

**Comment by sterlingbaldwin** [comment]
Sounds good to me, should be a lot easier to debug given the actual type instead of the letter.
