### ISSUE TITLE
needs to test for subdirectory usage in udunits include path

### ISSUE THREAD

**Issue by alaniwi** [PCMDI/cmor#545]
The `udunits2-devel` RPM from EPEL uses paths `/usr/include/udunits2/*.h` rather than `/usr/include/*.h`.

During build, this leads to:
```
gcc -c -g -DCOLOREDOUTPUT -I./include -I./include/cdTime  -lnetcdf -g -O2 -lnetcdf -ludunits2    Src/cmor.c
In file included from ./include/cmor.h:578:0,
                 from Src/cmor.c:9:
./include/cmor_func_def.h:8:22: fatal error: udunits2.h: No such file or directory
```

A successful build is possible using
```
make UDUNITS2FLAGS='-I/usr/include/udunits2 -ludunits2'
```

Could this issue be tested for in the configure step, and the include path set automatically, so that this workaround is not necessary?

**Comment by alaniwi** [comment]
(Feel free to rename this issue if you can think of a better title.)

**Comment by taylor13** [comment]
@mauzey1   Does it make sense to follow the above suggestions?
