### ISSUE TITLE
fix include of cdmsint.h

### ISSUE THREAD

**Issue by alaniwi** [PCMDI/cmor#55]
`include/cmor_func_def.h` has the line
`#include "cdmsint.h"`
 - why?

Surely cdmsint.h is for internal use within libcdms only, and other packages should not be using it. A "make install" on cdms does not install the internal header file. If content is needed externally, it should be in the external header file (cdms.h).

This is causing issues not while installing CMOR itself but when subsequently compiling things against CMOR, in particular CDO. (Can work around by installing cdmsint.h to /usr/include manually, but that's not the point.)

**Comment by doutriaux1** [comment]
cdmsint is needed for calendar things, you do NOT need libcdms installed at all, cdmsint.h is part of this repo excatly to avoid this kind of issues, see: https://github.com/PCMDI/cmor/blob/master/include/cdTime/cdmsint.h
