### ISSUE TITLE
Enabling netcdf deflation in CMOR output files

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#57]
I am hoping to use the default netcdf4 deflation in output files written by CMOR. Is this possible using the python interface?

**Comment by durack1** [comment]
@dnadeau4 following our discussion today here are the discussion points:

- What should defaults be, speed of read vs file sizes?
- Should shuffling and chunking be enabled by default?
- How should a user specify deflation (in the CMIP6_Amon.json tables) or in the CMOR3 driver file (my preference is driver file, the tables should only contain information not runtime options for CMOR3)

We'll need to consult with @taylor13 to finalize the default behavior of CMOR3

**Comment by durack1** [comment]
@doutriaux1 has comments about this - regarding "standards". Long story short, a user should be able to over-ride the Table default at runtime, however including the attributes `deflate`, `deflate_level` and `shuffle` in the Tables ensures that across variables the same default compression is applied regardless of whether the CMOR user is aware of the deflation functionality or not.

**Comment by taylor13** [comment]
Balaji is strongly advising for us to check out performance issues. GFDL 
has all but ruled out any sort of compression.  We'll talk Wednesday.

**Comment by durack1** [comment]
@dnadeau4 has this implemented in `3.0.6` with the following (python) notation:
```
cmor.set_deflate(varid,1,1,1) ; # shuffle=1,deflate=1,deflate_level=1 ; CMOR 3.0.6+
cmor.write( ...
```

**Comment by dnadeau4** [comment]
You can put the shuffle/deflation flag in the tables or call cmor.set_deflate.  I have also add the API to C and Fortran.   By default everything is netcdf3, I would like to default to netcdf4 with no compression.

**Comment by durack1** [comment]
@dnadeau4 I think defaulting to `netcdf4` is a good idea - it is the requested format for CMIP6 as far as I know

**Comment by durack1** [comment]
Just FYI, here is what the file sizes look like using various `deflate_level` flags:

| variable | cdms2 deflated | CMOR3 no-deflation | CMOR3 deflate_level=1 | CMOR3 deflate_level=3 | CMOR3 deflate_level=9 |
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| areacello | 36.1KB | 303.7KB | 55.6KB | - | - |
| siconc | 29.3MB | 433.1MB | 44.6MB | 43.2MB | 39.9MB |
| siconcbcs | 75.2MB | 433.1MB | 73.0MB | 72.3MB | 69.6MB |
| tos | 225.9MB | 433.1MB | 177.1MB | 174.8MB | 171.3MB |
| tosbcs | 239.2MB | 433.1MB | 185.1MB | 182.6MB | 178.4MB |

It would be useful to have associated timing/CPU load equivalents to validate the statement by Balaji

**Comment by dnadeau4** [comment]
create test Test/cmor_speed_and_compression_03.py
