### ISSUE TITLE
Remove references to deprecated function cmor_dataset and the old tests that used it.

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#570]
There are old tests and parts of the code that are left over from the time CMOR had the `cmor_dataset` function.  This function was used to pass user input into CMOR, which is now done with JSON files via `cmor_dataset_json`.
https://github.com/PCMDI/cmor/blob/807bf2a53b7128518ed5eb9b83424bd57ea65eb2/include/cmor_func_def.h#L66-L86
The Fortran tests in [old_cmor_tables](https://github.com/PCMDI/cmor/tree/master/Test/old_cmor_tables) use this function.  They are older versions of the current Fortran tests that use `cmor_dataset_json` so they should be removed from the repo.  [climatology_test.c](https://github.com/PCMDI/cmor/blob/master/Test/climatology_test.c) and [ipcc_test_code_json.c](https://github.com/PCMDI/cmor/blob/master/Test/ipcc_test_code_json.c) also use the deprecated function and should be removed or changed.

**Comment by taylor13** [comment]
Sounds like a good idea to me.
