### ISSUE TITLE
parent_mip_era and time: point

### ISSUE THREAD

**Issue by wachsylon** [PCMDI/cmor#590]
Hi again,
after having some experiences with CMOR3 I have two more things where you could help me.
1. (A mixture of report and question) The parent_mip_era is not changed if it is not set to "CMIP6" although a warning says so. Is it possible to have CMIP5 as parent_mip_era?
2. If the cell_method of a variable is time : point i.e. the time axis is time1, is there a variable which can have or requires time_bnds at the same time?
Best regards and thank you in advance,
Fabi

**Comment by durack1** [comment]
@wachsylon this is very old, so will close - please comment and reopen if required
