### ISSUE TITLE
getting sub_experiment_id to work as expected

### ISSUE THREAD

**Issue by markcollier** [PCMDI/cmor#592]
Hi, I have been trying to get cmor 3.5.0 to write out filenames like:

CMIP6/DCPP/CSIRO/CAFE-60/dcppA-hindcast/s1960-r1i1p1f1/Amon/tas/gn/v20200401/tas_Amon_dcppA-hindcast_CAFE-60_s1960-r1i1p1f1_gn_196011-196510.nc

by setting the sub_experiment and/or sub_experiment_id:

after a call to dataset_json:

cmor.set_cur_dataset_attribute('sub_experiment','initialized near end of year 1960')
cmor.set_cur_dataset_attribute('sub_experiment_id','s1960')

but it continues to write out:

CMIP6/DCPP/CSIRO/CAFE-60/dcppA-hindcast/s1960-r1i1p1f1/Amon/tas/gn/v20200401/tas_Amon_dcppA-hindcast_CAFE-60_r1i1p1f1_gn_196011-196510.nc

I just updated cmor and tried again without success although it seemed to remain at 3.5.0

any help appreciated...

**Comment by taylor13** [comment]
@mauzey1 (cc @markcollier )
I think we should already have a test case checking behavior when there is a sub-experiment defined.  For most CMIP6 experiments "sub_experiment_id = 'none'", but for the dcpp activity experiments it can be set to a year (preceded by an "s", e.g., "s1960").  In this case the sub-experiment id is prepended to the normally constructed "member_id" string.  
See  https://goo.gl/v1drZl where there is a section on "filename template" describing this.  The member i.d. also appears in the directory structure (also described in the linked document).

**Comment by mauzey1** [comment]
@markcollier 
Could you post the JSON file you used with the call to dataset_json to this issue?

**Comment by durack1** [comment]
@markcollier if you are planning on contributing this `CAFE-60` data to CMIP6, then you'll need to register the model in the [WCRP-CMIP/CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs) repo. The information for contributing modelling groups can be found at https://pcmdi.llnl.gov/CMIP6/Guide/modelers.html

By registering you won't have to hack the input json files, which may be part of the problem.

**Comment by markcollier** [comment]
Thanks guys, here is my standard dataset_json file where I overwrite sub_experiment{,id} as above.
We do not plan to submit as CMIP6 model as it is effectively GFDL's model, we have innovation in the assimilation side as well as producing better initial conditions as well as large ensembles. I didn't realise the missing sYYYY string to the variant label until I started looking at DCPP products on the ESG. It is really good to be able to generate refined data sets for activities outside of CMIP6 for all the obvious benefits, recently this has been the Large Ensembles activity with CSIRO Mk36 as well as our a a CAFE60 submission to being a lead data provider to the decadal forecasting activity organised by the WMO, so thats plenty for this library...most of these external activities don't care about details but I would prefer to get it right as there are often downstream benefits.

{
    "_control_vocabulary_file":     "CMIP6_CV.json",
    "_cmip6_option":                "CMIP6",
    "activity_id":                  "DCPP",
    "parent_activity_id":           "no parent",
    "outpath":                      "CMIP6",
    "parent_experiment_id":         "no parent",
    "experiment_id":                "dcppA-hindcast",
    "experiment":                   "year 1-10 hindcast initialized based on observations and using historical forcing",
    "calendar":                     "julian",
    "realization_index":            "1",
    "initialization_index":         "1",
    "physics_index":                "1",
    "forcing_index":                "1",
    "source_type":                  "AOGCM",
    "sub_experiment":               "none",
    "sub_experiment_id":            "none",
    "contact ":                     "Decadal Climate Forecasting Project external website: https://research.csiro.au/dfp/, internal wiki: https://confluence.csiro.au/display/DFP/Decadal+Forecasting+Project.",
    "branch_time":                  "0",
    "branch_time_in_child":         "0",
    "branch_time_in_parent":        "no parent",
    "parent_time_units":            "no parent",
    "parent_mip_era":               "no parent",
    "mip_era":                      "CMIP6",
    "parent_variant_label":         "no parent",
    "parent_source_id" :            "no parent",
    "branch_method":                "no parent",
    "grid":                         "native atmosphere N96 gaussian grid (90x144 latxlon)",
    "grid_label":                   "gn",
    "nominal_resolution":           "100 km",
    "tracking_prefix":              "hdl:21.14100",
    "institution_id":               "CSIRO",
    "institution":                  "Commonwealth Scientific and Industrial Research Organisation, Australia",
    "references":                   "O'Kane, T.J., Sandery, P.A., Monselesan, D.P., Sakov, P., Chamberlain, M.A., Matear, R.J., Collier, M.A., Squire, D.T. and Stevens, L., 2019, Coupled Data Assimilation and Ensemble Initialisation with Application to Multiyear ENSO prediction, J. Clim., 2019, 32, 997--1024, DOI: 10.1175/JCLI-D-18-0189.1 & Sandery, P.A., O'Kane, T.J., Kitsios, V., and Sakov, P., 2020, Climate model state estimation using variants of EnKf coupled data assimilation, Mon. Wea. Rev., 2020, accepted for publication, DOI 10.1175/MWR-D-18-0443.1",

    "run_variant":                  "forcing: GHG, Oz, SA, Sl, Vl, BC, OC, (GHG = CO2, N2O, CH4, CFC11, CFC12, CFC113, HCFC22, HFC125, HFC134a)",
    "source_id":                    "CAFE-60",
    "source":                       "CAFE-60",
    "output_path_template":         "<activity_id><institution_id><source_id><experiment_id><variant_label><table><variable_id><grid_label><version>",
    "output_file_template":         "<variable_id><table><experiment_id><source_id><variant_label><grid_label>",
    "license":                      "CMIP6 model data produced by CSIRO is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses). Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment. Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file). The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law."
}

**Comment by mauzey1** [comment]
In order to get the `sub_experiment_id` included in the file name, you will need to replace `<variant_label>` with `<member_id>` in the output templates.
```
"output_path_template":         "<activity_id><institution_id><source_id><experiment_id><member_id><table><variable_id><grid_label><version>",
"output_file_template":         "<variable_id><table><experiment_id><source_id><member_id><grid_label>",
```
`member_id` is the concatenation of `sub_experiment_id` and `variant_label`.

**Comment by taylor13** [comment]
@markcollier:  And to be safe you should probably get the latest dataset_jason file and examine it for any other differences between it and the one you are using.

**Comment by markcollier** [comment]
yes good point Karl. I have fixed the issue and it is working as expected.
Hope you guys are keeping well in the U.S., the reports are quite frightening - Australia has its relative isolation and low population in its favour but not out of the woods by no means. Today CSIRO announced it has started first rounds of testing potential vaccines, let's hope we can solve it globally and potentially other global issues collaboratively in the future.

**Comment by durack1** [comment]
To be honest @markcollier I’d also continue to update the [cmip6-cmor-tables](https://github.com/PCMDI/cmip6-cmor-tables) as there have been a series of fixes in recent releases, these will continue until no remaining issues exist
