### ISSUE TITLE
no longer working for obs4MIPs, PCMDIobs

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/cmor#608]
@mauzey1 @durack1  CMOR no longer appears to be working for projects other than CMIP6.  Using a code that previously worked with the following set in the input json:

_control_vocabulary_file":"PMPObs_CV.json

I am getting the following error:

(cdat_0611) bash-4.2$ python -i runCmor_ERA5_alllevs-CREATEIP.py
0 ua

C Traceback:
! In function: cmor_load_table_internal                                                                            
! 
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not find file: .//CMIP6_CV.json
!
!!!!!!!!!!!!!!!!!!!!!!!!!

C Traceback:
! In function: 
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Can't open/read JSON table .//CMIP6_CV.json
!
!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by durack1** [comment]
@gleckler1 which version of CMOR are you using, were you using?

**Comment by mauzey1** [comment]
@gleckler1 In [CMOR 3.6.0](https://github.com/PCMDI/cmor/releases/tag/3.6.0), the term `control vocabulary` has been replaced with `controlled vocabulary`.  So the correct input variable for the CV table should be `_controlled_vocabulary`.
This is reflected in [CMIP6_input_example.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/b73ef115532e5d177dd03f8f662fd262c8b688ba/Tables/CMIP6_input_example.json#L60)

**Comment by durack1** [comment]
@gleckler1 are you fixed? If so this should be closed

**Comment by gleckler1** [comment]
@durack1  Not quite.   I was having a problem creating a new conda env with the latest CDAT and CMOR.   When I have a chance to revisit that I will confirm this is fixed.   For now I am using an older env.   Any hints on how to create latest CDAT/CMOR are welcome. 
P

**Comment by mauzey1** [comment]
@gleckler1 I tried installing both CMOR 3.6.0 and CDAT in the same conda environment but encountered conflicts.  They seem to stem from a conflict with libnetcdf.  CMOR 3.6.0 requires libnetcdf 4.7.4 but CDAT from conda still needs libnetcdf 4.6.2.

**Comment by durack1** [comment]
@mauzey1 is there a way to resolve this, without alot of fiddling? For most of our workflows, we depend on CDAT alongside CMOR.

@muryanto1 @jasonb5 @downiec @forsyth2 FYI

**Comment by gleckler1** [comment]
@durack1 @mauzey1 @muryanto1 @jasonb5 @downiec @forsyth2 
To be more specific, it is cdms that we rely on for CMOR.  Can anyone advise on how to build a py3 conda env using the latest cmor and cdms?

**Comment by mauzey1** [comment]
@gleckler1 
I have recently updated the CMOR 3.6.0 builds on conda-forge to use the "nompi" version of libnetcdf.  Using the command `conda create -n cmor_cdms2_env -c conda-forge cmor cdms2 python=3.8` creates an environment that installs the latest versions of CMOR and CDMS2.

**Comment by gleckler1** [comment]
@mauzey1 Many thanks, this works!
