### ISSUE TITLE
variable mfo sector strlen=1

### ISSUE THREAD

**Issue by markcollier** [PCMDI/cmor#611]
Hi, I have been running old scripts with CMOR in python3 and noticed that when I try to write a variable like mfo the sector variable gets truncated to a single character, e.g. if I dump my nc file:

data:

 sector =
  "b",
  "b",
  "w",
  "d",
  "d",
  "d",
  "e",
  "f",
  "f",
  "f",
  "g",
  "i",
  "i",
  "m",
  "p",
  "t",
  "e",
  "t",
  "t",
  "e" ;

where my arguments to cmor.axis are:

coords_vals = ['barents_opening', 'bering_strait', 'windward_passage', 'davis_strait', 'denmark_strait', 'drake_passage', 'english_channel', 'faroe_scotland_channel', 'florida_bahamas_strait', 'fram_strait', 'gibraltar_strait', 'iceland_faroe_channel', 'indonesian_throughflow', 'mozambique_channel', 'pacific_equatorial_undercurrent', 'taiwan_luzon_straits', 'east_australian_current', 'tasman_front_west', 'tasman_front_east', 'east_australian_current_extension']

and length = len(['barents_opening', 'bering_strait', 'windward_passage', 'davis_strait', 'denmark_strait', 'drake_passage', 'english_channel', 'faroe_scotland_channel', 'florida_bahamas_strait', 'fram_strait', 'gibraltar_strait', 'iceland_faroe_channel', 'indonesian_throughflow', 'mozambique_channel', 'pacific_equatorial_undercurrent', 'taiwan_luzon_straits', 'east_australian_current', 'tasman_front_west', 'tasman_front_east', 'east_australian_current_extension'])

When I developed my scripts it was under python2, recently I upgraded to python3 and only noticed the issue when I tried to select out a "oline" which are not very useful in the current form. Not sure if it is a python3 thing or what, it is something of a awkward data type I think, when I print out sector I get:

<xarray.DataArray 'sector' (line: 20)>
array([b'b', b'b', b'w', b'd', b'd', b'd', b'e', b'f', b'f', b'f', b'g', b'i',
       b'i', b'm', b'p', b't', b'e', b't', b't', b'e'], dtype='|S1')

I found some info. on the |S1 type, hints of it being obsolete:

https://stackoverflow.com/questions/45573534/creating-string-based-array-introduces-random-b-before-string

I can provide a script/data if required, and provide other information if needed. It is a new anaconda installation of cmor.

I wasn't even quite sure on how to rewrite the coordinate "sector" in python to simply overwrite it as a simple fix...

Thanks, Mark.

**Comment by durack1** [comment]
@markcollier at a (very) long guess, the preceding `b'b'` may mean that it's not a string type? I am unfamiliar with xarray types. Often I will ensure that strings are unicode by using `print([x.encode('utf-8') for x in keys])`, with `keys` being the dictionary keys as input

**Comment by markcollier** [comment]
@durack1 when I open then save with xarray the original file data structures are preserved so there is nothing xarray peculiar, I would be interested to see if the development version reproduces my error, if not then I can try various software approaches - strangely enough my python2/cmor install ipkernel fails....so I cannot switch kernals in a jupyter lab to check it...
As I said, the script had no problems when I originally ran it under python2/cmor so unless there is some change in functionality there must be a bug or my software install is broken...

**Comment by durack1** [comment]
@markcollier it would surprise me that the behaviour in CMOR has changed, rather it's how py2 vs py3 treats lists of strings.

**Comment by markcollier** [comment]
@durack1 yes. I tried numerous ways of treating the string array but nothing seemed to force it to accept/define strlen>1

**Comment by durack1** [comment]
@markcollier can you force to use a pure python string or list type?

**Comment by mauzey1** [comment]
@markcollier Could you post your CMOR script where this is happening?

**Comment by markcollier** [comment]
print('BEGIN')

# coordinate_override_year = 1960
# coordinate_override = True
# # coordinate_override = False
# idir_override = '/flush5/col414/data'

# idir = '/scratch1/col414/data/'
idir = '/flush5/col414/data'

# odir = '/scratch1/col414/data/'
odir = '/flush5/col414/data'

diag = False
#diag = True

clobber = True
# clobber = False

iebeg,ieend = 1,2
iebeg,ieend = 1,4
iebeg,ieend = None,None

variables = ['mfo',]

variables_cmip6 = ['mfo',]

variables_units = ['kg s-1',]

experiment = 'piControl'
mip='CMIP'
table = 'Omon'
version = 'v20200323'
model = 'CAFE-60'
grid = 'gn'
physics_index = 1

today = date.today()
if(type(version) == type(None)):
    version = 'v'+today.strftime('%Y%m%d')
        
for cntV,variable in enumerate(variables):
    ifil = '/scratch1/col414/data/cafe60_controlc5_'+variables[cntV]+'_monthly_207001-209912.nc'
#     ifil = '/scratch1/col414/data/cafe60_controlc5_'+variables[cntV]+'_monthly_200001-209912.nc'
    print('ifil=',ifil)
    var_fh = xr.open_dataset(ifil)
    
    sector = var_fh.sector.values
    print('sector=',sector)

    j = ifil.split('/')[-1]
    k = j.split('_')[-1]
    l = k.split('.nc')[0]
    yyyymm_beg = l.split('-')[0]
    yyyymm_end = l.split('-')[-1]

    if(diag): print(yyyymm_beg,yyyymm_end)
    
    years = var_fh.time.to_index().year.tolist()
    months = var_fh.time.to_index().month.tolist()
    days = var_fh.time.to_index().day.tolist()
    hours = var_fh.time.to_index().hour.astype(float).tolist()
    minutes = var_fh.time.to_index().minute.astype(float).tolist()
    seconds = var_fh.time.to_index().second.astype(float).tolist()

    date_time_nums,date_time_stamps = [],[]
    for i, (year,month,day,hour,minute,second) in enumerate(zip(years,months,days,hours,minutes,seconds)):
        date_time_stamp = datetime.datetime(year, month, day) + datetime.timedelta(hours=hour)# , minutes=minute, seconds=second)
        date_time_stamps.append(date_time_stamp)
        date_time_nums.append(netCDF4.date2num(date_time_stamp, monthly_time_units, monthly_time_calendar))
        time = np.array(date_time_nums)

    years_beg = var_fh.time_beg.to_index().year.tolist()
    months_beg = var_fh.time_beg.to_index().month.tolist()
    days_beg = var_fh.time_beg.to_index().day.tolist()
    hours_beg = var_fh.time_beg.to_index().hour.astype(float).tolist()
    minutes_beg = var_fh.time_beg.to_index().minute.astype(float).tolist()
    seconds_beg = var_fh.time_beg.to_index().second.astype(float).tolist()
    
    date_time_nums_beg,date_time_stamps_beg = [],[]
    for i, (year_beg,month_beg,day_beg,hour_beg,minute_beg,second_beg) in enumerate(zip(years_beg,months_beg,days_beg,hours_beg,minutes_beg,seconds_beg)):
        date_time_stamp_beg = datetime.datetime(year_beg, month_beg, day_beg) + datetime.timedelta(hours=hour_beg) #, minutes=minute_beg, seconds=second_beg)
        date_time_stamps_beg.append(date_time_stamp_beg)
        date_time_nums_beg.append(netCDF4.date2num(date_time_stamp_beg, monthly_time_units, monthly_time_calendar))
        npdate_time_nums_beg = np.array(date_time_nums_beg) #+ .1 #######################################################################!!!!!

    years_end = var_fh.time_end.to_index().year.tolist()
    months_end = var_fh.time_end.to_index().month.tolist()
    days_end = var_fh.time_end.to_index().day.tolist()
    hours_end = var_fh.time_end.to_index().hour.astype(float).tolist()
    minutes_end = var_fh.time_end.to_index().minute.astype(float).tolist()
    seconds_end = var_fh.time_end.to_index().second.astype(float).tolist()
    
    date_time_nums_end,date_time_stamps_end = [],[]
    for i, (year_end,month_end,day_end,hour_end,minute_end,second_end) in enumerate(zip(years_end,months_end,days_end,hours_end,minutes_end,seconds_end)):
        date_time_stamp_end = datetime.datetime(year_end, month_end, day_end) + datetime.timedelta(hours=hour_end) #, minutes=minute_end, seconds=second_end)
        date_time_stamps_end.append(date_time_stamp_end)
        date_time_nums_end.append(netCDF4.date2num(date_time_stamp_end, monthly_time_units, monthly_time_calendar))
        npdate_time_nums_end = np.array(date_time_nums_end)

    time_bnds = np.column_stack((npdate_time_nums_beg, npdate_time_nums_end))
    
    ensemble = 1
    ensemble0 = ensemble - 1
    ensemble1 = ensemble + 1

    cmor.setup(inpath='/home/col414/da-notebooks/da-notebooks/cmip6-cmor-tables/',
               set_verbosity=cmor.CMOR_NORMAL,
               netcdf_file_action=cmor.CMOR_REPLACE, logfile='cmor.log')

    cmor.dataset_json('cafe60_piControl.json')

    table_cmip = cmor.load_table('cmip6-cmor-tables/Tables/CMIP6_Omon.json')
    table_grids = cmor.load_table('cmip6-cmor-tables/Tables/CMIP6_grids.json')
    table_coord = cmor.load_table('cmip6-cmor-tables/Tables/CMIP6_coordinate.json')

    cmor.set_table(table_cmip)

    cmor.set_cur_dataset_attribute('realization_index',str(ensemble))

    ripf = 'r'+str(ensemble)+'i1p'+str(physics_index)+'f1'

    ofil = odir+'/CMIP6/'+mip+'/CSIRO/'+ \
    model+'/'+experiment+'/'+ripf+'/'+table+'/'+variables_cmip6[cntV]+'/'+grid+'/'+version+'/'+ \
    variables_cmip6[cntV]+'_'+table+'_'+experiment+'_'+model+'_'+ripf+'_'+grid+'_'+yyyymm_beg[0:6]+'-'+yyyymm_end[0:6]+'.nc'

    print('ofil=',ofil)

    if(clobber and os.path.exists(ofil)):
        os.remove(ofil)

    if(not os.path.exists(ofil)):

        cmor.set_table(table_cmip)

        cmor.set_cur_dataset_attribute('realization_index',str(ensemble))

        if(type(version) != type(None)):
            cmor.set_cur_dataset_attribute('version',version)

        cmor.set_cur_dataset_attribute('physics_index',str(physics_index))

        cmorTime = cmor.axis('time', \
                 coord_vals = time, \
                 cell_bounds = time_bnds, \
                 units = monthly_time_units)
        
        sector_string = []
        for s in sector:
            sector_string.append(str(s))
        print(sector_string)

        oline_axis_id = cmor.axis(table_entry='oline', units='kg s-1', length=len(sector_string), coord_vals=sector_string)

        cmor.set_table(table_cmip)

        axis_ids = [cmorTime, oline_axis_id]

        cmorVar = cmor.variable(variables_cmip6[cntV], variables_units[cntV], axis_ids=axis_ids)

        if(diag): print('ensemble0=',ensemble0)

        data = var_fh[variables[cntV]]*1e9

        cmor.write(cmorVar, data.fillna(1e20).values)

        filename = cmor.close(cmorVar, file_name=True)

        print('Stored in:', filename)

        cmor.close()
        if(not os.path.exists(ofil)):
            print(CRED+' expected output file ofil not found....'+CEND)
var_fh.close()

print('END')

**Comment by markcollier** [comment]
@mauzey1 had to define cafe60 in CV file and I extend the number of online beyond the standard - although this does not matter as I have been able to generate them properly using python2/cmor in the past.

**Comment by mauzey1** [comment]
I noticed that you are assigning the units `kg s-1` to the `oline` axis.  Could that be the problem?
```
    oline_axis_id = cmor.axis(table_entry='oline', units='kg s-1', length=len(sector_string), coord_vals=sector_string)
```

**Comment by markcollier** [comment]
@mauzey1  when I try units='' - that in CMIP6_coordinate.json or 'none' it makes no difference.

**Comment by markcollier** [comment]
@mauzey1 let me know if I can provide the raw data and min. set of json files to try and reproduce my error (or not!)...

**Comment by mauzey1** [comment]
@markcollier I got the demo code working by making a few changes, and by downloading some data from ESGF.  I am currently trying to figure out why the `strlen` in the netcdf file is being set to one.  It should have been set to the length of the longest string in `sector`.

**Comment by mauzey1** [comment]
The issue seems to be from cmor.axis not handling unicode strings correctly.  If you remove `str(s)` from the code making the sector list, then it should put the correct names in the `sector` attribute of the file in Python 3.
```
    for s in sector:
        sector_string.append(s)
    print(sector_string)
```
I will investigate fixing this bug.

**Comment by markcollier** [comment]
Unless I'm doing something very silly, more than likely, didn't make any difference. This was probably one of the variations I tried...it is not very urgent.

**Comment by markcollier** [comment]
Any further advice on a fix/workaround?

**Comment by mauzey1** [comment]
@markcollier Try turning the list `sector_string` into a numpy array of zero-terminated bytes.
```
        for s in sector:
            sector_string.append(s.decode("utf-8"))
        print(sector_string)

        sector_string = np.array(sector_string, dtype='S')
        oline_axis_id = cmor.axis(table_entry='oline', units='kg s-1', length=len(sector_string), coord_vals=sector_string)
```

**Comment by markcollier** [comment]
the numpy string array was enough, I was trying that but didn't think/know of dtype='S'. Thanks much appreciated.

**Comment by durack1** [comment]
@mauzey1 should we augment the docs to suggest that `xarray` types are currently unsupported?

**Comment by mauzey1** [comment]
@durack1 I don't think this is an issue with xarray but rather an issue with cmor.axis not handling unicode strings correctly.  I am writing another issue to address this bug.
