### ISSUE TITLE
PrePARE crashing on some CMIP6 data  formatting errors: branch_time_in

### ISSUE THREAD

**Issue by martinjuckes** [PCMDI/cmor#624]
Some CMIP6 data has the global attributes `branch_time_in_child`, `branch_time_in_parent` set to a string. This is an error, the value should have type `numpy.float64`.

Rather than issuing an error report, this triggers an exception in PrePARE, and the only information printed is "data type ".0D" not understood", rather than an error message stating which attribute is causing the problem.

The  exception comes from PrePARE.py, line 1023:
```
   if not numpy.issubdtype(self.dictGbl[attr], numpy.float64):
```
This code fails if `self.dictGbl[attr]` is not a numpy type. The following works as intended:
```
   if not numpy.issubdtype( type( self.dictGbl[attr] ), numpy.float64):
```

This behaviour is shown with, for example `CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/day/tas/gr/v20200310/tas_day_EC-Earth3_historical_r1i1p1f1_gr_18500101-18501231.nc`

**Comment by durack1** [comment]
@martinjuckes thanks for reporting this.

@mauzey1, @piotrflorek, this could be a great little bug squish to kick off the collaborative work.

Ping @matthew-mizielinski @taylor13

**Comment by piotr-florek-mohc** [comment]
Thanks @durack1, indeed it seems pretty straightforward, and will help get me familiarised with Github workflow you use for CMOR.

(I will be using my MOHC account for this work)

**Comment by piotr-florek-mohc** [comment]
Hi, would it be possible to grant me access to the repository? I will be then able to do a PR here directly without having to fork it (which I suspect is the reason project's CI build hasn't been triggered by #625)

**Comment by durack1** [comment]
@mauzey1 do you have privs to "upgrade" @piotr-florek-mohc?

**Comment by mauzey1** [comment]
@martinjuckes 
I have merged @piotr-florek-mohc's changes for PrePARE, which should resolve this issue so I will close it.

@durack1 
For future pull requests, I have granted @piotr-florek-mohc push privileges for this repo.

**Comment by durack1** [comment]
@mauzey1 thanks, perfect!
