### ISSUE TITLE
Issue with json-c and Python 3.6 builds

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#635]
Recent CircleCI workflows have failed when building CMOR for Python 3.6.  The builds are giving the following errors.

Linux:
```
checking for json_object_new_object in -ljson-c... no
configure: error: Could not get a working json-c
```
OSX:
```
checking for Fortran libraries of ... 
checking for json_object_new_object in -ljson-c... no
configure: error: Could not get a working json-c
```

I will investigate why the json-c library is not working correctly with the Python 3.6 builds.

**Comment by durack1** [comment]
Thanks for digging through this @mauzey1, I think let's wrap up dropping Python 3.6 support in the next release, pointing to this conda-forge announcement in the release notes
