### ISSUE TITLE
CMOR 3.7

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#637]
- [x] Change configure.ac to 3.7.0 and rerun autoconf.
- [x] Verify that optimization is disabled from setup.py.in.
- [x] Review all issue lists and close all redundant issues (move unresolved issues to next milestone)
- [x] Validate version info is correctly written (CMOR version should be 3.7.0)
- [x] Validate data_specs_version written (01.00.33)
- [x] Increment CMOR 3.6.1 in INSTALL file to CMOR 3.7.0
- [x] Run all tests
- [x] Update master branch
- [x] Get the latest CMIP6_CV.json in cmip6-cmor-tables using the [cronjob script](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/scripts/createCMIP6CV.py).
- [x] Set 3.7.0 tag point in PCMDI/cmor repo
- [x] Create conda-forge version 3.7.0 in [cmor-feedstock](https://github.com/conda-forge/cmor-feedstock/)
- [x] Test cmor 3.7.0 from conda-forge `conda create -n cmor3.7.0 -c conda-forge cmor`
- ~~[ ] Update conda env export > cmor_3.7.0.yaml file~~
- [x] Prepare and publish release notes to [CMOR website](https://cmor.llnl.gov/news/)
- [x] Create new Release 3.7.0 in PCMDI/cmor
- [x] Update website so correct tag points (3.7.0) are noted for build notes
- [x] Create PDF from website. (use jekylll build and [Prince](https://www.princexml.com/)). post new tag to [cmor3_documentation](https://github.com/PCMDI/cmor3_documentation).
- [x] Obtain Zenodo DOI (not needed linked to latest release automatically)
- [x] Update README.md with updated Stable version info (should be 3.7.0) and updated Zenodo DOI info
- [x] Email cmor@llnl.gov, including the text: Please pass on this email to anyone you know who plans to prepare CMIP6 model output for the archive.

**Comment by durack1** [comment]
@mauzey1 we'll need to tweak the author list for the Zenodo entry, it seems that things need a bit of a tweak - https://zenodo.org/record/4328851

**Comment by durack1** [comment]
Also add noted tweaks to the Fortran wrapper, documented in https://github.com/PCMDI/cmip6-cmor-tables/issues/377

**Comment by mauzey1** [comment]
@durack1 For the Zenodo author list, who would we list?  The current list seems to everyone who contributed code to the project through GitHub.  Should the authors just be the main current developers?

**Comment by durack1** [comment]
@mauzey1 good question. It seems the [3.6.1](https://zenodo.org/record/4328851) lists all contributors, plus some. It would be nice to clean the names up so we have complete names rather than github handles.

I think we go with the core team, plus contributors, so:

Chris Mauzey, Karl E. Taylor, Paul J. Durack, Charles Doutriaux, Denis Nadeau, Emma Hogan, Jamie Kettleborough, Tobias Weigel, **kjoti**, **jmgonza**, Zeb Nicholls, Edward Betts, Jon Seddon, Fabian Wachsmann (**not sure we can expand from github names**)

@taylor13 any suggestions?

**Comment by mauzey1** [comment]
@durack1 We should also add Piotr Florek (@piotr-florek-mohc) to the list.

**Comment by durack1** [comment]
@mauzey1 absolutely, and anyone else
I erroneously omitted

**Comment by durack1** [comment]
@mauzey1 please let me know if I have showstopper PRs or issues that are getting in the way of this CMOR3.7.0 release

**Comment by mauzey1** [comment]
@durack1 I'm currently resolving issues related to the CircleCI nightly build and conda-forge feedstock.  I think I have the nightly build issue resolved so I will merge those into the CMOR 3.7.0 branch soon.

**Comment by durack1** [comment]
@mauzey1 excellent news, looking forward to seeing this live!

**Comment by mauzey1** [comment]
@durack1 Should I send emails to [cmor@llnl.gov](mailto:cmor@llnl.gov) and [pcmdi-cmip@llnl.gov](mailto:pcmdi-cmip@llnl.gov) about this release?

**Comment by durack1** [comment]
@mauzey1 yes please, just the cmor address, as the pcmdi-cmip is just 4 people (inside LLNL, plus @matthew-mizielinski)

**Comment by mauzey1** [comment]
Okay, I will just send a message through the CMOR mailing list.  I think that should be the only mailing list that we should use so we don't come off like spam on the other ones.
