### ISSUE TITLE
Illegal instruction error when region attribute is not found in the CV

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#638]
I encountered an error when working on #628.  It was when I tried to set the `region` attribute for the input4MIPs variable to a string made from a list that I got the "illegal instruction" error.  It turned out that CMOR was trying to create an error message that said that the string used for the attribute value was not found in a regular expression composed of all the [regions listed in the input4MIPs CV file](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/41a6c98858a3c3944fe91139b3bac27e2c336179/Tables/input4MIPs_CV.json#L149-L218).  This causes a problem since there are enough regions in that list to make the regular expression string exceed the maximum string length of CMOR.  The code that produces this message is below.
https://github.com/PCMDI/cmor/blob/e38ba87c81897cef00b765b8f451b250a0855f3a/Src/cmor_CV.c#L2008-L2031

This issue is related to the bigger issue of the maximum string length being only 1024 as listed in #530.  However, rather than tackle that larger issue here, I will just find a solution to handle errors for not finding attribute values in large lists in the CV.  Maybe just mention which attribute in the CV where it couldn't find the values.

**Comment by durack1** [comment]
@mauzey1 thanks for continuing to spring clean!

What would the likely investment be to tackle and solve #530? It seems like that is something that we may continue to trip over. I wonder if there is any possibility of initializing a dynamic variable rather than these fixed size variables instead?
