### ISSUE TITLE
CMOR 3.1 tests are not working

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#64]
I ran `make test` after installing CMOR 3.1 and `make` exited with an error:

```
% make test
r - cmor.o
r - cmor_axes.o
r - cmor_CV.o
r - cmor_variables.o
r - cmor_tables.o
r - cdTimeConv.o
r - cdUtil.o
r - timeConv.o
r - timeArith.o
r - cmor_grids.o
r - cmor_md5.o
r - arraylist.o
r - json_c_version.o
r - json_object_iterator.o
r - json_util.o
r - linkhash.o
r - random_seed.o
r - debug.o
r - json_object.o
r - json_tokener.o
r - libjson.o
r - printbuf.o
r - cmor_cfortran_interface.o
r - cmor_fortran_interface.o
rm -f ./ipcc_test_code ; gcc -I/home/h01/ehogan/software/netcdf/include -I/usr/local/sci/include -Iinclude/json-c -Iinclude -Iinclude/cdTime -g -O2   Test/ipcc_test_code.c -L/home/h01/ehogan/software/cmor/lib -I/home/h01/ehogan/software/cmor/include  -L. -lcmor -I/home/h01/ehogan/software/netcdf/include -I/usr/local/sci/include -L/home/h01/ehogan/software/netcdf/lib -lnetcdf    -L/home/h01/ehogan/software/udunits/lib  -Wl,-rpath=/home/h01/ehogan/software/udunits/lib -ludunits2 -lexpat  -I/home/h01/ehogan/software/udunits/include  -L/home/h01/ehogan/software/uuid/lib  -Wl,-rpath=/home/h01/ehogan/software/uuid/lib -luuid  -I/home/h01/ehogan/software/uuid/include  -lm   -o ipcc_test_code  >/dev/null 2>/dev/null; ./ipcc_test_code >/dev/null 2>/dev/null
make: *** [test_C] Error 127
```

I tried running `ipcc_test_code` directly:

```
% ./ipcc_test_code
ok mode is:0
Test code: ok init cmor
yep: GICCM1(2002), Nat

C Traceback:
! In function: cmor_outpath_exist
! called from: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You defined your output directory to be: 'CMIP6', but this
! directory does not exist
!
!!!!!!!!!!!!!!!!!!!!!!!!!
```

If I make a directory called `CMIP6` and try again I get:

```
% ./ipcc_test_code
ok mode is:0
Test code: ok init cmor
yep: GICCM1(2002), Nat
Test code: ok load cmor table(s)
Test code: defining axis region 
Test code: Redefining time/lat from O table
Test code: defining variables from table 1, down 
Test code: definig tas
Test code: ok we define hfogo positive: down 
Test code: writing time: 1 of 2
2d

C Traceback:
In function: cmor_CV_checkExperiment
! called from: cmor_setGblAttr
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: Your input attribute "sub_experiment_id" with value 
! "ds1968" will be replaced with value "s1968"
! as defined for experiment_id "piControl-withism".
! 
!  See Control Vocabulary JSON file.(Tables/CMIP6_CV.json)
! 
!
!!!!!!!!!!!!!!!!!!!!!!!!!

3d
writing tas
3d zfactor
writing ps
2d region
Test code: writing time: 2 of 2
2d
3d
writing tas
3d zfactor
writing ps
2d region
! ------
! CMOR is now closed.
! ------
! During execution we encountered:
!   1 Warning(s)
!   0 Error(s)
! ------
! Please review them.
! ------
```

Would it be possible to:
1. have the test create any required directories (i.e., `CMIP6`).
2. have all the tests run without `make` exiting with an error and produce a summary of how many tests passed / failed / errored.
3. fix the above issue; even though the message (and summary message) suggest that the message is a warning, it seems to be causing `make` to error.
4. add "run `make test`" to the release checklist in #62?

**Comment by dnadeau4** [comment]
I am not sure why CMOR 2 did not create the output directory (CMIP6) in this example.  I thought of adding the code, but need to ask if there is a reason for this behavior.  @doutriaux1 

As for number 2.  I have a lot of new test using ```unittest``` which will do exactly what you want.  Since most of the files are not using ```unittest``` I need to find a way to create this report.  They are 102 test and it would take me a month to change all of them to use ```unittest```.  I have other priorities right now such as CMIP6 validator.  I would love to have all my test in the same format though.  
They are some test that are commented out, for I never found a solution for them.  

3. Changing your attribute to force the one in the CMIP6_CV.json file is a warning.  If you rerun the test it should keep going, **and dies at the test_cmor_grid_alejandro for I forgot to comment it out**.

4. I was supposed to run ```make test``` but I am still learning about ```.travis.yml```  I have something in cmor_master, but it is still failing due to my python not having numpy....  Getting close!

**Comment by dnadeau4** [comment]
This will go in cmor-master branch (not master).

- [ ] have the test create any required directories (i.e., CMIP6).
- [ ] have all the tests run without make exiting with an error and produce a summary of how many tests passed / failed / errored.
-  [ ] fix the above issue; even though the message (and summary message) suggest that the message is a warning, it seems to be causing make to error.
-  [ ] add "run make test" to the release checklist in #62?

**Comment by dnadeau4** [comment]
I still have to finish the make test, but I have run_test.py now and will keep working on this.

**Comment by ehogan** [comment]
I have just installed CMOR 3.1.2 and I'm afraid `make test` is still not working. I tried running `run_test.py` but that doesn't work for me either. Would it be possible to reopen this ticket?

**Comment by dnadeau4** [comment]
They broke after I merged your code.  I fixed some of them, but I decided to change them all.  They are note real test, but just making sure files are created with certain options.   My other task(CDMS) is suffering from working on cmor....

**Comment by dnadeau4** [comment]
run_test should work look at the [travis](https://github.com/PCMDI/cmor/blob/master/.travis.yml) file.    All my submit are now passed with  [green lights](https://travis-ci.org/PCMDI/cmor/jobs/158570371)

**Comment by dnadeau4** [comment]
Emma,  I linked ``testTables`` to ``Tables`` and test started working again.   you can checkout cmor-3.1.3.

**Comment by ehogan** [comment]
Thanks Denis; I just tried `make test` using the `cmor-3.1.3` branch but it stops with an error at `test_cmor_grid_alejandro` as you mentioned in a previous comment (I notice this test uses an old-style MIP table; will the test work if a JSON MIP table is provided?).

When I run `python run_tests.py` on the command line (as in the travis file you linked to) I get:
```
Traceback (most recent call last):
  File "run_tests.py", line 4, in <module>
    testSuite = Test.all_tests.create_test_suite()
  File "/.../cmor/Test/all_tests.py", line 10, in create_test_suite
    for name in module_strings]
  File "/usr/local/sci/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_python_CMIP6_CV_HISTORY'
```
I can't figure out why this works for Travis but not on the command line :(

Given #98, it would be really good to be able to run all the tests to discover any remaining issues so they can be resolved as soon as possible.

**Comment by dnadeau4** [comment]
These are old test from CMOR2 for CMIP5 that I did not translate and they are are not compliant with Python unittest.   Nobody wants to work on them,  I will surely delete all these old tests in my last release, for now just comment them out in the Makefile.  I don't know who is Alejandro and what the test was for.    

I am not sure why your python unittest loader does not work for you.  I think you have an old version of Python.   I am running 2.7.12.

**Comment by doutriaux1** [comment]
@dnadeau4 these test are/were important for CMOR2 they were usually testing some somewhat obscure feature, weird parameters combination or such. They usually stem from real life issues. I don't think we should discard them. Let's get together and translate them to work with CMOR3

**Comment by dnadeau4** [comment]
I translated a lot of them already. That one (in Fortran) , somehow did not work: [test_cmor_grid_alejandro](https://github.com/PCMDI/cmor/blob/master/Test/test_cmor_grid_alejandro.f90)

My work in mainly cmip6_cv and I don't have time to fix bug in cmor anymore.  I am starting to work on another project.
