### ISSUE TITLE
update udunits dependency - 2.2.27.6 -> 2.2.28

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#647]
An upstream issue has been dropped at https://github.com/conda-forge/udunits2-feedstock/issues/44 - once this is addressed, the dependency can be updated

**Comment by durack1** [comment]
The `v2.2.28` release is now available from [conda-forge](https://anaconda.org/conda-forge/udunits2/files) - this should be good to update now

**Comment by mauzey1** [comment]
@durack1 

udunits2 2.2.28 gets installed with CMOR when creating a new Conda environment for it.  Testing hasn't shown any issues with it.

It doesn't look like further action is needed so I will close this issue.

**Comment by durack1** [comment]
@mauzey1 perfect, thanks!
