### ISSUE TITLE
Question: can CMOR handle time evolving hybrid height coordinates?

### ISSUE THREAD

**Issue by matthew-mizielinski** [PCMDI/cmor#649]
I have been looking at a potential submission to ISMIP6 for UKESM1-ice-LL which has an evolving representation of the Greenland ice sheet along with the hybrid height representation of the atmospheric levels.  The orography in the simulations updates once per year, which would lead to a requirement for the `orog` variable within the model output files to have a time axis (where variables are output on model levels).  

Our system has a few issues with variable orography data prior to calling CMOR, which we could work on, but I'd like to get a steer on whether we would expect CMOR to handle this before investigating further. I've had a quick look in the CMIP6 archive, but there isn't much data to compare to.

A look through the data request implies that the groups behind ISMIP6 are aware of this potential complication, which is why they haven't requested any variables on model levels from their own experiments -- the only request for data on model levels from ISMIP6 experiment historical-withism comes from VIACSAB (Atlantis) for variable `concdust` in MIP table `Emon`.  As such I don't see this as a relevant issue for CMIP6, but if ice-sheet representations are added into mainstream models (being talked about here) this may become a wider issue in the future.

Any thoughts would be welcome, but I wouldn't invest much time yet.

**Comment by durack1** [comment]
@matthew-mizielinski this is analogous to the [`volcello`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Omon.json#L4751-L4768) which was an `fx` field in CMIP5, but is now both an `Omon` (link above) and [`fx`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Ofx.json#L163-L180) in CMIP6 (obviously, this is a 3D x time, not a 2D x time as `orog`).

I wonder if simply adding `orog` to the [`CMIP6_IyrAnt.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_IyrAnt.json) and [`CMIP6_IyrGre.json`](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_IyrGre.json) is all the tweaks that are required?

@mauzey1 @taylor13 were any special tweaks required for the `volcello` "upgrade" in CMIP6?

**Comment by matthew-mizielinski** [comment]
@durack1, `volcello` and in the ocean is indeed similar, and this model could be applied in the atmosphere, i.e. reference an external variable -- Would only having single frequency variable, i.e. monthly `orog` in `Emon`, that is referenced by every other variable, or would we need orography at every frequency?

Note that it isn't just the `IyrAnt` and `IyrGre` mip tables that would be affected; for hybrid height models (such as HadGEM3 and UKESM) every variable on model levels would be affected (`co2` in `AERmon`, `cl` in `CFday`, `ta` in `6hrLev`, ...)

**Comment by matthew-mizielinski** [comment]
Thanks @taylor13, I've just had a dig and found and found some published hybrid pressure coordinate data, so I can see how that would work now for the parallel case I'm thinking of here with a time evolving orography field. 

As you note, looking at the formula terms file in with the MIP Tables suggests that it would be a case of adding a new orography term with a time axis and then making the appropriate CMOR calls.

Thanks @taylor13 and @durack1, for the pointers here, I think I can see where this is going, and will bear it in mind when we start dealing with a model including a dynamic ice sheet.
