### ISSUE TITLE
Error handling in CMOR 3.1

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#65]
Thank you for making the changes required to prevent the core dumps :)

I have discovered some differing behaviours in the way CMOR 3.1 handles errors.

**Example 1**

Error terminates the Python interpreter:
```
% ipython
Python 2.7.6 (default, Jan  3 2014, 16:42:21) 
Type "copyright", "credits" or "license" for more information.

IPython 2.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import cmor

In [2]: cmor.dataset_json('')
C Traceback:
! In function: cmor_is_setup
! called from: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You need to run cmor_setup before calling any cmor_function
!
!!!!!!!!!!!!!!!!!!!!!!!!!
%
```
**Example 2**

Error causes a `KeyboardInterrupt` exception to be thrown with no message. In addition, there is no log message, unless `cmor.close()` is called:

``` 
% ipython
Python 2.7.6 (default, Jan  3 2014, 16:42:21) 
Type "copyright", "credits" or "license" for more information.

IPython 2.2.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import cmor

In [2]: cmor.setup(logfile='cmor.log')

In [3]: cmor.dataset_json('')
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
KeyboardInterrupt: 

In [4]: more cmor.log

In [5]: cmor.close()
Out[5]: 0

In [6]: more cmor.log

C Traceback:
! In function: cmor_open_inpathFile
! called from: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: Could not understand file "./" Is this a JSON CMOR table?
!
!!!!!!!!!!!!!!!!!!!!!!!!!


C Traceback:
! In function: cmor_dataset_json
! 

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: JSON resource file not found
!
!!!!!!!!!!!!!!!!!!!!!!!!!

! ------
! CMOR is now closed.
! ------
! During execution we encountered:
!   1 Warning(s)
!   2 Error(s)
! ------
! Please review them.
! ------
! 

In [7]: 
```
Would it be possible to:

1. not exit the python interpreter when there is an error.
2. print to the log after each command is executed, rather than only when `cmor.close()` is executed.
3. use the message that is sent to the log as the exception message.

This ticket provides information relevant to CMOR 3.1, so #27 can probably be closed as a duplicate.

[Edited to remove "raise a more appropriate exception than `KeyboardInterrupt`"; I just noticed a comment from Denis in an e-mail that says "Now you will see a new message `Keyboard Interrupt`. There is nothing I can do about this, if I want to trap the signal." and trapping the signal is definitely more important than the exception type :)]

**Comment by ehogan** [comment]
Possibly related to this, in the [CMIP6 example](https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_experimentID.py) the following command is used:
```
error_flag = cmor.dataset_json("Test/test_python_CMIP6_experimentID.json")
```
In the CMOR2 User Guide, both Fortran and C return 0 upon success, whereas Python returns None. Is there a way for the exit code to be returned to `pywrapper.py` in the same way as Fortran and C? I understand there are cases where CMOR should explicitly fail, but if the underlying function returns the exit code rather than exiting itself, couldn’t the code in `pywrapper.py` check the exit code and then raise an exception / return the correct exit code, depending on what you want CMOR3 to do in each case?

**Comment by dnadeau4** [comment]
* **Example 1**  I created this message for you.  I return as soon as I detect that you did not call ```cmor.setup()```.  ```cmor.setup()``` set all memory to 0, so it is very important

* **Example 2** I just check the code and ```fclose()``` is called only by ```cmor_close()```,  I will look at change this behavior so that the file is open/close for each error. This should not be too difficult.

* No exit to python,  not sure, I am sending a SIGINT signal,  I tried SIGTERM, but you get the "Abort" message on red hat.  I tried other signal, but I need to program to stop,  already, I have noticed that python will run the function and only send the signal when all functions have ```return``(ed).   That creates weird behavior.  I just did not want to "kill -9" the process the way it used to do.  

* I am not sure what you mean by (3).  I do not have control of the "Keyboard Interrupt" message after the SIGINT signal has been sent.  I can look, but that seems hard.

* I think returning (0) instead of "None" in ```python``` is a great idea.  It will help my ```unittest``` a lot.   I'll try to do this next week.

**Comment by ehogan** [comment]
> Example 1: I created this message for you. I return as soon as I detect that you did not call cmor.setup(). cmor.setup() set all memory to 0, so it is very important

> No exit to python, not sure, I am sending a SIGINT signal, I tried SIGTERM, but you get the "Abort" message on red hat. I tried other signal, but I need to program to stop, already, I have noticed that python will run the function and only send the signal when all functions have `return(ed). That creates weird behavior. I just did not want to "kill -9" the process the way it used to do.

The Python interpreter is terminated when CMOR detects that `cmor.setup()` was not called because an `exit(1)` is used (https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L598) rather than `SIGINT`. Is there any chance that a `SIGINT` signal can be sent in this case, so that the Python interpreter is not terminated?

> Example 2: I just check the code and fclose() is called only by cmor_close(), I will look at change this behavior so that the file is open/close for each error. This should not be too difficult.

Great, thank you! :)

> I am not sure what you mean by (3). I do not have control of the "Keyboard Interrupt" message after the SIGINT signal has been sent. I can look, but that seems hard.

I haven't had much luck with figuring out if there is a way to send the log message to the exception :( I did find a way to change the type of exception though :) The following changes can be made to https://github.com/PCMDI/cmor/blob/master/Lib/pywrapper.py#L5 to raise a specific exception when a `SIGINT` signal is caught:

```
class CMORError(Exception):
    def __init__(self, message):
        super(CMORError, self).__init__(message)

def sig_handler(signum, frame):
    message = 'Problem with CMOR. Please check the logfile (if defined).'
    raise CMORError(message)

signal.signal(signal.SIGINT, sig_handler)
```
I ran some quick tests and this seems to work for me (i.e., I can catch all `CMORError` exceptions). I think this would be better than a `KeyboardInterrupt` exception :) 

> I think returning (0) instead of "None" in python is a great idea. It will help my unittest a lot. I'll try to do this next week.

Great, thank you! :)

**Comment by ehogan** [comment]
> I haven't had much luck with figuring out if there is a way to send the log message to the exception :(

Unless @doutriaux1 [comment](https://github.com/PCMDI/cmor/issues/27#issuecomment-121760238) can help?

**Comment by dnadeau4** [comment]
>> Example 1: I created this message for you. I return as soon as I detect that you did not call cmor.setup(). cmor.setup() set all memory to 0, so it is very important

>> No exit to python, not sure, I am sending a SIGINT signal, I tried SIGTERM, but you get the "Abort" message on red hat. I tried other signal, but I need to program to stop, already, I have noticed that python will run the function and only send the signal when all functions have `return(ed). That creates weird behavior. I just did not want to "kill -9" the process the way it used to do.

>The Python interpreter is terminated when CMOR detects that `cmor.setup()` was not called because an `exit(1)` is used (https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L598) rather than `SIGINT`. Is there any chance that a `SIGINT` signal can be sent in this case, so that the Python interpreter is not terminated?

That is right,  I decided to call exit() since there will be no log,  cmor.setup() was not called.   Without it, no log file is opened to write messages.   I just abandon boat and print this message to the user.  If I send a SIGINT, all functions need to return which creates a lot of unnecessarily and confusing messages.  cmor.setup() is a must and have to be called before anything.  Think of it like a ```__init__() ``` in Python.

>> Example 2: I just check the code and fclose() is called only by cmor_close(), I will look at change this behavior so that the file is open/close for each error. This should not be too difficult.

>Great, thank you! :)

>> I am not sure what you mean by (3). I do not have control of the "Keyboard Interrupt" message after the SIGINT signal has been sent. I can look, but that seems hard.

>I haven't had much luck with figuring out if there is a way to send the log message to the exception :( I did find a way to change the type of exception though :) The following changes can be made to https://github.com/PCMDI/cmor/blob/master/Lib/pywrapper.py#L5 to raise a specific exception when a `SIGINT` signal is caught:

>```
class CMORError(Exception):
    def __init__(self, message):
        super(CMORError, self).__init__(message)
   def sig_handler(signum, frame):
       message = 'Problem with CMOR. Please check the logfile (if defined).'
       raise CMORError(message)
   signal.signal(signal.SIGINT, sig_handler)
```
>I ran some quick tests and this seems to work for me (i.e., I can catch all `CMORError` exceptions). I think this would be better than a `KeyboardInterrupt` exception :) 

I am fine with the Keyboard Interrupt, if CMOR3 user input file is fine, we won't have a critical error.  

 At this moment, I am writing the "CMIP6 Validator" using the Control Vocabulary, but I'll try it when I get a chance.

>> I think returning (0) instead of "None" in python is a great idea. It will help my unittest a lot. I'll try to do this next week.

>Great, thank you! :)

**Comment by ehogan** [comment]
Closing in favour of #86 and #87.
