### ISSUE TITLE
Update CircleCI's Linux image

### ISSUE THREAD

**Issue by mauzey1** [PCMDI/cmor#650]
The current CircleCI Linux build for CMOR is using a deprecated Linux image that has an end-of-life on May 31, 2022.  It is discussed in this [blog post](https://circleci.com/blog/ubuntu-14-16-image-deprecation/?mkt_tok=NDg1LVpNSC02MjYAAAGCndcxoE8ffctZ5Stl-39Hx6aDpx11egbEaeqg77z5lbY5hPfU0BDHjgZx87jkH4uPPI-2WhCRJyrblSQfrWcT9zisf5zTystBF4K14h_NMNg).  Below is the current image being used.

https://github.com/PCMDI/cmor/blob/48727a1a381927831ac3c4b09e75ca6ecf439c53/.circleci/config.yml#L116-L118

I plan to replace `circleci/classic:latest` with `ubuntu-2004:202201-02`.

**Comment by durack1** [comment]
@mauzey1 thanks for catching this, please do increment
