### ISSUE TITLE
Would it be possible for cmor.dataset_json to accept a JSON string?

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#66]
I was wondering whether it would be possible to change `cmor.dataset_json` such that it can accept a JSON string as input as well as a JSON file name?

**Comment by dnadeau4** [comment]
I don't want to create another API at this time.  That involves to much test/code/documentation.  Can you just dump your string in a ```/tmp/a.json``` file?

**Comment by dnadeau4** [comment]
Is this still needed?  Did you find a work around?

**Comment by ehogan** [comment]
Thank you for following up @dnadeau4; we have a workaround :) Closing.

**Comment by taylor13** [comment]
Oops.  Above reference from #299 should not have been made.
