### ISSUE TITLE
Update cmor-site

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#673]
I just found https://pcmdi.github.io/cmor-site/ which discusses CMOR1 and CMOR2.

We should probably shut down the site, and pull any relevant content across to cmor.llnl.gov

@taylor13 pinging you here

**Comment by mauzey1** [comment]
The repo for this site is here: https://github.com/PCMDI/cmor-site

I could shut the site down from there.

**Comment by durack1** [comment]
@mauzey1 perfect, thanks.

I wonder, it seems most of these pages are *.md. How much work would you estimate it would take to drop these into an "archive" section of the existing cmor site? At the very minimum, we could link to the repo itself (https://github.com/PCMDI/cmor-site), providing a link back to material that is useful for archival purposes

**Comment by mauzey1** [comment]
@durack1  I don't think it would take long to create an "archive" section on cmor.llnl.gov.

There are several links on pcmdi.llnl.gov that link to cmor-site.  I think most of those could be changed to cmor.llnl.gov.

**Comment by durack1** [comment]
@mauzey1 if you'd be happy to complete this (plus redirects on pcmdi.llnl.gov) that would be great! I might reopen this as a task in progress

**Comment by mauzey1** [comment]
@durack1 With the [CMOR 1 doc archive](https://github.com/PCMDI/cmor3_documentation/pull/116) and the [link replacement for pcmdi.llnl.gov](https://github.com/PCMDI/pcmdi.github.io/pull/484), I think we can close this issue.

**Comment by durack1** [comment]
@mauzey1 perfect, thanks!
