### ISSUE TITLE
Building CMOR 3.7.1 with gfortran 10.1 fails at loader with several errors

### ISSUE THREAD

**Issue by strandwg** [PCMDI/cmor#686]
Most everything compiles OK, but at the linking step:

/usr/bin/ld: /glade/work/strandwg/conda-envs/CMOR/lib/libcmor.a(cmor.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /glade/work/strandwg/conda-envs/CMOR/lib/libcmor.a(cmor.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /glade/work/strandwg/conda-envs/CMOR/lib/libcmor.a(cmor_fortran_interface.o): unable to initialize decompress status for section .debug_info
/usr/bin/ld: /glade/work/strandwg/conda-envs/CMOR/lib/libcmor.a(cmor_fortran_interface.o): unable to initialize decompress status for section .debug_info
/glade/work/strandwg/conda-envs/CMOR/lib/libcmor.a: error adding symbols: File format not recognized

I've not seen these kinds of errors before. 

Any guidance is appreciated!

**Comment by mauzey1** [comment]
@strandwg Is this on Linux or Mac?  How was gfortran 10.1 installed on your machine?  Through conda?

**Comment by strandwg** [comment]
I was advised to use gfortran 10.1 as that's what CMOR was tested with as the Fortran compiler. I have no idea if gfortran was built with conda; the machine I'm using is our data processing platform which is Linux-based.

**Comment by mauzey1** [comment]
Would you mind providing the build steps that you went through to get to this point?  I assume you created an environment for CMOR using `conda create -n CMOR -c conda-forge cmor` since our discussion in https://github.com/PCMDI/cmor3_documentation/issues/120.

Did you use both gcc and gfortran installed on your machine when building Fortran programs with CMOR?  In our tests, we would install both compilers from conda-forge.
```
conda install -n CMOR -c conda-forge gcc_linux-64 gfortran_linux-64
export LDSHARED_FLAGS="-shared -pthread"

# Set prefix for configure step.
# ------------------------------------------------
export PREFIX=$(python -c "import sys; print(sys.prefix)")

# Configure the Makefile.
# ------------------------------------------------
./configure --prefix=$PREFIX --with-python --with-uuid=$PREFIX --with-json-c=$PREFIX --with-udunits2=$PREFIX --with-netcdf=$PREFIX  --enable-verbose-test

# Run the tests with the Makefile (without rebuilding CMOR).
# ------------------------------------------------
make test -o cmor -o python
```

**Comment by strandwg** [comment]
I use the system-installed compilers:

#!/bin/sh
#
source /etc/profile.d/modules.sh
#
module load conda
module load gnu/10.1.0
#
# install cmor
# ------------------------------------------------
conda create -n CMOR -c conda-forge cmor
conda activate CMOR

# Clone the CMIP6 table to your working directory.
# ------------------------------------------------
mkdir CMIP6_work
cd  CMIP6_work

# Disable SSL verification (firewall only).
# -----------------------------------------
export GIT_SSL_NO_VERIFY=true
git clone https://github.com/PCMDI/cmip6-cmor-tables.git

**Comment by mauzey1** [comment]
@strandwg Do you know which version of binutils you are using on your system?  I found a page that has the same error message you are getting with the solution to use binutils-2.32 or above.

https://wiki.gentoo.org/wiki/Project:Toolchain/Binutils_2.32_upgrade_notes/elfutils_0.175:_unable_to_initialize_decompress_status_for_section_.debug_info

**Comment by durack1** [comment]
@strandwg this issue has been unanswered for over a year, so closing - please reopen if an ongoing issue needs attention
