### ISSUE TITLE
CMOR configure script uses -R flag (Mac OS X 10.8.5, Xcode 5.1)

### ISSUE THREAD

**Issue by doutriaux1** [PCMDI/cmor#7]
Thanks @dakoop for reporting this one via UVCDAT.
The -R flag is hardcoded in the CMOR configure script (and configure.ac) under the RTAG variable; it should use the global flag or at least update its logic to use -Wl,-rpath, for compatibility with Clang 5.x.

**Comment by dnadeau4** [comment]
@doutriaux1  this seems to have been fixed in cmor3.   Is that what you mean?
```
case ${target_os} in
 linux-*)
   RTAG="-Wl,-rpath="
   FTAG="-Wl,-rpath="
 ;;
 darwin*)
   RTAG="-Wl,-rpath,"
   FTAG="-Wl,-rpath,"
 ;;
esac

```

**Comment by dnadeau4** [comment]
@doutriaux1  ping

**Comment by doutriaux1** [comment]
@dnadeau4 pong

**Comment by doutriaux1** [comment]
@dnadeau4 yes but basically since the options are identical now, simply remove the whole case statement

**Comment by dnadeau4** [comment]
Removing them make libnetcdf fails,   everything is now working. closing.
