### ISSUE TITLE
CVs and expt. names

### ISSUE THREAD

**Issue by dnadeau4** [PCMDI/cmor#70]
@durack1 
Dear Denis,

as I am using your CMOR3 tables for a while to extract variable lists, experiment lists etc., I am finding some issues, which I want to share with you:
1. empty tables / json read errors:
   CMIP6_emMonclim.json, CMIP6_Ofx.json, CMIP6_cfOff.json, CMIP6_em.json, CMIP6_SIday.json, CMIP6_emMonpt.json, CMIP6_emDaypt.json, CMIP6_em1hrclimmon.json, CMIP6_em1hr.json
2. variables with two different CF standard names:
   hfss: surface_downward_sensible_heat_flux, surface_upward_sensible_heat_flux
   rlds: surface_net_downward_longwave_flux, surface_downwelling_longwave_flux_in_air
   rsuscs: surface_upwelling_shortwave_flux_in_air_assuming_clear_sky, surface_upwelling_shortwave_flux_in_air
3. CF standard name typos or inconsistencies:
4. tnpeo: _t_endency_of_ocean_potential_energy_content
5. fProductDecomp: _C_arbon_flux_out_of_storage_product_pools_into_atmos_phere_?
6. expsi100: 3cbe53c2-12cc-11e6-b2bc-ac72891c3257
7. talk and talknat are inconsistently CF-named:
   sea_water_alkalinity_expressed_as_mole_equivalent
   seawater_alkalinity_expressed_as_mole_equivalent_natural_component
8. variable definitions (long name):
9. pr: Precipitation with exception of 'Rainfall Flux where Ice Free Ocean over Sea'
10. prsn:  Snowfall Flux; Snowfall Flux where Ice Free Ocean over Sea
11. tntscpbl:  Tendency of Air Temperature Due to Stratiform Cloud and Precipitation and Boundary Layer Mixing; Tendency of Air Temperature due to Stratiform Cloud Condensation and Evaporation
12. toz: The comment says that the unit is 'DU' but the unit_acronym is 'm'.
13. wetnh4: wet deposition rate of nh4; Wet Deposition Rate of NH4+NH3
14. general
15. Some 'modeling_realm's for variables or 'realm's in the header are missing, esp. of the em-Tables.
16. A couple of long_name mismatches but the content is the same.

Cheers,
Martina

**Comment by dnadeau4** [comment]
http://dreq01.vanillaforums.com/discussion/71/standard-name-issues-for-same-variable#latest

**Comment by dnadeau4** [comment]
@martinjuckes  I am not sure these were adresses.  I see inconsistency in Omon and Amon for #2.

**Comment by durack1** [comment]
@dnadeau4 can you clarify which version of the `dreq` you're using at the moment - is it *34*?
