### ISSUE TITLE
Compute HadGEM3-GC31-HH hist-1950 msftbarot from sobarstf and so

### ISSUE THREAD

**Issue by MargaridaS** [PCMDI/cmor#702]
Dear PCMDI CMOR Team,

I contact you because I would like to compute HadGEM3-GC31-HH hist-1950  msftbarot from sobarstf and so. Could this be done by multiplying sobarstf*so*1000?

I've tried with NCO commands but it fails due that so has 75 levels:
ncks -A -v so $sodir/$outfile_so $outdir/$outfile
ncap2 -O -s "msftbarot=msftbarot*so*1000" $outdir/$outfile $outdir/$outfile

Thank you very much in advance.
Best regards,
Marga

**Comment by taylor13** [comment]
I don't think sobarstf is a CMIP6 variable, so can't help you.  The CMIP6 ocean variables are defined in Griffies et al. (https://gmd.copernicus.org/articles/9/3231/2016/ ), where you might find some help.

**Comment by durack1** [comment]
Closing this as a non-CMOR-issue
