### ISSUE TITLE
unclear warning...

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/cmor#726]
@mauzey1 @durack1 After improving an [obs4MIPs demo](https://github.com/PCMDI/obs4MIPs-cmor-tables/tree/328_pjg_demoupdate/demo), I'm now getting a warning message that is not clear.  All 481 timesteps of the output is fine, but since this is a demo it would be good understand the reason for the warning which [I've seen elsewhere](https://gist.github.com/piotr-florek-mohc/02b40a8b9683814027d349bff4dd5bd5) in cell 23.  Any hints? 

C Traceback:
In function: cmor_close_variable
! called from: cmor_close
! 
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Warning: while closing variable 0 (pr, table obs4MIPs_Amon)
! we noticed **you wrote 0 time steps for the variable**,
! but its time axis 0 (time) has 481 time steps
!
!!!!!!!!!!!!!!!!!!!!!!!!!
! ------
! CMOR is now closed.
! ------
! During execution we encountered:
!   1 Warning(s)
!   0 Error(s)
! ------
! Please review them.
! ------

**Comment by durack1** [comment]
Can you point to the config, presumably on p and readable somewhere? It would be interesting to see the output and run CMOR with debugger statements on. @mauzey1 will likely know far more than I.

**Comment by gleckler1** [comment]
Everything needed to execute in repo dir or on gates via /home/gleckler1/git/obs4MIPs-cmor-tables/demo
>  python -i runCMORdemo_CMAP-V1902.py
output path would need to be changed for permissions.  Using 
cmor                      3.7.3           py311hc372c84_0    conda-forge
xcdat                     0.6.0              pyhd8ed1ab_0    conda-forge

**Comment by gleckler1** [comment]
@mauzey1 Thank you for explaining this - problem solved!

**Comment by durack1** [comment]
@mauzey1 is this potentially an issue that we'll see now that cdms transientVariables are no longer the default objects being passed to CMOR? Just wondering if the documentation etc needs a tweak?
