### ISSUE TITLE
default `realm = "REALM"` is always written although not required by CV

### ISSUE THREAD

**Issue by larsbuntemeyer** [PCMDI/cmor#736]
I think this is a similar issue as https://github.com/PCMDI/cmor/pull/727. For CORDEX, we have eliminated the `realm` attribute from the required global attributes (and also from table headers). However, cmor will write a default of `realm = REALM` ([example](https://wcrp-cordex.github.io/cordex-cmip6-cmor-tables/cmor-examples.html#example-from-fx-table)) no matter what.

**Comment by larsbuntemeyer** [comment]
This is now related: https://github.com/PCMDI/cmor/issues/736

**Comment by durack1** [comment]
@larsbuntemeyer agreed, this could be an opportunity to further reduce hard-coding of global attributes, with such items managed through a `required_global_attributes.json` input file. If there are other obvious cases like this, ping back on this thread and we'll consider this as the 3.9 cleanup work continues.

It it wasn't obvious, we have `realm` explicitly defined by [mip-cmor-tables](https://github.com/PCMDI/mip-cmor-tables/blob/main/Tables) (with interpretation, e.g. [APmon](https://github.com/PCMDI/mip-cmor-tables/blob/main/Tables/MIP_APmon.json) = atmospheric physics monthly, [OPmon](https://github.com/PCMDI/mip-cmor-tables/blob/main/Tables/MIP_OPmon.json) = ocean physics monthly, [AEday](https://github.com/PCMDI/mip-cmor-tables/blob/main/Tables/MIP_AEmon.json) = atmospheric aerosol daily, [OBmon](https://github.com/PCMDI/mip-cmor-tables/blob/main/Tables/MIP_OBmon.json) = ocean biogeochemistry monthly, etc), so there may be opportunities to further reduce global attribute clutter.

**Comment by larsbuntemeyer** [comment]
Thanks @durack1 , i'll check in here again if we find something similar!
