### ISSUE TITLE
input time type as INT

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/cmor#738]
We strive to CMORize an obs dataset that has the following time coordinate characteristics:

variables:
	int time(time) ;
		time:long_name = "Time" ;
		time:units = "days since 2000-03-01 00:00:00" ;
		time:delta_t = "0000-00-01 00:00:00" ;

time = 14, 45, 75, 106, 136, 167, 198, 228, 259, 289, 320, 351, 379, 410, 
    440, 471, 501, 532, 563, 593, 624, 654, 685, 716, 744, 775, 805, 836, 
    866, 897, 928, 958, 989, 1019, 1050, 1081, 1109, 1140, 1170, 1201, 1231, ...

as INT these do not reflect accurate mid-month values, and using CMOR the values (below) are altered and the bounds are not what we want as they do not represent accurate beg/end month values.  

Is there a way to have CMOR correct (adjust) these inappropriate time values or is the best path forward for it to be fixed before sending toe CMOR?
 

CMOR ouptut
--------------
 time = 14, 44.75, 75.25, 105.75, 136.25, 167, 197.75, 228.25, 258.75, 
    289.25, 320, 350.25, 379.75, 409.75, 440.25, 470.75, 501.25, 532, 562.75, 
    593.25, 623.75, 654.25, 685, 715.25, 744.75, 774.75, 805.25, 835.75, 

time_bnds =
  -1.5, 29.5,
  29.5, 60,
  60, 90.5,
  90.5, 121,
  121, 151.5,

**Comment by taylor13** [comment]
Since monthly mean data should have bounds, these need to be correctly specified.  Not sure what the easiest way is to do that is, but once you do that,  the coordinate values will be generated correctly too.  Note that currently the coordinate values are half-way between the bounds, which is what we want, but the bounds must be correctly specified.

**Comment by durack1** [comment]
@gleckler1 this seems like a case of bad data in, bad behaviours out. Not sure this is something we'd want any code changes for, do you agree?

**Comment by gleckler1** [comment]
Makes good sense to me.  We have a function to rectify the issue.  I was just curious to know if CMOR might be trying to deal with this somehow.   Thanks for the feedback.
