### ISSUE TITLE
Problem with default output_file_template?

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#74]
The default `output_file_template` for CMIP6 is `<variable_id><table><experiment_id><source_id><variant_label><grid_label>` (as specified in [the last comment](https://github.com/PCMDI/cmor/issues/67#issuecomment-226662695) in #67). However, https://github.com/PCMDI/cmor/blob/master/include/cmor.h#L230 defines the default `output_file_template` to be `<variable_id><table><experiment_id><source_id><variant_id><grid_label>` i.e., `variant_id` is used instead of `variant_label`. I also noticed that `variant_label` is defined twice in https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json, once on line 5 and the other on line 28. Is this why, when I remove `output_file_template` from https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_experimentID.json and run the [example](https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_experimentID.py), the resulting output file names are `masso_Omon_piControl_MIROC-ESM_variant_idgn_201001-201005.nc`?

**Comment by dnadeau4** [comment]
https://github.com/PCMDI/cmor/pull/72/commits/8fb2dd247373c85a825d458258cae20f90eb6c3f
