### ISSUE TITLE
DESTDIR support

### ISSUE THREAD

**Issue by waarmond** [PCMDI/cmor#745]
For packaging purposes  I would like to have basic DESTDIR support for `make DESTDIR="${pkgdir}" `.

Currently CMOR directly tries to write to the system e.g. /usr/include/cdTime

**Comment by mauzey1** [comment]
Our [current build procedure](https://cmor.llnl.gov/mydoc_cmor3_github/#configuring-cmor) for CMOR involves setting the install prefix before running ./configure.
```
./configure --prefix=$PREFIX ...
```

**Comment by durack1** [comment]
@waarmond will close, please reopen if the `$PREFIX` option doesn't work
