### ISSUE TITLE
Add CITATION.cff file

### ISSUE THREAD

**Issue by durack1** [PCMDI/cmor#749]
See example at https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CITATION.cff

@taylor13 @mauzey1 I will add this to my to-do in preparation for the CMOR 3.9.0 release

**Comment by taylor13** [comment]
If this is CMOR software, we should decide who should be included.

**Comment by durack1** [comment]
Exactly, this template can be the definitive "authorship" list which I am assuming is picked up by Zenodo as the DOI is issued. So can cover all contributions CMOR1 through 3

**Comment by durack1** [comment]
Update the CMOR User Guide - https://cmor.llnl.gov/pdf/mydoc.pdf, as this requires a bit of attention, including listing authors, like is visible in the CMOR1 ([here](https://zenodo.org/records/12690071)) and CMOR2 ([here](https://zenodo.org/records/12690366)) documentation

**Comment by mauzey1** [comment]
@durack1 So the content of this CITATION.cff should mostly be the same info we have in [.zenodo.json](https://github.com/PCMDI/cmor/blob/c24f83570777f1e0840b9b16b25f4e3f6ba0766f/.zenodo.json)?

**Comment by durack1** [comment]
Sorry @mauzey1 I hadn't made the comments above clear enough. My understanding is that if a CITATION.cff file exists, then Zenodo will pick this up and run with it - so it will overwrite existing settings in zenodo, I think.

@taylor13 is in today, and we wanted to work through this and the CMOR documentation CITATION.cff to make sure that all parties are listed, and the author order makes sense - will submit a PR with recommendations, hopefully later today

**Comment by durack1** [comment]
Also see https://github.com/PCMDI/cmor/blob/main/.zenodo.json

**Comment by durack1** [comment]
@mauzey1 @taylor13 is on vacation until next week, so I will circle and get this into a PR for you next week, apologies for the delay

**Comment by durack1** [comment]
@mauzey1 we'll also need to update the PDF documentation, which currently is missing the author list - see the CMOR1 documentation ([here](https://zenodo.org/records/12690071)) and CMOR2 documentation ([here](https://zenodo.org/records/12690366)).

The order for the CMOR3 documentation should be:
Doutriaux, Charles, Karl E. Taylor, Chris Mauzey, Denis Nadeau, Paul J. Durack.

@taylor13 let me know if I have missed anything obvious

**Comment by durack1** [comment]
@mauzey1 just noting before this issue is closed, we'll need to tweak the `2024-08-xx` in both the `CITATION.cff` and `.zenodo.json` before 3.9.0 is tagged

**Comment by mauzey1** [comment]
The publication dates were updated in both files before the 3.9.0 release.
