### ISSUE TITLE
cmor_set_cur_dataset_attribute in library interface

### ISSUE THREAD

**Issue by goord** [PCMDI/cmor#76]
Hi,

The documentation mentions that one can set global attributes via the API using the cmor_set_cur_dataset_attribute function. However, I haven't been able to discover such a routine in fortran- or c-interface. Is this method only exposed via python, and if so, is it planned to be exposed in the native interfaces in a future version?

Thank you,

Gijs van den Oord

**Comment by dnadeau4** [comment]
You can add any attributes(key:value) in your "input JSON file" for cmor 3  and that attribute will appear in your output netCDF file.  If your "key" start with the character "_",  you can use the it for "template" such as "output_file_template" or "output_path_template".    [See: test_python_user_interface_03.json](https://github.com/PCMDI/cmor/blob/master/Test/test_python_user_interface_03.json)

The API is exposed in C using libcmor.a.   Here is the declaration in cmor.h
```C
extern int cmor_set_cur_dataset_attribute( char *name, char *value,
					   int optional );
....
cmor_set_cur_dataset_attribute(GLOBAL_ATT_FURTHERINFOURL,
            szFurtherInfoURL, 0);

```
For some reason still unknown to me, the API is not exposed in Fortran.   The module name is "cmor_users_functions".  I will try to expose it and see if it works.  I am surprised that it is not there.

Denis

**Comment by dnadeau4** [comment]
I added `cmor_set_cur_dataset_attribute` in Fortran.   It is in the cmor-master branch.  I hope to merge it next week after the holiday (4th of July).
```Fortran
  print*, 'calling cmor_set_cur_dataset_attribute'
  error_flag = cmor_set_cur_dataset_attribute("language","Fortran",0)
  print*, 'returned from cmor_set_cur_dataset_attriute'
```

**Comment by goord** [comment]
Thank you, we appreciate the quick response!
