### ISSUE TITLE
Can not invoke CMOR in C++

### ISSUE THREAD

**Issue by dongli** [PCMDI/cmor#8]
Dear all,

I tried to invoke `cmor` in `c++`, and encountered the following link error:
```
$ clang++ -o test test.cpp -I/usr/local/include -I/usr/local/include/cdTime -I/usr/local/opt/ossp-uuid/include -I/usr/local/opt/udunits/include -L/usr/local/opt/ossp-uuid/lib -luuid -L/usr/local/opt/udunits/lib -ludunits2 -L/usr/local/lib -lcmor -lnetcdf
Undefined symbols for architecture x86_64:
 "cmor_setup(char*, int*, int*, int*, char*, int*)", referenced from:
     _main in test-547354.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
After some struggles, I figured out that I can solve this problem by changing all the `extern` in `cmor_func_def.h` to `extern "C"` so that those functions can be recognized by `c++`. But this makes `cmor` fail in `c`. This is just a inconsistent solution, so it would be nice that `cmor` will support the use in `c++` natively.

**Comment by dnadeau4** [comment]
@dongli Is this still something that you need?

**Comment by dnadeau4** [comment]
@dongli ping
