### ISSUE TITLE
Issues with the required_global_attributes in the CMIP6_CV.json file

### ISSUE THREAD

**Issue by ehogan** [PCMDI/cmor#88]
Running the [CMIP6 example](https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_experimentID.py) using the following in the `Test/test_python_CMIP6_experimentID.json` file:

```
{
    "_control_vocabulary_file":     "CMIP6_CV.json",
    "outpath":                      "CMIP6",
    "calendar":                     "360_day",
}
```

prints multiple `Your Control Vocabulary file specifies one or more required attributes.` error messages and tells me to set the following attributes:
- `activity_id`
- `branch_method`
- `experiment_id`
- `experiment`
- `forcing_index`
- `further_info_url`
- `grid`
- `grid_label`
- `grid_resolution`
- `initialization_index`
- `institution`
- `institution_id`
- `license`
- `physics_index`
- `realization_index`
- `variant_label`
- `source`
- `source_id`
- `source_type`
- `sub_experiment`
- `sub_experiment_id`

However, the [required_global_attributes](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json#L3) in the [CMIP6_CV.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json) file has the additional attributes:
- `Conventions`
- `creation_date`
- `mip_era`
- `data_specs_version`
- `frequency`
- `product`
- `realm`
- `table_id`
- `tracking_id`
- `variable_id`

all of which exist in the output netCDF file.

Some initial questions:
- Is there a way to distinguish between `required_global_attributes` that are required to exist in the file provided to `cmor.dataset_json` and those that are added by CMOR? Perhaps `required_global_attributes` could exist as a nested dictionary?
- Should [the documentation](http://cmor.llnl.gov/mydoc_cmor3_api/#cmordatasetjson) be updated to say that if a `_control_vocabulary_file` attribute exists in the JSON file that values for the attributes specified in the `required_global_attributes` must also exist in the JSON file? Should `outpath` and `calendar` be mentioned here? (I got errors when I didn't specify these attributes).
- Would it be possible to provide (via [the documentation](http://cmor.llnl.gov/mydoc_cmor3_api/#cmordatasetjson)) a list of valid attributes that can be specified in the JSON file?

I then added all those attributes to my JSON file and set them all equal to "a". The following errors were printed:
- First call: `Error: Your realization_index "a" is invalid. It must contain only characters between 0 and 9`, which was fixed
- Second call: `Error: Your initialization_index "a" is invalid. It must contain only characters between 0 and 9`, which was fixed
- Third call: `Error: Your physics_index "a" is invalid. It must contain only characters between 0 and 9`, which was fixed
- Fourth call: `Error: Your forcing_index "a" is invalid. It must contain only characters between 0 and 9`, which was fixed
- Fifth call: Multiple error messages relating to invalid values for `institution_id`, `source_id`, `experiment_id`, `grid_label`, `activity_id`, `further_info_url` and `sub_experiment_id`, which were fixed
- Sixth call: Multiple warning messages relating to invalid values for `institution`, `source` and `experiment`, multiple error messages relating to invalid values for `source_type` and `grid_resolution`, which were fixed
- Seventh call: Multiple `NetCDF Error` error messages, which I determined was due to the fact that the temporary filename `CMIP6/CMIP6/institute_idUKESM/CMIP/amip/r1i1p1f1/Omon/masso/gn/v20160817/masso_Omon_amip_UKESM_r1i1p1f1_gn24197.nc` already existed. Deleted the file.
- Eighth call: Completed

Some more questions:
- Should the errors from the first four calls be included with the errors in the fifth call?
- I noticed that each `experiment_id` in the [CMIP6_CV.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json) file has the attributes `experiment`, `sub_experiment_id`, `activity_id`, `mip_era`, `source_type` and `additional_source_type` associated with it. Since a warning is printed if `experiment` isn't specified (the value is inferred from `experiment_id`), could a warning (instead of an error) be printed for `sub_experiment_id`, `activity_id` and `source_type`? Alternatively, could CMOR set these values internally based on the `experiment_id` as it does for `mip_era` and `additional_source_type`?
- Should the temporary filenames be more unique so that if a problem occurs like above, the file can still be written (it wasn't clear that the problem was related to the fact that the file already existed on disk)
- No checks were performed on `branch_method`, `grid`, `license` (I see this is commented out in the [CMIP6_CV.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json) file), `variant_label` (there is an entry in the [CMIP6_CV.json](https://github.com/PCMDI/cmor/blob/master/TestTables/CMIP6_CV.json) file for this) and `sub_experiment`. Should there be?
- The following file was created: `CMIP6/CMIP6/institute_idUKESM/CMIP/amip/r1i1p1f1/Omon/masso/gn/v20160817/masso_Omon_amip_UKESM_r1i1p1f1_gn24197.nc`. The [CMOR_DEFAULT_PATH_TEMPLATE](https://github.com/PCMDI/cmor/blob/master/include/cmor.h#L231) is `<mip_era><institute_id><source_id><activity_id><experiment_id><variant_label><table><variable_id><grid_label><version>`, so the file should be `CMIP6/CMIP6/MOHC/UKESM/CMIP/amip/a/Omon/masso/gn/v20160817`, i.e., the value of the `institute_id` attribute from the JSON file wasn't used and the value of the `variant_label` attribute from the JSON file was ignored (in the filename too!). If the `variant_label` is constructed from the `realization_index`, `initialization_index`, `physics_index` and `forcing_index`, should the `variant_label` be removed from the `required_global_attributes`?

**Comment by ehogan** [comment]
I've just discovered the [CMIP6_global_attributes_filenames_CVs_20160714.docx](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk) via the [CMOR documentation](http://cmor.llnl.gov/mydoc_cmip6_user_input/#cmip6-cmor-user-input). Is this document the definitive source of information related to the required global attributes? If so, there appears to be some inconsistencies between this document and what CMOR3 is doing. Is work still ongoing to make CMOR3 consistent with this document? Would it be possible to provide details on how long this work will take?

**Comment by dnadeau4** [comment]
This document was created by @taylor13 and I used it to validate all the attributes.   All required attributes used by CV are coming through this list.   Still not sure what you are trying to do with CMOR.  Other people are using it without issues.   There were so many errors in your input JSON file, that I am not surprised the filename was not created properly.

**Comment by ehogan** [comment]
Apologies @dnadeau4 for not providing some background. I am working on integrating CMOR3 into the code I am working on. The code I am working on requires a configparser-style configuration file as input. I wanted to determine which options needed to be specified in this configuration file for CMOR3 to work, which is why I went through the above process and also asked the question:

* Is there a way to distinguish between `required_global_attributes` that are required to exist in the file provided to `cmor.dataset_json` and those that are added by CMOR?

If there was a list of `required_global_attributes` that the user needs to specify I could check that those attributes were defined in the configuration file required for the code I am working on (it wouldn't be necessary to check the attributes that CMOR3 adds). However, there are some inconsistencies between the current list of `required_global_attributes` and the [CMIP6_global_attributes_filenames_CVs_20160714.docx](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk) document. For example, the document says that `branch_method` is only required whenever the parent exists, so I don't think it should be specified in the `required_global_attributes`.

With regards to the incorrect filename, I was using a valid JSON file at that point, so the issues I describe are true issues.

**Comment by dnadeau4** [comment]
**This is a moving target.**  I spent so much time coding to match this document, but it changes every week.    The CF file data structure has changed drastically last month, and I decided to wait until final decisions are made.   I am done recoding the same thing over and over!  If the WIP can finalized this document that will be quite helpful for both of us.   Just get rid of branch_method in required_global_attributes.

**Comment by dnadeau4** [comment]
>* Is there a way to distinguish between `required_global_attributes` that are required to exist in the file provided to `cmor.dataset_json` and those that are added by CMOR? Perhaps `required_global_attributes` could exist as a nested dictionary?

I could do that, since CV is currently changing.

>* Should [the documentation](http://cmor.llnl.gov/mydoc_cmor3_api/#cmordatasetjson) be updated to say that if a `_control_vocabulary_file` attribute exists in the JSON file that values for the attributes specified in the `required_global_attributes` must also exist in the JSON file? Should `outpath` and `calendar` be mentioned here? (I got errors when I didn't specify these attributes).

I thought `outpath` was set to `.` by default.   I need to check that, I got these parameter from CMOR2 and just used them without checking if they were problematic.  

>* Would it be possible to provide (via [the documentation](http://cmor.llnl.gov/mydoc_cmor3_api/#cmordatasetjson)) a list of valid attributes that can be specified in the JSON file?

Actually any attribute found in the JSON will be created in the netCDF file except the one starting with `_`.   This is useful for other project.   When `_CMIP6` is set CMOR3 will run code to check CMIP6 particular metadata that are not used in other projects.   [cmor.c](https://github.com/PCMDI/cmor/blob/master/Src/cmor.c#L2738-L2744)

**Comment by dnadeau4** [comment]
> *Should the errors from the first four calls be included with the errors in the fifth call?

Yes, that must be old CMOR2 code remaining....

**Comment by dnadeau4** [comment]
> * if experiment isn't specified (the value is inferred from experiment_id), could a warning (instead of an error) be printed for sub_experiment_id, activity_id and source_type? Alternatively, could CMOR set these values internally based on the experiment_id as it does for mip_era and additional_source_type?

No, sub_experiment_id, activity_id and source_type are mandatory attributes and cannot be derived.   They are ESGF facets and we cannot publish files without them.   The USER need to set these.  

@taylor13 provided me with this [list](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_CV.json#L172-L202), I forces these values for each experiment.    If the WIP don't is happy with these, I will write a warning.

**Comment by ehogan** [comment]
I ran through the above using CMOR 3.2.1 and all the problems still exist, with the following differences:

* The multiple error messages mentioned in the "Sixth call" point are now included in the "Fifth call" point.
* The multiple warning messages mentioned in the "Sixth call" point now includes `sub_experiment`
* The error messages mentioned in the "Seventh call" point no longer occur.

**Comment by dnadeau4** [comment]
I changed a lot of `CRITICAL_ERROR` to `NORMAL_ERROR` and added a counter `ierr`.  This should diminished the number of time you need to run the program.  

I also reversed the filename template as mentioned in `google doc`:
[CMIP6_global_attributes_filenames_CVs_20160714.docx](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk)

The license has not been settle by the WIP yet (I think). 

I will write a `filename validator` and a `path validator`.
