### ISSUE TITLE
json-c not installed

### ISSUE THREAD

**Issue by MathisRosenhauer** [PCMDI/cmor#93]
I noticed that make install does not install json.h and friends which are needed by cmor.h through cmor_func_def.h. It is easy enough to do that manually but it would be nice if it worked out of the box.

**Comment by dnadeau4** [comment]
Thanks @MathisRosenhauer  I will look into it today.

**Comment by dnadeau4** [comment]
Done in 3.1.2,  will publish tomorrow.
