### ISSUE TITLE
Time coordinate variable in netCDF-4 file has large chunking value that affects file size

### ISSUE THREAD

**Issue by JimBiardCics** [PCMDI/cmor#99]
When a netCDF-4 file is created with chunking, the time coordinate variable has a large chunk size. This causes the netCDF file to be larger than necessary. Could you please set the chunk size to 1 for all 1-D coordinate variables and to (1,1) for all 1-D bounds variables? This should not be done for 2-D axis variables (grids).

**Comment by dnadeau4** [comment]
Jim,

I just merged the chunking of coordinates variables into cmor-3.1.3 branch.  I am not ready to release this branch on PCMDI channel, but if you need it I can create the tar ball on my personal channel.

Denis
